### ISSUE TITLE
FodyTarget condition excluding use during 'DesignTimeBuild' breaks use with Live Unit Testing

### ISSUE THREAD

**Issue by richardhauer** [Fody/Fody#1034]
https://github.com/Fody/Fody/blob/58bc705d0b0521cb7491d83a05be0df93b9f6595/Fody/Fody.targets#L32

@SimonCropp  Hi Simon, the commit with SHA 44c64e7 from way back in May 2017 introduced a condition to the `FodyTarget` that prevents execution when the flag `DesignTimeBuild` is set.  Do you remember why this was added? Is the condition for including this clause still valid?

It seems that VS builds for Live Unit Testing with the `DesignTimeBuild` flag set.  The condition in the targets file is preventing weaving from being executed in LUT builds.  This is a HUGE productivity drain.

Using a `Directory.Build.targets` I have re-written the `FodyTarget` for my project omitting this clause, as well as the `DelaySign` attribute which was causing a build error, and the system appears to be fully functional.

This clause was obviously added in response to a specific use-case where Fody was failing, but perhaps the circumstances leading to that case are no longer valid and the clause can be removed?

Thoughts? I can draw up a PR.

**Comment by SimonCropp** [comment]
it was to fix this issue https://github.com/Fody/Fody/issues/349

**Comment by davkean** [comment]
Design-Time builds don't produce binaries, Fody runs on top of a binary. Therefore cannot run in design-time builds.
