### ISSUE TITLE
.NET hot reload issue with fody 

### ISSUE THREAD

**Issue by ysmoradi** [Fody/Fody#1044]
#### Describe the issue

I've a small mvvm based dotnet maui project.
.NET hot reload works like a charm on project without fody, but it stops working after I add fody to the project and I got the following error no matter what I change.

![image](https://user-images.githubusercontent.com/5352980/140975490-c52d6f0f-d321-430a-b57f-db9332d61cb2.png)

```
Changing the version of an assembly reference is not allowed during debugging: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' changed version to '6.0.0.0'
```

#### Minimal Repro

First of all, I created a [working version](https://github.com/ysmoradi/MauiFodyHotReloadIssue/tree/working) of the project
Then I pushed [another commit](https://github.com/ysmoradi/MauiFodyHotReloadIssue/commit/6d104e2621d8645459f54f1625d7811e56581433) which adds fody to the project and .net hot reload got broken.

Note that not all fody plugins have this issue, for example Virtuosity.Fody is .net hot reload friendly.

#### Make an effort to fix the bug

I've no idea how to deal with this issue )":

**Comment by SimonCropp** [comment]
Just to confirm: To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue).

**Comment by SimonCropp** [comment]
support for hot reload will not be added by me any time soon. i suggest you stop using Fody or submit a PR that adds support

**Comment by bugproof** [comment]
I think it's not the issue with Fody itself but PropertyChanged.Fody my custom weaver works fine with hot reload with blazor wasm.

**Comment by ckorlinchak** [comment]
I had the same problem with a .net6 WPF application.  The application used both Stylet MVVM framework and PropertyChanged.Fody.  The issue did not exist with Stylet or PropertyChanged.Fody alone.  The solution that worked for my project was to include the source for Stylet in my project and not use the NuGet package.

**Comment by tom-englert** [comment]
Closed as stale, no such issues have been reported ever since.

**Comment by jaredthirsk** [comment]
> Closed as stale, no such issues have been reported ever since.
@tom-englert 

I encountered this again.  I ported my .NET 8 project to .NET 9.
I used dotPeek and noticed that with ReactiveUI.Fody in a project, it adds an extra reference to System.Runtime v8.  There is already a v9.  So Hot Reload probably is not expecting two versions of the same DLL and gets confused and fails with CS7038.
If I port the project back to .NET 8, there is no problem.

I have notified Microsoft and ReactiveUI:

https://github.com/dotnet/roslyn/issues/76284
https://github.com/dotnet/roslyn/issues/76284

**Comment by David-HH-Dev** [comment]
We have the same issue in a .NET 9 project.
error CS7038: Failed to emit module Changing the version of an assembly reference is not allowed during debugging: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=xxx' changed version to '9.0.0.0'.
I'm not sure which projects might interact. Is there a way to find that out or to workaround?

**Comment by jamiestmartin-bb** [comment]
I consistently see the exact same issue as @David-HH-Dev with PropertyChanged.Fody. Unclear whether it's that package or this causing it, because it's not obvious that either uses .net 8 at all. Just adding my 2c for anyone who finds this in the future.

**Comment by angularsen** [comment]
For ReactiveUI users, see: https://github.com/reactiveui/ReactiveUI/issues/3937#issuecomment-2657950243
