### ISSUE TITLE
Weavers sometimes not added to xml

### ISSUE THREAD

**Issue by distantcam** [Fody/Fody#105]
I haven't looked into this one yet so I'm not sure what's going on, but so far in 2013 any weaver I've tried has not added itself to the xml config.

Weavers I've tried:
- NullGuard
- Costura
- PropertyChanged
- PropertyChanging
- ToString
- Equals

**Comment by Codingale** [comment]
I've been having this again recently.

**Comment by SimonCropp** [comment]
@Codingale this is expected. MS has deprecated the feature that delivers that funtionality. you need to add it manually from now on

**Comment by Codingale** [comment]
But why! This slows down work considerably, do you know if there's a user voice thing or the article linking this deprecation notice?

**Comment by SimonCropp** [comment]
https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

> Some examples of scenarios that will not be supported include content folders (we have introduced ContentFiles), XDT transforms, PowerShell scripts i.e. install.ps1 and uninstall.ps1
