### ISSUE TITLE
Why could I not load a file or assembly or one of its dependencies? The system cannot find the file specified for Costura Fody and Xceed toolkit.

### ISSUE THREAD

**Issue by mojtabahakimian** [Fody/Fody#1062]
https://stackoverflow.com/questions/70520766/could-not-load-file-or-assembly-or-one-of-its-dependencies-the-system-cannot-fi

**Comment by tom-englert** [comment]
- are you patron?
- please provide a sample project to reproduce

**Comment by SimonCropp** [comment]
closing this. it is in the wrong repo, and the issue template was clearly ignored
