### ISSUE TITLE
Visual Studio 2022 for Mac Preview 5

### ISSUE THREAD

**Issue by SophisticatedConsulting** [Fody/Fody#1071]
Context: Xamarin solution with iOS and Android projects
Platform: MacOS 12.1, M1 Pro
IDE: Visual Studio 2022 for Mac Preview 5
Fody: 6.6.0 and MethodBoundaryAspect.Fody 2.0.144
Framework: .NET Standard 2.1

When I add Fody and MethodBoundaryAspect to a dependent library and build either the iOS or Android App I get the following errors:

### iOS

> [_app_].iOS/MTOUCH: Error MT2002: Failed to resolve assembly: 'System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' (MT2002) ([_app_].iOS)

### Android

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XA2002: Can not resolve reference: `System.Private.CoreLib`, referenced by `[_LibraryProject_]`. Please add a NuGet package or assembly reference for `System.Private.CoreLib`, or remove the reference to [_LibraryProject_].

The library itself build but the apps do not.
 
Is Fody simply not compatible with something here?

**Comment by SimonCropp** [comment]
read the issue template and raise anew issue
