### ISSUE TITLE
Cleaned library references are not removed from the deps.json file

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/Fody#1090]
Currently, weavers that set `ShouldCleanReference` to `true` get their library assembly removed from the dll references, but those will still be listed in the deps.json file. Most of the time this isn't a problem, but issues can arise in some cases.

See https://github.com/Fody/Anotar/issues/656

The rest of the issue description consists mostly of notes for myself, detailing my findings so far. I'll submit a PR for this when I'll have more time to work on it.

---

In order to fix this, Fody needs to remove the library path from the `RuntimeCopyLocalItems` items. This will remove the `"runtime"` part of the package dependency.

For instance, it will change this:

```JSON
"Anotar.Serilog.Fody/6.0.0": {
  "dependencies": {
    "Fody": "6.6.0",
    "Serilog": "2.10.0"
  },
  "runtime": {
    "lib/netstandard2.1/Anotar.Serilog.dll": {
      "assemblyVersion": "6.0.0.0",
      "fileVersion": "6.0.0.0"
    }
  }
},
```

to this:

```JSON
"Anotar.Serilog.Fody/6.0.0": {
  "dependencies": {
    "Fody": "6.6.0",
    "Serilog": "2.10.0"
  }
},
```

This fixes the reported issue in Anotar.

Fody and its weavers will remain as *package* dependencies in the deps.json file, but that shouldn't be a problem as long as no runtime dependency is defined.

After removing all references to `Anotar.Serilog.dll` from inputs of the `GenerateDepsFile` task (by removing them from the following items: `ReferencePath`, `ResolvedCompileFileDefinitions`, `NativeCopyLocalItems`, `ResourceCopyLocalItems`), references to the `Anotar.Serilog.Fody` and `Fody` packages still remain in the deps.json file. I believe these come from the project.assets.json file, which we cannot modify. That should be harmless though.

Even more so, `Anotar.Serilog.Fody` has a dependency on `Serilog` and brings the reference to the consuming project, so this relationship should remain in the deps.json file.

**Comment by tom-englert** [comment]
Looks like this needs the same we did for
`ReferenceCopyLocal`:

https://github.com/Fody/Fody/blob/master/Fody/UpdateReferenceCopyLocalTask.cs

**Comment by ltrzesniewski** [comment]
Exactly, although I'm not sure if we should allow adding to that list. Do you remember which weaver needs to add `ReferenceCopyLocal` items?

**Comment by tom-englert** [comment]
I don't think adding is a usecase.

**Comment by tom-englert** [comment]
Are `RuntimeCopyLocalItems` and ReferenceCopyLocal mutually exclusive?
i.e. only one list is present?

**Comment by ltrzesniewski** [comment]
They're both present:
- `RuntimeCopyLocalItems` come from the `ResolvePackageAssets` target
- `ReferenceCopyLocal` come from the `ResolveAssemblyReferences` target

I *suppose* the `RuntimeCopyLocalItems` include libraries from the `runtimes` NuGet directory, but I haven't checked that.
