### ISSUE TITLE
Fody Weaving skipped when Clean build initiated using msbuild

### ISSUE THREAD

**Issue by noblekurian13** [Fody/Fody#1114]
We are using Fody(ver 6.6.0) along with MethodBoundaryAspect(ver 2.0.145) to implement aspects for Exception handling and Method Execution duration tracking. When we build the application thru visual studio, the weaving is done and the aspects are hit where desirable. The nugets are downloaded before the build process is triggered.
For our deployments we are using msbuild command with the clean build option, the weaving does not occur.
We have made global settings in the Directory.Build.props file as below

<PropertyGroup Condition ="'$(ExceptionHandling)' == 'true'">
    <WeaverConfiguration>
      <Weavers VerifyAssembly="false" VerifyIgnoreCodes="0x80131869">
        <MethodBoundaryAspect />
      </Weavers>
    </WeaverConfiguration>
  </PropertyGroup>
We use a global variable (ExceptionHandling) to determine where the references and weaving should be avoided. 
<ExceptionHandling>true</ExceptionHandling>(in projects where no weaving is needed we add the variable with value false.)
The references added are as below
<ItemGroup Condition ="'$(ExceptionHandling)' == 'true'">
    <PackageReference Include="Fody" Version="6.6.0" />
    <PackageReference Include="MethodBoundaryAspect.Fody" Version="2.0.145" />
  </ItemGroup>

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by tom-englert** [comment]
@noblekurian13 any feedback on this, or can it be closed?
