### ISSUE TITLE
Allow yearly contribution

### ISSUE THREAD

**Issue by chrischu** [Fody/Fody#1127]
We would like to contribute to Fody via Open Collective, unfortunately Fody only offers the possibility of monthly contributions (while Open Collective should also support yearly contributions). 

It would be much easier for us to have yearly contributions (it makes our bookkeeping a whole lot simpler). Is there a way to also offer the possibility to do yearly contributions?

Thanks in advance!

**Comment by tom-englert** [comment]
There should be an "Individual" where you can select all parameters

**Comment by chrischu** [comment]
Ah cool I didn't see that. Thanks!
