### ISSUE TITLE
Update Cecil

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#1129]
Now that https://github.com/jbevain/cecil/issues/856 has been fixed, Cecil can be updated. (see also #1110)

@SimonCropp actually there are only the binaries of Cecil in the Fody repo. 
I assume you just did a local build of https://github.com/Fody/cecil at the fody3 branch, and then manually added the build output to the Fody repo.

Shouldn't we better add Cecil as a submodule to Fody, and build the binaries with Fody?

**Comment by ltrzesniewski** [comment]
I had to write [this](https://github.com/ltrzesniewski/InlineIL.Fody/blob/adf742ca7a4e485102f501935c8b281c4502482a/src/InlineIL.Fody/Extensions/CecilExtensions.cs#L437-L442) at some point, so there was definitely a custom `[Obsolete]` added in there. It doesn't seem like it's still there today though, but that may be unintentional.

**Comment by SimonCropp** [comment]
we cant submodule cecil. since i was never able to get this change into cecil

![image](https://user-images.githubusercontent.com/122666/193432192-b89057c2-d6cf-4db3-a4a7-657d5b8cb59e.png)

so fody is running a custom build of cecil. I will update cecil.dll

**Comment by SimonCropp** [comment]
oh and we have a custom StrongNameKeyPair
![image](https://user-images.githubusercontent.com/122666/193432222-92a1bb1b-ec3f-4334-b405-0afc624413d3.png)

**Comment by tom-englert** [comment]
@SimonCropp of course we would submodule https://github.com/Fody/cecil and use the `fody3 `branch

**Comment by SimonCropp** [comment]
@tom-englert ahh. sorry i mis-understood. happy to go with a submodule if u think that will be easier to manage.
