### ISSUE TITLE
FodyWeavers.xml in solution directory is not found/used

### ISSUE THREAD

**Issue by agaluzzi** [Fody/Fody#1136]
### Description of Problem

Using a `FodyWeavers.xml` file in the _solution directory_ (as a "global" weaver configuration) is not always working. More specifically, when a project that utilizes Fody weavers is within a _nested directory_ in the solution, Fody does not find the configuration file.

Per [the documentation](https://github.com/Fody/Home/blob/master/pages/configuration.md#a-file-in-the-solution-directory), when a project does not have its own configuration file, Fody should find and use a shared configuration file in the containing solution directory. However, this does not seem to be working properly.

### Environment

Fody 6.6.4
.NET 6.0.402
macOS 12.6

### Minimal Repro

See the attached solution: [GlobalFodyConfig.zip](https://github.com/Fody/Fody/files/9856031/GlobalFodyConfig.zip)

It has the following structure:
```
GlobalFodyConfig.sln
FodyWeavers.xml
   /Project1
   /src
      /Project2
```

From the solution directory, run the following command:
`dotnet run --project Project1`

Observe that the `FodyWeavers.xml` from the solution directory is used. (The output uses " is " as the property name/value separator.)

From the solution directory, run the following command:
`dotnet run --project src/Project2`

Observe that the `FodyWeavers.xml` from the solution directory is _not_ used. (The output uses the default ": " as the property name/value separator.) The following warning is also displayed:

> MSBUILD : warning : Fody: Could not find a FodyWeavers.xml file at the project level (/private/tmp/GlobalFodyConfig/src/Project2). A default file has been created. Please review the file and add it to your project. [/private/tmp/GlobalFodyConfig/src/Project2/Project2.csproj]

Additionally, `FodyWeavers.xml` and `FodyWeavers.xsd` files are created in the `src/Project2` directory.

**Comment by SimonCropp** [comment]
did you try to fix it?

**Comment by agaluzzi** [comment]
Yes, I have tried to come up with a fix, but haven't had much luck. Frankly, I haven't figured out how to _debug_ the weaver in order to see what's really going on. I even tried just adding some extra logging to the Fody package, but I'm having trouble even getting that to work. Apparently, my msbuild task skills are pretty lacking.

I suspect it has something to do with the `SolutionDirectoryFinder`:
```
public static string Find(string? solutionDir, string? nCrunchOriginalSolutionDir, string projectDirectory)
{
    if (!string.IsNullOrEmpty(nCrunchOriginalSolutionDir))
    {
        return nCrunchOriginalSolutionDir!;
    }

    if (!string.IsNullOrEmpty(solutionDir) && solutionDir != "*Undefined*")
    {
        return solutionDir!;
    }

    return Directory.GetParent(projectDirectory).FullName;
}
```

...and/or the msbuild properties that are getting injected into the `WeavingTask`:
```
[Required]
public string ProjectDirectory { get; set; } = null!;
...
public string? NCrunchOriginalSolutionDirectory { get; set; }
public string? SolutionDirectory { get; set; }
```

**Comment by tom-englert** [comment]
I guess the root cause is that you do not build the solution, but single projects, so the solution directory passed to Fody is not the directory where your solution is located.
To work with the solution directory you must build the solution.

Try to use "An MSBuild property in the project file" as described in the configuration documentation

**Comment by agaluzzi** [comment]
Using the `WeaverConfiguration` MSBuild property (in `Directory.Build.props`) does seem to work, as you suggest @tom-englert . I can go with that approach, but it's not my preferred option because the property is unrecognized by the IDE.

The "fallback" logic in `SolutionDirectoryFinder` also doesn't seem quite right:
```
return Directory.GetParent(projectDirectory).FullName;
```

Instead, could this code maybe traverse the parent directories until a `FodyWeavers.xml` file (or maybe a `.sln` file) is found?

**Comment by tom-englert** [comment]
The file in the solution directory is only supported for backward compatiblity. 

Modern projects should use directory.build.props

**Comment by agaluzzi** [comment]
OK, thanks @tom-englert !

**Comment by SimonCropp** [comment]
@tom-englert i had forgotten that. thanks
