### ISSUE TITLE
PropertyChanged.Fody can not run in .net 7 readytorun or aot.

### ISSUE THREAD

**Issue by kyuranger** [Fody/Fody#1147]
I created a new sample project with PropertyChanged.Fody for PropertyChanged.

It runs well without readytorun or aot. However, after publish with aot or readytorun, the program can not run any more.

Without PropertyChanged.Fody it won't like this.

However, PropertyChanged.Fody runs well in .net6 with readytorun.

What's the problem? Thank you.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
