### ISSUE TITLE
"The assembly has already been processed by Fody" in nuke

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/Fody#1167]
1. Checkout https://github.com/nuke-build/nuke/tree/feature/adaptive-logging
2. Execute `build.sh` or `build.ps1`
3. There should be an `msbuild.binlog` in the root

Note that calling `build.sh/ps1` will first compile all projects as part of compiling `_build.csproj`. After that, the `_build.csproj` will initiate another compilation. That's just what you end up when you do dogfooding :) Both produced warnings at some point.

The suggested property from #1023 did not change anything, but if it's MAUI specific, that explains it.

_Originally posted by @matkoch in https://github.com/Fody/Fody/issues/895#issuecomment-1475344904_

**Comment by ltrzesniewski** [comment]
I can repro this as I'm getting lots of _"The assembly has already been processed by Fody."_ warnings, but the produced binlog file does not contain those warnings.

**Comment by matkoch** [comment]
At which stage are you getting the warnings? Right at the beginning or rather in the middle?

**Comment by ltrzesniewski** [comment]
a `git clean -xdf` and `build.ps1` shows it's at the second (dotnet run) stage. Looks like the following command produces them:

> C:\Dev\Temp\nuke\.nuke\temp\dotnet-win\dotnet.exe build C:\Dev\Temp\nuke\nuke-common.sln --configuration Debug --no-restore --verbosity Minimal

**Comment by matkoch** [comment]
I checked again:

With `build.ps1` I get them twice. Once from `build.ps1` and once from the Compile target.

With `build.ps1 Clean Compile` I get them only from `build.ps1`. So it has something to do with existing artifacts.

**Comment by tom-englert** [comment]
> Note that calling `build.sh/ps1` will first compile all projects as part of compiling `_build.csproj`. After that, the `_build.csproj` will initiate another compilation. That's just what you end up when you do dogfooding :) Both produced warnings at some point.

Looks like this is the root cause. When you trigger multiple compilations, you should set a property per compilation - like the MAUI build does with `$(_ComputeFilesToPublishForRuntimeIdentifiers)` - so you can distinguish the build stages and switch of unneeded tasks.

**Comment by ltrzesniewski** [comment]
But that would trigger an unnecessary recompile I suppose. 🙁

The weaving task shouldn't be triggered on the second build if csc didn't run. Hooking Fody to `TargetsTriggeredByCompilation` looks like a good solution we could try, but that's not exactly a small change. 😅

**Comment by tom-englert** [comment]
Seems to depend on the project type:
https://github.com/dotnet/fsharp/pull/12100

**Comment by ltrzesniewski** [comment]
Of course there isn't any doc. 😅 

Here's the (rejected) proposal: https://github.com/dotnet/roslyn/issues/24053 - I don't know which PR really introduced it.

You're right: we need to take care about the compatibility. The code was already present in 2015 for C#: https://github.com/dotnet/roslyn/commit/aa8d4ae46473d381533407a3296e1bc25e1902a9 but F# is a concern though as it's only available since 2021.

**Comment by matkoch** [comment]
Is there any way to apply a workaround from my codebase?

**Comment by matkoch** [comment]
Afaik, MSBuild handles the warning suppression. You'd just need to use the MSBuild logger.

**Comment by ltrzesniewski** [comment]
You're right, I didn't know `$(NoWarn)` is special.

The following project doesn't display any warning:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
	<NoWarn>$(NoWarn);LOL</NoWarn>
  </PropertyGroup>

  <Target Name="Lol" AfterTargets="Build">
    <Warning Code="LOL" Text="Hello" />
  </Target>

</Project>
```

**Comment by matkoch** [comment]
Confused :) Is this workaround related?

**Comment by ltrzesniewski** [comment]
Well I was saying we could add error codes to Fody messages on our end, and that would require less work than I initially thought to silence Fody warnings.

That would be a temporary "solution". I still intend to take a closer look at this issue when I'll have some time.

**Comment by matkoch** [comment]
seems to work well!

**Comment by matkoch** [comment]
@tom-englert any idea when this could be released?

**Comment by matkoch** [comment]
Danke dir Tom! :)
