### ISSUE TITLE
`FileLoadException: Assembly with same name is already loaded` when multiple Fody-using projects are referenced

### ISSUE THREAD

**Issue by andrewlock** [Fody/Fody#1268]
#### You should already be a Patron

We (Datadog) have sponsored Simon through GitHub - hopefully that's sufficient, if not, just let me know 🙂 

#### Preamble

Where relevant, ensure you are using the current stable versions of the following:

 * Fody - `6.8.0` (latest stable)
 * InlineIL.Fody - `1.8.0` (latest stable) and `1.7.4`
 * MSBuild - `17.8.3+195e7f5a3`
 * .NET Core SDK - (`8.0.100`)

#### Describe the issue

We have been using InlineIL.Fody without issue in the Datadog .NET Client library. We recently had to add it to _another_ project. A third project then references those two:

```
Datadog.Trace.Runner
    |__Datadog.Trace (Uses Fody)
    |__Datadog.Trace.Coverage.Collector (Uses Fody)
```

Once we added Fody to the _Datadog.Trace.Coverage.Collector_ project, the _Datadog.Trace.Runner_ has started failing to build, with the following exception from MSBuild.

```
Fody: An unhandled exception occurred:
Exception: Assembly with same name is already loaded
Type: System.IO.FileLoadException
StackTrace:
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at IsolatedAssemblyLoadContext.LoadNotLocked(String assemblyPath) in C:\projects\fody\FodyCommon\IsolatedAssemblyLoadContext.cs:line 66
   at InnerWeaver.LoadFromFile(String assemblyPath) in C:\projects\fody\FodyIsolated\AssemblyLoader.cs:line 25
   at InnerWeaver.LoadWeaverAssembly(String assemblyPath) in C:\projects\fody\FodyIsolated\AssemblyLoader.cs:line 18
   at InnerWeaver.InitialiseWeaver(WeaverEntry weaverConfig) in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 159
   at InnerWeaver.InitialiseWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 147
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 108
Source: System.Private.CoreLib
TargetSite: System.Reflection.Assembly InternalLoad(System.ReadOnlySpan`1[System.Byte], System.ReadOnlySpan`1[System.Byte])
```

This was breaking our build- ([Public build in Azure Devops](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=156408&view=logs&j=c333b2e2-3335-5c92-02e4-50f3e033a320&t=1e0afc2c-7b7e-5c03-d953-c426d9532f22)).

I subsequently noticed that we were accidentally referencing two different versions of `InlineIL.Fody`. Fixing both projects to use the same assembly seems to have solved the issue, but it still feels like there may be something to investigate here...

#### Minimal Repro

Unfortunately, this appears to be hard to reproduce as it appears to be a race condition. I have not managed to create a minimal repro yet; I can't reproduce with a simplified version of the setup.

#### Make an effort to fix the bug

For a while I _thought_ that disabling MSBuild node reuse would work ([as it seemed to in the PR](https://github.com/DataDog/dd-trace-dotnet/pull/5470) and [test build](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=156364&view=results)), but even with `MSBUILDDISABLENODEREUSE=1` we were still seeing failures 🙁 The only thing that fixed it was ensuring that all dependent projects used the same version of `InlineIL.Fody`

**Comment by ltrzesniewski** [comment]
My guess would be that you didn't put the `PrivateAssets="All"` attribute on *all* the `Fody` and `InlineIL.Fody` `PackageReference` items, could you chack that?

**Comment by andrewlock** [comment]
(Un) fortunately I checked that already.

Datadog.Trace has this:
```xml
<PackageReference Include="Fody" Version="6.8.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="InlineIL.Fody" Version="1.8.0" PrivateAssets="All" />
```

and Datadog.Trace.Coverage.Collector has the same (with the now-updated InlineIL.Fody version):

```xml
<PackageReference Include="Fody" Version="6.8.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="InlineIL.Fody" Version="1.8.0" PrivateAssets="All" />
```

**Comment by ltrzesniewski** [comment]
Well, that would have been an easy explanation. In any case, Fody is trying to load two different versions of InlineIL I suppose, and that doesn't go very well.

The build log you posted seems to show the failure happens while building `Datadog.Trace.Coverage.collector` though, which may indeed point to an issue caused by node reuse.

While we probably should improve the error message, understanding the issue would be useful, since the assembly is loaded in a separate `AssemblyLoadContext` in order to avoid such problems in the first place... 😕 

Currently, there's a separate load context [for each *solution directory*](https://github.com/Fody/Fody/blob/2c3a7a8c58d6a92737d3c79db36db59f5d19f0fc/Fody/Processor.cs#L148-L162), so maybe that could be a brittle approach? Note that when you're not using a solution, the project's parent directory is [assumed to be the solution directory](https://github.com/Fody/Fody/blob/2c3a7a8c58d6a92737d3c79db36db59f5d19f0fc/Fody/SolutionDirectoryFinder.cs#L15).

**Comment by andrewlock** [comment]
> Currently, there's a separate load context [for each solution directory](https://github.com/Fody/Fody/blob/2c3a7a8c58d6a92737d3c79db36db59f5d19f0fc/Fody/Processor.cs#L148-L162), so maybe that could be a brittle approach? Note that when you're not using a solution, the project's parent directory is [assumed to be the solution directory](https://github.com/Fody/Fody/blob/2c3a7a8c58d6a92737d3c79db36db59f5d19f0fc/Fody/SolutionDirectoryFinder.cs#L15).

I think this could explain the issue then, both of these projects _are_ in the same solution directory in our project 🙂 And they're also in the same parent directory
