### ISSUE TITLE
The generated `nugets\x.Fody.x.x.x\x.Fody.nuspec` should probably not have a dependency on itself

### ISSUE THREAD

**Issue by schittli** [Fody/Fody#1307]
Hello

### thank you very much for your great work!
I'm trying to figure out if I can use Fody in one of my open-source projects 
**and I've probably stumbled across a little bug:**

#### Describe the issue

- I guess that FodyPackaging is creating this File: `.\nugets\AspectTrim.Fody.0.1.0\AspectTrim.Fody.nuspec`
- This `.nuspec` has a dependency to itself (just the essentials of the file):
   ``` XML
   <id>AspectTrim.Fody</id>
      <dependencies>
         <dependency id="AspectTrim.Fody" … 
   ```

- The content of **AspectTrim.Fody.nuspec** (I have jus stripped some items)
   ``` XML
   <?xml version="1.0" encoding="utf-8"?>
   <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
     <metadata>
       <id>AspectTrim.Fody</id>
       <dependencies>
         <group targetFramework=".NETStandard2.0">
           <dependency id="AspectTrim.Fody" version="0.1.0" exclude="Build,Analyzers" />
           <dependency id="Fody" version="6.9.1" include="All" />
         </group>
       </dependencies>
     </metadata>
   </package>
   ```

#### Test my assumption: The behavior when I add the package to a project

I try to add the package into a project and I change the specification in: 
`c:\Users\…\.nuget\packages\aspecttrim.fody\0.1.0\aspecttrim.fody.nuspec` 

##### Test 1: AspectTrim.Fody has a dependency on itself:
I try to install `AspectTrim.Fody` with the dependency on itself. It will fail:

```XML
   … <metadata>
    <id>AspectTrim.Fody</id>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="AspectTrim.Fody" version="0.1.0" exclude="Build,Analyzers" />
        <dependency id="Fody" version="6.9.1" include="All" />
      </group>
    </dependencies>
  </metadata> … 
```
*❌ The Result:*
```
Install failed … Cycle detected. 
jig.ch.TomLib -> AspectTrim.Fody 0.1.0 -> AspectTrim.Fody (>= 0.1.0).
```

##### Test 2: AspectTrim.Fody has **NO** dependency on itself:
I try to install `AspectTrim.Fody` **without** the dependency on itself. It will work:
```XML
   … <metadata>
    <id>AspectTrim.Fody</id>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <!-- <dependency id="AspectTrim.Fody" version="0.1.0" exclude="Build,Analyzers" /> -->
        <dependency id="Fody" version="6.9.1" include="All" />
      </group>
    </dependencies>
  </metadata> … 
```
*✔️ The Result:*
The Package was perfectly installed into the project 😃 

#### Minimal Repro

- If I am not mistaken, it should be a logical error that the generated .nuspec must not have a dependency on itself.

- But if you need to see that this dependency is generated on itself, you can compile Obsolete.Fody: 
   - the generated `.nuspec` file will have a dependency on Obsolete.Fody itself:
     `.\nugets\Obsolete.Fody.x.x.x\Obsolete.Fody.nuspec`

#### Make an effort to fix the bug

Ufff... I'm very surprised at how complex Fody is, so I wouldn't dare make a code suggestion. Pretty sure I would bring more bugs than correct them...

Thanks a lot, kind regards,
Thomas

**Comment by tom-englert** [comment]
> I guess that FodyPackaging is creating this File

No, it's MSBuild that generates the.nuspec file from your project properties

**Comment by schittli** [comment]
Hello @tom-englert ,
thank you, you're fast! 😃 

> > I guess that FodyPackaging is creating this File
> 
> No, it's MSBuild that generates the.nuspec file from your project properties

Oh, too bad Microsoft SW is involved, it's so full of bugs that the pain of working with it gets worse every day 😞 

… **But: Doesn't Fody deliver the specification to MSBuild,** which then causes it to create a loop in the dependency?

**Comment by tom-englert** [comment]
> I guess that FodyPackaging is creating this File

No, it's MSBuild that generates the.nuspec file from your project properties

**Comment by tom-englert** [comment]
No, creating a nuget package is a standard task, Fody is just adding some content
