### ISSUE TITLE
Problems with Microsoft.Bcl.Build

### ISSUE THREAD

**Issue by lucamenazzi** [Fody/Fody#137]
Hi,

Fody does not work anymore with version 1.0.21 of the package Microsoft.Bcl.Build

I am developing a new sample project with Xamarin Studio on my Mac notebook and after I have upgraded the nget pagkage the build process does not include any weavers anymore.

I am using the PropertyChanged.Fody weaver and after the upgrade of Microsoft.Bcl.Build to version 1.0.21 it does not work anymore and my ViewModels do not notify property changes to their Views.

Could you please help me.

Best regards.

Luca

**Comment by batkuip** [comment]
Having the same problem.  IOS project with BCL.  Fody does not execute.  Removing the BCL import directive works for me, although not sure what that in turn might break.

**Comment by SimonCropp** [comment]
@batkuip same deal. upload a repro somewhere

**Comment by SimonCropp** [comment]
@batkuip specifically if u can repro with an Xamarin Android app

**Comment by batkuip** [comment]
I'll try creating an IOS repo.  Last time I ran Xamarin Android I got stuck in licensing hell for a couple of months.

**Comment by SimonCropp** [comment]
@batkuip I can test an IOS repro.

**Comment by distantcam** [comment]
@batkuip Removing the BCL import won't break anything. The package is a build aid for older packages. If your build succeeds without it you don't need it.

**Comment by SimonCropp** [comment]
@batkuip can u tell what packages rely on BCL in your solution?

**Comment by batkuip** [comment]
Microsoft.Net.Http requires it.  Microsoft.Bcl.Build 1.0.14 works, 1.0.21 doesn't.  Weird part is that I've just created a project from scratch with just Fody + Bcl 1.0.21 and it works fine, so there seems to be something else at play as well.  

FodyTarget doesn't get executed in my own project with the Import Bcl statement.  Could be a Xamarin bug - I wonder if it has something to do with install.ps which I believe doesn't get executed when installing from Xamarin Studio.  I did compare project files and I couldn't see any major difference, so maybe not.

**Comment by omares** [comment]
I know this wont help much but wanted to report it that we have the same issue with our xamarin project and fody. Unfortunately i cant provide an ios example as we only have an android license.

**Comment by SimonCropp** [comment]
@omares out of curiosity does it build and run ok if you manualy hack out the blc nuget package?

**Comment by omares** [comment]
@SimonCropp Yes it does, but applying the hack haunts me every time i think about it :)

**Comment by SimonCropp** [comment]
@omares i think you need to raise this with microsoft. Fody is doing the most basic of msbuild integration and i am not sure how to proceed.

**Comment by omares** [comment]
Just in case, we are using fody in xamarin and build our projects using xamarin studio. So i am not sure if msbuild even applies here? Can this be the cause of the problem?

**Comment by SimonCropp** [comment]
@omares well if Fody works without build.bcl then it would seem in some way you are using msbuild
