### ISSUE TITLE
PeVerify the assembly once it has been weaved

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#150]
I rather have a failing build than a corrupt assembly. I had a failing boxing check in one of my assemblies which would have been "easy" to spot if Fody could somehow perform a PeVerify after weaving.

**Comment by GeertvanHorrik** [comment]
One option is to check for existing installations of PeVerify (and skip if none found). Another one might be to embed PeVerify into Fody (if allowed).

**Comment by GeertvanHorrik** [comment]
Hmm, I see this thread now: #35

**Comment by distantcam** [comment]
So can we close this?

Also, which fody plugin was causing the error?

**Comment by GeertvanHorrik** [comment]
Catel.Fody.

**Comment by GeertvanHorrik** [comment]
Not sure if we can close this one, I read that a PR could be accepted, not sure what the status is.

**Comment by SimonCropp** [comment]
Yes i will accept a PR for this

**Comment by GeertvanHorrik** [comment]
And what option do you prefer?

**Comment by SimonCropp** [comment]
But i think it should be off by default for perf reasons

**Comment by SimonCropp** [comment]
Run if it is installed i think would be best

**Comment by GeertvanHorrik** [comment]
**Without verification**

```
<Weavers>
  <ModuleInit/>
  <MethodTimer/>
  <Catel/>
</Weavers>
```

-or-

```
<Weavers VerifyAssembly="false">
  <ModuleInit/>
  <MethodTimer/>
  <Catel/>
</Weavers>
```

**With verification**

```
<Weavers VerifyAssembly="true">
  <ModuleInit/>
  <MethodTimer/>
  <Catel/>
</Weavers>
```

**Output with verification => failed**

```
Error	43	Fody: Verification of the assembly failed. Verifier used is 'PeVerify'.

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

// errors go here
```

**Comment by SimonCropp** [comment]
wouldnt it make more sense as a compilation constant? Then you could run it for a specific build config or even "only on the build server"?

**Comment by GeertvanHorrik** [comment]
Not sure how I can read them into Fody (couldn't find a config system), but this way I can switch it on whenever I want.

**Comment by SimonCropp** [comment]
constants should be in this https://github.com/Fody/Fody/blob/master/Fody/WeavingTask.cs#L30

**Comment by GeertvanHorrik** [comment]
Let me finish it in this form, we can tweak it later. Always hard to work on someone else's code base.

**Comment by SimonCropp** [comment]
sure. happy to support both config options. so finish this one and i will add the other after the merge

**Comment by GeertvanHorrik** [comment]
Question: do we only have access to the temp path (obj folder) or do we have access to the final one? I Want to verify the assembly when Fody is done (but there might be more steps in msbuild). However, I just want to ensure that after Fody, the assembly is ok.

**Comment by SimonCropp** [comment]
u only have access to the obj folder. 

do the call here https://github.com/Fody/Fody/blob/master/Fody/Processor.cs#L100

since not all reference will be in the obj u may need to process the output of peverify to exclude the missing reference errors??? u will need to check

**Comment by GeertvanHorrik** [comment]
It's exactly what I did and exactly what I encountered ;-)

**Comment by SimonCropp** [comment]
r u going to tweak the params passed to peverify?

**Comment by GeertvanHorrik** [comment]
Tried but there are more errors. Trying manual copy of references now (not ideal, but ok...).

**Comment by SimonCropp** [comment]
wont that pollute the obj with files that should not be there? AFAIK messing with the obj dir state is not a good idea. Is it not possible to pass refs into the peverify exe?

**Comment by SimonCropp** [comment]
another option would be to tweaks the .targets to also run something after the point where bin has been finalised so all the refs should be there???

**Comment by GeertvanHorrik** [comment]
Yes, that would be even better. I will push what I have now so we can discuss the code (separate branch anyway).

**Comment by SimonCropp** [comment]
ok will review

**Comment by GeertvanHorrik** [comment]
See #151, will close this one

**Comment by SimonCropp** [comment]
pushed to nuget

**Comment by GeertvanHorrik** [comment]
Cool, thanks!
