### ISSUE TITLE
Refactoring to Fody

### ISSUE THREAD

**Issue by jeffijoe** [Fody/Fody#152]
Hey, and nice job on Fody!

I am trying to replicate the following functionality in an AoP fashion:

```
/// <summary>
/// Tries the specified stuff to try.
/// </summary>
/// <param name="stuffToTry">The stuff to try.</param>
/// <exception cref="RepositoryException">All exceptions are wrapped in this.</exception>
protected void Try(Action stuffToTry)
{
    try
    {
        stuffToTry();
    }
    catch (CommonRdbException ex)
    {
        throw ExceptionUtil.ConvertRdbExceptionToRepositoryException(ex);
    }
    catch (RepositoryException ex)
    {
        if (ex.RepositoryError == RepositoryError.Error)
            LogTo.ErrorException("A RepositoryException with type Error was caught in the repository.", ex);
        throw;
    }
    catch (Exception ex)
    {
        LogTo.ErrorException("An unhandled exception was caught.", ex);
        throw new RepositoryException(
            string.Format("An unhandled exception was caught in the repository: {0}", ex.Message), ex);
    }
}
```

And usage..

```
Try(() => {
  // exceptions get wrapped and logged. Nice.
});
```

I know there is a method decorator add-in, but not sure how I would replicate the following code with it.

**Comment by SimonCropp** [comment]
i am a little confused. can you express this in before weaving and after weaving versions of your code

**Comment by jeffijoe** [comment]
Sure - this is what I am looking for:

## Your code

```
// The aspect
public class TryCatchAndLog : IInterceptor
{
    public override Intercept(IInterception interception)
    {
        // Could probably be optimized so we don't get a logger every time a method is invoked.
        var log = LogManager.GetLogger(interception.InterceptedType);
        try
        {
            interception.Run();
        }
        catch(ServiceException ex)
        {
             log.Warning("A service exception was caught - not that serious.", ex);
             throw;
        }
        catch(Exception ex)
        {
             log.Error("An unhandled exception was caught.", ex);
             throw new ServiceException("An unhandled exception was caught.", ex);
        }
    }
}

// The code using the aspect
public class MyClass
{
    [TryCatchAndLog]
    public void DoStuff()
    {
        Console.WriteLine("Hello");
    }
}
```

## After weaving

```
public class MyClass
{
    public void DoStuff()
    {
        var log = LogManager.GetLogger(this.GetType());
        try
        {
            Console.WriteLine("Hello");
        }
        catch(ServiceException ex)
        {
             log.Warning("A service exception was caught - not that serious.", ex);
             throw;
        }
        catch(Exception ex)
        {
             log.Error("An unhandled exception was caught.", ex);
             throw new ServiceException("An unhandled exception was caught.", ex);
        }
    }
}
```

Not sure if it's possible, but would be pretty cool.

**Comment by SimonCropp** [comment]
well that is actually pretty close to what method timer does https://github.com/Fody/MethodTimer#your-code

**Comment by jeffijoe** [comment]
Yeah, and also close to what the method decorator plugin does, but the difference is that in this example, the interceptor code written by the developer is wrapping the code being intercepted, instead of the plugin calling into the interceptor class' methods.

**Comment by SimonCropp** [comment]
well i guess you are at the point of writing some IL code :)

**Comment by SimonCropp** [comment]
i think u should start a github project to achive this. have a go at the IL weaving based on what you can seen in other projects and then ask for help when u hit a wall

**Comment by jeffijoe** [comment]
Never done any IL - it's scary :(

Is it possible to weave in code that is already compiled?

**Comment by SimonCropp** [comment]
yes it is. the costura project does some of that

**Comment by rileywhite** [comment]
[Bix.Mixers](https://github.com/rileywhite/Bix.Mixers) works like that. It takes code that the developer wrote in C# and that has been compiled, and it copies the IL into the target. In this way, the mixed-in IL matches the code produced by the current compiler settings (e.g. extra no-ops for debug mode).

I'm working (slowly) on supporting more use cases, including this one. The base clone-brush functionality that you're asking about is there, but it is not fully exposed in a public API. Free free to have a look, and since it's open source (Apache 2.0), you can always poach some of it :-)

A good place to start looking at the IL clone-brush functionality is [ILCloningContext](https://github.com/rileywhite/Bix.Mixers/blob/master/src/Bix/Mixers/ILCloning/ILCloningContext.cs).

**Comment by jeffijoe** [comment]
Might look into it if time allows :) 

~ Jeff Hansen
