### ISSUE TITLE
How to handle msbuild cancelation?

### ISSUE THREAD

**Issue by soloman817** [Fody/Fody#154]
Hi guys,

Sometimes, my fody plugin took sometime to finish, and if I click the "canel building" buttom in Visual Studio, very bad thing happens, cause during my plugin, I loaded some assemblies, and they are not explicitly disposed. So I was wondering how can fody support msbuild task cancelation?

I googled it, for example: http://stackoverflow.com/questions/9865982/how-do-you-write-an-msbuild-task-to-support-cancelation

it looks like the task should implement an interface, but I didn't see it in Fody source, so, any suggestions on this issue?

Regards,
Xiang.

**Comment by SimonCropp** [comment]
@soloman817 why are you "cause during my plugin, I loaded some assemblies"? are you using reflection during compile time?

**Comment by soloman817** [comment]
yes, we need to use reflection, we load the assembly user is building, then we find all types or methods with some attribute, and then we do some compiling for them, generate gpu code, and then we insert the generated gpu code into the assembly.

So far I found Fody doesn't support cancel, if I click cancel button, it will wait until my fody plugin finished, that is ok, but it would be good if fody can support cancellation.

**Comment by soloman817** [comment]
P.S, why we need load the assembly instead of read the type attributes by Cecil is, we need make instance of the type which has some attributes, then we call a function on that instance to do the compilation. 

You can reference here: http://quantalea.com/static/app/manual/compilation-aot_compilation_in_detail.html

because we support JIT (Just-In-Time, in runtime) compile, so the AOT (ahead-of-time, in Fody time)  compile is to create those instances during Fody time, and do JIT compile in Fody, then insert the generated GPU code.

**Comment by soloman817** [comment]
In one word, we compile GPU code during Fody time, and the source of the compilation is some objects which have to be created during runtime, so we have to load the assembly instead of reading them via Mono.Cecil.

**Comment by SimonCropp** [comment]
If you want explicit cleanup then your weavers should implement IDisposable
https://github.com/Fody/Fody/blob/master/FodyIsolated/InnerWeaver.cs#L145

**Comment by soloman817** [comment]
First, thanks very much for mention that fody plugin disposing method, I will fix our plugin by impl a IDisposable interface.

well, I think I'm talking about another issue. The MSBuild task has a cancellation, so, when I am in compiling (triggered by Fody), and that takes long time, so maybe user want to click the Cancel botton, and MSBuild allow that if the MSBuild task implemented ICancellableTask, but I cannot get that cancellation event from fody framework.

See this: http://stackoverflow.com/questions/9865982/how-do-you-write-an-msbuild-task-to-support-cancelation

**Comment by soloman817** [comment]
and currently, if we click Cancel botton during Fody compiling, MSBuild will wait fody task to be executed, that is fine. So I think this is not an issue, it is actually a feature improvement.

**Comment by distantcam** [comment]
@soloman817 Why are you using Fody for this? Why not just add build steps as part of the msbuild chain instead?

WPF does a similar thing with xaml files. They're processed as part of the build to baml files, which are then embedded as resources into the final assembly.

**Comment by soloman817** [comment]
@distantcam I think the reasons are:
- reuse some code, like insert resources
- for future extension, we might weave some GPU launching code in the future.

**Comment by SimonCropp** [comment]
Done in 1.28

Add this

    public void Cancel()
    {
    }

**Comment by soloman817** [comment]
Thanks :)
