### ISSUE TITLE
The "Fody.WeavingTask" task was not given a value for the required parameter "DefineConstants"

### ISSUE THREAD

**Issue by Hamcker** [Fody/Fody#159]
When installing Fody 1.27.0, just when compiling it shows following error and compilation fails. I checked out the source, DefineConstants is NOT required by attributes.

**The "Fody.WeavingTask" task was not given a value for the required parameter "DefineConstants"**

how can i solve it?

**Comment by SimonCropp** [comment]
try this http://www.nuget.org/packages/Fody/1.27.1-beta01

**Comment by Hamcker** [comment]
unfortunately didn't work :/

**Comment by SimonCropp** [comment]
upload a repro somewhere

**Comment by Hamcker** [comment]
I don't know if u r able to see this?
Please checkout and inform me.
https://Hamcker@bitbucket.org/hamckerteam/fodydefineconstants.git

**Comment by madhon** [comment]
I'm seeing exactly the same problem,  installed fody plus costura and the propertychanged taks into a brand new project

**Comment by SimonCropp** [comment]
can u try http://www.nuget.org/packages/Fody/1.27.1-beta03

**Comment by bendiksolheim** [comment]
We had the exact same problem, and fixed it by adding compile constant "Release" to the release build. I guess it's kind of a workaround, but at least it works.

**Comment by SimonCropp** [comment]
@bendiksolheim did http://www.nuget.org/packages/Fody/1.27.1-beta03 work for you?

**Comment by bendiksolheim** [comment]
@SimonCropp to be honest, I have not tried. We are releasing to the App Store today, so I would rather not do any large changes on things just before that :) Sorry!

**Comment by SimonCropp** [comment]
@bendiksolheim no worries. sorry for the hassle. and yes you should stick with what is stable until after your release

**Comment by madhon** [comment]
1.27.1-beta3 has fixed the error for me

**Comment by SimonCropp** [comment]
@madhon thanks.

deployed a non beta of 1.27.1 http://www.nuget.org/packages/Fody/1.27.1

**Comment by Hamcker** [comment]
@SimonCropp  thanks :)
