### ISSUE TITLE
Unhandled exception occurred

### ISSUE THREAD

**Issue by fvermeulen** [Fody/Fody#160]
I have a problem with Fody. I want to use the methodDecorator addIn, but I got a failure by building the product.

Can you help me to find the solution?

> Error: Fody: An unhandled exception occurred:
> Exception:
> Argument cannot be null.
> Parameter name: method
> StackTrace:
> at Mono.Cecil.ModuleDefinition.Import (Mono.Cecil.MethodReference,Mono.Cecil.IGenericParameterProvider) <0x000b3>
> at Mono.Cecil.ModuleDefinition.Import (Mono.Cecil.MethodReference) <0x0001f>
> at MethodDecorator.Fody.ReferenceFinder.GetMethodReference (Mono.Cecil.TypeReference,System.Func`2<Mono.Cecil.MethodDefinition, bool>) <0x00073>
> at MethodDecorator.Fody.ReferenceFinder.GetMethodReference (System.Type,System.Func`2<Mono.Cecil.MethodDefinition, bool>) <0x0002f>
> at MethodDecorator.Fody.MethodDecorator.Decorate (Mono.Cecil.MethodDefinition,Mono.Cecil.CustomAttribute) <0x000ff>
> at ModuleWeaver.Execute () <0x001e7>
> at (wrapper dynamic-method) object.lambda_method (System.Runtime.CompilerServices.Closure,object) <0x0002f>
> at InnerWeaver.ExecuteWeavers (System.Collections.Generic.List`1<WeaverHolder>) <0x000a6>
> at InnerWeaver.Execute () <0x00127>
> 
> Source:
> Mono.Cecil
> TargetSite:
> Mono.Cecil.MethodReference Import(Mono.Cecil.MethodReference, Mono.Cecil.IGenericParameterProvider)
>  (MyApp)

Fody-version: 1.27.1 (tested also with 1.26.4)
MethodDecorator.Fody: 0.8.1.1

**Comment by SimonCropp** [comment]
can u please raise this in the MethodDecorator repo
