### ISSUE TITLE
Fody causes CA1062 Errors

### ISSUE THREAD

**Issue by dalealleshouse** [Fody/Fody#163]
Including Fody via nuget causes code analysis to raise false positive errors. Specifically CA1062: Validate arguments of public methods. Has anyone seen this before?

Thanks in advance for your help! I love Fody!

**Comment by SimonCropp** [comment]
What weaver and can u supply the offending class?

**Comment by dalealleshouse** [comment]
It happens without even installing a weaver. Just referencing the base Fody nuget package. It happens in all of my classes, but here is an example of one.

    public class CustomerListStatusBuilder : ModuleStatusBuilder
    {
        public CustomerListStatusBuilder(Module module)
            : base(module)
        {
        }

        public override ModuleStatus BuildStatus(Portal portal)
        {
            if (portal == null)
            {
                throw new ArgumentNullException("portal");
            }

            if (portal.Survey == null || portal.Survey.State != SurveyState.Approved)
            ...
        }
    }

**Comment by SimonCropp** [comment]
i cant repro this. can you upload a repro somewhere?

**Comment by dalealleshouse** [comment]
This demonstrates the problem: https://github.com/dalealleshouse/FodyExample

Thank you very much for your time.

**Comment by SimonCropp** [comment]
@dalealleshouse so that seems to be a problem with MethodDecorator. this is not a project i manage. can u please raise an issue over here https://github.com/Fody/MethodDecorator
