### ISSUE TITLE
Collection properties, the event OnPropertyChanged isn't raised

### ISSUE THREAD

**Issue by dechandt** [Fody/Fody#166]
When I user collection properties, the event OnPropertyChanged isn't raised when I add or remove items from this collection.

```c#
var b = new A();

//On Add, OnPropertyChange isn't raised 
b.B.Add(new B());

//On Clear, OnPropertyChange isn't raised 
b.B.Clear();
```

```c#
[ImplementPropertyChanged]
public class A
{
    BCollection _b;

    public BCollection B
    {
        get
        {
            if (_b == null)
                _b = new BCollection();
            return _b;
        }
    }

    public void OnPropertyChanged(string propertyName, object before, object after)
    {
    }
}
public class B
{
    public string C { get; set; }
}
public class BCollection : System.Collections.ObjectModel.Collection<B>
{
}
```

**Comment by distantcam** [comment]
Correct. That is what [`INotifyCollectionChanged`](https://msdn.microsoft.com/en-us/library/system.collections.specialized.inotifycollectionchanged(v=vs.110).aspx) is for.

Also you probably meant to open this here https://github.com/Fody/propertychanged instead

**Comment by dechandt** [comment]
Yes, I meant to open into https://github.com/Fody/propertychanged.
So, **ImplementPropertyChanged**, does not inject **INotifyCollectionChanged** in Collection Properties?

**Comment by SimonCropp** [comment]
No it doesnt
