### ISSUE TITLE
Reference FodyCommon from within a weaver

### ISSUE THREAD

**Issue by eggapauli** [Fody/Fody#172]
The [docs](https://github.com/Fody/Fody/wiki/ThrowingAnExceptionFromAnAddin) say you can throw a special exception (`WeavingException`) to denote an error. `WeavingException` is defined in `FodyCommon`, so I need a reference to this dll.
The NuGet package `Fody` is a [development dependency](https://docs.nuget.org/release-notes/nuget-2.7#development-only-dependencies) and therefore NuGet won't reference the dll from within the project.  
The only way I currently see is cloning Fody, building it and referencing it from within my project (that also requires ILMerging it). This seems to be quite complicated for such a requirement. Is there an easier way? Am I missing something?

**Comment by SimonCropp** [comment]
Just copy the class definition

**Comment by eggapauli** [comment]
Ahh ok, so it's based on the full type name only? Perfect, thanks.

**Comment by SimonCropp** [comment]
Yep. Can u suggest edits to the doco to clarify this?

**Comment by eggapauli** [comment]
Hm I think instead of

> If the exception type is WeavingException then it will be interpreted as an "error".

i would write

> If you throw an exception named `WeavingException` then it will be interpreted as an "error".

But maybe it's just me that didn't understand it.
