### ISSUE TITLE
Is there a way to get the source file/line for a given class/method?

### ISSUE THREAD

**Issue by benblo** [Fody/Fody#178]
I'm aware that with partials and stuff this is non-trivial, but I seem to remember having seen an example of this somewhere...
I've tried getting the first instruction of the first method of the TypeDefinition, but the SequencePoint is null. Isn't the ModuleDefinition loaded with debug symbols?

**Comment by distantcam** [comment]
The module is loaded with debug symbols, but the first method and the first instruction may not have a sequence point.

Generally I search for the first instruction with a sequence point in a method.

**Comment by SimonCropp** [comment]
@benblois this what you want ?

```

    public static FileLocation GetLocation(this TypeDefinition typeDefinition)
    {
        foreach (var method in typeDefinition.Methods.Where(x => x.HasBody))
        {
            foreach (var instruction in method.Body.Instructions)
            {
                if (instruction.SequencePoint != null)
                {
                    return new FileLocation { Url = instruction.SequencePoint.Document.Url };
                }
            }
        }
        throw new Exception("Could not find location for " + typeDefinition.FullName);
    }
    public class FileLocation
    {
        public string Url { get; set; }
    }
    public static MethodLocation GetLocation(this MethodDefinition method)
    {
        foreach (var instruction in method.Body.Instructions)
            {
                if (instruction.SequencePoint != null)
                {
                    return new MethodLocation
                    {
                        Url = instruction.SequencePoint.Document.Url,
                        Line = instruction.SequencePoint.StartLine
                    };
                }
            }
        throw new Exception("Could not find location for " + method.FullName);
    }
    public class MethodLocation
    {
        public string Url { get; set; }
        public int Line { get; set; }
    }
```

**Comment by benblo** [comment]
Yes that works thanks! Though apparently some of my classes don't have any methods, or methods without a body. I looked around but couldn't find SequencePoints for fields, so I guess the info is just lost...

**Comment by SimonCropp** [comment]
i dont think fields have sequence points. 

but this is really a question specific to mono suggest u qualify the question here https://groups.google.com/forum/#!forum/mono-cecil
