### ISSUE TITLE
Asp.net vnext support

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Fody/Fody#181]
The new ASP.NET vNext system introduces the project.json which replaces much of the functionality of the project file (though there is still an xproj for Visual Studio's benefit).  It seems like inserting build targets from nuget packages will no longer be supported (though it is a little unclear). I'd like to be able to use Fody packages with vNext at least once VS 2015 is officially released.  I assume MS has some new way of hooking into the build process. Fody should support that.

**Comment by SimonCropp** [comment]
already covered here https://github.com/Fody/Fody/issues/169

and last time i looked the doco+feature was still very much in a state of flux.

if this has changed recently, or you want to give me a hand by getting started can u chime in on 169

thanks
