### ISSUE TITLE
Stand-alone msbuild skips weave step while Visual Studio build performs it

### ISSUE THREAD

**Issue by goldshtn** [Fody/Fody#182]
I'm using Fody.Costura to merge and clean dependencies. Everything builds fine in Visual Studio, but when running stand-alone msbuild (on my machine or [AppVeyor](https://ci.appveyor.com/project/goldshtn/msos/build/job/dt4i1b0j3mg4vwsk)), the Fody.WeavingTask is skipped and the resulting .exe doesn't have its dependencies merged.

To reproduce:

```
git clone -q --branch=master git://github.com/goldshtn/msos.git C:\Temp\msos-build-test
git checkout -qf d004f874df46a81d3c4372a373e35b1f7a079170
"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "msos.sln" /verbosity:detailed
```

This creates bin\x64\Debug\msos.exe that can't launch because it doesn't have the dependencies merged in. Building the same solution in Visual Studio 2013 works fine.

Here is the relevant section from the resulting build log:

```
Target "WinFodyTarget" in file "C:\Temp\msos-build-test\packages\Fody.1.26.1\build\Fody.targets" from project "C:\Temp\msos-build-test\msos\msos.csproj" (target "Compile" depends on it):
Using "Fody.WeavingTask" task from assembly "C:\Temp\msos-build-test\packages\Fody.1.26.1\build\..\\Fody.dll".
Task "Fody.WeavingTask"
    Fody (version 1.26.1.0) Executing
    ProjectDirectory: 'C:\Temp\msos-build-test\msos\'.
    AssemblyPath: 'C:\Temp\msos-build-test\msos\obj\x64\Debug\msos.exe'
    Found path to weavers file 'C:\Temp\msos-build-test\msos\FodyWeavers.xml'.
    Did not process because file has already been processed.
    Finding weavers
    Adding weaver dlls from 'C:\Temp\msos-build-test\Packages'.
    Fody weaver file added 'C:\Temp\msos-build-test\Packages\Costura.Fody.1.3.3.0\Costura.Fody.dll'
    Could not find packages dir from nuget config.
    SolutionDirectoryPath: C:\Temp\msos-build-test\
    Adding weaver dlls from 'C:\Temp\msos-build-test\packages'.
    Fody weaver file added 'C:\Temp\msos-build-test\packages\Costura.Fody.1.3.3.0\Costura.Fody.dll'
    SolutionDirectoryPath: C:\Temp\msos-build-test\
    Skipped scanning 'C:\Temp\msos-build-test\Tools' for weavers since it doesn't exist.
    No Weaver project file found.
    Finished finding weavers 25ms
      Finished Fody 148ms.
Done executing task "Fody.WeavingTask".
Done building target "WinFodyTarget" in project "msos.csproj".
```

When run from Visual Studio, the build log is slightly different -- notably, the line "Did not process because file has already been processed." is not displayed:

```
2>Target "WinFodyTarget" in file "C:\Dev\msos\packages\Fody.1.26.1\build\Fody.targets" from project "C:\Dev\msos\msos\msos.csproj" (target "Compile" depends on it):
2>Using "Fody.WeavingTask" task from assembly "C:\Dev\msos\packages\Fody.1.26.1\build\..\\Fody.dll".
2>Task "Fody.WeavingTask"
2>    Fody (version 1.26.1.0) Executing
2>    ProjectDirectory: 'C:\Dev\msos\msos\'.
2>    AssemblyPath: 'C:\Dev\msos\msos\obj\x86\Release\msos.exe'
2>    Found path to weavers file 'C:\Dev\msos\msos\FodyWeavers.xml'.
2>    SolutionDirectory path is 'C:\Dev\msos\'
2>    Finding weavers
2>    Adding weaver dlls from 'C:\Dev\msos\Packages'.
2>    Fody weaver file added 'C:\Dev\msos\Packages\Costura.Fody.1.3.3.0\Costura.Fody.dll'
2>    Could not find packages dir from nuget config.
2>    SolutionDirectoryPath: C:\Dev\msos\
2>    Adding weaver dlls from 'C:\Dev\msos\packages'.
2>    Fody weaver file added 'C:\Dev\msos\packages\Costura.Fody.1.3.3.0\Costura.Fody.dll'
2>    SolutionDirectoryPath: C:\Dev\msos\
2>    Skipped scanning 'C:\Dev\msos\Tools' for weavers since it doesn't exist.
2>    No Weaver project file found.
2>    Finished finding weavers 5ms
2>    Creating a new AppDomain
2>    Reference count=13
2>    Found debug symbols at 'C:\Dev\msos\msos\obj\x86\Release\msos.pdb'.
2>    Weaver 'C:\Dev\msos\Packages\Costura.Fody.1.3.3.0\Costura.Fody.dll'.
2>      Initializing weaver
2>      Loading 'C:\Dev\msos\Packages\Costura.Fody.1.3.3.0\Costura.Fody.dll' from disk.
2>      Executing Weaver 
2>      	Embedding 'C:\Dev\msos\ClrMemDiagExt\bin\x86\Release\ClrMemDiagExt.dll'
2>      	Embedding 'C:\Dev\msos\ClrMemDiagExt\bin\x86\Release\ClrMemDiagExt.pdb'
2>      	Embedding 'C:\Dev\msos\packages\CommandLineParser.2.0.71-alpha\lib\net45\CommandLine.dll'
2>      	Embedding 'C:\Dev\msos\packages\SharpZipLib.0.86.0\lib\20\ICSharpCode.SharpZipLib.dll'
2>      	Embedding 'C:\Dev\msos\packages\NetSerializer.3.0.0.0\lib\net40\NetSerializer.dll'
2>      Finished 'Costura' in 675ms 
2>  
2>      Writing assembly to 'C:\Dev\msos\msos\obj\x86\Release\msos.exe'.
2>      Finished writing assembly 528ms.
2>      Finished Fody 1705ms.
2>Done executing task "Fody.WeavingTask".
2>Done building target "WinFodyTarget" in project "msos.csproj".
```

**Comment by SimonCropp** [comment]
Please try with the newest nugets

**Comment by goldshtn** [comment]
I have the newest version of Costura, I updated Fody itself to 1.29.0-beta01 and now I'm getting a different error (VS still builds fine, it's just MSBuild):

```
The target "NonWinFodyTarget" listed in an AfterTargets attribute at "C:\Users\Sasha\Downloads\msos-master\msos\msos.csproj (227,47)" does not exist in the project, and will be ignored.
```

**Comment by goldshtn** [comment]
If it helps, here is the current state of my project after switching to the latest Fody NuGet: https://www.dropbox.com/s/ht4vxwv22vi0nuv/msos-master-withlatestfody.zip.zip?dl=0

**Comment by goldshtn** [comment]
I can also repro this with a clean new console application:

1) Create new C# console app
2) Add Fody 1.29.0-beta01 (latest)
3) Add Fody.Costura (latest)
4) From PM console, run `Install-CleanReferencesTarget`

Compiling from command line with MSBuild.exe produces the following message in the log:

```
The target "NonWinFodyTarget" listed in an AfterTargets attribute at
"C:\Temp\CosturaRepro\CosturaRepro\CosturaRepro.csproj (97,47)"
does not exist in the project, and will be ignored.
```

Compiling from Visual Studio -- builds fine, including:

```
1>Task "Fody.VerifyTask"
1>    Found path to weavers file 'C:\temp\CosturaRepro\CosturaRepro\FodyWeavers.xml'.
1>      Skipped Verifying assembly since it is disabled in configuration
1>      Finished verification in 4ms.
```

**Comment by SimonCropp** [comment]
@goldshtn i run https://www.dropbox.com/s/ht4vxwv22vi0nuv/msos-master-withlatestfody.zip.zip?dl=0 through msbuild and it works fine. r u restoring packages before building?

**Comment by SimonCropp** [comment]
@goldshtn something is definitely off with your setup. the target NonWinFodyTarget no longer exists in https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets. can u search your code base for NonWinFodyTarget

**Comment by goldshtn** [comment]
@SimonCropp Have you tried reproducing using my latest steps? I just tried it again with Fody-1.29.0 (published on July 20) and I'm getting the same result, which mentions NonWinFodyTarget. Is there any chance that the Install-CleanReferencesTarget cmdlet is doing the wrong thing? Here's where NonWinFodyTarget is mentioned in my .csproj file:

```
<Target Name="CleanReferenceCopyLocalPaths" AfterTargets="AfterBuild;NonWinFodyTarget">
    <CosturaCleanup Config="FodyWeavers.xml" Files="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')" />
  </Target>
```

**Comment by goldshtn** [comment]
It sure seems Install-CleanReferencesTarget wasn't updated. It still installs CosturaCleanup after NonWinFodyTarget. See [commands.psm1 line 76](https://github.com/Fody/Costura/blob/c58b420dc3c66f721eb759d6e691570361049bab/Fody/NugetAssets/commands.psm1#L76).

**Comment by distantcam** [comment]
> The target "NonWinFodyTarget" listed in an AfterTargets attribute at
"C:\Users\Sasha\Downloads\msos-master\msos\msos.csproj (227,47)" does not
exist in the project, and will be ignored.

Does this actually cause an error or is it just a warning? Install-CleanReferencesTarget wasn't updated because it still needs to work with older versions of Fody.

**Comment by goldshtn** [comment]
@distantcam It actually causes a problem, because the references are cleaned from the output directory, but the main executable does not embed them -- so you get FileNotFoundException at runtime when a referenced assembly is used.

**Comment by goldshtn** [comment]
@distantcam [Here's](https://www.dropbox.com/s/nhokodv0nknzvib/CosturaRepro2.zip?dl=0) a repro. Unzip, run msbuild on the CosturaRepro2.sln. Then launch bin\Debug\CosturaRepro2.exe -- it fails because the dependency was not embedded in it.

**Comment by SimonCropp** [comment]
@distantcam 

> still needs to work with older versions of Fody.

set a min version dependency on fody?

**Comment by SimonCropp** [comment]
can u raise this on the costura project. it doesnt seem to be a fody issue
