### ISSUE TITLE
Exception during build in VS2015 Enterprise (Release version)

### ISSUE THREAD

**Issue by Torgrimm** [Fody/Fody#187]
The only active weaver for the project is PropertyChanged.Fody 1.50.1

6>  Fody (version 1.11.5.0) Executing
6>MSBUILD : error : Fody: An unhandled exception occurred:
6>MSBUILD : error : Exception:
6>MSBUILD : error : Unknown custom metadata item kind: 6
6>MSBUILD : error : StackTrace:
6>MSBUILD : error :    bei Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
6>MSBUILD : error :    bei Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
6>MSBUILD : error :    bei Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
6>MSBUILD : error :    bei Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
6>MSBUILD : error :    bei Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
6>MSBUILD : error :    bei Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
6>MSBUILD : error :    bei Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
6>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
6>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
6>MSBUILD : error :    bei Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
6>MSBUILD : error :    bei Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
6>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
6>MSBUILD : error :    bei Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
6>MSBUILD : error :    bei InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\cb27d9fe612cd341\FodyIsolated\ModuleReader.cs:Zeile 16.
6>MSBUILD : error :    bei InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\cb27d9fe612cd341\FodyIsolated\InnerWeaver.cs:Zeile 31.
6>MSBUILD : error : Source:
6>MSBUILD : error : Mono.Cecil.Pdb
6>MSBUILD : error : TargetSite:
6>MSBUILD : error : Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)
6>MSBUILD : error : 
6>  	Finished Fody 132ms.

**Comment by distantcam** [comment]
Please update Fody to the latest version.

See also:
- https://github.com/jbevain/cecil/issues/186
- #129 #141 #171 #184
- https://github.com/Fody/Costura/issues/109
- https://github.com/Fody/PropertyChanged/issues/126

**Comment by Torgrimm** [comment]
Thanks for the quick help. That worked.
Somehow the update-package didn't worked. I had to remove everything Fody related from the project file.

I guess there were some conflicting lines from an earlier manual installation of Fody.

**Comment by alexjp** [comment]
its weird, i get something similar with Visual Studio 2015 Comunity:
```
Severity	Code	Description	Project	File	Line
Error		NotifyPropertyWeaver: Unhandled exception occurred Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(String module, ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(String module, BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at WeavingCommon.ModuleReader.Execute()
   at NotifyPropertyWeaverMsBuildTask.WeavingTask.Inner()
   at NotifyPropertyWeaverMsBuildTask.WeavingTask.Execute()	CostDistribution		
```

**Comment by SimonCropp** [comment]
can u please try to update to the newest of https://github.com/Fody/PropertyChanged and fody

and remove NotifyPropertyWeaver

**Comment by alexjp** [comment]
@SimonCropp I have Fody 1.29.0 and PropertyChanged.Fody 1.50.1.

I dont understand the "and remove NotifyPropertyWeaver". 

These are my nuget packages.config:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Caliburn.Micro" version="1.5.2" targetFramework="net4" />
  <package id="EntityFramework" version="6.0.2" targetFramework="net4" />
  <package id="Extended.Wpf.Toolkit" version="2.0.0" targetFramework="net4" />
  <package id="Fody" version="1.29.0" targetFramework="net4" developmentDependency="true" />
  <package id="PropertyChanged.Fody" version="1.50.1" targetFramework="net4" developmentDependency="true" />
</packages>
```

Also could it be that this is : "Unknown custom metadata item kind: 7", make it a different problem ?

**Comment by SimonCropp** [comment]
@alexjp upload a repro somewheree and i will debug it

**Comment by jpleed3** [comment]
I was getting a similar error with kind 6 when I first opened my project in VS2015. I opened my csproj file and found this, which was probably left over from NotifyPropertyChanged:

 <Target Name="AfterCompile">
    <NotifyPropertyWeaverMsBuildTask.WeavingTask />
  </Target>

Removing it solved my problem.

**Comment by alexjp** [comment]
@SimonCropp thanks for the help, but there is no need, @jpleed3 solved it!! i had the same thing!!

in my case, i had:
```
<UsingTask TaskName="NotifyPropertyWeaverMsBuildTask.WeavingTask" AssemblyFile="$(SolutionDir)Tools\NotifyPropertyWeaverMsBuildTask.dll" />
  <Target Name="AfterCompile">
    <NotifyPropertyWeaverMsBuildTask.WeavingTask />
  </Target>
```

Removed it, and it worked !
Being in the project file, must be why i did not find anything on searching NotifyPropertyWeaver.

Thank you @jpleed3  and @SimonCropp

**Comment by SimonCropp** [comment]
@jpleed3 good to hear

**Comment by jesperat** [comment]
Moved to VS2015 from VS2013.  In my case, I had to remove nuget references to older version of fody in my .csproj file.
Thanks!

**Comment by GirishVenkata** [comment]
We are getting the below error with Fody 



\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: The "Fody.WeavingTask" task failed unexpectedly. 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///c:\Jenkins\workspace\packages\Fody.2.0.3\FodyIsolated.dll' or one of its dependencies. Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    --- End of inner exception stack trace --- 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName) 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at ContainsTypeChecker..cctor() 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    --- End of inner exception stack trace --- 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at ContainsTypeChecker..ctor() 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at Processor..ctor() 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at Fody.WeavingTask.Execute() 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() 
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by SimonCropp** [comment]
@GirishVenkata did u try updating to the latest as is discussed in this issue?

**Comment by GirishVenkata** [comment]
its working after updating to latest package
