### ISSUE TITLE
About NuGet ids ending with ".Fody"

### ISSUE THREAD

**Issue by picrap** [Fody/Fody#188]
Hi,

the documentation states that packages name must end with ".Fody", and my experience shows that it's true :wink: 
Is it possible (I didn't look at the code) to remove this constraint? Not that I'm ashamed of using Fody, but I like small ids and URLs :smile:

**Comment by SimonCropp** [comment]
this is done for per reasons so we only need to scan a subset of assemblies in the packages directory

> small ids and URLs

what is the real impact of an extra 5 characters?

**Comment by picrap** [comment]
Right, the scan is a good reason
However, parsing directories whose name does not necessarily contain "Fody" and looking for assemblies whose name containes "Fody" would not really slow down parsing, would it? :wink: 
So to me:
- having `Fody` in the assembly name seems OK (I mean necessary)
- `Fody` in package id and hence in folder name is probably not necessary.
:stuck_out_tongue:

**Comment by SimonCropp** [comment]
@picrap sorry i cant really see enough value in changing this convention.
