### ISSUE TITLE
No PowerShell

### ISSUE THREAD

**Issue by DamianReeves** [Fody/Fody#192]
Given the fact that nuget is moving towards not running PowerShell scripts as part of the install experience, what is the current recommendation for Fody Addins?

**Comment by SimonCropp** [comment]
please try https://www.nuget.org/packages/Fody/1.29.1-beta2 and https://www.nuget.org/packages/PropertyChanged.Fody/1.50.2-beta2

**Comment by DamianReeves** [comment]
I'm curious. What has changed in these packages? I notice PropertyChanged.Fody still has an install.ps1 file.

**Comment by SimonCropp** [comment]
It uses msbuild to give u an error telling u how to modify fodyweavers.xml

It is the best I can do

The install.ps1 still delivers some value for the old project types
