### ISSUE TITLE
Specify config-filenames

### ISSUE THREAD

**Issue by MartinDemberger** [Fody/Fody#193]
In my solution I use Costura to embed a few of the referenced DLLs. I'm ably the generate the list of the embedded DLLs in the build-script.

If I use hand written config files and generated ones this isn't possible now because the used file must have the name 'FodyWeavers.xml'. It would be good if I can specify the names of the used config-files as parameter of FodyTask.

**Comment by SimonCropp** [comment]
Sorry i dont understand. Why would u want the list of embedded dlls to be dynamic?

**Comment by MartinDemberger** [comment]
I always embed all of my own dlls but now foreigner-dll. This has to be done in several projects which produce different exe-files.

**Comment by SimonCropp** [comment]
But at the project level the list of assemblies should be known statically. Hence u can hard code them

**Comment by MartinDemberger** [comment]
You are right: I can. But it's a moving target as I'm adding more and more projects to my solution (currently 132 projects including tests).
But this isn't the point. The point is that I want to use several fody-config-files in one project which isn't currently possible.

**Comment by SimonCropp** [comment]
they why cant u just hard code the list of foreigner dlls that you dont want merged https://github.com/Fody/Costura#excludeassemblies

But i dont seem to be understanding the complexities of you problem. Can you upload a solution structure that illustrates this probelm

**Comment by MartinDemberger** [comment]
To make it short: I want to have two config-files FodyWeavers-Costura.xml and FodyWeavers.xml in one project.
Background is that I have a very dynamic solution and want to embed all dlls with a specific file pattern. So FodyWeavers-Costura.xml is generated in the msbuild-script and FodyWeavers.xml is hand written and contains other Fody-Plugins.

**Comment by MartinDemberger** [comment]
I have found another solution. I generate FodyWeavers.xml with Costura and the additional plugins. It's no problem for me to define the additional plugins in the build-file.
