### ISSUE TITLE
Updated packages to latest version (1.29.3), now getting 'XXX expected to be executed'

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#194]
Pre: it was all working fine

Updated Fody, ModuleInit, ObsoleteEx, etc to latest version

Post: XXX expected to be executed. You may need to manually add '<XXX />' into your FodyWeavers.xml. eg <Weavers><XXX/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage

**Comment by GeertvanHorrik** [comment]
```
1>C:\Source\Gum.Ui\lib\Obsolete.Fody.4.0.1\build\dotnet\Obsolete.Fody.targets(13,5): error : XXX expected to be executed. You may need to manually add '<XXX />' into your FodyWeavers.xml. eg <Weavers><XXX/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage
```

**Comment by GeertvanHorrik** [comment]
I think you forgot to update Obsolete.Fody.targets when applying the latest fix.

**Comment by SimonCropp** [comment]
this should be fixed now. BTW what project type r u getting this in?

**Comment by GeertvanHorrik** [comment]
Thanks. This was NET40 / NET45.

**Comment by SimonCropp** [comment]
>Thanks. This was NET40 / NET45.

That is very strange. that file should not be include in those project types https://github.com/Fody/Obsolete/blob/master/Fody/Fody.csproj#L129

can u get me a repro, my understanding might be wrong

**Comment by GeertvanHorrik** [comment]
It's NET40 / NET45 and they share a common shared project. I will try to repro on a small project, but let me first fix the async thing.

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orchestra/blob/develop/src/Examples/Orchestra.Examples.TaskRunner/Orchestra.Examples.TaskRunner.NET45/Orchestra.Examples.TaskRunner.NET45.csproj#L120
