### ISSUE TITLE
Weaver with embedded dependencies (using Costura)

### ISSUE THREAD

**Issue by picrap** [Fody/Fody#201]
Hi,

I don't know if this question should be here or in Costura. It seems that Costura does the job, so I'm asking here :wink: 

I am working on my own Fody module (https://github.com/ArxOne/MrAdvice), and wanted to embed a reference in the weaver (the weaver references the library assembly).
When Fody tries to load the weaver, it fails saying that it can not find the referenced assembly which in embedded.
Am I missing something?
The build can be seen here: https://ci.appveyor.com/project/picrap/mradvice/build/weaving-advice-144 and the error messages are visible.
Also, the project and branch is here: https://github.com/ArxOne/MrAdvice/tree/weaving-advice . You can simply download the zip and build the solution (however this is probably not necessary).

Thanks for help.

**Comment by SimonCropp** [comment]
Costura is designed for people who own the top level application. You should avoid using it inside a library. I suggest you use ILMerge instead

**Comment by picrap** [comment]
Sure! But since I write a Fody weaver, you own the top level application, so it would have been great to allow this special feature...

**Comment by SimonCropp** [comment]
but fody is a pluggable tool. and costura doesnt actually change the assembly identity so two different addins could embed different versions of the same ref and cause all kinds of weird assembly loading issues. so this would be a bad idea to attempt to support it

also isnt just easy for you to ilmerge? i dont understand what costura adds any value for you here?

**Comment by picrap** [comment]
OK, your answer makes sense, so I'm going to use ILMerge (which I had in mind as a second choice).
