### ISSUE TITLE
Cant build after updating to VS2015

### ISSUE THREAD

**Issue by gfrSE** [Fody/Fody#202]
Getting this error message:

`1>D:\GFR\HMI\trunk\hmi\packages\Fody.1.29.3\build\portable-net+sl+win+wpa+wp\Fody.targets(50,5): error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly D:\GFR\HMI\trunk\hmi\packages\Fody.1.29.3\build\portable-net+sl+win+wpa+wp\..\packages\Fody.1.14.0\Fody.dll. Could not load file or assembly 'file:///D:\GFR\HMI\trunk\hmi\packages\Fody.1.29.3\build\packages\Fody.1.14.0\Fody.dll' or one of its dependencies. Das System kann die angegebene Datei nicht finden. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

Using Costura (1.3.5) with Fody (1.29.3) .

Before I used VS2013 and there were no problems.

**Comment by SimonCropp** [comment]
can u upload a repro somewhere?

**Comment by gfrSE** [comment]
Building "hmi"-project

http://www.megafileupload.com/5c0g/hmi.7z

**Comment by SimonCropp** [comment]
delete `<FodyPath>..\packages\Fody.1.14.0</FodyPath>` from `hmi\hmi-dbs\hmi-dbs.csproj` and `hmi\hmi\hmi.csproj`

**Comment by gfrSE** [comment]
Great, thanks !!
