### ISSUE TITLE
VS2013 giving me "Fody.WeavingTask" task failed unexpectedly. System.IO.FileNotFoundException: Could not load file or assembly 'FodyIsolated'

### ISSUE THREAD

**Issue by Yelnik** [Fody/Fody#204]
Previously I was getting essentially this same error with some other DLL, then I was getting this error with Mono.Cecil.DLL, and finally this is the newest one VS has come up with.

I've been asking about it here but haven't found a working solution: http://stackoverflow.com/questions/32893891/unable-to-compile-project-due-to-fody-errors-nothing-with-fody-or-any-other-co

Also, I'm not sure why it references "Could not load file or assembly 'FodyIsolated, Version=1.23.2.0, Culture=neutral" when the current version of Fody I have installed is 1.29.2.

**Comment by SimonCropp** [comment]
1.23.2 is indeed strange. can u upload a repro somewhere?

**Comment by Yelnik** [comment]
Unfortunately I can't really, its a very large solution with a lot of specific things to this workplace. My VS was acting up in general and everything got reinstalled, so I'm not sure if I'll still be getting this error now or now. I'll see.

**Comment by Yelnik** [comment]
I'm actually running on a clean build of Win7 and VS2013 right now and everything is now fine. However, I do still have the 'Windows.old' where my previous Windows install was, and, if I were to run the solution from that directory, it produces the same Fody error still.

**Comment by SimonCropp** [comment]
Do u have a bad fody path somewhere https://github.com/Fody/Fody/issues/202#issuecomment-145408204

**Comment by Yelnik** [comment]
This might be the case. I may go in and check if that's what the issue is. I ended up reinstalling things because I was getting other weird stuff happening with VS (like it saying my license is expired when it isn't/wasn't). 

If I check and find out what it was I'll let you know.

**Comment by SimonCropp** [comment]
assuming u fixed this. if not please let me know

**Comment by Yelnik** [comment]
Oh I didn't see this comment. It was fixed yes, at this point I'm not sure if I know exactly how or why... At some point I had to reinstall VS and upgraded to Windows 10 etc.

It seems like there was a bad path buried somewhere in my solution, whether it was rolling back or getting rid of all the DLL's that fixed it, I'm not exactly sure. Thanks for helping.
