### ISSUE TITLE
Support for Shared Projects in Visual Studio 2015

### ISSUE THREAD

**Issue by IsmailHassani** [Fody/Fody#207]
Hi guys,
I would like to know if fody supports shared projects. I use the NotifyPropertyChanged weaver but somehow the code isn't changed. Is there something i'm doing wrong?

**Comment by SimonCropp** [comment]
Assuming u need the weaver installed on every project that uses the shared project

**Comment by IsmailHassani** [comment]
Yes indeed. It solved my issue. Thanxxx.
