### ISSUE TITLE
Using fody for simply type of method composition

### ISSUE THREAD

**Issue by kasajian** [Fody/Fody#208]
We have a rather unusual coding guideline that our developers really like.  This guideline is a system that doesn't require any tools -- it's currently done by convention by each developer.   I'm wondering if Fody can be used to make some of these tasks more streamlined.

Problem statement:
- We have multiple assemblies which all have many different relatively stand-alone and isolated static methods that perform various types of utility operations.   Examples would be extensions methods that make dictionary access more functional, to string encryption, serialization helpers, csv parsers, etc.

The problem is that when one needs to use any of method from one of those assemblies, the entire assembly gets consumed by the project.   These assemblies get big over time as people put more and more methods in them.  So we need to periodically split them, categorize them, etc.

Solution we have right now.
Rather than reference the assemblies from the various projects, and require those assemblies to be shipped, we simply place loose .cs files in a folder that people then reference into their projects using "add link".
These "loose" .cs files have the following characteristics.
1.  They are all part of an assembly called "Includes", which does get built with our main solution, but "Includes.dll" is never referenced by anyone.
2.  Every class in the Includes project is "partial", and every method is "internal".
3.  We allow only one method per file.   A class may have 5 methods, which will require 5 separate files.  Someone may only want methods 1 and 3, so those are the only ones they'll "link" into their project.  Since the classes are "partial", the C# compiler takes care of the rest.
4.  When a production project wishes to reference on of these .cs files, they create a folder in their project called "Includes" (by convention), and place a link to the file from the Includes assembly.
5.  Since these classes are never public, they do not get exposed to the outside world by any production assembly.  Otherwise when an assembly references more than one production assembly each of which had referenced the same included method, there would be a conflict, since the namespaces are the same.
6.  We also have a rule that the include file that contains the C# method also contain the unit test for that method, right in the same file.   We put #if TEST around the unit test that way it only gets compiled when the Includes assembly is built.   Actually, the Includes assembly is called 'IncludesWithTest" in our system.  It's very nice to have the unit test of a method right there next to the method.

This is working out great, but it does introduce some minor undesirable side-effects that wouldn't exist otherwise.
1.  If we followed the normal model, we'd simply reference assemblies that contain utility classes that we wanted to use.   The advantage of that is that all those classes would be public, and for extension methods would be advertised as part of Intellisense.   This means if DevA adds a new extension method to Dictionary, then DevB would discover it if they were to view the list of methods using Intellisense.   But today, DevB may only discover new methods by looking through the source files in the Includes projects, something she'll likely do infrequently.
2.  This system has multiple manual steps that one has to get just right.  There's no tooling that leads down down the right path.

I'm wondering if the "inclusion" can be done post compile, instead of the way we're doing it now.   Imagine, that the IncludesWithTests assembly would be the way I described above, except that the methods would be public so that they can be referenced by each production assembly.  However, after all the assemblies are compiled, we pull the methods out of the IncludesWithTests.dll and inject them into whatever production assembly that referenced them, change their access from public to internal and remove the reference of IncludesWithTest from the production assemblies.   

That way, the programmers workflow is to simply reference the IncludesWithTest assembly as they would any other assembly.  Visual Studio compiles and all works fine.   But after the fact, we have a Fody plug-in that does the magic.   

Thoughts?

**Comment by SimonCropp** [comment]
i think there are better ways of solving this. have you considered using Paket and source dependencies ? https://fsprojects.github.io/Paket/dependencies-file.html#Sources

**Comment by kasajian** [comment]
I guess I don't see how packet solves any of the problems I listed.

What I want is the user experience that you get when you include an assembly into your project, such as .NET itself, where Visual Studio is aware of the reference thus gives you editor support when you want to "new" a class, or call a static method, or call an extension method..   Since it's in the library of referenced assemblies, its meta-data is available for browsing.   

If you were to have a model where every single class has to be included explicitly into your project, you have the advantage of only pulling in what you need, but with the disadvantage that if you didn't know about the existence of the file, Visual Studio wouldn't be able to help you.

For instance, if I'm in a console project, i wouldn't have a reference to system.windows.forms which means i couldn't type system.windows.forms dot and then bring up the messagebox class.

What I would like is a system where a bunch of assemblies are added as references, so that I get the Visual Studio editing experience that lets me access and browse those references, but I don't want to be dependent on any of those assemblies because the post-build step is smart enough to pull the IL out for just the methods I want and insert them into my code.

This can't be done to an arbitrary library, but if a library is built based on some a set of requirements, following certain rules, etc., then it could be done.

**Comment by SimonCropp** [comment]
sorry i dont really see how fody can help with this. so closing
