### ISSUE TITLE
Problem upgrading Fody

### ISSUE THREAD

**Issue by alexew1959** [Fody/Fody#210]
Have been attempting to compile the OpenCL.net source which seems to rely on an earlier version of Fody, something I have no experience with.

I unzipped the archive, opened in in VS2015, noticed the references and using the package manager upgraded Fody and extraconstraints.Fody to the latest versions. 

On build  get the error message 
Severity	Code	Description	Project	File	Line
Error		The "Fody.WeavingTask" task could not be loaded from the assembly C:\Users\alexew.SYNAPTICSYS\Documents\Visual Studio 2015\Projects\opencl.net2\trunk\packages\Fody.1.29.3\build\portable-net+sl+win+wpa+wp\..\packages\Fody.1.17.4.0\Fody.dll. Could not load file or assembly 'file:///C:\Users\alexew.SYNAPTICSYS\Documents\Visual Studio 2015\Projects\opencl.net2\trunk\packages\Fody.1.29.3\build\packages\Fody.1.17.4.0\Fody.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OpenCL.Net		

Which seems odd, referencing both the old and new versions. I have tried to find how this path is generated with no success.  Does anyone know how to resolve this?

**Comment by SimonCropp** [comment]
can u upload a repro somewhere?

**Comment by alexew1959** [comment]
Not much to repro.  Created a new VM. Installed VS2015. Download OpenCL.Net from sourceforge (http://sourceforge.net/projects/openclnet/). Unpacked it.  There were fody related error messages.  Went to package manager and updated fody. Tried compiling.  Saw conflicting version messages. Tried finding the references that were causing the conflict but could not.

Things are a bit nuts right now but I can upload the project post updates next week.

**Comment by distantcam** [comment]
I don't understand which download you're using.

- http://sourceforge.net/projects/openclnet/files/latest/download - Had no problems building.
- http://sourceforge.net/code-snapshots/svn/o/op/openclnet/code/openclnet-code-133-trunk.zip - Had problems building, but they were related to Windows Forms in a test project.

Neither of these downloads had any projects that used Fody at all.

**Comment by alexew1959** [comment]
Bit of a deadline jam right now. Will provide more detail next week. Seemed to recall something about the extraconstraints fody addition.

**Comment by alexew1959** [comment]
Reviewing my notes I was working with the codeplex version.  It appears there ARE TWO OPENCL.NET products.  One by Ananth B and another by Olav Kalgraf.

I have been working with the Ananth B version

**Comment by SimonCropp** [comment]
I undertsand you think your repo steps "are easy" but please save some time for the people who are trying to help you and upload a repro somewhere.

**Comment by alexew1959** [comment]
I understand – just not sure where to begin since  did no coding of my own at this point – I guess next week I will upload an archive of the project that is failing as a start.  Obviously can’t upload the VM or the VS 2015 ISO due to licensing issues.

**Comment by SimonCropp** [comment]
i dont understand the need for a VM?

**Comment by alexew1959** [comment]
Lol.  I'm starting to experiment with opencl so I set up a dev vm to work in

**Comment by distantcam** [comment]
I can see the problem now.

@SimonCropp I'm not sure what `FodyPath` does in the MSBuild. Should it be set?

@alexew1959 Another alternative, if you're playing with this in a VM why not install 2013 instead of 2015? The project should compile fine then.

**Comment by SimonCropp** [comment]
FodyPath is a back door for if u dont want to used MSBuild to get the task. TBH i have never seen it used

**Comment by alexew1959** [comment]
I can give that a shot

**Comment by alexew1959** [comment]
Doesn't seem like a long term solution though if I decide this is the way the project should go

**Comment by alexew1959** [comment]
Do you still need me to upload my project or do you have sufficient information to work with?

**Comment by SimonCropp** [comment]
yes can u upload a repro

**Comment by SimonCropp** [comment]
Will reopen when u upload a repro

**Comment by alexew1959** [comment]
Still not sure what a repro looks like when all I did was download a package and then try to upgrade fody
