### ISSUE TITLE
annoying Fody warning when some projects are not set to build in the configuration manager

### ISSUE THREAD

**Issue by benblo** [Fody/Fody#212]
So I have some configurations where about half the projects in the solution are not built.
![capture_d ecran_120915_105557_am](https://cloud.githubusercontent.com/assets/574187/11682168/7e6988c4-9e63-11e5-86ef-17289352a640.jpg)

In these configurations, we get one warning per project:
> Warning	15	Fody: AssemblyPath "E:\Unity Projects\SaF\Seasons-clone\VS\AdditiveScenes\AdditiveScenes.Editor\obj\XboxOne Debug\CodingJar.AdditiveScenes.Editor.dll" does not exists. If you have not done a build you can ignore this error.	AdditiveScenes.Editor

These warnings don't even appear in the build output, so I'm not sure how they're issued, but it'd be nice if I could suppress them somehow as they kinda flood the error list...

**Comment by SimonCropp** [comment]
i am having trouble reproing this. can u upload a sample sln somewhere?
