### ISSUE TITLE
Is there an option to only weave in certain configurations?

### ISSUE THREAD

**Issue by georgebearden** [Fody/Fody#215]
I am trying to figure out if there is a way to target certain addins for specific configurations of a solution.  For example, I would like to use the `MethodTimer` addin, but only in debug and release configurations, and not in other configurations.  

It would be awesome to be able to specify the target configurations in the `FodyWeavers.xml` file or something similar.

I understand that this does not make sense for many of the addins out there, but can see it being useful for others.

Thanks!

**Comment by SimonCropp** [comment]
No. currently there is not. the reason is i am yet to see a use case for it. even in your example you could put an `#if debug` in your `MethodTimeLogger`. The JIT will then optimize away the call.

**Comment by georgebearden** [comment]
I see what you are saying about `#if debug`, but I believe that would only JIT away the logging intercept, not the actual compiled `StopWatch` code.  I was hoping for a way to not expand out the `Time` attribute into the `StopWatch` code at all, basically ignoring the `Time` attribute all together.

**Comment by SimonCropp** [comment]
have you measured how much of a performance impact this change would really have?

**Comment by georgebearden** [comment]
That is a good point!  I did some local testing and with how quick the `Stopwatch` is, the difference was negligible, e.g., ~200 milliseconds on average per 1,000,000 method calls with the `Time` attribute.  Thanks for getting back to me Simon, I am going to go ahead and close this issue.

**Comment by SimonCropp** [comment]
Curious. Were those times in release mode and with no debugger attached?

**Comment by distantcam** [comment]
You can also use #if around the Time attribute then nothing changes.

**Comment by georgebearden** [comment]
@distantcam That is a good idea also!  
@SimonCropp. Those times were in Debug on the following specs:
* Visual Studio 2015 Version 14.0.23.107
* NET Framework Version 4.6.01038
* Core i7 @ 3.5GHz

and here is the code snippet.  It might seem so quick because in the test I am intercepting the logger and not actualy outputting anything.
```csharp
public static class MethodTimeLogger
{
    public static void Log(MethodBase methodBase, long milliseconds)
    {
    }
}

class Program
{
    [Time]
    static void TestMethod()
    {
            
    }

    static void Main(string[] args)
    {
        int numIterations = 100;
        long totalMillis = 0;

        for (int i = 0; i < numIterations; i++)
        {
            var stopwatch = Stopwatch.StartNew();

            for (int j = 0; j < 1000000; j++)
                TestMethod();

            stopwatch.Stop();
            totalMillis += stopwatch.ElapsedMilliseconds;
        }
        
        Debug.WriteLine(totalMillis / numIterations);
    }
}
```

**Comment by SimonCropp** [comment]
can u try the test in release mode with no debugger attached. to get a closer approximation of the effect of a production system

u also want to put one `TestMethod();` call outside the loop to let the jit warm it up

**Comment by georgebearden** [comment]
Thanks for the tip on warming up the JIT.  I had to move to a different machine (same VS and .NET but Core i7 2.5GHz instead of 3.5GHz) and re-ran the following tests in debug with debugger attached and release without debugger attached and got the following results after 100 iterations of 1,000,000 method calls.
* Debug with debugger attached: 407 milliseconds average per 1,000,000 method calls
* Release without debugger attached: 287 milliseconds average per 1,000,000 method calls

**Comment by SimonCropp** [comment]
yeah so i think that is fast enough.  most people seem to assume a stopwatch is an expensive action to perform. but it is really only asking the clock for two numbers and then doing a diff. so it has very little impact.  I will leave this closed for now

in the next version of fody i do intend to pass the current VS config through to the weavers. so if there are some edge cases where a weaver wants to optimize for release or debug then it would be possible.  but again it has been several years and i have not seen a case where it justifies the effort

**Comment by georgebearden** [comment]
Yep, I totally agree Simon.  Thanks for working through this with me :smile:
