### ISSUE TITLE
Add a mechanism to disable Weavers without failing the build

### ISSUE THREAD

**Issue by 0x53A** [Fody/Fody#216]
when the FodyWeavers.xml file does not contain any weavers, the build fails with

     error : Fody: You don't seem to have configured any weavers.

When diagnosing an issue, it would be great to be able to temporarily disable all postprocessing.

I propose to add some mechanism to explicitly disable all wavers without failing the build.

My proposal would be to be able to set an Attribute on the `Weavers` Element which disables Fody.

e.g.:

    <?xml version="1.0" encoding="utf-8"?>
    <Weavers CompletelyDisableFody="true">
        <AutoDependencyProperty />
    </Weavers>

If this is set, no postprocessing is done by Fody.

**Comment by 0x53A** [comment]
I have started a sample implementation here: https://github.com/0x53A/Fody

**Comment by SimonCropp** [comment]
Wouldnt be be simpler to comment out the relevant lines in csproj?

**Comment by SimonCropp** [comment]
Actually i think it is time to remove that error. It was mostly a transitional thing from notifypropertyweaver. How about if we downgrade it to a warning?

**Comment by 0x53A** [comment]
> Wouldnt be be simpler to comment out the relevant lines in csproj?

Sure, but changing the csproj is non-obvious, also you need to unload the project and afterwards reload it. (This is high-level complaining =) )

> Actually i think it is time to remove that error. It was mostly a transitional thing from notifypropertyweaver. How about if we downgrade it to a warning?

Changing it to a warning is probably better: it is simpler and more obvious to the user that Fody is disabled, most people ignore Informational messages.

**Comment by distantcam** [comment]
@SimonCropp I thought that error was in there for project.json projects that may not add the weaver to the FodyWeavers.xml.

**Comment by SimonCropp** [comment]
@distantcam yeah but it is not "just for project.json" projects. thoughts on changing those things to warnings?

**Comment by distantcam** [comment]
@SimonCropp We've had the same discussion for GitVersion. Ultimately if you make it a warning then it can be escalated to error in the project settings if the user wants. De-escalating from error to warning is not possible so I always prefer warnings over errors.
