### ISSUE TITLE
Upgrading from 1.28.3 to 1.29.4 causes PEVerify to fail.

### ISSUE THREAD

**Issue by BobbyCannon** [Fody/Fody#220]
All I did was upgrade from 1.28.3 to 1.29.4 with no code changes and PEVerify fails.

```
FROM:
<package id="Fody" version="1.28.3" targetFramework="net452" developmentDependency="true" />

TO:
<package id="Fody" version="1.29.4" targetFramework="net452" developmentDependency="true" />
```

Configuration
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="true">
	<Costura />
</Weavers>
```

Build Output
```
2>    Fody:   Verifying assembly
2>MSBUILD : error : Fody: PEVerify of the assembly failed.
```

Is this due to a Fody bug or did the verify step just get better and now it is showing an existing issue in my code? What should I look for?

**Comment by BobbyCannon** [comment]
I just built a new sample project and it works fine. I guess I'll have to just dig into why my project is failing.

**Comment by ulrichb** [comment]
Could you also copy the following lines of the build log (to get the console output of PEVerify, see [PeVerifier.cs line 101](https://github.com/Fody/Fody/blob/25b7f8bfc8b94a0546a4eda7ae12905c170baaa8/Fody/PeVerifier.cs#L101))?

**Comment by BobbyCannon** [comment]
I will get you the info soon as I can. This is on a side project and right now I'm at work. ;)

**Comment by SimonCropp** [comment]
can u upload a repro somewhere

**Comment by SimonCropp** [comment]
there is a new beta version of fody on nuget. can u try that?

**Comment by BobbyCannon** [comment]
After some changes is the project I can no longer repo. Regretfully I did not do enough due diligence to maintain the failure state. 

Do you want me to close this issue?

**Comment by SimonCropp** [comment]
yeah may as well close. we can always re-open if u can repro in the future
