### ISSUE TITLE
Set FodyWeavers.xml Build-Action to None?

### ISSUE THREAD

**Issue by MeirionHughes** [Fody/Fody#221]
It seems when you install Fody the default Build Action for FodyWeavers.xml is "Content"... this unfortunately causes nupack to think its a required file (when you use project-based packing) and pull it into nupck file. Subsequently, it then gets installed via nuget into dependent projects (I think)

I know you're going to say its nuget's problem; but this has caught me out a couple of times and most other config files are set to "None".

**Comment by SimonCropp** [comment]
for me the default build action for FodyWeavers.xml is None

can u give me some nuget commands that repro this

**Comment by MeirionHughes** [comment]
I'm not doing anything special; Visual Studio 2015 community edition. Console Application 4.6. Installing Fody 1.29.4 via GUI adds FodyWeavers.xml with "Content" build action. Same happens with Install-Package Fody. 

I earlier said it was down as Resource, but I should have said Content.
