### ISSUE TITLE
Use Fody to generate IoC Registration code

### ISSUE THREAD

**Issue by molinch** [Fody/Fody#222]
Hi,

We are making mobile apps using Xamarin and one of the thing that considerably slows down app startup is the IoC registration. This happens because most IoC libs rely on reflection which is slow.
This registration, in one of our app, takes from 1 to 2 seconds. It is huge in the mobile app world.

I know how to generate the code to manually register our classes for IoC, therefore I have no clue if Fody could help for this scenario: basically use reflection, generate the code, inject it so app relies on hardcoded registration.

Do you have any idea?

**Comment by SimonCropp** [comment]
of course it is possible. but i dont know of any addin that currently does this

**Comment by distantcam** [comment]
I do know of the Stiletto project (https://github.com/benjamin-bader/stiletto) but that project hasn't updated in over a year.

The problem with doing IoC with Fody is that there are certain things that IoC does that can only be done at runtime, and Fody is a compile time tool. The main thing I can think of is assembly scanning, but if all the types are available at compile time it should be possible to create an IoC with Fody.

**Comment by molinch** [comment]
Thanks @distantcam for the link to Stileto, I will check what they did.
On our side all types are known at compile time so it would be realistic.
