### ISSUE TITLE
Updating Fody overwrites FodyWeavers.xml

### ISSUE THREAD

**Issue by WilliamBZA** [Fody/Fody#223]
Upgraded from 1.25.0 to 1.29.4 and the FodyWeavers.xml file was replaced with an empty one with no weavers.

**Comment by SimonCropp** [comment]
@WilliamBZA this was actually a bug in the uninstall of older versions. which i cant fix since i cant retroactively patch those nugets without doing the uninstall. if it happens moving forward raise another issue
