### ISSUE TITLE
Framework version of plugins

### ISSUE THREAD

**Issue by dittodhole** [Fody/Fody#230]
The documentation does not contain any information on this issue, so I thought I might ask here.

Which .NET Framework version should be targeted in plugins?
Is there any binding to the framework version of Fody or is a weaver somehow executed in a disconnected way?
If Fody is currently written against .NET 4.0, I strongly suggest upgrading to (at least) .NET 4.5.2, since [Microsoft discontinues .NET 4.0, 4.5 and 4.5.1](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/).

**Comment by SimonCropp** [comment]
plugins should target the same of higher version of .net as fody.

so yes 4.5.2 should work fine.
