### ISSUE TITLE
MissingMethodException on static property

### ISSUE THREAD

**Issue by kwaazaar** [Fody/Fody#231]
I have a public sealed class with a static property (with only a getter). Inside this getter, I invoke a static method of a class in a referenced assembly. For some reason I get a MissingMethodException (so it does seem to find the assembly itself!?).

However, not on all machines (I tested on two different Windows 10 desktops, but kept up-to-date). Not sure if this is a .NET framework version mismatch, since both have 4.6 installed.

Can I force the loading of all assemblies, for example by using a static constructor?

**Comment by SimonCropp** [comment]
what addin are you seeing this in?

also can you upload a repro?
