### ISSUE TITLE
Add weaver + version info to weaved assembly

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#232]
Sometimes I need to check which weavers and versions were used against an assembly. What do you think of a simple generated class like this:

```
[GeneratedCode("Fody", "1.29.4")]
internal static class FodyWeavingResults
{
    internal const string CatelFodyWeaver = "1.14.0";
    internal const string ModuleInitWeaver = "1.30.0";
}
```

**Comment by SimonCropp** [comment]
How about using this attribute https://msdn.microsoft.com/en-us/library/system.reflection.assemblymetadataattribute(v=vs.110).aspx

**Comment by GeertvanHorrik** [comment]
Looks good, happy to contribute if you wish.

**Comment by GeertvanHorrik** [comment]
We need to be a bit careful:

.NET Framework
Available since 4.5

**Comment by SimonCropp** [comment]
So with those limitations perhaps your idea is better?

And yep more than happy to accept a pr for this

**Comment by SimonCropp** [comment]
still want this?

**Comment by GeertvanHorrik** [comment]
Yes, sorry, still on the list. So busy, I wish I could clone myself...

**Comment by kamil-mrzyglod** [comment]
@GeertvanHorrik What about generating a file, similar to `FodyWeavers.xml`? What are your use cases?

**Comment by GeertvanHorrik** [comment]
Use case is that I can see on a deployed assembly what weavers (and version) were used. For example, I had a bug in one of the weavers, then I can quickly see if the generated assembly used a buggy version / a weaver was applied to an assembly.

**Comment by kamil-mrzyglod** [comment]
@GeertvanHorrik I see. Definitely could try to make a PR for this but for sure not this week. Please ping me if you try to implement this so I won't duplicate your work :)

**Comment by GeertvanHorrik** [comment]
@kamil-mrzyglod , if you are interested in taking this one, please do, I am swamped with OSS stuff so getting this of my list would be great. If not, let me know and I will fix this anyway.

**Comment by GeertvanHorrik** [comment]
Closing this one since we can discuss the final results in #252
