### ISSUE TITLE
Allow option to ignore specific errors for PEVerify

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#233]
For example, I have this one:

```
[MyApp.Controls.AdvertisementControl::InitializeAdControl]  [HRESULT 0x8000000F] - Typename or Namespace was not found in metadata file.
```

This is caused because the types are checked at runtime for some components in UWP. I think we can ignore this error by default or maybe allow a comma separated list of errors to ignore?

**Comment by SimonCropp** [comment]
Try this https://github.com/Fody/Fody/blob/master/Fody/PeVerifier.cs#L137

**Comment by GeertvanHorrik** [comment]
Very nice, thanks :)

**Comment by GeertvanHorrik** [comment]
Look how beautiful, thanks @SimonCropp 

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="true" VerifyIgnoreCodes="0x801318F3,0x80131869,0x8000000F">
  <ModuleInit/>
  <MethodTimer/>
  <Catel />
</Weavers>
```

**Comment by SimonCropp** [comment]
I have the memory of a gold fish. I have actually documented that https://github.com/Fody/Fody/wiki/AssemblyVerification
