### ISSUE TITLE
Recursive call property when binding with converter.

### ISSUE THREAD

**Issue by maukur** [Fody/Fody#234]
Converter Code
`public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)`
        `{`
           ` return !(bool)value;`
      `  }`
     `   public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)`
       ` {`
          `  return !(bool)value;`
     `   }`

ViewModel Code

`public bool IsVisible => true;`

Xaml 
`<ListView IsVisible="{Binding IsVisible, Converter={StaticResource BooleanInverter}}" }"/>`

**Comment by SimonCropp** [comment]
is this in the wrong project?

**Comment by maukur** [comment]
When i`m not use Fody, this code is work

**Comment by SimonCropp** [comment]
what weavers r u using?

**Comment by maukur** [comment]
I`m download last stable version fody in npm and it is automatically created "FodyWeavers.xml" 
`<Weavers>`
`  <PropertyChanged/>`
`  <AsyncErrorHandler/>`
`  <MethodTimer/>`
 ` <ConfigureAwait/>`
`</Weavers>`

**Comment by SimonCropp** [comment]
please upload a repro
