### ISSUE TITLE
Cannot build Fody project with nuget

### ISSUE THREAD

**Issue by TimMurphy** [Fody/Fody#236]
Given a simple console project
And given the project includes package Anotar.NLog.Fody, and suspect I any Fody package
When ```nuget pack <project>.csproj -Build ```
Then the following error is thrown

> c:\Users\Tim\Code\timmurphy\cannot-build-fody-project-with-nuget\packages\Fody.1.29.4\build\dotnet\Fody.targets(50,5): error MSB4127: The "Fody.WeavingTask" task could not be instantiated from the assembly "c:\Users\Tim\Code\timmurphy\cannot-build-fody-project-with-nuget\packages\Fody.1.29.4\build\dotnet\..\..\\Fody.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Fody.WeavingTask' to type 'Microsoft.Build.Framework.ITask'.
> 
> c:\Users\Tim\Code\timmurphy\cannot-build-fody-project-with-nuget\packages\Fody.1.29.4\build\dotnet\Fody.targets(50,5): error MSB4060: The "Fody.WeavingTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
> 
> Done building project "cannot-build-fody-project-with-nuget.csproj" -- FAILED.

The above can be reproduced by:

- cloning https://github.com/TimMurphy/cannot-build-fody-project-with-nuget
- nuget restore
- pack.bat

**Comment by SimonCropp** [comment]
suspect u have this issue https://github.com/NuGet/Home/issues/2356

**Comment by SimonCropp** [comment]
sure enough if i DL the nightly build from here https://dist.nuget.org/index.html it works. 

should i close this since i ti not a Fody issue?

**Comment by TimMurphy** [comment]
Probably. When I get time to breath I will check it out for myself.

On Sat, Apr 23, 2016 at 3:47 PM, Simon Cropp <notifications@github.com>
wrote:

> sure enough if i DL the nightly build from here
> https://dist.nuget.org/index.html it works.
>
> should i close this since i ti not a Fody issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fody/Fody/issues/236#issuecomment-213669676>
>



-- 
Tim Murphy

Need a website and/or blog that's easy to create and update? Check out
Impressive
Mark <http://impressivemark.com/>.

**Comment by SimonCropp** [comment]
ok will close this for now. ping me if u have more issues

**Comment by TimMurphy** [comment]
Confirmed it works with nightly build NuGet.CommandLine.3.5.0-rc-1236
