### ISSUE TITLE
Configuring weavers based on build configuration

### ISSUE THREAD

**Issue by patchandthat** [Fody/Fody#237]
I know this has been raised before, #158 and possibly relates to #179, but I have another use case where I'd like to be able to disable specific weavers based on build configuration.

Specifically, I'm using MethodDecoratorEx to inject logging code, but I don't want this to run for debug builds as it currently prevents me from stepping through the source, and the logging code is only useful for me when releasing to production.

Currently I'm working around the issue by just commenting out items in FodyWeavers.xml, but it would be nice to have a less error prone way of doing it.  I tried adding conditions to targets in the .csproj, but all I succeeded in doing that way was making a mess of things.  I guess overwriting the xml in a pre-build event could also be an option?

**Comment by SimonCropp** [comment]
>  it currently prevents me from stepping through the source

shouldnt this be fixed in MethodDecoratorEx  ?
