### ISSUE TITLE
Incorrect type for array allocated on the stack

### ISSUE THREAD

**Issue by afish** [Fody/Fody#240]
Hi!
I am using the following code to add a variable for accessing byte arrays allocated on the stack (with stackalloc keyword):
```
public void Execute()
{
     // ...
     var arrayType = ModuleDefinition.ImportReference(typeof(byte*));
     var variableDefinition = new VariableDefinition(arrayTypeDefinition);
     // ...
}
```
Code compiles and executes fine, however, the generated assembly has incorrect type in definitions. It is `uint8` instead of `uint8*`:

![incorrecttype](https://cloud.githubusercontent.com/assets/650922/15091861/62aeadca-1457-11e6-9fd4-9d4e77671273.png)

When I dump the code using ILdasm, add missing star to the type, and compile the code using ILasm it works as expected.

I have .NET Framework 4.5.1, Windows Server 2012 R2, compile application as AnyCPU in Debug mode.

**Comment by SimonCropp** [comment]
Not had to do this before. But I imagine it has something to do with using a pointertype https://github.com/jbevain/cecil/blob/master/Mono.Cecil/PointerType.cs

**Comment by SimonCropp** [comment]
suggest u raise this on the cecil project
