### ISSUE TITLE
Can't install Fody.Cecil nuget in any Xamarin project

### ISSUE THREAD

**Issue by Korayem** [Fody/Fody#242]
Error Message: Installing `Fody.Cecil` is failing because target `MonoDroid 6` isn't found

**Comment by SimonCropp** [comment]
Why r u trying to install it?

**Comment by SimonCropp** [comment]
so Fody.Cecil is specifically for people writing fody addins. so it doesnt make sense for it to be MonoDroid compat

**Comment by Korayem** [comment]
It's because I am getting an error `Could not load file or assembly 'Mono.Cecil'` while running `ConfigureAwait.Fody` nuget so I thought of installing it manually.

**Comment by SimonCropp** [comment]
sorry that is not a problem with fody. u need to raise an issue in the ConfigureAwait project
