### ISSUE TITLE
How to log the exception with Fody?

### ISSUE THREAD

**Issue by heyixiaoran** [Fody/Fody#245]
I remember Fody can log the exception with some attribute.  But now I can find the sample  and forgot which should be use. Can somebody show me how some code? Thanks

**Comment by 0xG** [comment]
Log the exception? Maybe you're talking about [`WeavingException`](https://github.com/Fody/Fody/wiki/ThrowingAnExceptionFromAnAddin)? It stops the build process and shows `WeavingException.Message` as an error.

**Comment by heyixiaoran** [comment]
No. I remember fody have a AOP way to log . Just use like LogError attribute on the method.

**Comment by SimonCropp** [comment]
do you mean this https://github.com/Fody/Anotar#exception-logging  ?
