### ISSUE TITLE
any idea of when Fody will support RTM? (or does it already support it?)

### ISSUE THREAD

**Issue by mgmccarthy** [Fody/Fody#249]

**Comment by distantcam** [comment]
It might help if you're a bit more specific as to which RTM.

**Comment by mgmccarthy** [comment]
Sorry, .NET Core RTM.

**Comment by 304NotModified** [comment]
related: https://github.com/Fody/Fody/issues/206

**Comment by SimonCropp** [comment]
Fody now supports netstandard1.4 and above. Compat will be gradually added to downstreams
