### ISSUE TITLE
Build fails if there are no weavers configured.

### ISSUE THREAD

**Issue by aensidhe** [Fody/Fody#250]
Hello.

It is very possible this is not a bug.

I have a Common project which will contain MethodDecorators for MethodDecorator weaver, so it had installed Fody nuget package in it as a dependency for MethodDecorator. But it will not use any weavers.

If I delete FodyWeavers.xml build fails with message:

```
MSBUILD : error : Fody: No configured weavers. It is possible you have not installed a weaver or have installed a fody weaver nuget into a project type that does not support install.ps1. You may need to add that weaver to FodyWeavers.xml manually. eg. <Weavers><WeaverName/></Weavers>. see https://github.com/Fody/Fody/wiki/SampleUsage [d:\Repos\eVote\Serve
r\Common\Common.csproj]
```

If I make it empty it'll fail with similar message.
If I specify MethodDecorator (as I have it installed) it fail build with message "No decorators, etc".

I have a workaround: to remove Fody's Tasks from project. But this is not good and can lead to problems while upgrading package.

My proposal is to have MsBuildProperty something like "SkipFody" to be able to write Fody-specific code without using it in place.

Regards,
Anatoly.

**Comment by weitzhandler** [comment]
I experienced the same issue. Uninstalling and re-installing `PropertyChanged.Fody` and `Fody` fixed the issue.

**Comment by eberkund** [comment]
I am experiencing the same issue, uninstalling and reinstalling several times **did not** fix the issue.

**Comment by renzska** [comment]
If your project is a .netstandard app the FodyWeavers.xml cannot be added when the package is added. You'll need to add it to the root of the project manually:

```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  
</Weavers>
```

**Comment by renzska** [comment]
@eberkund, 2.0.2 adds a check and message for this:

https://github.com/Fody/Fody/commit/5383a396c5974e205a637ccf2a42e56538607d09

**Comment by weitzhandler** [comment]
@eberkund:  
> I am experiencing the same issue, uninstalling and reinstalling several times did not fix the issue.

Surprisingly, if I'm uninstalling the package `Fody` and reinstalling it to the minimum version possible, the issue disappears.

**Comment by SimonCropp** [comment]
@aensidhe what project type are you targeting?

**Comment by eberkund** [comment]
@renzska I did create the file manually but I will give the new version I try regardless and see if it helps.

**Comment by SimonCropp** [comment]
can anyone share a repro?

**Comment by weitzhandler** [comment]
Didn't double check the repro, just writing from my memory, based on the experience I encountered, maybe not all the details are significant (for example PCL).

- Create a PCL (maybe a simple Console App or DLL will also repro)
- Add `PropertyChanged.Fody`
- Create some INPC classes
- Compile and run
- Now update the package `Fody` to the latest version
- The error should be raised

**Comment by SimonCropp** [comment]
do u choose to overwrite the fodyweavers.xml?

**Comment by weitzhandler** [comment]
I don't remember :|

**Comment by SimonCropp** [comment]
Can u verify

**Comment by eberkund** [comment]
I updated to the latest version and it is working for me now

**Comment by weitzhandler** [comment]
I now updated to the latest version (selecting overwrite) and looks like the issue is gone.

**Comment by weitzhandler** [comment]
I now updated to the latest version (selecting overwrite) and the project compiles.
There is this warning tho:
>Fody: No configured weavers. It is possible no weavers have been installed or a weaver has been installed into a project type that does not support install.ps1. It may be necessary to manually add that weaver to FodyWeavers.xm;. eg.
`<Weavers>  
    <WeaverName/>  
</Weavers>`
see https://github.com/Fody/Fody/wiki/SampleUsage	Hatzoloh.App

**Comment by SimonCropp** [comment]
@weitzhandler can u upload a repro?

**Comment by SimonCropp** [comment]
closed due to no response

**Comment by deanilvincent** [comment]
I'm working Xamarin.Forms PCL Project then I got this error. I just added the file "FodyWeavers.xml" inside the main "Portable" project then I get it running :)

**Comment by weitzhandler** [comment]
Tx for sharing!

**Comment by deanilvincent** [comment]
You're welcome @weitzhandler Did you fix yours? :)

**Comment by SimonCropp** [comment]
So I am a little confused. Do people still thnk this is a bug? Or is it just the fact that the new project system does not allow use to generate and add weavers to the fodyweavers.xml?

**Comment by weitzhandler** [comment]
@SimonCropp 
Looks like you can close it. Should I have further issues and I'll report back here.

**Comment by SimonCropp** [comment]
@weitzhandler cool. Thanks for following up

**Comment by LGFN** [comment]
I had this same issue, and yes, I hit "Yes" on the overwrite prompt (I didn't know better). For the record, I eventually solved it by adding "<PropertyChanged />" between the "<Weavers>" tags.

**Comment by Dentax** [comment]
I had the same issue too. I solved it by adding `<Costura />` to FodyWeavers.xml between the `<Weavers>` tags.

**Comment by BoiseBaked** [comment]
After wasting a lot of time, I got Fody Weaver to work and after encountering the build error "Fody: No configured weavers...." The trick is to uninstall both Fody and PropertyChanged.Fody. Then only install PropertyChanged.Fody (which will install the Fody NuGet for you). I Installed the latest available PropertyChanged.Fody NuGet (2.5.8) which installed the latest Fody NuGet available to me (3.1.3). Then I created "FodyWeavers.xml" file in the parent directory of the project folder that uses Fody and PropertyChanged.Fody NuGets, that is, not in the project folder where expect it to be. The content of "FodyWeavers.xml" in the project's parent folder must be valid XML:
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged />
</Weavers>

You know the PropertyChanged.Fody NuGet packaged is mentioned in Troelson's latest book, "Pro C# 7."

I think it would be helpful to Troelson if the NuGet author would get the install process to work correctly in the Visual Studio 2017.

**Comment by SimonCropp** [comment]
@BoiseBaked there is no trick to getting fody working. the steps are covered here https://github.com/Fody/PropertyChanged/#usage

if you have some problem after running through those steps, then please raise a new issue that includes a repo of the state of your solution.

**Comment by joshmclean** [comment]
For me, it was re-installing both Costura.Fody and Fody. After re-installing Fody (same version), I got this issue. But reinstalling Costura.Fody resolved that.
