### ISSUE TITLE
[Question] How as I supposed to change build order without adding project reference?

### ISSUE THREAD

**Issue by aensidhe** [Fody/Fody#251]
Hi.

We use command line builds with MSBuild and resharper feature "ReSharper Build" which runs build from VS as it is command line MSBuild build. So, I'm confused.

Thank you.

**Comment by SimonCropp** [comment]
Why do you need to change the build order?

**Comment by aensidhe** [comment]
@SimonCropp oh, I'm sorry, I forgot to add link.

I'm trying to use https://github.com/Fody/Fody/wiki/InSolutionWeaving . Step 3.

**Comment by SimonCropp** [comment]
Build order is stored in the .sln. So that should be respected by command line builds

**Comment by aensidhe** [comment]
@SimonCropp why can't I just add a project reference without actual assembly reference like described [here](https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/how-to-have-a-project-reference-without-referencing-the-actual-binary/)? What will go wrong?

**Comment by SimonCropp** [comment]
That should also work

**Comment by aensidhe** [comment]
Thank you.
