### ISSUE TITLE
Build fails with .net reactor (Obfuscator)

### ISSUE THREAD

**Issue by dinekro** [Fody/Fody#254]
Hello.

Our release build fails after obfuscation:

> Fody: Fody (version 1.29.2.0) Executing
> MSBUILD : error : Fody: An unhandled exception occurred:
> MSBUILD : error : Exception:
> MSBUILD : error : Недопустимый формат исполняемого файла (.exe) или библиотеки (.dll).
> MSBUILD : error : StackTrace:
> MSBUILD : error : 
> MSBUILD : error : Server stack trace: 
> MSBUILD : error :    в Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
> MSBUILD : error :    в Mono.Cecil.PE.ImageReader.ReadImage()
> MSBUILD : error :    в Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
> MSBUILD : error :    в Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
> MSBUILD : error :    в Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
> MSBUILD : error :    в IsolatedContainsTypeChecker.Check(String assemblyPath, String typeName) в c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\IsolatedContainsTypeChecker.cs:строка 13
> MSBUILD : error :    в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
> MSBUILD : error :    в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> MSBUILD : error : 
> MSBUILD : error : Exception rethrown at [0]: 
> MSBUILD : error :    в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
> MSBUILD : error :    в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
> MSBUILD : error :    в IContainsTypeChecker.Check(String assemblyPath, String typeName)
> MSBUILD : error :    в ContainsTypeChecker.Check(String assemblyPath, String typeName) в c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\ContainsTypeChecker.cs:строка 24
> MSBUILD : error :    в Processor.ShouldStartSinceFileChanged() в c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\FileChangedChecker.cs:строка 6
> MSBUILD : error :    в Processor.Inner() в c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:строка 68
> MSBUILD : error :    в Processor.Execute() в c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:строка 46
> MSBUILD : error : Source:
> MSBUILD : error : Mono.Cecil
> MSBUILD : error : TargetSite:
> MSBUILD : error : Void ReadOptionalHeaders(UInt16 ByRef, UInt16 ByRef)
> MSBUILD : error :

How we can config .csproj? Or something else?

Best regards,
Pavel

**Comment by SimonCropp** [comment]
Can u configure fody to run prior to the obfuscator?

**Comment by dinekro** [comment]
I would like to do it. How can I do that?

**Comment by SimonCropp** [comment]
i assume u are doing the obfuscation as part of msbuild, so in the csproj. so u need to change the order in your csproj

**Comment by SimonCropp** [comment]
sorry i dont have the capacity to test with.net reactor. i suggest you raise an issue with them and ask them how to fix. feel free to include me in the conversation
