### ISSUE TITLE
Request: Configurable location of fodyweavers.xml

### ISSUE THREAD

**Issue by jammerware** [Fody/Fody#255]
Hi,

Just discovered Fody - it's awesome! Is there a way to configure the location of the fodyweavers.xml file? If possible, I want the capability to place it somewhere other than the root of the project it's weaving. Is this possible?

Thanks!

**Comment by kamil-mrzyglod** [comment]
@jammerware Why would you want to change the location? What is the purpose?

**Comment by jammerware** [comment]
I'm mostly just interested in the freedom to organize my solution as I see fit. I could also see potential value in sharing configuration across projects, but I'm new to this.

**Comment by kamil-mrzyglod** [comment]
@jammerware If I remember correctly, Fody allows you to have 3 different `FodyWeavers.xml` files located:
* in your assembly executing directory(possibly `bin`)
* in your project directory
* in your solution directory

They are processed each by each so e.g. if you'd like to override solution configuration of weavers, you have to add a project-specific `FodyWeavers.xml` file.

**Comment by SimonCropp** [comment]
Sorry the complexity of this config option is not really justified.

**Comment by Arithmomaniac** [comment]
I had a similar problem, but just used a MSBuild task to copy a FodyWeavers.xml file to the project root at compile time.
