### ISSUE TITLE
Running Fody before Code Contracts

### ISSUE THREAD

**Issue by flcdrg** [Fody/Fody#259]
I'm trying out using Fody together with Code Contracts (via NuGet).

To get them playing nicely, I wanted to ensure that Fody ran before Code Contracts (so that weavers like NullGuard had a chance to do their thing).

There was a couple of things I needed to do to make this work:

Ensure that Code Contracts was imported in the .csproj file after Fody

```
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <PropertyGroup>
    <CodeContractsInstallDir>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\packages\DotNet.Contracts.1.10.20606.1\'))</CodeContractsInstallDir>
  </PropertyGroup>
```

then

```
  <Import Project="..\..\packages\Fody.1.29.4\build\dotnet\Fody.targets" Condition="Exists('..\..\packages\Fody.1.29.4\build\dotnet\Fody.targets')" />
  <Import Project="$(CodeContractsInstallDir)\MsBuild\v$(VisualStudioVersion)\Microsoft.CodeContracts.targets"/>

```

Change Fody's .targets file to hook into CompileDependsOn instead of AfterTarget.

```
  <PropertyGroup>
    <CompileDependsOn>$(CompileDependsOn); FodyTarget</CompileDependsOn>
  </PropertyGroup>
```

If that looks reasonable, I'm happy to look at creating a PR. If there's a better way to do that, I'm happy to learn!

**Comment by flcdrg** [comment]
(Having said that, Code Contracts isn't noticing the updated code after Fody runs)

**Comment by kamil-mrzyglod** [comment]
@flcdrg - I've got a similar problem(I had to run transformations from SlowCheetah before Fody), but instead messing with Fody's .targets, I imported my custom .targets file, which reconfigured the way how tasks are executed:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="RunTransformationsOnDemand" BeforeTargets="AfterCompile"
    <CallTarget Targets="TransformAllFiles"/>
  </Target>
</Project>
```

**Comment by SimonCropp** [comment]
https://github.com/Fody/Fody/pull/263#issuecomment-296443086
