### ISSUE TITLE
Visual Studio extension (vsix) using Fody includes extra assemblies

### ISSUE THREAD

**Issue by flcdrg** [Fody/Fody#260]
Building a custom Visual Studio 2015 extension that also uses Fody, causes these extra assemblies to be included in the .vsix file:
- Mono.Cecil.dll
- Mono.Cecil.Mdb.dll
- Mono.Cecil.Pdb.dll
- Mono.Cecil.Rocks.dll
- Weavers.dll
- Weavers.pdb

(the last two relate to a custom weaver that is created by a separate project in the same solution)

**Comment by SimonCropp** [comment]
what do u mean by "uses Fody"?

**Comment by GeertvanHorrik** [comment]
He probably runs Fody against his vsix file. I think you can manually exclude dependencies from vsix packaging.

**Comment by flcdrg** [comment]
I meant that i use Fody to modify the assembly which contains my VS extension. (eg. I use the PropertyChanged add-in).

Presumably there's some impact that running Fody in the build that is causing the Vsix part of the build to add these extra files to the vsix file, even though I don't have any assembly references to them.

This seems like a bug to me that by using Fody, it would leave traces of itself behind that the Vsix MSBuild targets are then noticing and spuriously adding as dependencies.

**Comment by GeertvanHorrik** [comment]
Maybe vsix packaging checks nuget, but ignores developmentDependency?

**Comment by SimonCropp** [comment]
i suspect vsix ignores copy local

**Comment by SimonCropp** [comment]
try adding a ref to something else and  setting it to copy local = false and see if it is added to the vsix

**Comment by flcdrg** [comment]
@GeertvanHorrik pretty sure it wouldn't be NuGet-related.

@SimonCropp I'll test copy local and see what happens

**Comment by GeertvanHorrik** [comment]
The reason I assumed this is because Fody & Mono are never really referenced (only via target files). Could it be this part causing it:

>> the last two relate to a custom weaver that is created by a separate project in the same solution

**Comment by flcdrg** [comment]
Ok.. Tried this:

1. Created new VSIX Project
2. Added Newtonsoft.Json through NuGet (defaults to CopyLocal=true)
3. Built project and confirmed .vsix contains Newtonsoft.Json.dll
4. Changed CopyLocal=false
5. Rebuild project and confirmed .vsix does not contain Newtonsoft.Json.dll

**Comment by flcdrg** [comment]
@GeertvanHorrik Yes, that sounds plausible

**Comment by SimonCropp** [comment]
I think u need to upload a repro. Or share a github URL

**Comment by GeertvanHorrik** [comment]
Set copy false to Mono.Cecil + the weaver to false. Fody should pick it up without a reference as well.

**Comment by flcdrg** [comment]
@GeertvanHorrik I'll give that a try. 

If it doesn't help then @SimonCropp I'll post a URL.

thanks for the suggestions

**Comment by SimonCropp** [comment]
But that's the problem. A project should have no reference to fody or Cecil

**Comment by flcdrg** [comment]
First test confirms that just using PropertyChanged does not add those assemblies, so @GeertvanHorrik I think you're right it is the custom weaver that is triggering this somehow.

**Comment by flcdrg** [comment]
Ok.. @GeertvanHorrik you were on to something. Marking the Mono.Cecil references in the custom weaver project as CopyLocal=false resulted in them not being included in the .vsix file. The Weavers.dll is still there so that's not a complete workaround.

**Comment by flcdrg** [comment]
This repo is reproducing the problem for me - https://github.com/flcdrg/XsltCop/tree/master

**Comment by GeertvanHorrik** [comment]
Is your main vsix project referencing the weaver? If so, why? If it's only so it gets build, set it as build dependency instead.

**Comment by flcdrg** [comment]
No, the main project does not reference the weaver project (unless you're seeing something I've missed)

**Comment by GeertvanHorrik** [comment]
I think I know what the cause is, but cloning the repro now. Give me 15 minutes.

**Comment by flcdrg** [comment]
No worries, thanks!

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/25437070/7a4f243c-2a95-11e7-9abf-4888b809d39d.png)

**Comment by flcdrg** [comment]
Humour me and run msbuild from the command line

**Comment by GeertvanHorrik** [comment]
2>------ Rebuild All started: Project: Gardiner.XsltTools, Configuration: Debug Any CPU ------
2>    Fody: Fody (version 1.29.4.0) Executing
2>      Fody/PropertyChanged:   	Removing reference to 'PropertyChanged'.
2>    Fody:   Finished Fody 55ms.

**Comment by GeertvanHorrik** [comment]
So it's not using the weaver?

**Comment by GeertvanHorrik** [comment]
Updating Fody to 2.0 and using the vs2017 branch.

**Comment by flcdrg** [comment]
It should be.. try doing a /t:clean first rather than rebuild?

I get 
      Fody/PropertyChanged:   Executing Weaver
      Fody/PropertyChanged:     Gardiner.XsltTools.Options
      Fody/PropertyChanged:             FeedbackAllowed
      Fody/PropertyChanged:                     FeedbackAllowed skipped since call already exists
      Fody/PropertyChanged:     Gardiner.XsltTools.Margins.TopMarginViewModel
      Fody/PropertyChanged:             SelectedValue
      Fody/PropertyChanged:                     SelectedValue
      Fody/PropertyChanged:             Templates
      Fody/PropertyChanged:                     Templates
      Fody/PropertyChanged:     Removing reference to 'PropertyChanged'.
      Fody/PropertyChanged:   Finished 'PropertyChanged' in 245ms

      Fody/Weavers:   Executing Weaver
      Fody/Weavers:   Finished 'Weavers' in 7ms

**Comment by GeertvanHorrik** [comment]
Can you show your Fody output? It's not picking up the weaver here.

**Comment by GeertvanHorrik** [comment]
But I expected Fody/[your weaver] output stuff as well. Is it running your weaver at all?

**Comment by flcdrg** [comment]
umm. let me check. So you still don't have extra binaries in the vsix?

**Comment by GeertvanHorrik** [comment]
Yep, it is running your weaver. I added a logging call to the Execute method:

```
LogInfo("Running the XsltTools weaver");
```

Now the output is:

```
2>    Fody: Fody (version 2.0.5.0) Executing
2>      Fody/PropertyChanged:   	Removing reference to 'PropertyChanged'.
2>      Fody/Weavers:   Running the XsltTools weaver
2>    Fody:   Finished Fody 660ms.
```

Vsix content:

![image](https://cloud.githubusercontent.com/assets/1246444/25437552/0769297a-2a97-11e7-9019-18cdd01409c6.png)

**Comment by flcdrg** [comment]
Curious.. and yet the AppVeyor builds are behaving the same as my machine so I know it doesn't "just work on my machine" :-)

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/25437774/c7246efa-2a97-11e7-997c-9d3b99f28ffa.png)

**Comment by flcdrg** [comment]
![image](https://cloud.githubusercontent.com/assets/384747/25437823/d68445e8-2ad6-11e7-9250-71d29f7cb41c.png)

**Comment by GeertvanHorrik** [comment]
How can I run from cmd line? Is there a batch / ps file?

**Comment by flcdrg** [comment]
No, I should write a `cake` script.

For now, just run `msbuild` in the root directory

**Comment by flcdrg** [comment]
When running `msbuild /v:diag`, I'm seeing the following getting logged:

> VSIXSourceItem
>     ..\..\LICENSE
>         Link = Resources\LICENSE
>         IncludeInVSIX = true
>         VSIXSubPath = Resources
>     C:\dev\git\Gardiner.XsltTools\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.dll
>         ResolvedFrom = {HintPathFromItem}
>         CopyLocal = true
>         FusionName = Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
>         ImageRuntime = v4.0.30319
>         HintPath = ..\..\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.dll
>         Private = True
>         OriginalItemSpec = Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL
>         Version = 0.9.6.0
>         ReferenceSourceTarget = ResolveAssemblyReference
>         ReferenceOutputAssembly = false
>         LinkLibraryDependencies = false
>         FullConfiguration = Debug|AnyCPU
>         SetConfiguration = Configuration=Debug
>         Configuration = Debug
>         SetPlatform = Platform=AnyCPU
>         Platform = AnyCPU
>         BuildReference = true
>         IncludeOutputGroupsInVSIX = BuiltProjectOutputGroupDependencies
>         IncludeOutputGroupsInVSIXLocalOnly = DebugSymbolsProjectOutputGroup;
>         MSBuildSourceProjectFile = C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\Gardiner.XsltTools.Weavers.csproj
>         MSBuildSourceTargetName = BuiltProjectOutputGroupDependencies

and then a little bit further there's:

>     C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\obj\Debug\Weavers.dll
>         IsKeyOutput = true
>         FinalOutputPath = C:\dev\git\Gardiner.XsltTools\Weavers\bin\Debug\Weavers.dll
>         TargetPath = Weavers.dll
>         OriginalItemSpec = C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\obj\Debug\Weavers.dll
>         ReferenceOutputAssembly = false
>         LinkLibraryDependencies = false
>         CopyLocal = false
>         FullConfiguration = Debug|AnyCPU
>         SetConfiguration = Configuration=Debug
>         Configuration = Debug
>         SetPlatform = Platform=AnyCPU
>         Platform = AnyCPU
>         BuildReference = true
>         IncludeOutputGroupsInVSIX = BuiltProjectOutputGroup;GetCopyToOutputDirectoryItems;SatelliteDllsProjectOutputGroup
>         IncludeOutputGroupsInVSIXLocalOnly = DebugSymbolsProjectOutputGroup;
>         MSBuildSourceProjectFile = C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\Gardiner.XsltTools.Weavers.csproj
>         MSBuildSourceTargetName = BuiltProjectOutputGroup

So somehow the `VSIXSourceItem` property or item is getting those extra values set

**Comment by flcdrg** [comment]
Looks like even with `msbuild /v:d` logging it's got useful info. Here's the bit where it's collecting those VSIXSourceitems values. For some reason after it runs in the extension project, it's also running in the Weavers project too..

> Done executing task "CreateVsixSourceItemFromReferences".
> Using "SplitIncludeOutputGroupsInVSIX" task from assembly "C:\dev\git\Gardiner.XsltTools\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\VSSDK\Microsoft.VsSDK.Build.Tasks.dll".
> Task "SplitIncludeOutputGroupsInVSIX"
> Done executing task "SplitIncludeOutputGroupsInVSIX".
> Task "MSBuild"
>   Global Properties:
>     Configuration=Debug
>     Platform=AnyCPU
> Project "C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools\Gardiner.XsltTools.csproj" (4) is building "C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\Gardiner.XsltTools.Weavers.csproj" (3:6) on node 1 (BuiltProjectOutputGroupDependencies target(s)).
> Building with tools version "15.0".
> Target "BuildOnlySettings" skipped. Previously built successfully.
> Target "PrepareForBuild" skipped. Previously built successfully.
> Target "AssignTargetPaths" skipped. Previously built successfully.
> Target "ResolveReferences" skipped. Previously built successfully.
> Target "BuiltProjectOutputGroupDependencies" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets" from project "C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\Gardiner.XsltTools.Weavers.csproj" (entry point):
> Done building target "BuiltProjectOutputGroupDependencies" in project "Gardiner.XsltTools.Weavers.csproj".
> Done Building Project "C:\dev\git\Gardiner.XsltTools\src\Gardiner.XsltTools.Weavers\Gardiner.XsltTools.Weavers.csproj" (BuiltProjectOutputGroupDependencies target(s)).
> Done executing task "MSBuild".
> Task "CreateVsixSourceItemFromReferences"
>   Skipping item: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Microsoft.CSharp.dll
>   Adding item: C:\dev\git\Gardiner.XsltTools\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.dll
>   Adding item: C:\dev\git\Gardiner.XsltTools\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.Mdb.dll
>   Adding item: C:\dev\git\Gardiner.XsltTools\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.Pdb.dll
>   Adding item: C:\dev\git\Gardiner.XsltTools\packages\FodyCecil.1.29.4\lib\net40\Mono.Cecil.Rocks.dll
>   Skipping item: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll

**Comment by flcdrg** [comment]
A bit more digging around and I've discovered that MSBuild item `ProjectReferenceWithConfiguration` is being set to include the Weavers project. This item is used inside `Microsoft.VsSDK.targets` and passed in to `SplitIncludeOutputGroupsInVSIX` which seems to be used to figure out which projects should be looked at to get bits for the Vsix. 

On a hunch I checked the solution dependencies and yes, I have a Solution dependency that makes the weaver compile first before the main project.

I removed this dependency and bingo, no extra assemblies in the Vsix.

So know we know why they're ending up there - now just have to figure out a way to make the weaver build first, but not be considered as a source of assemblies for the vsix.

**Comment by GeertvanHorrik** [comment]
Using unreferenced solution dependencies is not cool :-(

The whole point of project dependencies is *not* to reference them but still control the order they are built in.

**Comment by flcdrg** [comment]
I've raised this with the Visual Studio Extensibility team. I'll post back any response or workarounds suggested.

**Comment by SimonCropp** [comment]
Please ping back here is u ever get a response
