### ISSUE TITLE
May I ask for an Extension for easing the use of RXUI with Xamarin Forms?

### ISSUE THREAD

**Issue by escamoteur** [Fody/Fody#268]
Hi,

I think I found a great use case for an extension, but after looking at the Foody samples I have to admit that writing my own Extension is way out of my league.

I want to use RxUI together with another MVVM Framework for Xamforms as RxUI does not really support Xamforms navigation at this time.

Problem is that RxUI expects it's viewmodel stored in a "ViewModel" Property and Xamarin forms Views normaly use a BindingContext property which most MVVM frameworks assign the Viewmodel on Navigation.

It could be solved by

```
    public new Object BindingContext
    {
        get { return ViewModel; }
        set
        {
            ViewModel = value;
            base.BindingContext = value;
        }
    }
```

But it would have to be added to all Views.

So I thought what about a ReRoute.Fody Extension that allows the rerouting of properties to other properties by an Attribute on the class?

Any chance for something like that?

Best
Thomas

**Comment by distantcam** [comment]
@escamoteur Could you create a base ViewModel that has the BindingContext property, and that all ViewModels inherit from?

**Comment by escamoteur** [comment]
Thanks for coming back to me!

Problem is multiple inheritance. I thought that a general Extension for rerouting properties could be useful.
I have another solution now but still I think it could be a good idea.

If you don't think so, just close the issue

**Comment by distantcam** [comment]
Ah, yeah a base vm won't help there.

To be honest, I'm not sure it's worth doing. As you've pointed out writing Fody plugins is difficult, and this sounds like a small use case (RXUI + other MVVM framework + Xamarin Forms).

Another option would be to bug the RXUI people into supporting Xamarin Forms properly. Also google just pointed me to https://www.nuget.org/packages/reactiveui-xamforms/ but I don't know how helpful that is.

**Comment by escamoteur** [comment]
Understood. The link you gave is the current implementation of RxUI for XamForms but it has some serioius flaws. 
But no problem. I thought this would be an quick thing to do for you Fody pros ;-)

Thanks
