### ISSUE TITLE
Issue with Fody 1.30.0-beta01 on linux with mono

### ISSUE THREAD

**Issue by AlexanderButs** [Fody/Fody#269]
Hi.

Trying to build project with simple aspects (using MrAdvice.Fody). Build failed with next error:
error : Error building target AfterCompile: Microsoft.Build.BuildEngine.InvalidProjectFileException: Unable to parse condition "Exists(@(IntermediateAssembly))" : Expected an item list at position 8 in condition "Exists(@(IntermediateAssembly))". Missing opening parantheses after the '@'. ---> Microsoft.Build.BuildEngine.ExpressionParseException: Expected an item list at position 8 in condition "Exists(@(IntermediateAssembly))". Missing opening parantheses after the '@'.

Previous version (Fody 1.29.4) is working ok, but sometime hangs build process on weaving stage. Also sometime I get mono crash on build stage, which hasn't happened before fody is installed.

Use mono ver. 3.12.0 and xbuild to build project.

**Comment by SimonCropp** [comment]
same problem with version 2.0?

**Comment by renzska** [comment]
Fody 2.0.2 is breaking with this error on a new clean multiplatform Xamarin.Forms app: see post here: https://github.com/Fody/Fody/issues/305
