### ISSUE TITLE
Fody breaks on nested class

### ISSUE THREAD

**Issue by tpluscode** [Fody/Fody#270]
We've hit this weird issue when Fody merely touches an assembly and the there is any attribute used like 

```
[SomeAttribute(typeof(Parent.Child[]))]
public class Irrelevant {}
```

Each bit is important here:
1. `Child` must be nested
2. `typeof` must be used with an array of child

In the rewritten assembly the above is changed to

```
[SomeAttribute(typeof(Child[]))]
public class Irrelevant {}
```

It obviously fails at runtime because loses the parent class. It works fine for `[SomeAttribute(typeof(Parent.Child))]` or any other usage of `Parent.Child[]`. Strangely specific issue.

Is it something anyone is aware of. @jbevain maybe? I've seen some Cecil discussions from 8 years ago. I find it unlikely that it hasn't been fixed though. Looks like some weird corner case. So, is that an issue with Fody or indeed Cecil?

**Comment by distantcam** [comment]
My guess would be it's a Cecil problem. Fody is just a framework that performs the following during the build.

- Decompile assembly using Mono.Cecil
- Load and run Fody plugins on decompiled code
- Recompile assembly using Mono.Cecil

> I've seen some Cecil discussions from 8 years ago. I find it unlikely that it hasn't been fixed though.

I don't . ;)

**Comment by jbevain** [comment]
Yeah that looks like a Cecil issue. I'll look into it.

**Comment by tpluscode** [comment]
@distantcam I saw this http://mono.1490590.n4.nabble.com/Nested-types-re-appear-as-global-types-td1551003.html

Not sure it's even related though

**Comment by jbevain** [comment]
That's fixed in https://github.com/jbevain/cecil/commit/7fe43fc5402ae80084613af306e306826b2aba7a

That will go in the beta 2 of Cecil 0.10.

**Comment by SimonCropp** [comment]
Try fody 2.0

**Comment by tpluscode** [comment]
Works great 👍
