### ISSUE TITLE
Incorrect 0x13 / 0x11 opcodes (stloc.s / ldloc.s) when used Fody project

### ISSUE THREAD

**Issue by 3F** [Fody/Fody#271]
**Updated**: the new details about problem **[here](https://github.com/Fody/Fody/issues/271#issuecomment-256715340)**

```
full body: 133001000900000002000011 -> 001713042B0011042A
full body: 133001000900000003000011 -> 001713042B0011042A
```

Please forget about DllExport at all !  try to use Fody + ILDasm directly -> then recompile again with ILAsm 
as it described below to reproduce problem:

-------

I have a report about problem when used your Fody and our DllExport from user @OzzyL

https://github.com/3F/DllExport/issues/17

I already described what's going on **[here](https://github.com/3F/DllExport/issues/17#issuecomment-253760805)**

> 14.10.2016 17:22, Oscar Lund:
> 
> > Hi Denis,
> > 
> > Thanks for your detailed respone in the tracker!
> > 
> > But I tried to reproduce the issue using the sample you provide in the tracker. But was not able.
> > Could you please send me the solution? It will help me to file the issue with Fody.
> > 
> > Best Regards
> > Oscar
> 
> To reproduce this problem as I wrote, you should:
> - Add Fody and, for example, ModuleInit in project
> - Then add my sample of class
> - Build project to get library or .exe module
> - Then manually use ILDasm for this (.dll or .exe) - you will see now the incorrect instruction that I wrote in comment
> - And finally try to compile by ILAsm ( ! )  - will be fail because the IL code is incorrect as you can see

So you can also try to reproduce my [sample](https://github.com/3F/DllExport/issues/17#issuecomment-253760805):

_Fody + ModuleInit + Debug info: Full or pdb only:_

``` csharp
namespace Sample1
{
    internal class ClassA
    {
        public bool m1()
        {
            int a, b, c;

            return true;
        }
    }
}
```

this works, but note the `.locals` def -->

``` csharp
  .method public hidebysig instance bool 
          'm1'() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  1
    .locals init ([0] int32 'a',
             [1] int32 'b',
             [2] int32 'c',
             [3] bool )                                <<<<<<<
    .line 6,6 : 9,10 'D:\\tmp\\Sample1\\ClassA.cs'
    IL_0000:  nop
    .line 9,9 : 13,25 ''
    IL_0001:  ldc.i4.1
    IL_0002:  stloc.3                                  <<<<<<< ok
    IL_0003:  br.s       IL_0005

    .line 10,10 : 9,10 ''
    IL_0005:  ldloc.3                                  <<<<<<< ok
    IL_0006:  ret
  }
```
- `0x0A - 0x0D` i.e. `stloc.0 - stloc.3`  + see also `0xFE 0x0E`
- `0x06 - 0x09` i.e. `ldloc.0 - ldloc.3`  + see also `0xFE 0x0C`

Now, **when failed** (by short forms - 0x13 and 0x11):

just define new var

``` csharp
int a, b, c, d; // >>> d 
```

because: 
- to reference on new variable (local variable via index from/to stack) now used 0x13 / 0x11 opcodes i.e.  -> `stloc.s / ldloc.s`
- and this is it, see below:

``` csharp
  .method public hidebysig instance bool 
          'm1'() cil managed
  {
    // Code size       9 (0x9)
    .maxstack  1
    .locals init ([0] int32 'a',
             [1] int32 'b',
             [2] int32 'c',
             [3] int32 'd',
             [4] bool )                                 <<<<<<
    .line 6,6 : 9,10 'D:\\tmp\\Sample1\\ClassA.cs'
    IL_0000:  nop
    .line 9,9 : 13,25 ''
    IL_0001:  ldc.i4.1
    IL_0002:  stloc.s                                   <<<<<< incorrect*
    IL_0004:  br.s       IL_0006

    .line 10,10 : 9,10 ''
    IL_0006:  ldloc.s                                   <<<<<< also here
    IL_0008:  ret
  }
```
- `0x13 <unsigned int8>` i.e. `stloc.s index` therefore: **syntax error** at token ':' in:     IL_0004:  br.s       IL_0006  (from ILAsm)

without debug info it generated correctly:

``` csharp
    .locals init (int32 V_0,
             int32 V_1,
             int32 V_2,
             int32 V_3,
             bool V_4)                  <<<<<
    IL_0000:  nop
    IL_0001:  ldc.i4.1
    IL_0002:  stloc.s    V_4            <<<<<
    IL_0004:  br.s       IL_0006

    IL_0006:  ldloc.s    V_4            <<<<<
    IL_0008:  ret
  }
```

please check it

**Comment by 3F** [comment]
ah yes, without Fody it can be like this (Debug info: full):

```csharp
  .method public hidebysig instance bool 
          'm1'() cil managed
  {
    // Code size       9 (0x9)
    .maxstack  1
    .locals init ([0] int32 'a',
             [1] int32 'b',
             [2] int32 'c',
             [3] int32 'd',
             [4] bool 'V_4')
    .line 6,6 : 9,10 'D:\\tmp\\Sample1\\ClassA.cs'
    IL_0000:  nop
    .line 9,9 : 13,25 ''
    IL_0001:  ldc.i4.1
    IL_0002:  stloc.s    'V_4'
    IL_0004:  br.s       IL_0006

    .line 10,10 : 9,10 ''
    IL_0006:  ldloc.s    'V_4'
    IL_0008:  ret
  }
```

**Comment by GeertvanHorrik** [comment]
@3F You can verify the generated assemblies using VerifyAssembly="true":

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="true">
  <MethodTimer/>
  <Catel/>
  <LoadAssembliesOnStartup/>
</Weavers>
```

However, if you are not modifying the export by any weavers, this is probably a cecil issue.

**Comment by 3F** [comment]
@GeertvanHorrik 

well, I think it more related for CoreCLR, i.e. ILDasm

seems it works with `4.5.22220.0`, code above was generated by:
```
Microsoft (R) .NET Framework IL Disassembler.  Version 4.6.1055.0
```
hmm, can you try also

**Comment by 3F** [comment]
I see that **1304** & **1104** are correct instructions. And probably the dnSpy simply knows how to describe this link to [4] variable (return type) for decompiled form - IL

```csharp
	/* 0x000002A1 17           */ IL_0001: ldc.i4.1
	/* 0x000002A2 1304         */ IL_0002: stloc.s   4
	/* 0x000002A4 2B00         */ IL_0004: br.s      IL_0006

	/* 0x000002A6 1104         */ IL_0006: ldloc.s   4
```
full body: `133001000900000002000011 -> 001713042B0011042A`


```csharp
	/* 0x00000495 17           */ IL_0001: ldc.i4.1
	/* 0x00000496 1304         */ IL_0002: stloc.s   V_4
	/* 0x00000498 2B00         */ IL_0004: br.s      IL_0006

	/* 0x0000049A 1104         */ IL_0006: ldloc.s   V_4
```
full body: `133001000900000003000011 -> 001713042B0011042A`


i.e. the main difference - .locals def

*dnSpy 3.0.0-beta:*

```csharp
	.locals init (
		[0] int32 a,
		[1] int32 b,
		[2] int32 c,
		[3] int32 d,
		[4] bool        <<<< ~ same
	)
vs
	.locals init (
		[0] int32 a,
		[1] int32 b,
		[2] int32 c,
		[3] int32 d,
		[4] bool V_4
	)
```

well, I don't know whose problem mostly :) but it appears with Fody /*just: Install-Package ModuleInit.Fody*

**Comment by SimonCropp** [comment]
does it only occur when u use ModuleInit?

**Comment by 3F** [comment]
@SimonCropp sorry, but I don't use Fody projects. I only tested this combination with our both projects by request @OzzyL.

Cc: @OzzyL

But as I remember: this was also with other Fody module that I checked at same time. Thus the reason **not only** by ModuleInit. **Fody is primarily**.

Try to reproduce as I described above, start with:

* `nuget install DllExport`
* `nuget install <Fody module>`  <<<< 


Mainly fault by .locals def, as I noticed above because:

```
:)
133001000900000002000011 -> 001713042B0011042A
133001000900000003000011 -> 001713042B0011042A
```
so probably need to look lexical grammar of disassembler, however Fody directly affects on this, anyway.


ah yes, with latest changes I implemented our custom version of ILAsm/ILDasm on coreclr - v1.5 changelog entry:

```
* NEW: Added our custom IL Assembler as option to fix incorrect 0x13 / 0x11 opcodes. #17
          GUI Configurator + MSBuild property: `DllExportOurILAsm`
          It should help for users of Fody projects, etc.
          https://github.com/Fody/Fody/issues/271
         
          IlAsm 4.5.1 https://github.com/3F/coreclr
          based on 4.5.22220.0 / coreclr 1.0.4
          changelog of our coreclr for this release: https://github.com/3F/coreclr/blob/master/changelog.txt 
```
**Thus make sure that** `[] Use our IL Assembler` is unchecked (msbuild: DllExportOurILAsm = false) - https://github.com/3F/DllExport/issues/17#issuecomment-257427399

![d05dd0d6-9fca-11e6-82a0-f5101974f06b](https://cloud.githubusercontent.com/assets/3246589/25314380/7182e20e-284b-11e7-8e53-a28c9a308876.png)

**Comment by 3F** [comment]
**and for clarify**, mainly you should look this problem not with DllExport or ILAsm, but mainly with ILDasm + Fody of course.

**Comment by distantcam** [comment]
I have found the "problem" here.

Here's the IL output from ILdasm with debug symbols.

```
  .locals init ([0] int32 a,
           [1] int32 b,
           [2] int32 c,
           [3] int32 d,
           [4] bool )
  IL_0000:  nop
  IL_0001:  ldc.i4.1
  IL_0002:  stloc.s    
  IL_0004:  br.s       IL_0006
  IL_0006:  ldloc.s    
  IL_0008:  ret
```

And without debug symbols.

```
.method public hidebysig instance bool  M2() cil managed
{
  // Code size       9 (0x9)
  .maxstack  1
  .locals init (int32 V_0,
           int32 V_1,
           int32 V_2,
           int32 V_3,
           bool V_4)
  IL_0000:  nop
  IL_0001:  ldc.i4.1
  IL_0002:  stloc.s    V_4
  IL_0004:  br.s       IL_0006
  IL_0006:  ldloc.s    V_4
  IL_0008:  ret
} // end of method Class1::M2
```

See the difference? The op code is the same, but because the boolean is an unnamed variable in the symbol file it's named BLANK, and so when writing out the instruction at `IL_0002` it's writing the variable name as blank. ILdasm insn't smart enough to handle this situation, so it looks like the variable symbol is missing, even though it isn't.

Also another way to tell it's there is by the IL line counts. `IL_0002` has 2 bytes because the next line is `IL_0004` so the variable reference is there, just not displayed.

Whatever caused the original error had nothing to do with these op codes, and possibly nothing to do with Fody.

**Comment by 3F** [comment]
@distantcam did you read explanations above at all ?!

about difference I already wrote **[here](https://github.com/Fody/Fody/issues/271#issuecomment-256715340)**:

```
full body: 133001000900000002000011 -> 001713042B0011042A
full body: 133001000900000003000011 -> 001713042B0011042A
```

the problem only with ILDasm after Fody, and ... ILDasm does not affect on opcode if you don't know.

> to handle this situation, so it looks like the variable symbol is missing,

exactly, so what is this situation after assembling with Fody when ILDasm can't describe label


> I have found the "problem" here.

:)

**Comment by distantcam** [comment]
@3F The variable symbol isn't missing, it's empty. So the op code isn't wrong, it's just written out wrong by ILdasm.

The two outputs from ILdasm are from exactly the same file, just one had symbol names for the variable ('a', 'b', 'c', 'd', '') and the other didn't have the symbols, so ILdasm created them ('V_0', 'V_1', 'V_2', 'V_3', 'V_4').

**Comment by 3F** [comment]
@distantcam 

omg, I just don't update title for this issue !! should I ? because it was as a first thinking about this problem, but when I started debug I noticed what's going on. The old title I leaved 'as is'.

btw, my thoughts exactly about short codes 0x0A-0x0D (I mean logic for lexical analyser when it found 0x13) because this is a more appropriate explanationcan of this behaviour what do you think ?

**Comment by SimonCropp** [comment]
@3F do u get the same problem when u just round trip the assembly with cecil?
