### ISSUE TITLE
Solution using project.json fails

### ISSUE THREAD

**Issue by Allann** [Fody/Fody#272]
I have a solutions with numerous class project pairs, a full .Net4.6.1 class library and an associated xunit test class library.  The class library uses ModuleInit.Fody and MethodTimer.Fody and has the appropriate FodyWeaver.xml file.  This solution builds fine on and logged in PC where VS2015 Update 3 manually kicks of the build, as does the build server (also has VS2015 U3 installed).  
However, building the solution via a CI gated checkin fails with:

```
Fody: No configured weavers. It is possible you have not installed a weaver or have installed a fody weaver nuget into a project type that does not support install.ps1. You may need to add that weaver to FodyWeavers.xml manually. eg. <Weavers><WeaverName/></Weavers>. see https://github.com/Fody/Fody/wiki/SampleUsage
     9>MSBUILD : error : Fody: No configured weavers. It is possible you have not installed a weaver or have installed a fody weaver nuget into a project type that does not support install.ps1. You may need to add that weaver to FodyWeavers.xml manually. eg. <Weavers><WeaverName/></Weavers>. see https://github.com/Fody/Fody/wiki/SampleUsage [D:\TfsData\_work\117\s\Jbssa.Extensions\Jbssa.Extensions.SystemInfo.Tests\Jbssa.Extensions.SystemInfo.Tests.csproj]
           Fody:   Finished Fody 3ms.
```

The test projects do NOT use Fody but appears from the message that they have to.  Is this really the case?  No files need to be changed in the test project so I don't see the point in adding Fody addins there.

Here is the project.json file from one of the test projects:

```
{
  "dependencies": {
    "xunit": "2.1.0",
    "xunit.runner.visualstudio": "2.1.0"
  },
  "frameworks": {
    "net461": { }
  },
  "runtimes": {
    "win-anycpu": { },
    "win": { }
  }
}
```

And the Class library project.json file:

```
{
  "dependencies": {
    "Jbssa.Core": "4.6.16292.7",
    "MethodTimer.Fody": "1.16.0",
    "ModuleInit.Fody": "1.5.9.0"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win-anycpu": {},
    "win": {}
  }
}
```

Any additional info needed to help with this can be made readily available.

**Comment by Allann** [comment]
As a workaround, I have added the same Fody Addin to the test projects.  For ModuleInit I have included an empty ModuleInitializer.cs class too.

**Comment by ravensorb** [comment]
Any update on this -- I cannot seem to get fody to run on any 4.6 projects that use project.json.

**Comment by SimonCropp** [comment]
Given project json is going away http://www.talkingdotnet.com/bye-bye-project-json-xproj-welcome-back-csproj/ I can't see the value in implementing this
