### ISSUE TITLE
Fody and/or Costura forces PDB generation

### ISSUE THREAD

**Issue by Bilge** [Fody/Fody#278]
Fody/Costura forces a PDB to be generated and linked into the target executable even when [PDB generation has been explicitly disabled in the build options](http://stackoverflow.com/a/2371056/1041515). Fody/Costura must not override my preference to disable PDB generation.

I am unable to determine whether Fody or Costura is the source of this fault as I cannot use one without the other (Fody throws an exception at build time if there are "no configured weavers"). Since Costura is no longer maintained I hope the error is, in fact, with Fody and that it can be addressed.

**Comment by distantcam** [comment]
I am unable to reproduce this.

Make sure the setting to disable PDB generation is set for all configurations (Debug, Release, etc).

**Comment by Bilge** [comment]
Why would I ever disable PDB generation for *all configurations*? Perhaps you do not understand how configurations work; only one can be active at any given time, and therefore, I would only need to disable it for the active configuration, never *all configurations*. As to your attempt to reproduce the issue, what exactly have you observed that makes you think this is not reproducible?

**Comment by distantcam** [comment]
Steps I used to try and reproduce.

- Created a new WPF application
- Changed the settings for PDB generation as per the link provided for all configurations.
- Installed Costura, Autofac, PropertyChanged.
- Build.
- Going to the output folder, there is no PDB file for the application I have just built.

**Comment by Bilge** [comment]
As I suspected, you have only checked the `bin\Release` folder which is just a copy target directory, not the working directory for generated output.

**Comment by distantcam** [comment]
At what point did I say I checked the `bin\Release` folder? I made sure that *all configurations* were set to not output debug info, and then checked `bin\Debug` and `bin\Release` after building both configurations.

**Comment by distantcam** [comment]
Here's the full code I used to try and reproduce this. https://github.com/distantcam/PDBRepro

**Comment by Bilge** [comment]
You should not be checking *anything* under `bin`. As I explained in my [prior post](https://github.com/Fody/Fody/issues/278#issuecomment-261687183), you must check in the `obj` folder and/or use a hex editor on the executable or other tool to verify that the PDB has been linked.

**Comment by distantcam** [comment]
![image](https://cloud.githubusercontent.com/assets/1298847/20452469/4b694e8a-ae45-11e6-8752-7be1fd0576f9.png)

You edited your post after I had seen it.

As explained in this issue - https://github.com/Fody/Costura/issues/162 - linking to the PDB has nothing to do with Costura or Fody and cannot be disabled by the compiler.

**Comment by Bilge** [comment]
This is patently false. Removing Fody will immediately cease generating,
and consequently linking, the PDB. I urge you to try it in your little test
project and see for yourself.

**Comment by distantcam** [comment]
Now that I know what I'm looking for (the original description was not helpful) I can confirm this is a Fody bug. I can also reproduce the problem with PropertyChanged.

Looking at the https://github.com/Fody/Fody/blob/master/FodyIsolated/ModuleWriter.cs it always writes debug symbols regardless of whether the original assembly has them or not.

**Comment by Bilge** [comment]
Is it something quick and easy to fix or not?

**Comment by SimonCropp** [comment]
fody, and many addins, need the pdb to give better quality errors.

Is there some reason you dont wnat to produce a pdb?

**Comment by Bilge** [comment]
@SimonCropp Certainly. It is because the full physical path to the PDB embeds is embedded in the executable which is a privacy concern.

**Comment by SimonCropp** [comment]
wouldnt this suffice https://github.com/Fody/Costura/#includedebugsymbols  ?

**Comment by Bilge** [comment]
Since it has been over 6 months I no longer recall if I tried that. I believe I did exhaust all the options before giving up but I can't guarantee it.

**Comment by SimonCropp** [comment]
ok fody no longer forces pdb generation
