### ISSUE TITLE
Using emitted code from within modified assembly

### ISSUE THREAD

**Issue by tpluscode** [Fody/Fody#279]
Is there any way to use the code produced by Fody from the modified assembly so that there is full IntelliSense?

For example Virtuosity makes members virtual but this code will not compile

``` c#
public class Parent 
{
    public string Property { get; set; }
}

public class Child : Parent 
{
    public override string Property 
    { 
        get
        {
            return "can't override";
        } 
    }   
}
```

Is there any way to make this happen?

**Comment by kamil-mrzyglod** [comment]
If you reference a modified assembly then I guess so.

**Comment by SimonCropp** [comment]
Yeah it is not really possible. U can fake some scenarios using interfaces, eg how janitor does with idisposable and propertychanged does with INPC. But in general it is not possible
