### ISSUE TITLE
Unable to not weave a given class

### ISSUE THREAD

**Issue by DavidA94** [Fody/Fody#282]
I have a class which implement INotifyPropertyChanged, and its implementation is very specialized. I do not want Fody to weave that class. However, there is no way, outside of tagging every property to not be used, which is not acceptable. This is forcing me to not use Fody in my project. There should be a way to only weave classes with a given property, or at worst, you should be able to tag a class to not be weaved.

**Comment by kamil-mrzyglod** [comment]
I guess you should post an issue for [PropertyChanged](https://github.com/Fody/PropertyChanged), not Fody because what and how is weaved is not Fody's responsibility. It only runs weavers.

**Comment by distantcam** [comment]
@DavidA94 You can add the `DoNotNotify` attribute to the class.

**Comment by SimonCropp** [comment]
yep this should be in the  PropertyChanged project
