### ISSUE TITLE
Is it possible to disable fody generated code at runtime

### ISSUE THREAD

**Issue by skd123us** [Fody/Fody#285]
I would like to add simple method timing statements using fody, but would like to keep if off in production code unless I need to produce statistics.

Is this possible? is there a huge overhead?

**Comment by SimonCropp** [comment]
this should work for you https://github.com/Fody/MethodTimer

and no the overhead is not large

**Comment by kamil-mrzyglod** [comment]
So this weaver is perfectly fine for you - you can configure your `Log(MethodBase methodBase, long milliseconds)` method and log time conditionally if logging is on in web/app.config.
