### ISSUE TITLE
Operator "==" not working when the attributed class is in the same assembly as call site

### ISSUE THREAD

**Issue by orc886** [Fody/Fody#286]
This is from 2014 and yet been solved
Looked at: https://github.com/Fody/Equals/issues/10

**Comment by distantcam** [comment]
@orc886 There's no need to open another issue in a different project when you have already commented on the other issue.

**Comment by orc886** [comment]
I don't know what is needed, or what should or shouldn't be done. But people wasted many man-hours on dealing with this trivial issue, when the library should have simplified their workflow.

**Comment by distantcam** [comment]
You knew there was already an open issue. You deliberately opened a duplicate, wasting my time.

**Comment by kamil-mrzyglod** [comment]
Complaining about "wasted man-hours" on OSS project issue tracker is well... difficult to understand to me.

**Comment by SimonCropp** [comment]
No need for the duplicate issue
