### ISSUE TITLE
Updating Fody from Nuget Package Manager overwrite existing FodyWeavers.xml

### ISSUE THREAD

**Issue by lamLeX** [Fody/Fody#288]
I installed PropertyChanged.Fody and it automatically installs Fody 1.29.2. with the FodyWeavers.xml configured for PropertyChanged addin.

After that, when I try to update the Fody package to 1.29.4, package manager overwrites the xml file with default empty weaver file as if you don't configure Fody with any addin. 

I could choose not to overwrite the file. But I may not know if the xml file may change in the future version of Fody.

**Comment by SimonCropp** [comment]
It won't change in a future version

**Comment by GiroSA** [comment]
This still happens. I have had to add back my weavers every time after an update.

This is an extremely disruptive (and expensive) bug.

**Comment by SimonCropp** [comment]
@GiroSA this has been fixed in all the weavers under the fody org. if it is happening with some other weaver u should open an issue in that repo

**Comment by GiroSA** [comment]
Is Costura not part of fody org?

**Comment by SimonCropp** [comment]
it is, and it no longer manipulates the FodyWeavers.xml
