### ISSUE TITLE
Application has only 2 GB address space after fody executes

### ISSUE THREAD

**Issue by KPT85** [Fody/Fody#291]
Hello everybody,

I noticed that my program has only 2 GB address space when I use fody. When I don't use fody I have 4 GB address space. When I manually set the "large memory support" in the file header using a post build the problem is solved. Then I again have 4 GB address space. 
Does anyone know if the address space is inentually set to 2 GB by fody or if this is a bug?

Best regards,
Thomas

**Comment by SimonCropp** [comment]
Can u upload a repro

**Comment by SimonCropp** [comment]
also can u try version 2.0?

**Comment by SimonCropp** [comment]
closed due to no response
