### ISSUE TITLE
Could not load type 'AutoDependencyPropertyMarker.AutoDependencyPropertyAttribute' from assembly 'System.Drawing"

### ISSUE THREAD

**Issue by alexiej** [Fody/Fody#294]
Hi,

I've got the issue when I use AutoDependency property from a simple field. It looks like it tries to get AutoDependencyProperty from Assembly (System.Drawing).

This gives me an issue:

    ```
    private string _Text;

        [AutoDependencyPropertyMarker.AutoDependencyProperty]
        public string Text
        {
            get { return _Text; }
            set
            {
                _Text = value;

            }
        }
```

But this not:

    ```
    [AutoDependencyPropertyMarker.AutoDependencyProperty]
        public string Text { get; set; }
```

Is it possible to change other fields or use set after the change with AutoDependencyProperty ?

> System.Windows.Markup.XamlParseException occurred
>   HResult=0x80131501
>   Message=Could not load type 'AutoDependencyPropertyMarker.AutoDependencyPropertyAttribute' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>   Source=PresentationFramework
>   StackTrace:
>    at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
>    at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
>    at CroneyeApplication.Views.Dialogs.SetupTaskView.InitializeComponent() in   ..\SetupTaskView.xaml:line 1
> 
> Inner Exception 1:
> TypeLoadException: Could not load type 'AutoDependencyPropertyMarker.AutoDependencyPropertyAttribute' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by SimonCropp** [comment]
what weaver are you using?

**Comment by SimonCropp** [comment]
can u raise this in the project for specific weaver you are using
