### ISSUE TITLE
Fodys breaks debugger's "step over" in async methods

### ISSUE THREAD

**Issue by vitidev** [Fody/Fody#295]
After adding fody (+any extension. I tried PropertyChanged and Janitor) breaks debugger's feature "step over" 

For example, simple console project (VS 2017 RTM + target framework 4.6.1 + Fody 1.29.4 + PropertChanged 1.52.1)
![fodybug0](https://cloud.githubusercontent.com/assets/2243958/24001226/3cfd9964-0a66-11e7-8351-ce6de70427ae.gif)

The behavior is observed in VS2015/2017, both installed in one system.

"run to next breakpoint" and "run to cursor" features still work in async methods

**Comment by SimonCropp** [comment]
Can u try 2.0

**Comment by vitidev** [comment]
VS 2017 RTM + target framework 4.6.1 + Fody 2,0 + PropertChanged 1.52.3 - working
 I can't check VS 2015

**Comment by SimonCropp** [comment]
@vitidev thanks. will close this one for now
