### ISSUE TITLE
Request:ToString Extension

### ISSUE THREAD

**Issue by zredb** [Fody/Fody#300]
Hi, 
    I think Fody is a good tool for static weaving, And I searched the Fody Addin list, I don't find the addin of ToString, would anyone can develop it? It main function is weave a ToString method which can output the all of the public property's name and value of the class.
    thanks a lot!

**Comment by distantcam** [comment]
Is [Fody/ToString](https://github.com/Fody/ToString) not enough?

**Comment by zredb** [comment]
Thank you for tell me this. I will try it later. thank you!
