### ISSUE TITLE
Cannot build project when Assembly Signing is enabled

### ISSUE THREAD

**Issue by itrx** [Fody/Fody#303]
Fody has saved me from a lot of trouble, but today our client required that we sign one of the mini standalone applications we made for our bigger project, whenever I enable project signing in the solution I get an unhanded exception in the output window. The only weaver I have is **Costura**.

Details below:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Unable to obtain public key for StrongNameKeyPair.
StackTrace:
   at System.Reflection.StrongNameKeyPair.ComputePublicKey()
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 85
Source:
mscorlib
TargetSite:
Byte[] ComputePublicKey()	EtasOutIn			
`

As a result I cannot even build until I disable signing. I believe I can sign it with an external tool once the assembly is published, but this might need to be looked at.

**Comment by SimonCropp** [comment]
can u upload a repro?

**Comment by itrx** [comment]
New to GIT and I am not sure what is meant by repro in this context, do you want me to write down what I am doing to reproduce it step by step?

**Comment by SimonCropp** [comment]
sorry not a git repo. a repro as in "a solution that reproduces the problem"

**Comment by SimonCropp** [comment]
are u using password protected signing?

**Comment by itrx** [comment]
Apologies, I forgot about this issue after I figured out I cannot send you a copy that reproduces the issue. It didn't throw such error on an empty WinForms application. I kept getting the error at different times, same error for the record after some recent updates. The signing is not password protected and as it turned out the issue wasn't related to the signing.

I realized Visual Studio doesn't sign when doing manual project rebuilds and working with the debug folder's executable. I thought it cannot sign cause that's the only thing I done to cause the error, enable either of the signings. But as it turns out the actual signing happens when you publish the project and I had this error for a while by then, manifesting itself with signing enabled and at during some nuget updates it became consistent and didn't allow me to build project.

I've currently downgraded them both for things to work smoothly, Costura to 1.3 and Fody to 1.29.4 and it works well. Packages everything and signs with success.

**Comment by SimonCropp** [comment]
U dont need to send me your application. Just the a small repro with enough moving pieces to illustrate the issue. The repro can even have emply classes.

**Comment by itrx** [comment]
I'll try to patch something around together, again. Was unsuccessful last time. Please leave this open, I'll get back to it within a week.

**Comment by SimonCropp** [comment]
Hanks

**Comment by SimonCropp** [comment]
Thanks

**Comment by SimonCropp** [comment]
let me know when u get that repro together
