### ISSUE TITLE
Issue After 2.0.2+ - Fody: Found no debug symbols.

### ISSUE THREAD

**Issue by CDAGaming** [Fody/Fody#309]
After Updating Fody to 2.0.2 and later to higher builds, Visual Studio is able to build my app fine, but on msbuild(Appveyor), it fails with the following:

`Fody: Found no debug symbols.`

Any Info Needed further can be provided, so i hope this can be resolved.

**Comment by distantcam** [comment]
AppVeyor is being very weird at the moment. 2 hours ago I couldn't build because the `before_build` wasn't executing, and now it cannot connect to github because it's unauthorized. Maybe wait until tomorrow and try again.

**Comment by CDAGaming** [comment]
Ok @distantcam , hope this can be figured out soon :P

**Comment by SimonCropp** [comment]
Does it only happen with specific addins?

**Comment by CDAGaming** [comment]
It has onlt ever happened after updating to Fody 2.0.2 and Above, still persists on latest 2.0.5

Apparently @distantcam fixed this in Costura.Fody, but needs to update Appveyor settings to get it building again

**Comment by Furtif** [comment]
yes same bug    
 Fody: Fody (version 2.0.5.0) Executing
MSBUILD : error : Fody: Found no debug symbols. [c:\projects\rocketbot2\RocketBot2\RocketBot2.csproj]
    Fody:   Finished Fody 1266ms.
Command exited with code 1

**Comment by CDAGaming** [comment]
This Commit has supposivley fixed the symbol issue: https://github.com/Fody/Costura/commit/0d6c57c079f80c364dd304582f069b46ce81ebc2

However, Appveyor settings(As Support had said, because it was referencing a vs2015 image) need to be updated in order for it to build, as it now requires VS2017 and BuildTools v141 to build

Appveyor Support Convo can be found here in this commit as well as the support convo with appveyor: https://github.com/Fody/Costura/commit/ed8194d88335a1dc3860a0bc57e5b97e8a9bd68f

**Comment by Furtif** [comment]
In version 1.29.x the bug does not exist is that from 2.0.0

**Comment by Furtif** [comment]
Or maybe it is a bug appveyor simply seen that locally everything is fine ?!

**Comment by Furtif** [comment]
I just tested with this in appveyor configuration

Configuration: Debug

Successes build not bugs

**Comment by CDAGaming** [comment]
It is something in the release configuration, on generating symbols

**Comment by CDAGaming** [comment]
https://ci.appveyor.com/project/RocketBot/rocketbot/build/0.0.0.231
Furtif's Successfull Build

**Comment by Furtif** [comment]
If you want to disable pdb file generation, you need to use the "Advanced build settings" dialog available in project properties after clicking the "Advanced..." button" located in the lower part of the Build tab.

Set Output - Debug info: to None for release build configuration and no pdb files will be generated.

source at http://stackoverflow.com/questions/2371032/c-sharp-release-version-has-still-pdb-file

**Comment by Furtif** [comment]
Apparently the bug exists only in Release ...

I test all modes fail all

**Comment by Furtif** [comment]
Release build local is ok !!!! Only appveyor release fails

**Comment by Furtif** [comment]
<Costura IncludeDebugSymbols='true' /> = fail
<Costura IncludeDebugSymbols='false' /> =fail

**Comment by CDAGaming** [comment]
https://github.com/Fody/Fody/pull/315

This may fix the Issue in Fody itself, Appveyor would still be down for Cosura

**Comment by distantcam** [comment]
Costura is building on Appveyor now.

**Comment by CDAGaming** [comment]
Yup I saw, am happily awaiting update and will apply tomorrow. Thanks so far for this @distantcam we really appreciate it

**Comment by SimonCropp** [comment]
so given this isnt a fody problem any objection with closing?

**Comment by CDAGaming** [comment]
Closing as it had been Costura Fody Issue

**Comment by CDAGaming** [comment]
Hey, if this was a Costura issue, and it is fixed on repo, why hasn't IT gotten an update @distantcam

**Comment by Furtif** [comment]
:) all ok thanks
