### ISSUE TITLE
AfterWeaving bug in Fody 2.0.4

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Fody#310]
It seems that deleting the Read\Write [block of code](https://github.com/Fody/Fody/commit/d44961d677770701c833b5b8e4215e2f96e06ec5#diff-a8c8e70bc0a71922674d3246d026bcb6L89) from the InnerWeaver causes an error when trying to load an assembly using a Fody weaver with an AfterWeaving task when built in Release mode.

Assemblies built in Release mode using Fody 2.0.3 work fine, but assemblies built with 2.0.4 throw "An attempt was made to load a program with an incorrect format."

**Comment by SimonCropp** [comment]
@jasonwoods-7 can u upload a repro?

**Comment by SimonCropp** [comment]
@jasonwoods-7 and to be honest i deleted that code since i can understand what is meant to do. yes i know i wrote it years ago and should have added comments. any thoughts?

**Comment by GeertvanHorrik** [comment]
Looks like assembly verification is broken as well. Now getting this error:

```
Fody: Cannot verify assembly, file 'C:\Source\MyProject\output\debug\NET40\MyProject\MyProject.dll' does not exist
```

**Comment by GeertvanHorrik** [comment]
Created a separate issue for assembly verification #311

**Comment by jasonwoods-7** [comment]
Ok, you can see the issue in my Vandelay add-in.

Using the master branch (which uses Fody 2.0.3), building the solution with
`MSBuild Vandelay.sln /t:Rebuild /p:Configuration=Release`
succeeds.

Switching to the fody205 branch and running the same command to build produces the following errors:
```
"R:\home\jwoods\src\git\Vandelay\Vandelay.sln" (Rebuild target) (1) ->
"R:\home\jwoods\src\git\Vandelay\Fody\Fody.csproj" (Rebuild target) (2) ->
"R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\ReferenceAssembly.csproj" (default target) (3:3) ->
(FodyVerifyTarget target) ->
  MSBUILD : error : Fody: PEVerify of the assembly failed. [R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\ReferenceAssembly.csproj]
MSBUILD : error : [MD](0x8007000B): An attempt was made to load a program with an incorrect format.\r [R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\ReferenceAssembly.csproj]
MSBUILD : error : 1 Error(s) Verifying R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\bin\Release\Vandelay.dll\r [R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\ReferenceAssembly.csproj]
MSBUILD : error :  [R:\home\jwoods\src\git\Vandelay\ReferenceAssembly\ReferenceAssembly.csproj]
```

I found that moving the call to ExecuteAfterWeavers to before WriteModule [fixes](https://github.com/jasonwoods-7/Fody/commit/d95c6d9a0a044f13a9ef31293fb3a2b3a2b3d3a2) my issue.

I'm honestly not sure why this fixes the issue.

I even used ILDASM to output all the IL to a file using Fody 2.0.5 & my custom version with this change in it, and the only differences in the IL between the two files are the MVID guid, Image base address, & the FodyVersion constant.

**Comment by jasonwoods-7** [comment]
Oh, never mind the moving ExecuteAfterWeavers to before WriteModule change I made to Fody.  Turns out the resulting assemblies don't contain the git stamp anyway.

**Comment by jasonwoods-7** [comment]
[Re-adding](https://github.com/jasonwoods-7/Fody/commit/2dd5da4c9e6047359bef5b80a7a82f56dc6dcf89) the Read\Write block of code after calling ExecuteAfterWeavers rearranges some of the attributes in the resulting IL.

I'm not familiar enough with IL to know why rearranging the attributes magically makes the resulting assembly valid.

**Comment by SimonCropp** [comment]
@jasonwoods-7 i will put that code back in

**Comment by SimonCropp** [comment]
@jasonwoods-7 actually perhaps we shouldnt do that. i went and had a look at your project. It is using Stamp. I removed that and the assembly is no longer corrupt. so it seems to be a problem that that specific weaver. Given that project is no longer maintained i suggest moving over to https://github.com/GitTools/GitVersion

**Comment by jasonwoods-7** [comment]
ok, i'll look into that.
