### ISSUE TITLE
Unhandled Exception in VB.net projects when no "Root namespace" set

### ISSUE THREAD

**Issue by vincenormand** [Fody/Fody#313]
In VB.net projects using version 2.0.5 of Fody, when no "Root namespace" is set, this exception occurs :

```
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : startIndex cannot be larger than length of string.
1>MSBUILD : error : Parameter name: startIndex
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at System.String.Substring(Int32 startIndex, Int32 length)
1>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbReader.GetImport(PdbScope scope, ModuleDefinition module)
1>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbReader.ReadScopeAndLocals(PdbScope scope, MethodDebugInformation info)
1>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.ImmediateModuleReader.ReadMethodsSymbols(TypeDefinition type, ISymbolReader symbol_reader)
1>MSBUILD : error :    at Mono.Cecil.ImmediateModuleReader.ReadTypesSymbols(Collection`1 types, ISymbolReader symbol_reader)
1>MSBUILD : error :    at Mono.Cecil.ImmediateModuleReader.ReadSymbols(ModuleDefinition module)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 88
1>MSBUILD : error : Source:
1>MSBUILD : error : mscorlib
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : System.String Substring(Int32, Int32)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 65ms.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

It was working before with version 1.29.2 of Fody.

**Comment by SimonCropp** [comment]
can u share a repro?

**Comment by vincenormand** [comment]
https://1drv.ms/u/s!AiC4h8X_PmBFgYBLbZMvaYwev5osww

**Comment by SimonCropp** [comment]
@jbevain looks like a possible cecil bug.  need a dll from me?

**Comment by jbevain** [comment]
Yes please. Something small idea that I could use in the test suite :) Thanks!

**Comment by SimonCropp** [comment]
replaced by https://github.com/jbevain/cecil/pull/410

**Comment by SimonCropp** [comment]
actually i will leave this open to track pulling in cecil when it is fixed

**Comment by GirishVenkata** [comment]
Facing same issue 
We are getting the below error with Fody. We are trying to build it from jenkins. It was working fine previously all of a sudden we are getting this error during msbuild.

\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: The "Fody.WeavingTask" task failed unexpectedly.
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///c:\Jenkins\workspace\packages\Fody.2.0.3\FodyIsolated.dll' or one of its dependencies. Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: --- End of inner exception stack trace ---
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at ContainsTypeChecker..cctor()
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: --- End of inner exception stack trace ---
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at ContainsTypeChecker..ctor()
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at Processor..ctor()
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at Fody.WeavingTask.Execute()
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
\packages\Fody.2.0.3\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()

**Comment by SimonCropp** [comment]
@GirishVenkata why do u think that is the same issue. and can u try with the latest of fody
