### ISSUE TITLE
VariableDefinition and Name property in FodyCecil

### ISSUE THREAD

**Issue by reflection-emit** [Fody/Fody#317]
Can we have a Name property in the VariableDefinition type please. This is very handy in certain situations. The names can be random initially, but it should keep the names we set while weaving. Identifying the variables by index is not possible sometimes.
<br/>
Imagine you have a weaver that adds different things to multiple methods. On the first run it adds a local variable named "result". In method A the index is 2, in method B the index is 6 and in method C the index is 4. On the second run of the weaver adds something else to these methods which also uses the "result" variable. If the VariableDefinition has a name property it would be easy to identify and reuse the variable. With only the index available it is not very straight forward. You have to have a separate dictionary for every method which you have to refresh every time you remove or insert a new variable.

**Comment by SimonCropp** [comment]
FodyCecil  is a direct copy of https://github.com/jbevain/cecil and all questions should be asked there .

it is only shipped as a diff package for convenience of downstream fody addins
