### ISSUE TITLE
Changelog/Release Notes

### ISSUE THREAD

**Issue by cremor** [Fody/Fody#322]
Since version 2.0 was released recently I tried to find a changelog or some release notes. Most projects on GitHub that I know either link to a changelog in the README.md file or use the releases page. Even if no changelog is written manually, the releases page at least lists all tags. But it seems like you don't tag your releases, so the page is completely useless. The last tag it shows is from 2015.

Via Google I found the issue #261 in which you pointed to the GitHub milestones. This is better than nothing, but still has a big issue in my opinion: It is not discoverable at all. At least you should link to it in README.md if this is your "official" place to learn about changes in new versions. But even if you do this I would still suggest that you tag your releases.

**Comment by SimonCropp** [comment]
> . At least you should link to it in README.md if this is your "official" place to learn about changes in new versions. 

sounds good. send me a PR

> But even if you do this I would still suggest that you tag your releases.

i will try and do better at this moving forward
