### ISSUE TITLE
Version 2 is incompatible with version 1

### ISSUE THREAD

**Issue by ygoe** [Fody/Fody#323]
I get an exception about an unexpected version of Cecil when I upgrade from Fody 1.29.4 to 2.0.6. I needed to go back to the old version, that works. Is this breaking change intentional?

**Comment by SimonCropp** [comment]
yes this is intentional

**Comment by ygoe** [comment]
Where can I find information on how to make it work again? Now I need to take care not to update this NuGet package to the latest version.

**Comment by SimonCropp** [comment]
what weavers r u using?

**Comment by ygoe** [comment]
Only [ViewModelKit](https://github.com/ygoe/ViewModelKit) this time.

**Comment by SimonCropp** [comment]
then u need to update this https://github.com/ygoe/ViewModelKit/blob/master/ViewModelKit.Fody/packages.config to fody cecil 2.0

**Comment by ygoe** [comment]
Will this be backwards compatible with older Fody versions and/or other weavers that may still require Fody 1?

**Comment by SimonCropp** [comment]
no

**Comment by ygoe** [comment]
That's an "interesting" upgrade story. So now we have two distinct worlds of Fody add-ins and none of this is documented anywhere? I guess I'll just limit my add-in's NuGet compatibility with Fody < 2.0 to be safe.

**Comment by SimonCropp** [comment]
Not really accurate. Fody follows semver. We had to make a breaking change since the underlying library (Cecil) made some breaking changes. So you should be able to update your weaver to fodycecil v2 and move forward from there

**Comment by ygoe** [comment]
Yes, I can perfectly do this. Now that I know it. But I've found a couple of other weavers in the public list alone that haven't been updated yet. And they can't be used together with newer versions of the already updated weavers. Older versions are always available but may be hard to identify, depending on version semantics. So, it's an "upgrade all or nothing" journey. If one part can't upgrade, you have to stay at the old level.
