### ISSUE TITLE
Migrating plugins to .NET Standard

### ISSUE THREAD

**Issue by tpluscode** [Fody/Fody#324]
Hey. I wanted to submit a PR to update NullGuard to netstandard, which unfortunately means updating Anotar as well.

Is there any Fody plugin already migrated and usable with .NET Standard?

**Comment by SimonCropp** [comment]
yes

 * https://github.com/Fody/Obsolete
 * https://github.com/Fody/Janitor

**Comment by tpluscode** [comment]
Thanks. I looked at Obsolete and I tried a different approach to convert Anotar.Custom. I think that it should be possible to come up with a more troublesome process but a better effect in terms of the code and testability of plugins targeting .NET Standard.

I notice that Obsolete contains `AttributeAssembly` and `AttributeAssemblyNetStandard` built separately. Why not use multiple targets as supported in the new `csproj`? This way you'll get multiple targets when building. For Obsolete I'm currently successfully building the `CustomReferenceAssembly` project for PCL, net35 and .NET Standard 1.0. The problem is that it's necessary to convert every single csproj and I notice that targets will have to be decided on per-Anotar basis because the actual logging libraries target various frameworks. Some don't support Core/Standard at all at this point.

I'm convinced though that this is worth the trouble so that we can run tests against all targets. Unfortunately I've already bumped into an issue with Cecil (looks like jbevain/cecil#306 where `TypeReference#Resolve()` returns null for type `System.String`. I'll follow up soon in a PR to Obsolete...

**Comment by SimonCropp** [comment]
> I notice that Obsolete contains AttributeAssembly and AttributeAssemblyNetStandard built separately. Why not use multiple targets as supported in the new csproj

@tpluscode that is a very good point and i will make that change

**Comment by tpluscode** [comment]
> i will make that change
Cool!

And did you have a chance to look at what I've done so far with Anotar? There is an issue and I'd still have to set up CI.

**Comment by SimonCropp** [comment]
@tpluscode i did. i will use part of your PR in moving it forward. hopefully this week. ATM i am focusing on property changed and netstandard
