### ISSUE TITLE
AutoFac assembly scanner x.Namespace "ProcessedByFody"

### ISSUE THREAD

**Issue by hubert-associates** [Fody/Fody#325]
When I add Fody (newest version) to newest version of AutoFac and populate the AutoFac container using something like:

builder .RegisterAssemblyTypes(this.ThisAssembly) .Where(x => x.Namespace.StartsWith("Samples.Tasks")) .AsImplementedInterfaces() .AutoActivate() .SingleInstance();

I get a null argument exception whenn the enumerator hits the AssemblyQualifiedName "ProccessedByFody".

Feature, bug, pointers? Thanks!

<?xml version="1.0" encoding="utf-8" ?> <Weavers> <ReactiveUI /> </Weavers>

**Comment by SimonCropp** [comment]
can u upload a repro

**Comment by hubert-associates** [comment]
Not yet, still frittering away Xamarin dependency issues. ASAP. Here is what my CoreModules.cs must now do to workaround this ProcessedByFody issue:

         protected override void Load(ContainerBuilder builder) 
        {
            base.Load(builder);

            builder
                .RegisterType<CoreServicesImpl>()
                .AsImplementedInterfaces()
                .SingleInstance();

            builder
                .RegisterAssemblyTypes(this.ThisAssembly)
                .Where(x => x?.Namespace != null && x.Namespace.StartsWith("ClRay.Views"))
                .AsSelf()
                .InstancePerDependency();

            builder
                .RegisterAssemblyTypes(this.ThisAssembly)
                .Where(x => x?.Namespace != null && x.Namespace.StartsWith("ClRay.ViewModels")) 
                .AsSelf()
                .InstancePerDependency();
        }

**Comment by cremor** [comment]
Are you sure it's an ArgumentException? Because `x.Namespace.StartsWith()` will throw a NullReferenceException for all classes that are in the root namespace - like the one that is new in Fody 2.0

**Comment by SimonCropp** [comment]
it would really save me some time if someone uploaded a repro

**Comment by SimonCropp** [comment]
and yes @cremor a null namespace is valid

**Comment by SimonCropp** [comment]
please comment back here when u have confirmed it is not a null namespace problem
