### ISSUE TITLE
InSolutionWeaving not working in VS2015?

### ISSUE THREAD

**Issue by jagt** [Fody/Fody#326]
Hi,

I'm following the [InSolutionWeaving ](https://github.com/Fody/Fody/wiki/InSolutionWeaving) wiki page and downloaded project from master branch and tried out the 'Integration' project, and then tried to open the solution with VS2015.

At first the solution fails to load and I have to manually comment out this line in each `csproj` files:

``` 
<Import Project="$(SolutionDir)\..\ForSample\build\lib\Fody.targets" />
```

After that I've successfully built the solution, but found the tests failed. I've examined the built dlls they aren't processed.

I'm wondering if I'm doing something wrong or I've encountered a bug?
Thanks in advance!

**Comment by SimonCropp** [comment]
can u try building the main [Fody Solution](https://github.com/Fody/Fody/blob/master/Fody.sln) prior to using the Integration solution.

**Comment by SimonCropp** [comment]
i updated the instructions for the Integration sln
