### ISSUE TITLE
Latest Version Installing With NuGet

### ISSUE THREAD

**Issue by afx2004** [Fody/Fody#327]
I cannot install the latest Fody packages in NuGet within Visual Studio 2010.  When I try to install Costura.Fody I get:
> Attempting to resolve dependency 'Fody (≥ 2.0.6)'.
> Install-Package : External packages cannot depend on packages that target projects.
> At line:1 char:16
> + Install-Package <<<<  Costura.Fody
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
>     + FullyQualifiedErrorId : 
> NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
When attempting to install Fody I get:
> Installing 'Fody 2.0.6'.
> Successfully installed 'Fody 2.0.6'.
> Adding 'Fody 2.0.6' to NMS300Diagnostics.
> Uninstalling 'Fody 2.0.6'.
> Successfully uninstalled 'Fody 2.0.6'.
> Install failed. Rolling back...
> Install-Package : Specified argument was out of the range of valid values.
> Parameter name: supportedFrameworks
> At line:1 char:16
> + Install-Package <<<<  Fody
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], ArgumentOutOfRangeException
>     + FullyQualifiedErrorId : 
> NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Version 1.3.3.0 of Costura.Fody, which uses version 1.28.3 of Fody, installs successfully.

**Comment by SimonCropp** [comment]
What version of .net is the target project?

**Comment by afx2004** [comment]
It is targeting .NET 4 Client Profile

**Comment by SimonCropp** [comment]
what version of nuget r u using? https://github.com/NuGet/Home/issues/652

**Comment by afx2004** [comment]
I'm using 2.8.6.  As far as I can tell there are no further updates for NuGet in Visual Studio 2010.

**Comment by SimonCropp** [comment]
Then unfortunately you will need to update to a newer version of VS
