### ISSUE TITLE
Project.json builds broken after update to 2.0

### ISSUE THREAD

**Issue by Alexx999** [Fody/Fody#335]
For project.json based projects Fody can't select proper version - if, say, versions 1.52 and 1.53 of PropertyChanged.Fody are both present in nuget cache on build system it will pick one not based on what version is referenced in project.json but just randomly picked one (for example for PropertyChanged.Fody it's always 1.53 even if my Fody is 1.x and it breaks build, for MugenMVVMToolkit.Fody it's always 4.x even if my Fody is 2.0 and that again breaks build).
It's huge issue actually because it completely locks out build server - after building project that uses new version of Fody it can't build projects with old Fody until nuget package cache is cleared and vice versa.

**Comment by SimonCropp** [comment]
unfortunately project.json was never properly released and has since been deprecated by MS 

here is a tool to migrate off https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-migrate

let me know if the problem persists afterwards

**Comment by Alexx999** [comment]
Well, project.json file is still used for all the UWP and netstandart portable projects (at least in VS2015 and VS2017) - they do have .csproj file but nuget packages are managed via project.json
Sorry if title made you think that we still use outdated .NET Core web tools.

**Comment by SimonCropp** [comment]
did u try running dotnet migrate on the solution in question?

**Comment by Alexx999** [comment]
I realized that since I'm not a web dev I've missed all that .NET Core fun (never used it) so I have no idea what's going on there.
I ran some tests, long story short: VS2015 doesn't even support new csproj format (at least for non-web projects) and you must use bleeding edge tools to get that support in VS2017.

Full story: I tried playing around with VS2015 and VS2017 (both with all available updates: Update 3 for 2015 and 15.2 for 2017) and here are my results:
If you create project from template Visual C# -> Windows Universal -> Class Library (Windows Universal) in VS2015 you always get project.json
If you create project from same template in VS2017 you can choose 15063 SDK that will be based on latest format (but there's large exclamation mark that warns about VS2015 not supporting this). However this SDK is optional even in VS2017 and all previous versions are still project.json based.
If you create portable library in VS2015 and switch it to netstandard it will be project.json based.
If you create portable library in VS2017 - it will be project.json based from the beginning for some combinations (for example, Windows 10 + .NET 4.6) and "classic" csproj for others. Also, if you switch from portable to netstandard it will be always project.json based.
However in VS2017 there's ".Net Standard" template that creates project in "new" format.

Overall - it's a mess and it's very easy to shoot yourself in a leg here.
Also, I there are perfectly valid cases where project.json still exists in latest Microsoft tools (supporting existing UWP applications that target SDKs prior to 15063).
Also it turned out that VS2015 can't open projects in "new" format, only project.json based ones for all cases described above, so if you need VS2015 for any reason - you're stuck with project.json.

**Comment by SimonCropp** [comment]
https://twitter.com/davidfowl/status/730219570783363073
https://wildermuth.com/2016/05/12/The-Future-of-project-json-in-ASP-NET-Core

so u can understand my hesitation to do extra work to support something that was really never out of preview and is now being phased out. i suggest either migrating back to csproj+package.json or moving to VS2017 and the new project system (PackageReference inside the csproj)

**Comment by Alexx999** [comment]
Yeah, I understand that.
However, thing is that while it was never out of preview for .NET Core but for us desktop devs it was part of all Windows 10 SDKs prior to latest one (which is until very recently).

For UWP switching to latest SDK can be breaking change, and switching to VS2017 and re-creating all the projects from scratch (since project.json is still supported here - there's no auto-upgrade now) is a little bit extreme solution too.
Also, there's build servers and other infrastructure so it can be huge pain to update (I'm yet to test "new" project build on out server).

**Comment by SimonCropp** [comment]
ok i am ok with supporting this in the interim. can u submit a PR?

**Comment by SimonCropp** [comment]
@Alexx999 any update on a PR?

**Comment by SimonCropp** [comment]
i looked at this and it is non trivial. i cant see any of this information exposed at the MSBuild level (as it is with the new 2017 csproj format). so this would mean full understanding the project.json format https://github.com/aspnet/Home/wiki/Project.json-file

**Comment by Alexx999** [comment]
@SimonCropp sorry for disappearing - project got postponed for a few years :)
Well, I guess it's not really worth the effort now - after all I was able to upgrade our projects by hand. I suppose .NET Core contains code for reading this format but I'm not sure if it's possible to use it as standalone reader.

**Comment by SimonCropp** [comment]
> NET Core contains code for reading this format

I suspect somewhere there is some nuget code that can read it. but given MS moving away from that format any bug would not be fixed and i suspect the code would soon be deprecated.

Do you need any help moving to the new 2017 csproj format. TBH i am not sure it is possible to use with all project types but i might be able to help u in some ways.

but given the scope of this bug should fody detect Project.json and throw a build error?

**Comment by Alexx999** [comment]
Maybe a warning would be nice - it still kinda works as long as you use only one package version.

**Comment by distantcam** [comment]
This is going to become a problem going forward, and won't go away. The new MSBuild format for referencing nuget packages also uses this system, and the common cache location.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

So the problem here is that Fody doesn't know what versions of what packages to use. Could we pass the `PackageReference` values into Fody?

**Comment by Alexx999** [comment]
@distantcam well, from my experience PackageReference (in .csproj) was detected by Fody just fine, there was problem only with older csproj+project.json combo

**Comment by SimonCropp** [comment]
@Alexx999 i will accept a PR that adds  a warning

**Comment by SimonCropp** [comment]
fyi i added this fyi i added this https://github.com/Fody/Fody/#not-supported

**Comment by Alexx999** [comment]
@SimonCropp "Projects mixing the old .csproj format with new <PackageReference> nodes" - it's new UWP format. So UWP projects are not supported at all - neither old (csproj + project.json) nor new 2017 (csproj + PackageReference) formats.

**Comment by SimonCropp** [comment]
@Alexx999 not sure i grok your comment. are you proposing a content change? or asking a question?

**Comment by SimonCropp** [comment]
i am really sorry but i dont think there is any way to fix this problem. if u come up with any ideas please open a PR or a new issue.
