### ISSUE TITLE
Error with Fody Version 1.29.4

### ISSUE THREAD

**Issue by anselantz** [Fody/Fody#337]
1>    Fody: Fody (version 1.29.4.0) Executing
1>MSBUILD : error : Fody: Could not load 'ModuleWeaver' from 'PropertyChanged.Fody, Version=1.53.0.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
1>MSBUILD : error : It is possible you need to update the package.
1>MSBUILD : error : exception.LoaderExceptions:
1>MSBUILD : error : System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>MSBUILD : error : System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>MSBUILD : error : System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 63ms.

**Comment by SimonCropp** [comment]
1.53 requires 2.0 of fody. I am surprised nuget let u install that combo

**Comment by frooti7** [comment]
@SimonCropp I am getting this error with ModuleWeaver 2.5.10.0
My PropertyChanged.Fody has version 2.2.5
If i update my PropertyChanged.Fody to latest then havoc happens. All the references get lost.
And [AddINotifyPropertyChangedInterface] is not recognized by using PropertyChanged. 
Please help. Its hindering my work
