### ISSUE TITLE
Error property DebugSymbols / PackageDefinitions not defined 

### ISSUE THREAD

**Issue by michaelbradley91** [Fody/Fody#338]
Importing the Fody.targets file results in a build error with version 2.0.8 (updating to handle Mono 5):

.../packages/Fody.2.0.8/build/portable-net+sl+win+wpa+wp/Fody.targets: Error: Error executing task Fody.WeavingTask: Task does not have property "DebugSymbols" defined

Oddly just removing the DebugSymbols line from the targets file allows me to build correctly. I saw a similar issue regarding PackageDefinitions on version 2.0.7 if that is relevant.

Thanks in advance for any help!

**Comment by SimonCropp** [comment]
Can u turn your build log to verbose and tell me if there is a msbuild bariable that points to the path of the pdb?

**Comment by michaelbradley91** [comment]
The OutputPath points to where the symbols file would go (bin\Debug) - it is written with a backslash unlike the other paths... Otherwise, DebugSymbols is defined and set to True, with the type Full.

Did you mean a different build variable?

**Comment by yozzozo** [comment]
I am also seeing the PackageDefinitions issue on Fody 2.0.8.  I am on Visual Studio for MAC (basically Xamarin Studio), latest public stable release (7.0.3146).  I am trying to build an iOS project.

project/packages/Fody.2.0.8/build/netstandard1.4/Fody.targets(64,11): error MSB4064: The "PackageDefinitions" parameter is not supported by the "Fody.WeavingTask" task. Verify the parameter exists on the task, and it is a settable public instance property.

**Comment by lprichar** [comment]
I had the same problem as @yozzozo in VS on a PC after upgrading Fody to 2.0.8 in VS for Mac (we have different developers with different environments).  In my case there was an old Import statement in the csproj that I deleted and the problem went away.  The offending line looked like this:

`<Import Project="..\packages\Fody.1.29.4\build\portable-net+sl+win+wpa+wp\Fody.targets" Condition="Exists('..\packages\Fody.1.29.4\build\portable-net+sl+win+wpa+wp\Fody.targets')" />`

**Comment by SimonCropp** [comment]
@michaelbradley91 @yozzozo can u confirm u dont have duplicate target imports?

**Comment by michaelbradley91** [comment]
I was able to resolve my particular case by changing back to version 2.0.7. I suspect I had the "Package Definitions" issue when I last tried 2.0.7 due to pointing at the wrong targets file somewhere as @lprichar suggested - thanks!

@SimonCropp I did check my target file imports while on 2.0.8 and they appeared to be correct and I didn't notice a duplicate import, but I could be mistaken. I'd be happy for this issue to be considered resolved if there is no one else experiencing it after checking their imports.

Thanks for everyone's help!

**Comment by yozzozo** [comment]
Thanks, I followed @lprichar 's instructions and the problem went away.  I had the duplicate line as well and removing it fixed the issue.

Perhaps this is a symptom of Xamarin Studio / Visual Studio Mac not properly handling NuGet package updates?  I know that PowerShell scripts are not run on this platform, maybe that has something to do with it?

**Comment by SimonCropp** [comment]
I suspect people are being hit by this nuget bug https://github.com/NuGet/Home/issues/2449 which was fixed two days ago

**Comment by SimonCropp** [comment]
@michaelbradley91  not really happy closing this if u are still getting it. can you create a repro and upload it somewhere. and also share a verbose build log for building that repro?

**Comment by SimonCropp** [comment]
ok given there is no response i will close this. @michaelbradley91 if u ever get the time please upload a repro
