### ISSUE TITLE
PEVerify is failing

### ISSUE THREAD

**Issue by BobbyCannon** [Fody/Fody#339]
I upgraded Fody to 2.0.8 and also other Fody nugets and now PEVerify is failing.

<package id="Costura.Fody" version="1.4.1" targetFramework="net462" developmentDependency="true" />
<package id="Fody" version="2.0.8" targetFramework="net462" developmentDependency="true" />
 <package id="PropertyChanged.Fody" version="1.53.0" targetFramework="net462" developmentDependency="true" />

<?xml version="1.0" encoding="utf-8"?>
<Weavers VerifyAssembly="true">
	<Costura />
	<PropertyChanged />
</Weavers>

Error		Fody: PEVerify of the assembly failed.
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x02000096; interface:0x020001ee; method:0x06000fbb). [token:0x0900002E]
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x02000096; interface:0x020001ee; method:0x06000fbc). [token:0x0900002E]
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x02000096; interface:0x020001ee; method:0x06000fc5). [token:0x0900002E]
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x02000096; interface:0x020001ee; method:0x06000fc6). [token:0x0900002E]
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x020000b6; interface:0x020000b5; method:0x0600070e). [token:0x09000040]
[MD](0x80131B51): Warning: Class does not implement interface method in this module (class:0x020000b6; interface:0x020000b5; method:0x0600070f). [token:0x09000040]
[IL]: Error: [C:\Workspaces\Epic Solution\EpicCoders\OmniShell.Desktop\bin\Debug\OmniShell.exe : OmniShell.Desktop.OmniExtensions::ThrowException][offset 0x00000030] Unable to resolve token.(Error: 0x80131869)
... and many more 0x80131869

Is it "safe" to ignore 80131869? Or should I roll back to v1.29.4?

**Comment by SimonCropp** [comment]
80131869 is expected if u do not have an expected dependency existing in the same directory. is that the case? 

it is the reason it is the example here https://github.com/Fody/Fody/wiki/AssemblyVerification
