### ISSUE TITLE
Setting breakpoint in VisualStudio with Fody > 2.0 is not possible

### ISSUE THREAD

**Issue by Ralf1108** [Fody/Fody#341]
It seems that Fody starting with version 2 doesn't create correct pdb files anymore. This becomes visible when break points are set in weaved code.

See attached solution "DebuggingFodyBug". [DebuggingFodyBug.zip](https://github.com/Fody/Fody/files/1004313/DebuggingFodyBug.zip)
It contains 2 projects:

Project "DebuggingOldFodyOk"
Setting breakpoinst works.
It uses following nuget packages:

- Fody 1.29.4
- FodyCecil 1.29.4
- MethodBoundaryAspect.Fody 0.3.29.0

Project "DebuggingLatestFodyBug"
Setting breakpoinst doesnt work.
It uses following nuget packages:

- Fody 2.0.8
- FodyCecil 2.0.8
- MethodBoundaryAspect.Fody 0.3.31.0

Changes in MethodBoundaryAspect.Fody were just adapt to the API changes for Fody version 2.

If you try out the test cases and want to compile the project make sure that only one version of the "MethodBoundaryAspect.Fody" can be installed for the whole solution as Fody seems to always take the latest. So to compile the project "DebuggingOldFodyOk" the nuget package in project "DebuggingLatestFodyBug" has to be downgraded to older version too. Is this really a limitation of Fody?

**Comment by Ralf1108** [comment]
This is how it looks if aspect code in project "DebuggingLatestFodyBug" has an breakpoint:
This breakpoint is never reached.
![grafik](https://cloud.githubusercontent.com/assets/3949137/26105624/f6146b92-3a42-11e7-8172-84060110f6f7.png)


It should look rather like in project "DebuggingOldFodyOk":
![grafik](https://cloud.githubusercontent.com/assets/3949137/26105694/52800742-3a43-11e7-88a6-b7951e02e45b.png)


I think either a change in Fody 2 or the used Mono.Cecil 0.10 changed creation of pdb files so Visual Studio thinks they doesn't match or are incompatible with source code.

**Comment by Ralf1108** [comment]
FYI: ILCode of the executables looks the same except that variable names are different because latest Mono.Cecil doesn't support them any more.

**Comment by distantcam** [comment]
I can't get MethodBoundaryAspect.Fody 0.3.31.0 to compile with FodyCecil 2.0.8.

**Comment by distantcam** [comment]
Oh I see what's going on. The old project is trying to run Fody 1.29.4 which is picking up the newer MethodBoundaryAspect.Fody 0.3.31.0 and failing.

**Comment by distantcam** [comment]
The problem is in MethodBoundaryAspect. Because it's inserting code at the beginning of the method the debug symbols are becoming out of alignment. This is a problem introduced by Mono.Cecil 0.10.

@GeertvanHorrik created an extension method to help realign the debug symbols when you rewrite a method. https://github.com/Catel/Catel.Fody/blob/develop/src/Catel.Fody/Extensions/CecilExtensions.debuginfo.cs#L23

**Comment by SimonCropp** [comment]
the fact that this is failing in debug for MethodBoundaryAspect but not if i change it to obsolete.fody makes me think it is symbols alignment issues in MethodBoundaryAspect

**Comment by SimonCropp** [comment]
lol @distantcam beat me

**Comment by Ralf1108** [comment]
wow, awesome response time! :-)
thx to @distantcam: i will try your proposed extension method asap!

**Comment by Ralf1108** [comment]
@SimonCropp because of the dependency remark
MethodBoundaryAspect does not only contain the weaver but also the base class from which new aspects can derive and insert code when method is called/exited/throws exception.

**Comment by SimonCropp** [comment]
ok. but it should put that in a dedicated attribute assembly with no reference on cecil

**Comment by Ralf1108** [comment]
I will try to factor the base class out of the aspect. thx!

**Comment by Ralf1108** [comment]
yes... when fixing pdb from @distantcam suggestion it works again.
Thank you very much ! :-)
