### ISSUE TITLE
Fody: An Unhandled Exception Occured, Could not load file or assembly

### ISSUE THREAD

**Issue by benzsuankularb** [Fody/Fody#343]
Environment : 

- Visual Studio Community Mac
- FodyCecil 2.0.8
- Fody 2.0.8

There're 3 projects in the solution

1. MyLibrary - netstandard1.3
2. Weaver.Fody - Addin project, have reference to MyLibrary.
3. Application - Make use of Weaver.Fody addin, I've tried both netstandard1.3, 1.6 and netframework4.6.

Following case has no error during build Application project, Also `using MyLibrary` there.

```
using MyLibrary

// In ModuleWeaver
public void Execute() {
       // blah blah... without any reference to MyLibrary's types.
}
```

Following case got this error during build Application project
`An Unhandled Exception Occured, Could not load file or assembly 'MyLibrary...`

```
using MyLibrary

// In ModuleWeaver
public void Execute() {
       // blah blah... without any reference to MyLibrary's types.
       typeof(MyLibrary.MyType); // make use MyLibrary.
}
```

Before this it's happened randomly. I've tried to remove and add reference of MyLibrary many time.
Sometimes it's work, Sometime it doesn't.
But currently not work anymore.

What I've tried so far :

- Restart IDE + Clean Before Build Addin & Application
- Downgrade FodyCecil & Fody.
- Change Application target 
   - .netstandard1.3 - compiled pass but never get trough Execute()
   - .netstandard1.6 & .netframework4.6 - compiled failed. (but work well with [https://github.com/Fody/BasicFodyAddin](BasicFodyAddin) and my case1 above).
- Remove & add reference(MyLibrary) many time.
- Add MyLibrary as assembly to addin.
- Retarget MyLibrary to .netstandard1.6.

**Comment by benzsuankularb** [comment]
Oh, Look like I found something, Not sure it's the actual issue & don't know how to fix it.

NOTE : MyLibrary as NUNET.

```
Fody:   Loading '/Users/admin/Developments/NUNET/Packages/NUNET.Weavers.Fody.1.0.0/NUNET.Weavers.Fody.dll' from cache.
        Fody/NUNET.Weavers:   Executing Weaver 
    MSBUILD : error : Fody: An unhandled exception occurred:
    MSBUILD : error : Exception:
    MSBUILD : error : Could not load file or assembly 'NUNET, Version=1.0.6346.6347, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    MSBUILD : error : StackTrace:
    MSBUILD : error :   at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
    MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x00087] in <f5b06ea159ca4327ad4d03ee98b9636b>:0 
    MSBUILD : error :   at InnerWeaver.Execute () [0x0004d] in <f5b06ea159ca4327ad4d03ee98b9636b>:0 
    MSBUILD : error : 
```
![Uploading Screen Shot 2560-05-17 at 3.36.15 AM.png…]()

Difference version in error log and reference windows. (1.0.6346.6347 and 1.0.6346.4143)

**Comment by GeertvanHorrik** [comment]
Could be a VS for Mac issue with the msbuild pipeline? Did you try the same thing on windows?

**Comment by benzsuankularb** [comment]
@GeertvanHorrik Will tell you when I've tried.

**Comment by SimonCropp** [comment]
@benzsuankularb  NUNET.Weavers.Fody should have any of its references ilmerged
