### ISSUE TITLE
Build error with the DebugSymbols feature on UWP apps

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#344]
![image](https://cloud.githubusercontent.com/assets/1246444/26141360/c730de20-3adb-11e7-8bff-af37169bc603.png)

Still investigating.

**Comment by SimonCropp** [comment]
check if nuget actually updated the include in the csproj

**Comment by distantcam** [comment]
I suspect it's msbuild still using the old WeaverTask assembly with the new target file. Have you tried killing the msbuild process?

**Comment by GeertvanHorrik** [comment]
I checked old msbuild instances, but maybe I oversaw one, it's still early here ;-)

Give me a few minutes

**Comment by GeertvanHorrik** [comment]
It was and outdated [app].nuget.targets. The csproj doesn't directly reference this target file (probably all automatic), but it's in the same dir as the csproj.

Thanks for the help 👍
