### ISSUE TITLE
Release build assemblies modified by Fody 2.0 can't load their symbols

### ISSUE THREAD

**Issue by cremor** [Fody/Fody#350]
I found a problem with Fody 2.0 that didn't happen with Fody 1.29.4 and only appears in release builds. It seems like Fody 2 breaks loading PDB files for those builds.

To be more specific, just enabling "optimize code" or changing "debugging information" to "pdb-only" doesn't trigger the problem. It seems to happen when the project file doesn't specify `<DebugSymbols>true</DebugSymbols>`. If you remove this one line from the project file (I don't think there is a GUI element for it), even debug builds are affected.

This has a few effects:

1. (The big one) Exception stack traces won't have any file or line number information in them, which makes debugging exceptions from log files harder.
2. When "Just my code" is enabled, Visual Studio usually shows a dialog that informs the user that debugging optimized assemblies with "Just my code" enabled doesn't work correctly. This dialog is not shown if the assembly was modified by Fody 2.0.
3. If you continue debugging anyway, the output window usually shows "Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.". But for an assembly modified by Fody 2.0 it shows "Module was built without symbols.", which is wrong because the default release build "debugging information" setting "pdb-only" was used.

It seems like it doesn't matter which weaver is used. It reproduced the problem with PropertyChanged.Fody (2.0.1), ConfigureAwait.Fody (self compiled from the pull request distantcam/ConfigureAwait#14) and even with BasicFodyAddin.Fody (0.4.0), always using Fody 2.0.10.

To reproduce the problem, create a new console application, paste the following code, add Fody and a weaver and start it in a release build.

```
using System;

namespace FodyReleaseSymbolsTest
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Method1();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.ReadLine();
        }

        static void Method1()
        {
            Console.WriteLine("in method 1");
            Method2();
        }

        static void Method2()
        {
            Console.WriteLine("in method 2");
            Method3();
        }

        static void Method3()
        {
            Console.WriteLine("in method 3");
            throw new Exception("Test");
        }
    }
}
```

Expected output:
```
in method 1
in method 2
in method 3
System.Exception: Test
   bei FodyReleaseSymbolsTest.Program.Method3() in C:\path\to\Program.cs:Zeile 35.
   bei FodyReleaseSymbolsTest.Program.Method2() in C:\path\to\Program.cs:Zeile 29.
   bei FodyReleaseSymbolsTest.Program.Method1() in C:\path\to\Program.cs:Zeile 23.
   bei FodyReleaseSymbolsTest.Program.Main(String[] args) in C:\path\to\Program.cs:Zeile 11.
```
   
Actual output:
```
in method 1
in method 2
in method 3
System.Exception: Test
   bei FodyReleaseSymbolsTest.Program.Method3()
   bei FodyReleaseSymbolsTest.Program.Method2()
   bei FodyReleaseSymbolsTest.Program.Method1()
   bei FodyReleaseSymbolsTest.Program.Main(String[] args)
```

**Comment by SimonCropp** [comment]
given fody performs the same operation in debug and release this is a bug in mono cecil can u please raise a bug here https://github.com/jbevain/cecil. sorry for the redirection

**Comment by cremor** [comment]
Fixed in Fody 2.1.0-beta0003

**Comment by SimonCropp** [comment]
@cremor thanks for getting back to me. and sorry again for the misdirection

**Comment by SimonCropp** [comment]
2.1 stable is now deployed
