### ISSUE TITLE
NetStandard Targets Not Running In-Solution Weavers

### ISSUE THREAD

**Issue by TylerBrinkley** [Fody/Fody#352]
I'm in the middle of converting [Enums.NET](https://github.com/TylerBrinkley/Enums.NET/tree/one-solution-to-rule-them-all) over from project.json to csproj and have come across an issue with Fody. My Enums.NET project is multi-targeting various .net framework versions as well as .net standard versions. The .net framework targets are running the in-solution weavers but the .net standard targets are not. However, my test project uses in-solution weavers and multi-targets as well but with .net core app instead of .net standard and those are running just fine. Do you know what could be the issue?

To reproduce you could clone my branch linked above.

**Comment by TylerBrinkley** [comment]
I believe this is due to the fact that I'm targeting .NET Standard 1.0, 1.1, and 1.3 and according to https://github.com/Fody/Fody/issues/206#issuecomment-296487890 Fody currently only supports .NET Standard 1.4+. Ugh, is there anything I can do to get it to run on the lower .NET Standard versions? Is seems odd to me that the Fody runtime is dependent on the project's target framework version.

**Comment by SimonCropp** [comment]
I just released a beta targeting 1.0

**Comment by TylerBrinkley** [comment]
Thanks, that fixed it for me!

**Comment by SimonCropp** [comment]
Good to hear. Should have a stable release mid next week.
