### ISSUE TITLE
PropertyChanged.Fody version is not passed when using PackageReference.

### ISSUE THREAD

**Issue by virzak** [Fody/Fody#354]
Happens when using Fody 2.0.10

Steps to reproduce.

Using VS 2017, PackageReference
Start project 1 using version 1.53.0 Use ImplementPropertyChangedAttribute
Make sure it builds and runs.

Start project 2 using version 2.1.0

Rebuild Project 1
Project 1 will no longer have INotifyPropertyChanged

Tried putting this into the FodyTarget, but got an empty string.

```
<Error Text="Throw @(PackageDefinitions->'%(ResolvedPath)')" />
```

**Comment by SimonCropp** [comment]
sorry i am a little confused here. what exactly is broken?

**Comment by virzak** [comment]
Project 1 that was previously weaved using 1.53.0 will now be weaved using 2.1.0 since it is in the global nugget folder, since its introduction by project 2.

**Comment by SimonCropp** [comment]
Ok can u upload a repro so i can have a look at this in more detail?

**Comment by virzak** [comment]
[PropertyChanged.Fody.Test.zip](https://github.com/Fody/Fody/files/1050357/PropertyChanged.Fody.Test.zip)

It is really minimal. If you have another project anywhere in your system that uses a higher version of propertychanged.fody, this will stop working.
`
        static void Main(string[] args)
        {
            var a = (INotifyPropertyChanged)(new TestClass());
        }

        [ImplementPropertyChanged]
        public class TestClass
        {
            public int Value { get; set; }
        }
`

**Comment by distantcam** [comment]
I see the problem now. This is similar to #335

**Comment by SimonCropp** [comment]
on note  `ImplementPropertyChanged` is deprecated

and mixing versions of a weaver withing the same sln is not supported

**Comment by distantcam** [comment]
Even ignoring the mixing within a solution, the problem will still occur if
you ever used a later version of a weaver.

**Comment by virzak** [comment]
These projects could very well belong to different solutions and you would still have the same issue.

This issue is just to demonstrate that once you upgraded the package with breaking change, all other

**Comment by SimonCropp** [comment]
@virzak but those project have not been updated to the csproj format

eg in your sample

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
```

rather than https://github.com/Fody/FodyAddinSamples/blob/master/PropertyChangedSample/PropertyChangedSample.csproj

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
```

TBH i am surprised VS even support mixing in that way

**Comment by SimonCropp** [comment]
also the fact that in when u mix an old csproj with `PackageReference` nodes  that no `PackageDefinitions` exists should be considered a bug in MSBuild

**Comment by SimonCropp** [comment]
in that mixed mode u are susceptible to the same problem as `project.json` because we are using the global nuget dir but we have no way of determining what version of the nugets to use

**Comment by distantcam** [comment]
That's the thing, I don't think that global nuget cache is going away. I
think Microsoft is going to keep that approach.

**Comment by SimonCropp** [comment]
@distantcam and that is fine. in the new 2017 sdk style projects msbuild passes us the correct nuget versions.

**Comment by SimonCropp** [comment]
fyi i added this https://github.com/Fody/Fody/#not-supported

**Comment by SimonCropp** [comment]
as it stands i dont think there is any way for us to fix this
