### ISSUE TITLE
VS2015, Fody is not embedding the dll

### ISSUE THREAD

**Issue by cguanes** [Fody/Fody#355]
I used Fody and Costura.Fody with VS2013, it worked perfect and it was very simple way to have the library embedded on same binary.
Now I migrated to VS2015 and it is not working anymore.
I have the Fody and Costura.Fody updated to last version 2.10 and 1.6.1.
Is this a known problem?
I used to just install the nuget packages and didn't need to configure anything... Something changed?

Thank you.

**Comment by distantcam** [comment]
I am unable to reproduce your problem. Could you provide more information?

**Comment by SimonCropp** [comment]
It would be helpful if u uploaded a solution that reproduces the issue

**Comment by SimonCropp** [comment]
Let me know if u ever get around to that repro

**Comment by cguanes** [comment]
I will make a small project to reproduce and send it to you.

Thanks

Carlos
