### ISSUE TITLE
Fody >= 2.0.8 producing assemblies without debug information

### ISSUE THREAD

**Issue by bording** [Fody/Fody#360]
While testing to see if #357 successfully enables the sourcelink scenario, I noticed it still was wasn't working. I tested the PDB, and it had all of the correct info. However, I noticed in the VS Modules debugger windows that it was showing that "Binary was not built with debug information", so it wasn't even trying to load the PDB.

After testing all of the recent releases to see where this started happening, 2.0.7 and earlier are producing assemblies that can load symbols correctly, but 2.0.8 and newer are all broken.

The older 2.0.x releases aren't tagged, but looking at the milestones it appears that #334 was the only change between 2.0.7 and 2.0.8. I verified that $(DebugSymbols) was true in the build I was using to test this, so it would appear that the newly added DebugSymbols property is false even when it shouldn't be, causing Fody to incorrectly skip writing the PDB.

**Comment by bording** [comment]
I tried adding a log warning to https://github.com/Fody/Fody/blob/master/FodyIsolated/SymbolsFinder.cs#L19 and that's definitely what's happening. This DebugSymbols property is false even when it shouldn't be.

**Comment by bording** [comment]
Digging into this a bit more, seems like it might be related to the SDK-style csproj format. Investigating...

**Comment by bording** [comment]
OK, so looking at both the original and SDK-style projects, $(DebugSymbols) appears to be the wrong property to base this check on, because by default this value isn't set on Release builds, but those builds are still producing PDBs. 

It looks like $(_DebugSymbolsProduced) is a better option, because that value seems to accurately reflect the PDB-generation state indepent of the value of $(DebugSymbols).

**Comment by SimonCropp** [comment]
@davkean according to this https://msdn.microsoft.com/en-us/library/bb629394.aspx `DebugSymbols` is 

> A boolean value that indicates whether symbols are generated by the build.

So isnt the behavior @bording describes above a bug?

**Comment by SimonCropp** [comment]
@bording the problem with `_DebugSymbolsProduced` is that given it is undocumented there is no guarantee that it works on other versions or incarnations of msbuild.

**Comment by distantcam** [comment]
`DebugSymbols` defaults to true when `DebugSymbols` is blank and `Configuration == Debug`

https://github.com/Microsoft/msbuild/blob/master/src/Tasks/Microsoft.Common.CurrentVersion.targets#L142

That would explain the variance between Debug/Release. I don't know why it only defaults for Debug though.

**Comment by SimonCropp** [comment]
@distantcam the problem is in release it is false even when producing pdbs

**Comment by distantcam** [comment]
I meant the variance in the DebugSymbol value, not the pdb output. :)

**Comment by distantcam** [comment]
It looks like a combination of `DebugSymbol` and `DebugType` are used to calculate whether a pbd is generated.

https://github.com/Microsoft/msbuild/blob/master/src/Tasks/Microsoft.Common.CurrentVersion.targets#L145-L151

`DebugType` is set in release builds, and seems to override `DebugSymbol`. Fody should follow the same logic.

**Comment by SimonCropp** [comment]
@distantcam i just came to the same conclusion https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L66

**Comment by SimonCropp** [comment]
but isnt the `Condition=" '$(ConfigurationName)' == 'Debug'` part of this
```
<DebugSymbols Condition=" '$(ConfigurationName)' == 'Debug' and '$(DebugSymbols)' == '' and '$(DebugType)'==''">true</DebugSymbols>
```

a bug?

What i name a configuration should have not impact on config. eg i might call a config `Debug2` to experiment with some tweaks, but looking at the above code it would have unintended side effects

**Comment by distantcam** [comment]
That whole section is a bug. If `DebugType == full` for example, then the value of `DebugSymbol` is irrelevant.

**Comment by SimonCropp** [comment]
@bording i just published https://www.nuget.org/packages/Fody/2.1.0-beta0002 with the `DebugType` hack.

**Comment by distantcam** [comment]
Bug filed - https://github.com/Microsoft/msbuild/issues/2169

**Comment by SimonCropp** [comment]
2.1 stable is now deployed

**Comment by drauch** [comment]
This seems to be unresolved still. We cannot debug into assemlbies rewritten by Fody if we use the new project format + target the full .NET framework 4.7.

Breakpoints are not hit either, because of the following error:

![image](https://user-images.githubusercontent.com/1516470/29264282-bce520a6-80dc-11e7-92b7-64c4c5997d72.png)

If we disable Fody the debugger works fine.

**Comment by drauch** [comment]
@SimonCropp : Do you think it has to do with this issue, or is it better to create a new issue for the problem?

**Comment by chrischu** [comment]
Any update on this issue?

**Comment by SimonCropp** [comment]
@chrischu does the behaviour differ between release and debug builds?

**Comment by chrischu** [comment]
We only really tried with debug builds really, but correct me if I'm wrong: I don't think release builds have a better likelihood of working, do they?

**Comment by SimonCropp** [comment]
ok can can u try the version 2.3.2 https://www.nuget.org/packages/Fody/2.3.2

**Comment by chrischu** [comment]
It works correctly when using DebugType=full as seen here (but that also worked with the older version):
![image](https://user-images.githubusercontent.com/447251/34197549-4c94a3d6-e567-11e7-8120-c93f8b419f23.png)

However, when we set the DebugType to portable the breakpoints are no longer hit (the tooltip from @drauch's comment on Aug 14 is shown when hovering over the breakpoint).

**Comment by drauch** [comment]
Any update on this?
