### ISSUE TITLE
Fody 2.1.0 - The "DebugSymbols" parameter is not supported by the "Fody.WeavingTask" task

### ISSUE THREAD

**Issue by renzska** [Fody/Fody#362]
I'm hitting the following trying to use Fody.2.1.0:

> /packages/Fody.2.1.0/build/portable-net+sl+win+wpa+wp/Fody.targets(11,11): Error MSB4064: The "DebugSymbols" parameter is not supported by the "Fody.WeavingTask" task. Verify the parameter exists on the task, and it is a settable public instance property. (MSB4064)

I'm running Visual Studio for Mac.

**Comment by renzska** [comment]
More details with more accurate source code line numbers:

> /packages/Fody.2.1.0/build/portable-net+sl+win+wpa+wp/Fody.targets(65,11): error MSB4064: The "DebugSymbols" parameter is not supported by the "Fody.WeavingTask" task. Verify the parameter exists on the task, and it is a settable public instance property.

> /packages/Fody.2.1.0/build/portable-net+sl+win+wpa+wp/Fody.targets(53,5): error MSB4063: The "Fody.WeavingTask" task could not be initialized with its input parameters.

**Comment by distantcam** [comment]
Try quiting VS and then reopening the solution.

**Comment by renzska** [comment]
Tried this, but it still fails.

I removed the DebugSymbols line and then I get a DebugType line. Removed both of those lines and it works...

```
DebugSymbols="$(DebugSymbols)"
DebugType="$(DebugType)"
```

**Comment by distantcam** [comment]
That's because the build process is still using the old version of Fody. Removing those lines will fail next time the build process is restarted.

Usually quitting VS fixes that problem. I'm not sure how to force the msbuild process to exit on a Mac.

**Comment by renzska** [comment]
I'll restart and see if that solves it.

**Comment by rprouse** [comment]
I am seeing this too after updating to Fody 2.1.0 and updating PropertyChanged.Fody to 2.1.2 using the latest update to VS 2017.

- I tried restarting Visual Studio and even rebooting
- I checked that the imports in my project file are correct and there are no duplicates
- Two other very similar projects are building fine

The only thing that worked was downgrading back to Fody 2.0.7.

**Comment by SimonCropp** [comment]
Can u please upload a repro?

**Comment by SimonCropp** [comment]
let me know if u ever get around to that repro

**Comment by rprouse** [comment]
I will do, thanks. It is happening on one of three projects for me and I can't repro on a project I can share, so best to close for now.

**Comment by TimKras** [comment]
Same problem here. One of our projects gives these errors.

**Comment by SimonCropp** [comment]
Again. I need a repro

**Comment by TimKras** [comment]
I found the problem. It is located in the csproj file.
At the bottom there are multiple Import lines after upgrading:

 Condition="Exists('..\packages\Fody.1.29.4\build\dotnet\Fody.targets')" />
 <Import Project="..\..\..\Solution1\Project1\packages\Fody.1.29.4\build\dotnet\Fody.targets" Condition="Exists('..\..\..\Solution1\Project1\packages\Fody.1.29.4\build\dotnet\Fody.targets')" />
 <Import Project="..\..\Solution1\Project1\packages\Fody.2.0.10\build\netstandard1.4\Fody.targets" Condition="Exists('..\..\Solution1\Project1\packages\Fody.2.0.10\build\netstandard1.4\Fody.targets')" />
 
When removing the first two lines, the error is gone. It looks like the Import statements are not cleaned when updating the nuget packages.

**Comment by SimonCropp** [comment]
@TimKras yeah that is a bug in nuget https://github.com/NuGet/Home/issues/2449

**Comment by rprouse** [comment]
> When removing the first two lines, the error is gone. It looks like the Import statements are not cleaned when updating the nuget packages.

Hopefully that is it for us too although a bad version of the targets was my first thought and I went through our CSPROJ file. Maybe I missed it. I will try upgrading again.
