### ISSUE TITLE
New Fody does no longer support FodyWeavers.xml at solution level?

### ISSUE THREAD

**Issue by chrischu** [Fody/Fody#363]
I noticed that updating to Fody 2.1.0 adds a FodyWeavers.xml file to every project (as usual), however with this version it seems I cannot remove those files since I then get build errors ("Could not file a FodyWeavers.xml at the project level"). Is this expected behavior?

I really liked having just one FodyWeavers.xml file at the solution level that applied to all projects in previous version.

**Comment by chrischu** [comment]
Hello? Anybody there?

**Comment by SimonCropp** [comment]
if u leave the FodyWeavers.xml at the project level does it still use the solution level?

**Comment by chrischu** [comment]
Yes it does. 

In my opinion the exception in https://github.com/Fody/Fody/blob/master/Fody/ConfigFileFinder.cs#L21 should probably be changed to only throw when there is neither a solution nor a project level config.

I guess the original intent was to handle projects that do not support content file adds, but maybe there is another way to solve this?

**Comment by SimonCropp** [comment]
> I guess the original intent was to handle projects that do not support content file adds, but maybe there is another way to solve this?

it is. and i am open to suggestions

> should probably be changed to only throw when there is neither a solution nor a project level config.

agreed. this is a bug and i will try to get to it this weekend

**Comment by chrischu** [comment]
Mhh according to https://github.com/NuGet/Home/issues/4803 content files are actually supported (you just have to put them in the contentFiles folder (for netstandard projects) as well as the content folder (for older projects)).

Unfortunately it seems as if editing content files is not supported anymore, but in the mentioned thread they propose using init.ps1 to create those files, maybe that's an option?

**Comment by chrischu** [comment]
Is there any update regarding this issue?

**Comment by SimonCropp** [comment]
Sorry i have not gotten to it. Do u want to try for a pull request?

**Comment by chrischu** [comment]
Created a pull request https://github.com/Fody/Fody/pull/371.

I hope you like the solution I used :).

**Comment by drauch** [comment]
I'm really looking forward to that too, please release it, the PR seems mergeable 👍

**Comment by SimonCropp** [comment]
this should now be on nuget. sorry for the delay
