### ISSUE TITLE
NETStandard 2.0 - "Fody: An unhandled exception occurred"

### ISSUE THREAD

**Issue by OrihuelaConde** [Fody/Fody#364]
`5>  Fody: Fody (version 2.1.0.0) Executing
5>MSBUILD : error : Fody: An unhandled exception occurred:
5>MSBUILD : error : Exception:
5>MSBUILD : error : La secuencia no contiene ningún elemento coincidente
5>MSBUILD : error : StackTrace:
5>MSBUILD : error :    en System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
5>MSBUILD : error :    en ModuleWeaver.ExecuteWinRT()
5>MSBUILD : error :    en ModuleWeaver.FindCoreReferences()
5>MSBUILD : error :    en ModuleWeaver.Execute()
5>MSBUILD : error :    en lambda_method(Closure , Object )
5>MSBUILD : error :    en InnerWeaver.ExecuteWeavers() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 181
5>MSBUILD : error :    en InnerWeaver.Execute() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 86
5>MSBUILD : error : Source:
5>MSBUILD : error : System.Core
5>MSBUILD : error : TargetSite:
5>MSBUILD : error : TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
5>MSBUILD : error :
5>  Fody:   Finished Fody 21ms.`

NETStandard.Library 2.0-preview3
Visual Studio 2017 15.3 Preview 2

**Comment by SimonCropp** [comment]
what weaver(s) r u using?

**Comment by OrihuelaConde** [comment]
PropertyChanged

**Comment by SimonCropp** [comment]
can u close this and re-open in the PropertyChanged repo
