### ISSUE TITLE
Weaver version determine logic question

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#368]
I've been trying to use the right (debug version) weaver, but somehow I couldn't get it to work. Then I enabled normal logging and noticed this:

```
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\caseless.fody\1.4.2\Caseless.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.14.0\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.15.0\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.15.0-unstable0002\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.16.0\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.16.1\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.17.0-unstable0013\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\catel.fody\2.4.0-unstable0004\Catel.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.3.3\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.3.5\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.4.0\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.4.1\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.5.0\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.5.1\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.6.0\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.6.1\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\costura.fody\1.6.2\Costura.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\equals.fody\1.6.2\Equals.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\equals.fody\1.7.0\Equals.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\equals.fody\1.7.1\Equals.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\jetbrainsannotations.fody\1.0.5\JetBrainsAnnotations.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\loadassembliesonstartup.fody\1.7.0\LoadAssembliesOnStartup.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\loadassembliesonstartup.fody\1.8.0\LoadAssembliesOnStartup.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\loadassembliesonstartup.fody\1.8.1\LoadAssembliesOnStartup.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.15.10\MethodTimer.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.16.0\MethodTimer.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.17.0\MethodTimer.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.18.0\MethodTimer.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.19.0\MethodTimer.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\moduleinit.fody\1.5.9\ModuleInit.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\moduleinit.fody\1.6.0\ModuleInit.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\obsolete.fody\4.0.5\Obsolete.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\obsolete.fody\4.1.0\Obsolete.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\obsolete.fody\4.2.1\Obsolete.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\obsolete.fody\4.2.2\Obsolete.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\propertychanged.fody\1.52.1\PropertyChanged.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\propertychanged.fody\1.53.0\PropertyChanged.Fody.dll'
2>    Fody: Fody weaver file added 'C:\Users\geert\.nuget\packages\visualize.fody\0.4.5\Visualize.Fody.dll'
2>    Fody: No Weaver project file found.
2>    Fody: Finished finding weavers 30ms
2>    Fody: Creating a new AppDomain
2>    Fody: Reference count=217
2>    Fody: Found debug symbols at 'C:\Source\MyProject\src\MyProject\obj\x86\Debug\MyProject.pdb'.
2>    Fody: Weaver 'C:\Source\MyProject\src\../lib\ModuleInit.Fody.1.6.0\ModuleInit.Fody.dll'.
2>    Fody:   Initializing weaver
2>    Fody:   Loading 'C:\Source\MyProject\src\../lib\ModuleInit.Fody.1.6.0\ModuleInit.Fody.dll' from disk.
2>    Fody: Weaver 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.19.0\MethodTimer.Fody.dll'.
2>    Fody:   Initializing weaver
2>    Fody:   Loading 'C:\Users\geert\.nuget\packages\methodtimer.fody\1.19.0\MethodTimer.Fody.dll' from disk.
2>    Fody: Weaver 'C:\Users\geert\.nuget\packages\catel.fody\2.16.1\Catel.Fody.dll'.
2>    Fody:   Initializing weaver
2>    Fody:   Loading 'C:\Users\geert\.nuget\packages\catel.fody\2.16.1\Catel.Fody.dll' from disk.
2>      Fody/ModuleInit:   Executing Weaver 
2>      Fody/ModuleInit:   Finished 'ModuleInit' in 75ms 
```

Interesting is this line:

Fody: Weaver 'C:\Users\geert\.nuget\packages\catel.fody\2.16.1\Catel.Fody.dll'.

Where I have installed 2.17.2 (first to the project, then to the whole solution, restarted (all) VS afterwards). 

Here is the directory structure inside 'C:\Users\geert\.nuget\packages\catel.fody'

![image](https://user-images.githubusercontent.com/1246444/27484461-937436a2-5829-11e7-8337-5e46ac14841d.png)

Any idea why it force picks the last stable version instead of the one specified as dependency?

**Comment by GeertvanHorrik** [comment]
Checking the following interesting code locations:

1. https://github.com/Fody/Fody/blob/5383a396c5974e205a637ccf2a42e56538607d09/Fody/InstanceLinker/WeaversConfiguredInstanceLinker.cs#L23
2. https://github.com/Fody/Fody/blob/master/Fody/AddinFinder/AddinFilesEnumerator.cs#L14

I think the latest is the issue.

**Comment by GeertvanHorrik** [comment]
Not sure if Fody should just pick the latest, best would be if a version (based on nuget config) could be specified.

**Comment by SimonCropp** [comment]
in the old csproj system there is no way to determine the nuget version. and parsing and determining the correct nuget version from the nuget config is more difficult than it sounds. so fody assumes the latest in the packages dir. this was always correct when the packages dir was at the solution level. but broke when the global cache was added in the new csproj system. but in the new csproj system we do have access to the nuget info in msbuild, hence we can determin the correct version.

So give the above description i would guess u r using either project.json or mixing the old and new project formats? as described here https://github.com/Fody/Fody#not-supported  ?

**Comment by GeertvanHorrik** [comment]
Thanks for your fast and detailed reply on your Friday evening!

This affects a UWP app (which is .net core), but will be migrated to the new project system at a later stage if I am not mistaken. For now I will make sure the latest stable version is useful :)

Thanks!

**Comment by SimonCropp** [comment]
TBH i think the fact that it doesnt use the latest unstable is a bug

**Comment by MendelMonteiro** [comment]
We have a CI server which builds for multiple branches (including older production branches) and the nuget packages folder are shared and not cleaned between the different branches.  When we update our Fody version in one of our development branches suddenly our production branches start trying to load the new, incompatible, version.

I am surprised other people have not run into this problem before.

**Comment by SimonCropp** [comment]
@MendelMonteiro are u using any of the not supported scenarios ? https://github.com/Fody/Fody#not-supported

**Comment by MendelMonteiro** [comment]
I don't think so but I'll have to check on monday to be sure

**Comment by MendelMonteiro** [comment]
I've checked and we are using old-school .csproj files **without** package reference nodes.

**Comment by SimonCropp** [comment]
TBH i dont know how to fix this. PRs are accepted

**Comment by SimonCropp** [comment]
give MS has started closing issues for the old csproj format with "move to package references" https://github.com/NuGet/Home/issues/4165#issuecomment-337397392 i think it is safe to assume that the old csproj is abandonware. as such i wont be putting any effort into fixing this. if someone else wants to i will accept a PR.
