### ISSUE TITLE
Doesn't work in Visual Studio for Mac

### ISSUE THREAD

**Issue by MihaMarkic** [Fody/Fody#369]
Testing PropertyChanged in Visual Studio for Mac and it spits out:

"Fody: Could not find a weaver named PropertyChanged"

I'm guessing it just some sort of path problem. Also tried directly with msbuild.

**Comment by SimonCropp** [comment]
can u upload a repro solution?

**Comment by MihaMarkic** [comment]
I'm just investigating.

Below is MSBuild output. It finds fody in .nuget, but doesn't find propertychanged.fody directory for some reason.

I'm looking at code in ScanNuGetPackageRoot, this thing:
`var fodyWeaverDirectories = Directory.EnumerateDirectories(nuGetPackageRoot, "*.?ody")
.Where(dir => dir.ToLowerInvariant().EndsWith(".fody"));`

I tried running it within MacOS (passing /Users/miha/.nuget/packages/ as nuGetPackageRoot) and it find both.

> FodyTarget:
    Fody: Fody (version 2.0.0.0) Executing
    Fody: ProjectDirectory: '/Users/miha/Projects/testing/FodyStandard/FodyStandard/'.
    Fody: AssemblyPath: '/Users/miha/Projects/testing/FodyStandard/FodyStandard/obj/Debug/netstandard1.4/FodyStandard.dll'
    Fody: Found path to weavers file '/Users/miha/Projects/testing/FodyStandard/FodyStandard/FodyWeavers.xml'.
    Fody: SolutionDirectory path is '/Users/miha/Projects/testing/FodyStandard/'
    Fody: Finding weavers
    Fody: Skipped scanning '/Users/miha/Projects/testing/FodyStandard/Packages' for weavers since it doesn't exist.
    Fody: Could not find packages dir from nuget config.
    Fody: SolutionDirectoryPath: /Users/miha/Projects/testing/FodyStandard/
    **Fody: Adding weaver dlls from '/Users/miha/.nuget/packages/fody'.**
    Fody: SolutionDirectoryPath: /Users/miha/Projects/testing/FodyStandard/
    Fody: Skipped scanning '/Users/miha/Projects/testing/FodyStandard/Tools' for weavers since it doesn't exist.
    Fody: No Weaver project file found.

**Comment by MihaMarkic** [comment]
Uploaded sample to [my server](https://misc.rthand.com/FodyStandard.zip).
Works on Windows but not on Mac.

**Comment by MihaMarkic** [comment]
I see that I'm missing the last part of output.

> MSBUILD : error : Fody: Could not find a weaver named 'PropertyChanged'. 
    MSBUILD : error : If you have nuget package restore turned on you probably need to do a build to download the weavers. 
    MSBUILD : error : Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate nuget package. 
    MSBUILD : error : Perhaps you need to run 'Install-Package PropertyChanged.Fody'. This url may provide more information http://nuget.org/packages/PropertyChanged.Fody/

**Comment by MihaMarkic** [comment]
Interesting, if I "dirty" build fody on Mac and insert few Logger.LogDebug lines here and there, substitute binaries in Fody package, then it finds propertychanged assembly, but crashes later due to some other error (VTable setup of type InnerWeaver failed).

**Comment by MihaMarkic** [comment]
Seems similar to #331 but that is supposed to be fixed, right?

**Comment by MihaMarkic** [comment]
OK, found out what's really going on. Installing PropertyChanged.Fody in VS for Mac installs it along Fody 2.0.0. Furthermore Fody is nested within PropertyChanged.Fody and VS4M won't update it to the latest version nor offer upgrade notification.
I did manually install Fody 2.1.0 from NuGet and then it starts working properly.
At the end this is a VS4M/NuGet issue.
