### ISSUE TITLE
Is it possible to call Fody from the command line?

### ISSUE THREAD

**Issue by r3db** [Fody/Fody#372]
For example like this:

`Fody.exe MyProject.csproj`
or
`Fody.exe MyAssembly.dll MyFodyWeavers.xml`

The reason I ask is because I'm using Roslyn to compile my Solution.
And Roslyn completely ignores Fody's build step.

**Comment by distantcam** [comment]
You're not using MSBuild to call the Roslyn compiler? Fody integrates with MSBuild.

I created a standalone wrapper exe for Fody to work with Unity here https://github.com/distantcam/Fody4Unity. You could take that and make your own version.

**Comment by r3db** [comment]
Roslyn does use MSBuild but it seems to completely ignore Fody.
Thanks for the suggestion, I'll check your wrapper, it seems the way to go.

Thanks
