### ISSUE TITLE
Set VerifyAssembly attribute by default

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#373]
In a perfect world, I would love to have it set to true, but I understand that you are a bit hesitant to do so. However, what if we add the  VerifyAssembly="false" to the FodyWeavers.xml template? Makes people more aware of the feature and then I only have to add "true" to new projects.

**Comment by SimonCropp** [comment]
> However, what if we add the VerifyAssembly="false" to the FodyWeavers.xml template

I think that would be viable historically. but kind of pointless moving forward give in the new VS project system that file is no longer added

**Comment by GeertvanHorrik** [comment]
Does the end-developer have to add it manually or why is it no longer being added?

**Comment by SimonCropp** [comment]
MS deprecated that feature. so people now have to add it manually

**Comment by GeertvanHorrik** [comment]
In that case let's close this ticket. Thanks for the fast response!

**Comment by SimonCropp** [comment]
agreed. it is not ideal but i cant think of anything better

**Comment by distantcam** [comment]
> MS deprecated that feature. so people now have to add it manually

Is there a doc page about this? I'm getting more and more issues about this. Eg Fody/Costura#223

**Comment by SimonCropp** [comment]
yeah should prob update this https://github.com/Fody/Fody/wiki/SampleUsage#2-add-the-weaver-nuget-package
