### ISSUE TITLE
Fody looking for weaver .csproj at invalid path

### ISSUE THREAD

**Issue by BrunoJuchli** [Fody/Fody#376]
I'm on Fody 2.1.2 and developing using VS 2017.3 Preview 4 as well as .net core 2.0 preview 2.
I tried to structure my project similarly to `PropertyChanged.Fody`.

My "Integration Test" assembly uses the new VS2017 csproj format and has a `<ProjectReference...` to the weaver (`StaticProxy.Fody`). When building the integration test assembly, within the same solution as the weaver, i get an unhandled exception with message:

> Could not find a part of the path '(...)\StaticProxy.Fody.VS2017\IntegrationTests\StaticProxy.Fody\StaticProxy.Fody.csproj'.

That's because the folder `IntegrationTests` was not removed from the path.

Btw., the stacktrace is:

> StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at AddinFinder.FindAddinDirectories() in C:\projects\fody\Fody\AddinFinder\AddinSearchDirectories.cs:line 23
   at Processor.FindWeavers() in C:\projects\fody\Fody\Processor.cs:line 119
   at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 87
   at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 48

and the "Build" output just before the exception is:

> 2>        Task Parameter:DebugSymbols=True
> 2>        Task Parameter:DebugType=portable
> 2>          Fody: Fody (version 2.1.2.0) Executing
> 2>          Fody: ProjectDirectory: 'C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\'.
> 2>          Fody: AssemblyPath: 'C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\obj\Debug\net462\IntegrationTests.dll'
> 2>          Fody: Found path to weavers file 'C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\FodyWeavers.xml'.
> 2>          Fody: SolutionDirectory path is 'C:\Development\StaticProxy.Fody.VS2017\'
> 2>          Fody: Finding weavers
> 2>        MSBUILD : error : Fody: An unhandled exception occurred:
> 2>        MSBUILD : error : Exception:
> 2>        MSBUILD : error : Could not find a part of the path 'C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\StaticProxy.Fody\StaticProxy.Fody.csproj'.
> 2>        MSBUILD : error : StackTrace:
> 2>        MSBUILD : error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> 2>        MSBUILD : error :    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
> 2>        MSBUILD : error :    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
> 2>        MSBUILD : error :    at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
> 2>        MSBUILD : error :    at AddinFinder.FindAddinDirectories() in C:\Code\Fody\Fody\Fody\AddinFinder\AddinSearchDirectories.cs:line 23
> 2>        MSBUILD : error :    at Processor.FindWeavers() in C:\Code\Fody\Fody\Fody\Processor.cs:line 119
> 2>        MSBUILD : error :    at Processor.Inner() in C:\Code\Fody\Fody\Fody\Processor.cs:line 87
> 2>        MSBUILD : error :    at Processor.Execute() in C:\Code\Fody\Fody\Fody\Processor.cs:line 48

I'm currently having a look at the source code of Fody to find the issue.

My code: https://github.com/BrunoJuchli/StaticProxy.Fody

**Comment by BrunoJuchli** [comment]
So... It seems the tooling i'm using is supplying invalid `@(PackageDefinitions->'%(ResolvedPath)')`.

In [`Fody.targets`  the `@(PackageDefinitions->'%(ResolvedPath)'](https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L64) are passed into the `WeavingTask`.
The only manipulation to the PackageReferences I can find on the whole path is when the [WeavingTask converts the `string[]` array to a list with `PackageDefinitions = PackageDefinitions?.ToList()`](https://github.com/Fody/Fody/blob/c0e777a69258e3432308fd1e4e32cfdd1d12fba5/Fody/WeavingTask.cs#L69).

This means that apparently the tooling version i'm using is generating the wrong path from my `<ProjectReference Include='...'/>`.
The path generated vs expected:

> C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\StaticProxy.Fody\StaticProxy.Fody.csproj
> C:\Development\StaticProxy.Fody.VS2017\StaticProxy.Fody\StaticProxy.Fody.csproj

**Comment by BrunoJuchli** [comment]
Opened Issue with dotnet/sdk: https://github.com/dotnet/sdk/issues/1435

**Comment by BrunoJuchli** [comment]
@SimonCropp 
I guess the way I'm trying to run things is not a supported scenario, anyway, is it?

However, It probably would be best to handle this (instead of failing) in one way or the other: either support *.csproj PackageDefinitions and employ these weavers or ignore/filter them (should this be silent, if not, what's the best way to report this to the user)?

Would you be inclined to taking a PR? If yes, requirements / pointers would be appreciated

**Comment by gtbuchanan** [comment]
Is there a workaround for this? Perhaps being able to exclude projects from Fody analysis? I see the [PR was merged](https://github.com/dotnet/sdk/issues/479), but it's not slated for release until v2.1.3 (which has no release date).

**Comment by SimonCropp** [comment]
Afaik this is fixed and released. If u r experiencing something similar I suggest u raise and anclue a repro. Or better yet submit a pr that fixes the issue
