### ISSUE TITLE
Is placing weaver plugins in the parent folder of Fody.dll officially supported?

### ISSUE THREAD

**Issue by mario-d-s** [Fody/Fody#381]
According to the [AddinSearchPaths](https://github.com/Fody/Fody/wiki/AddinSearchPaths) wiki page, the following 3 methods of wiring weavers are supported:
* Nuget Package directories
* SolutionDir/Tools
* A project in the solution named 'Weavers'.

I want to use Fody + [PropertyChanged](https://github.com/Fody/PropertyChanged) for a single project in a solution that contains 25 projects, but we don't use Nuget at our company so I had to find a manual solution. The third one, I understand, is for custom plugins.

I also prefer not to choose the second "solution-wide" way because it simply doesn't affect the other 24 projects.

So I went digging into the code and found that Fody [looks for plugins in its own parent directory](https://github.com/Fody/Fody/blob/master/Fody/AddinFinder/AddinSearchDirectories.cs#L87).

Using a project structure like this:
* Project <- .csproj sets `$(FodyPath)` to `$(ProjectDir)Build\Fody` and imports `Build\Fody.targets`
  * Build
    * Fody <- contains `Fody.dll` and dependencies
    * PropertyChanged.Fody <- contains `PropertyChanged.Fody.dll`
    * Fody.targets
  * FodyWeavers.xml <- contains `<PropertyChanged />`

Everything works perfectly.

My only fear is that this may no longer work in future versions of Fody since the parent folder of `Fody.dll` is not listed as an official addin search path.

So, is the documentation incomplete or am I doing something I shouldn't?

**Comment by SimonCropp** [comment]
i dont understand this

> I also prefer not to choose the second "solution-wide" way because it simply doesn't affect the other 24 projects.

that will not happen. it only includes weavers when u have them in the fodyweavers.xml. just having binaries sitting in a solution dir will not cause them to execute

**Comment by mario-d-s** [comment]
@SimonCropp I understand your confusion, but that part was purely a non-technical issue. The solution is shared across a large team and I wanted to contain (hide) all the fody stuff as much as possible into just the one project that would make use of it.  My concern was that others would be confused about the Tools folder and start misusing it for other stuff.

**Comment by SimonCropp** [comment]
Can u clarify why you are not using nuget?
