### ISSUE TITLE
Documentation for manual install (i.e. without Nuget)

### ISSUE THREAD

**Issue by mario-d-s** [Fody/Fody#382]
There is a wiki page that promises to detail a manual setup procedure: [Setup](https://github.com/Fody/Fody/wiki/Setup#how-to-manually-add-to-a-project).

It has been empty since august of 2013 however, but the [preceding revision](https://github.com/Fody/Fody/wiki/Setup/c0c8006243525d816ede8ed5b4c2fbf6c39d9a09) seems correct to me (in that the specified procedure works fine).

I needed to do a manual setup recently and I might be the only one still interested, but I was wondering about the reason that page had been cleared?

I can help write a new one if that is still of interest.

**Comment by SimonCropp** [comment]
i decided it was too much effort for people to install without nuget. also nuget is so ubiqutous these days
