### ISSUE TITLE
Link weaved code with stack trace.

### ISSUE THREAD

**Issue by benzsuankularb** [Fody/Fody#385]
I weaved my methods in a class
1. Add new method B
2. Put the body of method A to body of B.
3. Replace body of A with new code.
After weaved, code line in this class couldn't show on stack trace when having exception.

> System.ExampleException : blah
>  at NS.MyClass.MethodB (string str) [0x00020] in <37d86fb498314636b0fa0e142a85aa4c>:0
>  at NS.MyClass.InvokeMethodB () [0x00001] in /NS/MyClass.cs:36

This make very hard to debug.
Any ways to link the stack trace with weaved code.

**Comment by SimonCropp** [comment]
* what version of fody are you using 
 * what weaver and what version are you using

**Comment by benzsuankularb** [comment]
- .Net4.6
- Fody 2.1.2
- I've tried both Mono.Cecil and FodyCecil 2.1.2

I notice maybe ```MethodDefinition.DebugInformation``` are something related to what I need.
I've tried to fix properties but nothing change in stack trace.

* Note : Stack trace of all methods except weaved method in this class work normally.

**Comment by benzsuankularb** [comment]
OK, solved.

Make a copy of ```MethodDefinition.DebugInformation.SequencePoints``` from original method to weaved one is the way.

@SimonCropp Thank so much for your support.
