### ISSUE TITLE
Control Fody behaviour for particular configurations

### ISSUE THREAD

**Issue by akamyshanov** [Fody/Fody#387]
Apologies for raising the same topic once again (https://github.com/Fody/Fody/issues/158, https://github.com/Fody/Fody/issues/237). However, I now have a use case where I can't find a decent workaround.

The project provides Web API and uses https://github.com/Fody/Costura to pack all dependencies into a single executable. After the merge referenced DLLs are deleted from the output folder. I would also like to generate stuff from the assembly with the help of https://github.com/RSuter/NSwag. The problem is that NSwag loads the assembly via reflection and fails to load the dependencies because Costura not doing it's magic.

So, at the time being I'm forced to enable `DisableCleanup` and manually remove the DLLs after the build.

A totally valid solution in this case would just be to cancel any Fody actions with a defined constant (or something similar).

**Comment by akamyshanov** [comment]
For anyone struggling with something similar, we've ended up with a more or less decent workaround.
The idea is to conditionally override any imported targets from Fody or it's weavers to do nothing instead of what they're doing originally.

Project file **after** any Fody imports:
```xml
<!-- or any other condition you like -->
<Import Project="DisableFody.targets" Condition="'$(Configuration)' == 'SwaggerGen'" />
```

DisableFody.targets:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Override Fody targets to do nothing -->
  <Target Name="FodyTarget" />
  <Target Name="FodyVerifyTarget" />
  
  <!-- And it's weavers, for example Costura -->
  <Target Name="CosturaFilterReferenceCopyLocalPaths"/>

</Project>
```

**Comment by SimonCropp** [comment]
can u upload a small repro that shows what you r trying to do with swagger?

**Comment by akamyshanov** [comment]
@SimonCropp 
Sure: https://github.com/akamyshanov/webapi-costura-nswag
[master](https://github.com/akamyshanov/webapi-costura-nswag/tree/master) branch builds fine
[costura](https://github.com/akamyshanov/webapi-costura-nswag/tree/costura) branch fails

In short, if methods of a controller reference types from a separate assembly, NSwag cannot load them (since the DLLs aren't there anymore after Costura cleanup) and fails.

**Comment by aakash1906** [comment]
@akamyshanov :
Reg. your comment - The workaround does not work with the new SDK-style projects because .targets from <PackageReferece/> are always added after any user-defined ones.

We can get around for SDK-style projects following this workaround.

<PackageReference Include="Fody" Version="2.4.6">
		<ExcludeAssets>build</ExcludeAssets>
	</PackageReference>
<Import Project="$(NuGetPackageRoot)fody\2.4.6\build\fody.targets" />
<Import Project="DisableFody.targets" Condition="'$(Configuration)' == 'SwaggerGen'" />

Even if we don't give ExcludeAssets above, it will still work. It will just give a warning about importing targets twice but will still work.

**Comment by akamyshanov** [comment]
It seems that this feature has been silently added to the project by bc0f7c195c7256ba052858e5aa28faa1ce2051b1. Not sure whether it was intentional, but it works.

Adding the code below to the `.csproj` file disables weaving:
```xml
<PropertyGroup>
  <DisableFody>true</DisableFody>
</PropertyGroup>
```

Of course, msbuild conditions also work!

🍾
