### ISSUE TITLE
Unable to include Realm sub project in parent project

### ISSUE THREAD

**Issue by Belxanthian** [Fody/Fody#391]
I have created a logging project using Realm and have compiled it Fody processes that project fine, however when I try to include that project into a parent project I get a Fody Exception.

7>    Fody: Fody (version 2.0.6.0) Executing
7>MSBUILD : error : Fody: An unhandled exception occurred:
7>MSBUILD : error : Exception:
7>MSBUILD : error : Operation is not valid due to the current state of the object.
7>MSBUILD : error : StackTrace:
7>MSBUILD : error :    at Mono.Collections.Generic.Collection`1.Enumerator.CheckState()
7>MSBUILD : error :    at Mono.Collections.Generic.Collection`1.Enumerator.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
7>MSBUILD : error :    at ModuleWeaver.<GetReferencedTypes>d__70.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
7>MSBUILD : error :    at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
7>MSBUILD : error :    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
7>MSBUILD : error :    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
7>MSBUILD : error :    at ModuleWeaver.WeaveSchema(TypeDefinition[] types)
7>MSBUILD : error :    at ModuleWeaver.Execute()
7>MSBUILD : error :    at lambda_method(Closure , Object )
7>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 180
7>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 85
7>MSBUILD : error : Source:
7>MSBUILD : error : Mono.Cecil
7>MSBUILD : error : TargetSite:
7>MSBUILD : error : Void CheckState()
7>MSBUILD : error : 
7>    Fody:   Finished Fody 205ms.

If I remove the reference to my logging pcl the parent project will build properly.  Both projects use Realm but two different Realm files. (Logging.realm and Registration.realm)

Any help would be appreciated.

Thanks

**Comment by SimonCropp** [comment]
can u upload a repro
