### ISSUE TITLE
Fody update process leaves artefacts in .csproj files breaking builds

### ISSUE THREAD

**Issue by luetm** [Fody/Fody#393]
Hi!

We have Fody in our project for a while and recently made the jump from v1 to v2. When creating new installations we noticed, that all the projects, that once had a reference to v1 Fody and PropertyChanged.Fody do not build anymore. The problem is this line in the *.csproj file ...

`<Error Condition="!Exists('..\packages\Fody.1.29.4\build\dotnet\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.1.29.4\build\dotnet\Fody.targets'))" />`

... that did not get updated by the nuget update process. The replacement ...

`<Error Condition="!Exists('..\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets'))" />`

.. got added as the new line instead. It's fixable with a regex search replace over the whole solution, but I thought maybe you were not aware of it!

Cheers and thanks for Fody!

luetm

**Comment by luetm** [comment]
Sorry, this seems to be a nuget problem, not of this package. Sorry!

**Comment by SimonCropp** [comment]
yeah sorry. i was going to reply as such but could not find the relevant nuget bug.
