### ISSUE TITLE
Visual Studio F5 doesn't work with Fody but the produced dll is working

### ISSUE THREAD

**Issue by foresightyj** [Fody/Fody#394]
I was trying out Fody the first time. I created a new console project in VS2017 and installed the Equals.Fody package and tried with the following code:

    class Program
    {
        static void Main(string[] args)
        {
            var p1 = new Person { Age = 10, Name = "Xixi" };
            var p2 = new Person { Age = 10, Name = "Xixi" };

            Console.WriteLine(p1 == p2);
            Console.ReadKey();
        }
    }

    [Equals]
    public class Person
    {
        public int Age { get; set; }
        public String Name { get; set; }
    }

If I run this directly in Visual studio by pressing F5, the result is `false`:

![image](https://user-images.githubusercontent.com/1296736/29491584-14f79a6c-8592-11e7-9b37-802f884e3f7e.png)

I peeked into the exe via ilspy, the generated code is exactly as Equals.Fody described:

![image](https://user-images.githubusercontent.com/1296736/29491591-2667fd96-8592-11e7-8474-6bd094c239a2.png)

I tried with Linqpad by loading the generated exe in `bin/Debug`, and the code worked as intended:

![image](https://user-images.githubusercontent.com/1296736/29491549-6c1054a2-8591-11e7-8bd6-b4f4fd0a03e2.png)

It seems that pressing F5 runs the code before the weaving process actually happened but the produced dll/exes are just fine. This is obviously not good for development. Am I missing anything? I was looking for common FAQs but didn't find any in Fody's github page.

**Comment by SimonCropp** [comment]
What version of fody and what version of VS?

**Comment by foresightyj** [comment]
I am using VS2017 with Fody.2.1.2 and Equals.Fody.1.7.1

**Comment by SimonCropp** [comment]
can u upload a solution that reproduces the problem.

and also are you running the latest of VS 2017?

**Comment by foresightyj** [comment]
I always had problems in uploading a zip file to github.

I uploaded my project to github, [HERE](https://github.com/foresightyj/HelloFody)

Thanks for your time.

**Comment by distantcam** [comment]
This is an equals fody bug. Same as Fody/Equals#10

**Comment by foresightyj** [comment]
@distantcam thanks for the info :-)
