### ISSUE TITLE
Pass path of XML-Documentation file to weaver

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#397]
Weavers adding new types or members that are public visible should be able to extend the XML documentation to include the new content.

**Comment by SimonCropp** [comment]
What weavers need this. 

And is not viable to go with a convt based on the path to the assembly?

**Comment by tom-englert** [comment]
I was evaluating e.g. [AutoDependencyProperty.Fody](https://blog.machinezoo.com/no-more-dependencyproperty-with) and found that when using it there was no more documentation for the dependency properties that were generated.

Unfortunately the default location of the documentation file is even different depending on the Visual Studio version that created the project, and is subject to custom configuration. Sometimes it's not even in the intermediate but already in the target folder.

**Comment by SimonCropp** [comment]
Good enough for me. I will review your PR in Monday
