### ISSUE TITLE
Using netstandard 2.0 weaver in a console app (.net 4.6.1) fails with FileNotFoundException

### ISSUE THREAD

**Issue by csnemes** [Fody/Fody#401]
I'm trying to create the netstandard 2.0 version of my plugin but I've encountered the following issue: When I create a test console app (.net 4.6.1) and add the nuget package containing my weaver (.netstd 2.0) it resolves the dependencies correctly and also creates the FodyWeavers.xml. But when I build the project I got the following error: `
Error		Fody: Could not load 'ModuleWeaver' from 'Tracer.Fody, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
It is possible you need to update the package.
exception.LoaderExceptions:
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
I'm using the latest fody 2.1.2 both for my weaver and for the test console. Do you have any idea what I'm doing wrong?
Thanks

**Comment by SimonCropp** [comment]
upload a small repro

**Comment by SimonCropp** [comment]
my guess would be Tracer.Fody is referencing netstandard, and at build time the weaving is not happening in a netstandard compat runtime

**Comment by csnemes** [comment]
I upgraded to Fody 2.2.0 and cleaned up the project file (it contained import for multiple versions of fody.targets) and now it works properly.
