### ISSUE TITLE
Fody.dll does not get inherited from other project

### ISSUE THREAD

**Issue by AlenToma** [Fody/Fody#406]
I will start by saying that i really love this library, it make my life really easy.
But now i have a problem, i have build a library that called Generic.LightDataTable and added it to nuget.
i have added Fody and PropertyChanged.Fody as Dependencies. but when the user install the nuget package, PropertyChanged.Fody injection never work until he install it manually, so additionally to my library he have to download again Fody from nuget.

is there a configuration fix or something to avoid that ? please help

**Comment by SimonCropp** [comment]
can u upload a repro illustrating the problem

**Comment by AlenToma** [comment]
Hi Simon and thank you for answering so quickly.
[Here ](https://mega.nz/#!MxYkhDqC!tWB3SKW7ptKvms_Q84bCx2GvqIWrj6YyI-w-4zSSkLY) i have added a test Project that represent the problem, i have also added some screen shot that shows that Fody is fully installed.
you could also see my lightdatatable repo at [Here](https://github.com/AlenToma/LightDataTable.Core)

what i want is that Fody functionality gets inherited from other project without the need to install it separately. 

With regards Alen Toma

**Comment by SimonCropp** [comment]
the problem is in your nuspec u have

```
<dependency id="Fody" version="2.1.2" exclude="Build,Analyzers" />
```

when what u want is 

```
<dependency id="Fody" version="2.1.2" include="Build" />
```

**Comment by SimonCropp** [comment]
https://github.com/AlenToma/LightDataTable.Core/pull/2
