### ISSUE TITLE
Version 2.1.3 doesn't add targets reference to .NET 4.5 project files

### ISSUE THREAD

**Issue by cervengoc** [Fody/Fody#407]
We have a large solution where we're using `Fody` in many projects. Upgrading from `2.1.2` to `2.1.3` broke our code because the `Fody.targets` references just disappeared from all the corresponding projects. Downgrading back to `2.1.2` adds the references again and everything works fine.

Could you please investigate this issue? Thank you in advance for your help.

OS: Windows 8.1 x64
IDE: Visual Studio 2017 (latest)
Projects: Classic .NET 4.5 C# projects
Special settings: Nothing except for a custom `repositoryPath` setting in `nuget.config` which points `..\..\packages` so one level upper than default.

**Comment by SimonCropp** [comment]
Does it also occur in net 452? https://github.com/Fody/Fody#supported-runtimes

**Comment by cervengoc** [comment]
@SimonCropp thank you for pointing that out. It was indeed a 4.5 project. When I changed to 4.5.2 it seems to work fine. It would be good to emphasize these more. Also it would be good if you could add some kind of release notes for each release because now it's really hard - it not impossible - to find what actually happened in a version.

Thank you for your work, I'm gonna close this.
