### ISSUE TITLE
Fody does not postprocess the assembly

### ISSUE THREAD

**Issue by toverux** [Fody/Fody#412]
Hi mainteners,

I've just installed Fody in a new Xamarin.Forms project.
This is a recent setup with Visual Studio 2017 (15.3.5).

With latest version 2.1.3, Fody does not start (no error, no message in console, no weaver applied - IL code unchanged).

Dowgrading to 2.1.2 fixes this and I can see the usual messages:

```
1>    Fody: Fody (version 2.1.2.0) Executing
1>      Fody/ReactiveUI:   ReactiveUI 7.4.0.0
1>      Fody/ReactiveUI:   ReactiveUI.Fody.Helpers 2.2.11.0
1>      [...]
1>    Fody:   Finished Fody 62ms.
```

I've got only one weaver installed for now, [ReactiveUI.Fody](https://github.com/kswoll/ReactiveUI.Fody).

**Comment by SimonCropp** [comment]
what .net runtime are you targeting? https://github.com/Fody/Fody#supported-runtimes

**Comment by toverux** [comment]
PCL Profile 111, is that supported? I'm quite inexperienced in this ecosystem. What surprises me is that it breaks on a patch version and the package seems compatible with my profile since it installs via NuGet without complaining.

**Comment by SimonCropp** [comment]
> package seems compatible with my profile since it installs via NuGet without complaining.

nuget is not great in it capacity to make this a failing case.

>  What surprises me is that it breaks on a patch version

yes this was un-intentional. i am trying to work out how to move forward given the current status

is it possible to target netstandard in Xamarin.Forms?

**Comment by toverux** [comment]
It seems so, for a few months: https://blog.xamarin.com/building-xamarin-forms-apps-net-standard/
But project templates are still based on PCLs. I'll try to find a good guide (most are outdated) and migrate.

**Comment by toverux** [comment]
So upgrading to the new VS 2017 csproj and netstandard seems a bit hard and I had a bad time, will do that when my skill get better :smile:

So I've rollbacked all the changes and tried again to upgrade to Fody 2.1.3. I noticed that the upgrade was causing this diff in the csproj:

```diff
     <Error Condition="!Exists('..\packages\Xamarin.Forms.2.4.0.282\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xamarin.Forms.2.4.0.282\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.targets'))" /> 
-    <Error Condition="!Exists('..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets'))" />
   </Target> 
-  <Import Project="..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets" Condition="Exists('..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets')" />
```

...without adding a reference to Fody 2.1.3.

So I changed the csproj manually so it looks like this:

```diff
     <Error Condition="!Exists('..\packages\Xamarin.Forms.2.4.0.282\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xamarin.Forms.2.4.0.282\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.targets'))" /> 
-    <Error Condition="!Exists('..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets'))" />
+    <Error Condition="!Exists('..\packages\Fody.2.1.3\build\netstandard1.2\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.2.1.3\build\netstandard1.2\Fody.targets'))" />
   </Target> 
-  <Import Project="..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets" Condition="Exists('..\packages\Fody.2.1.2\build\portable-net+sl+win+wpa+wp\Fody.targets')" />
+  <Import Project="..\packages\Fody.2.1.3\build\netstandard1.2\Fody.targets" Condition="Exists('..\packages\Fody.2.1.3\build\netstandard1.2\Fody.targets')" /> 
```

And that works just fine. Does that looks viable? Also, why did I had to do that?

**Comment by SimonCropp** [comment]
I temporarily added pcl support back in 2.2. I will try to find a better way to depreciate it

**Comment by toverux** [comment]
Thank you!
