### ISSUE TITLE
version >2.0.6 not working with realm

### ISSUE THREAD

**Issue by dafi81** [Fody/Fody#413]
the update to realm 2.0 has fody >= 2.1.2 as a dependency. My app is no longer working. It compilse fine but at runtime there are is no Realm- Unhandled Exception:
System.InvalidOperationException: No RealmObjects. Has linker stripped them? See https://realm.io/docs/xamarin/latest/#linker-stripped-schema occurred.

I created a min Version of the Problem: https://drive.google.com/open?id=0B7Tkmvhy_ZYIOWdhZHhMUmtTQk0

**Comment by SimonCropp** [comment]
can u try updating to net452 https://github.com/Fody/Fody#supported-runtimes

**Comment by dafi81** [comment]
Can you explain how I can do that?
![pcl_selectiondialog](https://user-images.githubusercontent.com/16352569/31860710-c3e39d56-b71e-11e7-848f-feb3c5f366ed.PNG)

**Comment by SimonCropp** [comment]
https://developer.xamarin.com/guides/cross-platform/application_fundamentals/net-standard/

**Comment by SimonCropp** [comment]
I temporarily added pcl support back in 2.2. I will try to find a better way to depreciate it
