### ISSUE TITLE
Fody fails to find assembly with the same name

### ISSUE THREAD

**Issue by Logerfo** [Fody/Fody#415]
I have the current setup:
```
Solution1
  -Library1
  -Weavers1
Solution2
  -Library2
  -Weavers2
```
>Weavers1 depends on Library1.
Weavers2 depends on Library1 and Weavers1.
Library2 depends on Library1, Weavers2 and Weavers1. 

In my case, both weaver projects were named "Weavers", which caused the following error trying to build Solution2: `Could not load type 'Weavers.Utils' from assembly 'Weavers...`
Renaming any of the Weaver projects fixed the issue.

**Comment by Logerfo** [comment]
Searching through the code I've found out the cause of this issue:
https://github.com/Fody/Fody/blob/3705c852155aa90013c2251f783c5860be1a9bef/Fody/WeaverProjectFileFinder.cs#L40
Fody only looks for the first reference with the name "Weavers.dll"
A solution for this may come by itself with the implementation requested in my other issue https://github.com/Fody/Fody/issues/416.

**Comment by SimonCropp** [comment]
closed since https://github.com/Fody/Fody/pull/419#issuecomment-352729393
