### ISSUE TITLE
Idea for replacing feature "Installing Weaver updates FodyWeavers.xml"

### ISSUE THREAD

**Issue by BrunoJuchli** [Fody/Fody#422]
Facts:
 - with the **new csproj format** nuget removed the "on installation" extension point, so the weavers cannot add themselves to the FodyWeavers.xml
 - this means a breaking change
 - Fody loses some usability (more manual steps involved)
 - this behavior could technically be retained for old-style csproj format

Now, in my opinion:
- having different behavior depending on csproj format is *ugly*
- having to support the old behavior just for some customers is not good use of our "spare time"

So I was thinking that maybe, instead of just removing the feature, you (@SimonCropp) might be open to a PR that replaces this feature with a different mechanism?

Suggestion
-----------------------

Given the following **assumption**:

> We want to run all weavers we have installed, so if we're fine with their default values, we don't mind whether they are actually configured in a file or not.

This would mean we could "just" execute all installed weavers. If they're not in the config file: use default settings. If they're in the config file: use configured settings.

Now come the **caveats**.  Even though I don't remember exactly what they are, I know there are multiple search paths. The assumption might not be valid for all search paths. Let's say there would be a search path "nuget package cache". Since the new csproj format/nuget stores all nuget packages you ever use in that cache, being in that cache does not state that we want to use it.

So to go further with this, we would need to specify which search paths are eligible for automatic inclusion.

Feedback
---------------

I would like to ask you (@SimonCropp) if that's generally a direction that would be ok with you, and if so, for some guidances. I'm ready to dive deeper into the source code and check all the current options for search paths etc. I'd make an assessment / concept and ask you to review it. If we agree on specifics I would implement that.

**Comment by SimonCropp** [comment]
firstly thanks for taking the time to put together this quality proposal.

unfortunately this is approach i have considered before and ruled out due to a few complexities

the primary one is that order of weavers is important. as soon as you have more than one there is the possibility of either desired or undersired effects of that order. eg when using the combo of Fielder, PropertyChanged and Validar. there is no way that order can be inferred without the xml config

**Comment by BrunoJuchli** [comment]
I agree that configuration is still necessary for lots of use cases.
If 99% of users were to just use one weaver (that doesn't need to be configured - extra-bonus-constraint) then I'd say the feature would have been worth it.
But of course, it would also have to be designed in a way so that it doesn't hide issues. As soon as there are multiple weavers it should make configuration of all mandatory.

So since we don't know how usage of Fody is actually distributed I guess the current approach - do it manually - is the sensible thing. I personally use multiple weavers quite often.

If anything, for my personal usage scenarios, I'd see more benefit in sharing weaver configurations. We basically have all the same weaver configs in all our prod and all our test assemblies.

But if I've got it right, sharing is already possible - by copying to the output directory.
Only problem there is that we copy all files to the same output directory :D
