### ISSUE TITLE
Broken project build succeeds second time in Visual Studio

### ISSUE THREAD

**Issue by matburton** [Fody/Fody#423]
Steps to reproduce with Fody 2.2.1:
1. Create this `example.csproj` with adjacent `FodyWeavers.xml` file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModuleInit.Fody" Version="1.7.0" />
  </ItemGroup>
</Project>
```
2. Open `example.csproj` in Visual Studio 2017 (I used 15.4.4)
3. `Build Solution` and note the build fails correctly with `Fody: Could not find path to weavers file`
4. `Build Solution` again and note the build succeeds when it shouldn't (might need to repeat this if you get lucky somehow)

This is not unique to this mistake, e.g. if we create this adjacent `FodyWeavers.xml` file:
```
<Weavers>
    <ModuleInit/>
</Weavers>
```

Then the build fails correctly with an error from the `ModuleInit.Fody` plugin.
But again a second build succeeds when it shouldn't.

I'm guessing maybe this is because the build is classed as `up-to-date` because there is output in the `obj` folder that matches the input files in the project?

I couldn't reproduce this by doing `msbuild /t:Restore;Build example.csproj`

(Sorry I was just experimenting with Fody and don't have the know-how fix this myself)

**Comment by BrunoJuchli** [comment]
Could you please provide the build output of an ok and a failing build? I'm experience an issue which might be related and I'm wondering if there are some matching symptoms.

**Comment by SimonCropp** [comment]
Closed due to no response
