### ISSUE TITLE
"WeaverXYZ expected to be executed. ..." when building even though weaver is configured

### ISSUE THREAD

**Issue by BrunoJuchli** [Fody/Fody#424]
I'm posting this here, not on Equals.Fody, because it affects other weavers, too.

- VS 15.4.5/15.4.4
- Target Framework: .net Framework 4.7.1
- classic csproj with packages.config
- Fody 2.2.1.0
- Equals.Fody.1.7.1
- Issue also reproducible on other work mates computers. We all use the same tooling versions (just that some of us are still on Win7 while some are on Win10).

I *sometimes* get the following error when building:
(sometimes => never after clean)

> Equals expected to be executed. You may need to manually add '&lt;Equals /&gt;' into your FodyWeavers.xml. eg &lt;Weavers&gt;&lt;Equals/&gt;&lt;/Weavers&gt;. See https://github.com/Fody/Fody/wiki/SampleUsage

- FodyWeavers.xml already contains `<Equals>`.
- Now, if I delete the assembly.dll and build again, the error vanishes, but sometime later will occur again

Build Output
--------------------

*Initial (ok) Build*

> 4>------ Build started: Project: Erowa.EMC.DeviceCore, Configuration: Debug x86 ------
> 4>  Weavers file: C:\work\current\net\source\Erowa.EMC.DeviceCore\FodyWeavers.xml
> 4>    Fody: Fody (version 2.2.1.0) Executing
> 4>    Fody:   Finished Fody 36ms.
> 4>  Erowa.EMC.DeviceCore -> C:\work\current\net\artifacts\Debug\Server\Erowa.EMC.DeviceCore.dll
> 4>    Fody:   Skipped Verifying assembly since it is disabled in configuration
> 4>    Fody:   Finished verification in 0ms.
> ========== Build: 4 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

*Problematic build* (previous build already finished)

> 1>------ Build started: Project: Erowa.EMC.DeviceCore, Configuration: Debug x86 ------
> 1>  Erowa.EMC.DeviceCore -> C:\work\current\net\artifacts\Debug\Server\Erowa.EMC.DeviceCore.dll
> 1>C:\work\current\net\source\packages\Equals.Fody.1.7.1\build\dotnet\Equals.Fody.targets(13,5): error : Equals expected to be executed. You may need to manually add '<Equals />' into your FodyWeavers.xml. eg <Weavers><Equals/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage
> ========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

Investigation
---------------------

Suspicious: With the problematic build, Fody is not running but `FodyEqualsVerification` is. 
`FodyTarget` is configured with `AfterTargets="AfterCompile"`, `FodyEqualsVerification` is configured with `AfterTargets="AfterBuild"`, so we have a definite mismatch there.

observation: At the time when `FodyEqualsVerification` is executed, `$(FodyExecutedWeavers)` is `string.Empty`.

Now, I changed `FodyEqualsVerification` to have **`AfterTargets="FodyTarget"`**. But that changes *absolutely* **nothing**:

- Build output still doesn't show any Fody messages
- `FodyEqualsVerification` still runs
 - --> build still fails with same warning
- `$(FodyExecutedWeavers)` still *empty*

This seems *very* suspicious since I would now either expect both targets to run or none of them to run. If both would have run, Fody should have produced some output in the build log.
@SimonCropp Or am i wrong here? Is there some optimization in the Fody task (I don't know of) that it will detect that there were no changes and it'll not execute?

**Comment by BrunoJuchli** [comment]
Possibly related to https://github.com/Fody/Fody/issues/423

**Comment by SimonCropp** [comment]
perhaps related to this https://github.com/Fody/Fody/wiki/TaskAddsAFlagInterface ?

**Comment by SimonCropp** [comment]
> With the problematic build, Fody is not running but FodyEqualsVerification is.
FodyTarget is configured with AfterTargets="AfterCompile", FodyEqualsVerification is configured with AfterTargets="AfterBuild", so we have a definite mismatch there.

this is by design since we need all the files to exist for PE verify to run. if u run in the obj dir they will not exist yet

**Comment by SimonCropp** [comment]
i suspect the problem is here https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L85

at the very least we should add a `'$(DesignTimeBuild)' != 'true'`

also when u get the problem can u tell me what `FodyWeavingTargetWasRun` evaluates to?

**Comment by SimonCropp** [comment]
we could possibly add `FodyTarget` https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L48 to the `FodyVerifyDependsOnTargets` variable (in a new prop) and then make `FodyVerifyTarget` depend on that new set of targets https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L85

then we could drop the need for `FodyWeavingTargetWasRun`

**Comment by BrunoJuchli** [comment]
@SimonCropp Thanks for your time and inputs. I'll check the contents of `FodyWeavingTargetWasRun` next time the problem occurs.
I'll also check for the contents of the condition at https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L85

To be hoenst, to me it seemed like Fody weaving might have been skipped because VS/MSBuild detected there were no changes, but the after-build Equals verification target was still run.

Not all weavers produce a warning when they aren't run, right?
If you remember, could you tell me why deleting Equals.dll from TargetDir is necessary? (Or rather why copying it there is necessary in the first place). https://github.com/Fody/Equals/blob/master/NuGet/dotnet.targets#L7

**Comment by SimonCropp** [comment]
i released a new version of equals. can u try that?

**Comment by BrunoJuchli** [comment]
@SimonCropp 
Thanks. Will do. We always update all our dependencies every second week ;-)
Tough: I haven't run into the issue again since I reported it. When I reported it, it occured quite often. Why it stopped occuring - no clue. I have updated Visual Studio...

I'll close this issue for now and reopen it in case it'll occur again.

**Comment by SimonCropp** [comment]
Cool. I am fairly sure i fixed. But i just wanted and 3rd party confirmation. So yep just let me know if u hit it again

**Comment by BrunoJuchli** [comment]
@SimonCropp great, thanks. Could you point me to the fix/commit? I'd like to become more of an expert for Fody/msbuild. Might make it easier to contribute :-)
