### ISSUE TITLE
Feature request: CodeInsight with mixins

### ISSUE THREAD

**Issue by mrpmorris** [Fody/Fody#431]
Not sure if this is even possible, but I'd really like to be able to mix-in features from another class *and* have the mixed in features available in code-insight and at compile time.

```
public class SomeMixIn()
{
  public string MixInMethod() => "Hello";
}

[MixIn(typeof(SomeMixIn))]
public class ClassThatHasMixIn
{
}

var instance = new ClassThatHasMixIn();
string mixinResult = instance.MixInMethod();
Console.WriteLine(mixinResult);
```

Is this even possible?

**Comment by SimonCropp** [comment]
would one of these suffice? https://bitbucket.org/skwasiborski/mixins.fody/wiki/Home https://github.com/rileywhite/Cilador  ?

**Comment by mrpmorris** [comment]
@SimonCropp I think you may have misunderstood the request. I am not requesting mixins, I am requesting the ability to have code-insight in the editor for class that have mixins.

For example, in the first link I would have to implement the interface that the mixin implements and add (ToBe.Introduced).  I just want to be able to specify a mix-in and then the editor would act as if I had already added the interface + implemented it, without me having to type anything.

I am hoping the new language services in the IDE will make this possible.

**Comment by SimonCropp** [comment]
@mrpmorris have you done a spike to verify it is possible?

**Comment by mrpmorris** [comment]
@SimonCropp Sorry, I am not familiar with that term. Obviously, therefore, the answer is "no", but I would like to understand your question. Could you elaborate, please?

**Comment by SimonCropp** [comment]
http://www.extremeprogramming.org/rules/spike.html

**Comment by mrpmorris** [comment]
Ah, I see, thanks! It's not a technology I am currently familiar with, how about you?

PS: Check Twitter :)

**Comment by SimonCropp** [comment]
not really something i am experienced with either :(
