### ISSUE TITLE
Fody v2.3.1 breaks Xamarin.Forms

### ISSUE THREAD

**Issue by Dids** [Fody/Fody#435]
While I haven't been able to track down the main reason causing the issue, v2.3.0 and below work fine, while v2.3.1 causes a rather nasty (and hard to track down) exception to be caused when used with Xamarin.Forms:

```
Error MSB4018: The "XamlCTask" task failed unexpectedly.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
```

I'm more interested in what changed between v2.3.0 and v2.3.1 and if the upcoming v2.3.2 will fix it.

**Comment by SimonCropp** [comment]
what weaver(s) re you using?

**Comment by renzska** [comment]
I'm getting it with just the PropertyChanged weaver.

**Comment by Dids** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged/>
    <AsyncErrorHandler/>
    <RealmWeaver/>
</Weavers>
```

I guess it could be `PropertyChanged` that's causing it. I'll see if removing it makes any difference.

**Comment by SimonCropp** [comment]
TBH i am not sure what the issue is. but i reverted a pdb change in 2.3.2 that may fix it. can u try it and let me know

**Comment by Dids** [comment]
Can confirm that 2.3.2 does indeed fix it!

**Comment by SimonCropp** [comment]
ok sorry about the hassle. on my next release i will add Xamarin.Forms to my list of smoke tests.
