### ISSUE TITLE
Fody messes up referenced assembly versions

### ISSUE THREAD

**Issue by cbruegg** [Fody/Fody#438]
While migrating a Xamarin project with Realm DB to .NET Standard 2.0, @mb236 and I stumbled upon an issue that causes Fody to mess up the referenced assembly versions in the weaved assembly:

`The type 'IReflectableType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reflection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

A sample project reproducing the error can be found [here](https://github.com/HiP-App/HiP-Forms/tree/iss-hipm-821).
1. Checkout the branch `iss-hipm-821`
2. Add the file [Constants.cs](https://gist.github.com/cbruegg/2524f57781b6ac23bcb337ca8d3fdc10) in `Hip-Mobile-Internal` (top-level folder)
3. Build the project `HipMobileUI`

I believe we're using Fody 2.* in that branch, however I've also reproduced this after updating the package to the latest version.

Originally we thought this was an issue with the C# compiler, but @joperezr thinks it's an issue with Fody. See also [our filed issue in their bugtracker](https://github.com/dotnet/standard/issues/591) for more details.

**Comment by SimonCropp** [comment]
what weavers are you using? can u provide a small sln that reproduces the problem?

**Comment by cbruegg** [comment]
This uses the RealmWeaver. The line where the error occurs doesn't have anything to do with the error itself, so producing a small sln might be hard. Any chance you could just use the provided one? If not, I'll spend some time on this during the holidays.

**Comment by SimonCropp** [comment]
Out of curiosity how do u know it is fody and not the realm weaver?

**Comment by cbruegg** [comment]
To be honest, I don't know. Maybe it's a combination of both, maybe it's just the RealmWeaver or it's just Fody. Unfortunately I don't know enough about the Fody internals.

**Comment by SimonCropp** [comment]
I suggest you initially raise an issue with the realmweaver
