### ISSUE TITLE
Allow weavers to prevent writting assemblies.

### ISSUE THREAD

**Issue by Keboo** [Fody/Fody#454]
Currently Fody [always writes](https://github.com/Fody/Fody/blob/master/FodyIsolated/InnerWeaver.cs#L103) back the module. 
For one of my weavers, I would like it if it were possible for the weaver to communicate back to Fody that writing the assembly should not be done (or is not needed). Because my weaver does not need the assembly written, I believe this would allow it to be used, without breaking the edit-and-continue in Visual Studio (am I wrong is this assumption?)

I am happy to submit a PR for this, but wanted to discuss how to best implement it (since there may be more than one weaver being applied). As present it does not appear that there is any precident for weavers communicating back information. Thoughts? Feedback? Suggestions?

**Comment by SimonCropp** [comment]
Sounds reasonable. Although before we go into more details, i am curious what your weaver is doing that it sometimes doesn’t need to modify an assembly?

**Comment by Keboo** [comment]
Thanks for the reply. The weaver is generating some C# files based on the type hierarchy of the ModuleDefinition (as well as the other assemblies it references). Obviously these files are being generated post-compile so I am not expecting them to be included in the project. 
I considered just writing my own MSBuild task, but I would end up re-creating much of what you have already done with Fody. I have also considered using Roslyn but given that I want to process the type hierarchy of the current project as well as the assemblies it references it did not seem like the right tool for the job.

**Comment by SimonCropp** [comment]
not really the target use case, but i think your "didnt modify assembly" can still be accommodated. 

if you want to attempt a PR 

 * have a look at where execute is called https://github.com/Fody/Fody/blob/master/FodyHelpers/BaseModuleWeaver.cs#L115
 * add a mechanism to BaseModuleWeaver to communicate "no changed" back up
 * aggregate that over all weavers
 * propagate that info back up the stack

**Comment by Keboo** [comment]
Excellent. I realize that this is not really what Fody was designed for (it just works out that it is the closest tool I know of). 
I will take a stab at a PR and let you know if I run into any issues.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
