### ISSUE TITLE
Fody >= 2.3.4 cannot find weavers when using Paket

### ISSUE THREAD

**Issue by csmager** [Fody/Fody#456]
I updated from Fody 2.1.X to 2.3.15 and I get this in my log:
```
Fody: SolutionDirectory path is 'C:\..\'
Fody: Finding weavers
Fody: FindAddinDirectories:
Fody:   No PackageDefinitions
Fody:   Scanning SolutionDir/Packages convention: C:\..\Packages'.
Fody:     Fody weaver file added 'C:\..\Packages\NullGuard.Fody\lib\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\Packages\NullGuard.Fody\package\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\Packages\NullGuard.Fody\_rels\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\Packages\PropertyChanged.Fody\lib\PropertyChanged.Fody.dll'
Fody:     Fody weaver file added 'C:\..\Packages\PropertyChanged.Fody\package\PropertyChanged.Fody.dll'
Fody:     Fody weaver file added 'C:\..\Packages\PropertyChanged.Fody\_rels\PropertyChanged.Fody.dll'
Fody:   Skipped directory from Nuget Config since it could not be derived.
Fody:   Scanning the MsBuildThisFileDirectory parent: C:\..\packages\'.
Fody:     Fody weaver file added 'C:\..\packages\NullGuard.Fody\lib\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\packages\NullGuard.Fody\package\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\packages\NullGuard.Fody\_rels\NullGuard.Fody.dll'
Fody:     Fody weaver file added 'C:\..\packages\PropertyChanged.Fody\lib\PropertyChanged.Fody.dll'
Fody:     Fody weaver file added 'C:\..\packages\PropertyChanged.Fody\package\PropertyChanged.Fody.dll'
Fody:     Fody weaver file added 'C:\..\packages\PropertyChanged.Fody\_rels\PropertyChanged.Fody.dll'
Fody:   Scanning SolutionDir/Tools directory convention: 'C:\..\Tools'.
Fody:   Skipped NuGetPackageRoot since it is not defined.
Fody: No Weaver project file found.
```

The two dlls that should be found are at `C:\..\packages\PropertyChanged.Fody\PropertyChanged.Fody.dll` and `C:\..\packages\NullGuard.Fody\NullGuard.Fody.dll`.

I found a similar issue (#437) that was fixed in 2.3.3, so I've tried going back to 2.3.3 and it works correctly. I've tracked down that release that broke this as 2.3.4.

The [diff](https://github.com/Fody/Fody/compare/2.3.3...2.3.4) shows a number of changes relating to this area. 

What seems to be happening is that within `ScanDirectoryForPackages`, these directories are being caught within `newStyleDirectories` (as they end with `.Fody`) rather than `oldStyleDirectories` (as they don't contain `.Fody.` given the Paket omits the versions by default).

I would create a PR to add `yield return GetAssemblyFromNugetDir(packageDirectory, packageName)` inside the `newStyleDirectories` loop, but I'm not sure if this is the correct way to fix it (mainly because I'm not sure what a 'new style directory' is!)

**Comment by SimonCropp** [comment]
sorry about that. A PR would be appreciated. focus on a failing a unit test, then i can verify the correctness of you code to make that test pass.

also is it possible to mix and match nuget and paket in one sln? if so can u add a project that targets paket to this https://github.com/Fody/FodyAddinSamples? that way it will be caught in a smoke test for any future release

**Comment by csmager** [comment]
I've created the PR with the failing test & had a go at the fix.

I can add a paket-style project to the samples, but because of the mix I can't actually get it to fail. This is because we end up with two folders in `packages` - one from NuGet and one from Paket. 
```
BasicFodyAddin.Fody.1.04\
BasicFodyAddin.Fody\
```
As a result, the scanning finds the dll in the first one and the build is fine. As such, I'm not sure how much value adding this in would add - especially given having both package managers adds some complexity too.
