### ISSUE TITLE
.net 4.5 support

### ISSUE THREAD

**Issue by StuiterSlurf** [Fody/Fody#458]
I'm trying to update my Fody from 2.2.1 to Fody 2.3.15 and now I see that there is no support anymore for .net 4.5. 

Why is that?

**Comment by SimonCropp** [comment]
So fody has two diff requirements for .net version

1. What framework the target assembly can be using. Afaik there is no strict limitation from the fody core perspective on this. You should be able to in theory manipulate an assembly targeting .net 1. The only limitation from this perspective is what target runtime an individual weaver supports. 

2. What runtime is required the context of the msbuild. This is only a requirement on dev machines and build servers. The reason this gets increased occasionally is so downstream weavers can make assumptions on that runtime and its newer features. 

So when u say 4.5 support do you mean 1 or 2?

**Comment by SimonCropp** [comment]
@marcells fody doesnt support 4.5 since it is no longer supported by MS 

https://github.com/Fody/Fody#supported-runtimes
https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview

**Comment by SimonCropp** [comment]
@marcells note that you are also conflating "build runtime" with "execution runtime".  technically fody does support 4.5. and your weaver does not need to reference the same runtime that you target at execution time

**Comment by marcells** [comment]
Alright. Thanks. I try to upgrade to a newer .NET Framework. But maybe it's not possible, cause some of our customers may use quite old installations.

**Comment by marcells** [comment]
I've got it to work. 😉
