### ISSUE TITLE
Default SolutionDirectory - breaking change 2.3.17 to 2.3.18

### ISSUE THREAD

**Issue by csmager** [Fody/Fody#465]
In 2.3.17 and earlier, if I run a build of a specific project, I see this logged:
```
Fody: ProjectDirectory: 'C:\dev\solution\src\Project\'.
Fody: AssemblyPath: 'C:\dev\solution\src\Project\obj\Release\net452\Project.dll'
Fody: Found path to weavers file 'C:\dev\solution\src\Project\FodyWeavers.xml'.
Fody: SolutionDirectory path is 'C:\dev\solution\'
Fody: Finding weavers
```
Since 2.3.18, I see this logged:
```
Fody: ProjectDirectory: 'C:\dev\solution\src\Project\'.
Fody: AssemblyPath: 'C:\dev\solution\src\Project\obj\Release\net452\Project.dll'
Fody: Found path to weavers file 'C:\dev\solution\src\Project..\FodyWeavers.xml'.
Fody: Found path to weavers file 'C:\dev\solution\src\Project\FodyWeavers.xml'.
Fody: SolutionDirectory path is 'C:\dev\solution\src\Project\'
Fody: Finding weavers
Fody: FindAddinDirectories:
Fody:   No PackageDefinitions
Fody:   Skipped SolutionDir/Packages convention 'C:\dev\solution\src\Project\Packages' since it doesn't exist.
Fody:   Skipped directory from Nuget Config since it could not be derived.
Fody:   Scanning the MsBuildThisFileDirectory parent: C:\dev\solution\'.
Fody:   Skipped scanning 'C:\dev\solution\src\Project\Tools' since it doesn't exist.
Fody:   Skipped NuGetPackageRoot since it is not defined.
Fody: No Weaver project file found.
```
And this then fails the build.

It looks like [this](https://github.com/Fody/Fody/compare/2.3.17...2.3.18#diff-a300e654d96b2e003891d7098d57b1c9R16) was probably the change that caused it, but I'd assume it was made for a reason.

I can workaround by specifying `SolutionDir` in my build script, but I thought it was worth querying.

**Comment by SimonCropp** [comment]
Sorry. And good catch. 

Can u share a repro so i can add it to the integration tests?

**Comment by csmager** [comment]
The only way I could break this was to convert to paket. When using NuGet it seems that `PackageDirectories` gets populated and the relevant weavers are found in there.

Even then, `dotnet build` seems to populate `PackageDefinitions` too. There's obviously some magic here I don't understand!

I could only get this to fail by directly invoking msbuild directly:
```
msbuild BasicFodyAddinSample\BasicFodyAddinSample.csproj /target:Restore;Build
```
Which gives me this:
```
Fody: Fody (version 1.0.0.0) Executing
Fody: ProjectDirectory: 'C:\dev\FodyAddinSamples\BasicFodyAddinSample\'.
Fody: AssemblyPath: 'C:\dev\FodyAddinSamples\BasicFodyAddinSample\obj\Debug\net47\BasicFodyAddinSample.dll'
Fody: Found path to weavers file 'C:\dev\FodyAddinSamples\BasicFodyAddinSample\FodyWeavers.xml'.
MSBUILD : error : Fody: SolutionDir "C:\dev\FodyAddinSamples\BasicFodyAddinSample..\" does not exist. [C:\dev\FodyAddinSamples\BasicFodyAddinSample\BasicFodyAddinSample.csproj]
Fody:   Finished Fody 40ms.
```
Repo is here: https://github.com/csmager/FodyProjectBuildTest

**Comment by csmager** [comment]
FWIW, it seems the subtle difference between my calling msbuild.exe and what `dotnet build` does is
```
msbuild /restore /target:Build
```
vs
```
msbuild /target:Restore;Build
```
They seem to pull in slightly different targets. This isn't really relevant as the default `SolutionDir` is incorrect in both cases - it just doesn't break the build when `PackageDefinitions` is provided.

**Comment by SimonCropp** [comment]
can u try 2.3.19

**Comment by csmager** [comment]
Thanks. This fixes for the repro (as the solution directory is the parent of the project directory). It doesn't fix for the repo I initially spotted this on, because the structure I have is `SolutionDir\src\ProjectDir\`.

I'm happy to specify the solution directory in this case, I think what you've got is the best guess for most situations.

**Comment by SimonCropp** [comment]
Ok i will mark this as fixed. 

But could we perhaps do some tree walking to better support your scenario?
