### ISSUE TITLE
The "Fody.VerifyTask" task was not given a value for the required parameter "SolutionDir".	

### ISSUE THREAD

**Issue by tzachshabtay** [Fody/Fody#466]
I'm getting this with Visual Studio 2017 when I'm building my project from a clean directory (using Fody.PropertyChanged). After doing random builds/rebuilds a few times it goes away.
If I delete bin and obj folders and try to compile the error returns.

To reproduce: get my project from here- https://github.com/tzachshabtay/MonoAGS
Try building the solution with  Any CPU + Debug as your configurations.

**Comment by SimonCropp** [comment]
can u try 2.3.19

**Comment by tzachshabtay** [comment]
Ah, sorry, yes, it works fine with 2.3.19, thanks.
