### ISSUE TITLE
how to use project reference instead nuget package

### ISSUE THREAD

**Issue by zhaoqinghai** [Fody/Fody#471]
I want to refer to fody directly through a local project without having to publish it to NuGet. But when I compile, it throws 'Fody:an unhandled exception occurred'

**Comment by SimonCropp** [comment]
Can u upload a repro that shows what you are trying  to achieve

**Comment by zhaoqinghai** [comment]
i push project to https://github.com/zhaoqinghai/log,

**Comment by SimonCropp** [comment]
so you r trying to write a fody addin? if so have u seen this https://github.com/Fody/BasicFodyAddin ?

**Comment by zhaoqinghai** [comment]
thank you ,i will try
