### ISSUE TITLE
Getting warnings in Xamarin.Forms Project

### ISSUE THREAD

**Issue by Osmosis311** [Fody/Fody#484]
Hi,

I'm getting 46 warnings in my Xamarin.Forms project related to Fody.  When the project runs, it seems to work fine (using PropertyChanged), but I don't get what these warnings are.

`  Fody: Can't find 'System.Data, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
        Tried:
    /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/Microsoft.Win32.Primitives.dll`

(another warning mentions System.Linq, same message)

Am I doing something wrong perhaps?  Any guidance?

Thanks!

**Comment by jpiechowiak** [comment]
We've got the same issue in our company. 
This warning (error?) occuring for me only when build using MSBuild command line. We use MSBuild directly on Jenkins. 

Error started occuring when we switched to .Net Standard 2.0 recently. 
I've got this warning, but build completes successfuly. I use only one weaver - PropertyChanged.

This behaviour increases size of log file from something around 2MB to 50MB

**Comment by SimonCropp** [comment]
can u repro this without xamarin?

**Comment by jpiechowiak** [comment]
I think that issue is connected with .Net Standard 2.0. Earlier without .Net Standard I don't have any problems. Currently have workaroud to reduce log by changing verbose level in msbuild process. 

I am going to check this later.

**Comment by SimonCropp** [comment]
I have significantly dialed back the amount of logging on the current release. Still havnt found the root cause though

**Comment by Osmosis311** [comment]
Just cleaned and rebuilt my XF project.  Up to 131 Fody warnings.  I'm not using NETStandard.

**Comment by Osmosis311** [comment]
@SimonCropp I'm not sure how to attempt to reproduce without Xamarin.  I guess just a regular .NET Project in VS4Mac?

**Comment by SimonCropp** [comment]
not going to get around to this. if someone wants it fixed please submit a PR

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
