### ISSUE TITLE
Question: Does FodyCecil has to be netsstandard2.0?

### ISSUE THREAD

**Issue by GibSral** [Fody/Fody#487]
Hi, 
is there any reason that FodyCecil is netstandard2.0 as it only references netstandard1.3 Mono.Cecil dlls?

Thanks in advance
Lars

**Comment by SimonCropp** [comment]
because it is designed to be consumed by fody addins. which run in msbuild (net46) or dotnet build (netstandard 2.0)

**Comment by GibSral** [comment]
I do not fully understand this, because dotnet build as well as msbuild can for sure build netstandard1.3 assemblies.
Would it be possible to add a target for netstandard1.3 because as it is now I cannot use my aspects in projects with netstandard < 2.0?

Thanks 
Lars

**Comment by SimonCropp** [comment]
dotnet build can output  netstandard1.3  assemblies. but the donet build exe (that runs on your dev machine) is compile against and run in netcore2
