### ISSUE TITLE
Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files. 

### ISSUE THREAD

**Issue by elevenloveseleven** [Fody/Fody#488]
The Fody works well until 6 Feb 2018 my project. Now sometimes it works; sometime it shows the following result with no assembly embeded. 

FodyTargets:
"Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files." 

I'm using Fody version 2.0.6. 

Do you have any idea of what could cause this problem?

Thank you

**Comment by SimonCropp** [comment]
did u solve this?
