### ISSUE TITLE
Error using Fody with MSBuild after upgrading 2.2.1 > 2.3.0

### ISSUE THREAD

**Issue by Tide** [Fody/Fody#489]
I am using MSBuild to compile a solution at runtime.  Everything works fine until I upgrade Fody to 2.3.0 or newer.  Is there something I need to do different now or is this a bug?  I will do further investigation.  However,  I wanted to get a post up in case someone already has an answer.

`: ERROR C:\5lzg2nij.ocv\packages\Fody.2.3.0\build\net452\Fody.targets(54,5): 
The "Fody.WeavingTask" task could not be loaded from the assembly C:\5lzg2nij.ocv\
packages\Fody.2.3.0\build\net452\..\..\tasks\net46\Fody.dll. Could not load file or assembly 
'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> 
declaration is correct, that the assembly and all its dependencies are available, and that the task 
contains a public class that implements Microsoft.Build.Framework.ITask.
System.Windows.Data Error:`

**Comment by Tide** [comment]
I read on another project that you need to add a reference to the NuGet package for Microsoft.Build.Utilities.Core.  I tried downloading Fody and doing it myself but I can not get Fody to build.

**Comment by Tide** [comment]
I set up a Test solution and repository to illustrate the situation.  Run the FodyTest solution and blick the build button and you will see the error.  Then click the open runtime solution button and build that solution and you can see it build.  If you change Fody to 2.2.1 or older the build button will go back to working.

[https://github.com/Tide/FodyTest](https://github.com/Tide/FodyTest)

**Comment by SimonCropp** [comment]
that repro doesnt use fody

**Comment by Tide** [comment]
Not sure what you mean.
https://github.com/Tide/FodyTest/blob/master/FodyTest/FodyTest/bin/Debug/RuntimeApp/packages/Fody.2.4.4/Fody.2.4.4.nupkg

**Comment by SimonCropp** [comment]
but there is no nuget reference to fody

**Comment by SimonCropp** [comment]
sigh i have just realized u have two solutions in your repro

**Comment by Tide** [comment]
No problem thanks for looking into it.
