### ISSUE TITLE
WPF: View won't update by manually editing the view model

### ISSUE THREAD

**Issue by McTopaz** [Fody/Fody#494]
In my WPF application I have a view with a TextBox where I can type any text which will appear in a Label automatically. Both the TextBox and the Label have the _Text_ and _Content_ properties bound to the same property in my ViewModel. This binding works as expected. The ViewModel has the _AddINotifyPropertyChangedInterface_ set to it in the class definition.

I added a button to the view. In the click event I assigned the property in Viewmodel to a random value. But the TextBox or the Label won't update.

So I reworked the ViewModel, and added the INotifyPropertyChanged interface and the PropertyChanged event to see if that worked. And yepp, that worked! I can change the text in the Label by either the TextBox or by clicking the button.

Is this a bug?

Here is the code to verify. (It should be just "copy-paste-run")

**MainWindow.xaml**
```
<Window x:Class="WpfApplication1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApplication1"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    
    <Window.DataContext>
        <local:VM />
    </Window.DataContext>

    <StackPanel Orientation="Horizontal">
        <Label Content="Specify a text" />
        <TextBox Text="{Binding Path=Text, UpdateSourceTrigger=PropertyChanged}" Width="100" Background="CornflowerBlue" />
        <Label Content="The text was" />
        <Label Content="{Binding Path=Text, UpdateSourceTrigger=PropertyChanged}" Width="100" Background="Lime" />
        <Button Content="Some text" Width="60" Click="Button_Click" />
    </StackPanel>
</Window>
```

**MainWindow.xaml.cs**
```
using System.ComponentModel;
using System.Windows;

namespace WpfApplication1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var vm = this.DataContext as VM;
            vm.Text = "some text from the button";
        }
    }
}
```

**Fody.Weavers.xml**
```
<?xml version="1.0" encoding="utf-8" ?>
<Weaver>
</Weaver>
```

**ViewModel with INotifyPropertyChanged**
```
    public class VM : System.ComponentModel.INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        string text;

        public VM()
        {
            text = "hello";
        }

        public string Text
        {
            get { return text; }
            set
            {
                text = value;
                NotifyPropertyChanged(nameof(Text));
            }
        }

        private void NotifyPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
```

**ViewModel with AddINotifyPropertyChangedInterfaceAttribute**
```
    [PropertyChanged.AddINotifyPropertyChangedInterfaceAttribute]
    public class VM
    {
        public string Text { get; set; }

        public VM()
        {
            Text = "hello";
        }
    }
```

Just switch between the ViewModels to test the two different scenarios.
Enter any text in the blue colored area which should end up in the green colored area.
Press the button and some text should appear, depending on the ViewModel, in both the blue and green areas.

I use Visual Studio 2015 and compiling to NET Framework 4.5.2.

/Best regards,
Steffe

**Comment by SimonCropp** [comment]
U r missing a node in fody weavers xml https://github.com/Fody/PropertyChanged/#add-to-fodyweaversxml

**Comment by McTopaz** [comment]
Thank you!
