### ISSUE TITLE
Lazy-load types in TypeCache

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#496]
At the moment I see that the TypeCache adds all public types by default. Why not lazy-load the types on-demand? I know that this is a discussion about taking the pain upfront vs at compile time, but instead of caching all public types from say mscorlib, any weaver would property only need up to 10 types, so even with lazy-loading, the whole process would be faster without pre-caching.

What if we make the following changes:

1. Lazy-load by default
2. Add a `Preload` method for developers that don't want to take the lazy-load "hit"

**Comment by tom-englert** [comment]
Isn't the most time spent loading the assembly? 
I would guess you can neglect the time indexing the types compared to the time Cecil needs to load the assembly.
