### ISSUE TITLE
Error while trying to publish project containing Fody.PropertyChanged to AWS Lambda

### ISSUE THREAD

**Issue by TonyHenrique** [Fody/Fody#498]
I have a Desktop app with Fody and it builds.
Now I am building a ASP Net Core 2.0 WebAPI to publish to AWS, but this error appears:

> Executing publish command
> ... invoking 'dotnet publish', working folder 'C:\temp\AWSServerless1\AWSServerless1\bin\Release\netcoreapp2.0\publish'
> ... publish: Microsoft(R) Build Engine versÆo 15.6.82.30579 para .NET Core 
> ... publish: Copyright (C) Microsoft Corporation. Todos os direitos reservados.
> ... publish:   Restore completed in 117,91 ms for C:\temp\AWSServerless1\AWSServerless1\AWSServerless1.csproj.
> ... publish:   Restore completed in 125,89 ms for C:\temp\AWSServerless1\AWSServerless1\AWSServerless1.csproj.
> ... publish:   Restore completed in 64,4 ms for C:\temp\AWSServerless1\AWSServerless1\AWSServerless1.csproj.
> ... publish:   utils -> C:\Users\tonyv\source\repos\Sistema\utils\bin\Release\utils.dll
> ... publish: C:\temp\AWSServerless1\packages\Fody.2.4.6\build\Fody.targets(71,5): error MSB4062: A tarefa "Fody.WeavingTask" não foi carregada do assembly C:\Users\tonyv\source\repos\Sistema\SistemaWPF\packages\Fody.2.0.7\build\netstandard1.4\..\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. O sistema não pode encontrar o arquivo especificado. Confirme se a declaração <UsingTask> está correta, se o assembly e todas as suas dependências estão disponíveis e se a tarefa contém uma classe pública que implementa Microsoft.Build.Framework.ITask. [C:\Users\tonyv\source\repos\Sistema\Entidades\Entidades.csproj]
> 

![image](https://user-images.githubusercontent.com/6307623/37491008-269e9360-287b-11e8-8525-53c2eff0b67d.png)

**Comment by SimonCropp** [comment]
can u upload a solution that reproduces the problem

**Comment by TonyHenrique** [comment]
While I was preparing a new simple solution to reproduce the problem, I figured out:

My Entities Class Library was in .Net 4.6.2, and being referenced on the AWS ASP Net Core 2 Web API Project.

**I converted the Entity Class Library to .Net Standard 2 , added Fody Property Changed, and it Works well with Fody PropertyChanged.**

I converted this way, I replaced the .csproj contentes with this, and then added the NuGet packages:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
 
</Project>

```

**Comment by SimonCropp** [comment]
Cool. So we should close this?
