### ISSUE TITLE
Method 'WriteModule' in type 'Mono.Cecil.Pdb.NativePdbWriter' from assembly 'Mono.Cecil.Pdb, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' does not have an implementation.

### ISSUE THREAD

**Issue by victor-kachesov** [Fody/Fody#499]
After upgrade Visual Studio 2017 to new version 15.6.2 I started to get this error. 

```
3>    Fody: Fody (version 2.0.0.0) Executing
3>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.Compression.Cab.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.Compression.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.WindowsInstaller.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.WindowsInstaller.Package.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\StdCommon\bin\Debug\netstandard1.4\StdCommon.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\WPFModulPOS.Common\bin\Debug\WPFModulPOS.Common.dll'
3>MSBUILD : error : Fody: An unhandled exception occurred:
3>MSBUILD : error : Exception:
3>MSBUILD : error : Method 'WriteModule' in type 'Mono.Cecil.Pdb.NativePdbWriter' from assembly 'Mono.Cecil.Pdb, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' does not have an implementation.
3>MSBUILD : error : StackTrace:
3>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
3>MSBUILD : error :    at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
3>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
3>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
3>MSBUILD : error : Source:
3>MSBUILD : error : Mono.Cecil.Pdb
3>MSBUILD : error : TargetSite:
3>MSBUILD : error : Mono.Cecil.Cil.ISymbolWriter GetSymbolWriter(Mono.Cecil.ModuleDefinition, System.String)
3>MSBUILD : error : 
3>    Fody:   Finished Fody 41ms.
```

**Comment by victor-kachesov** [comment]
After upgrade Visual Studio 2017 to new version 15.6.2 I started to get this error.

`3>    Fody: Fody (version 2.0.0.0) Executing
3>      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.Compression.Cab.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.Compression.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.WindowsInstaller.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\Libs\Microsoft.Deployment.WindowsInstaller.Package.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\StdCommon\bin\Debug\netstandard1.4\StdCommon.dll'
3>      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\ModulPos\WPFModulPOS.Common\bin\Debug\WPFModulPOS.Common.dll'
3>MSBUILD : error : Fody: An unhandled exception occurred:
3>MSBUILD : error : Exception:
3>MSBUILD : error : Method 'WriteModule' in type 'Mono.Cecil.Pdb.NativePdbWriter' from assembly 'Mono.Cecil.Pdb, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' does not have an implementation.
3>MSBUILD : error : StackTrace:
3>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
3>MSBUILD : error :    at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
3>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
3>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
3>MSBUILD : error : Source:
3>MSBUILD : error : Mono.Cecil.Pdb
3>MSBUILD : error : TargetSite:
3>MSBUILD : error : Mono.Cecil.Cil.ISymbolWriter GetSymbolWriter(Mono.Cecil.ModuleDefinition, System.String)
3>MSBUILD : error : 
3>    Fody:   Finished Fody 41ms.`

**Comment by SimonCropp** [comment]
Upload a solution that reproduces the problem

**Comment by victor-kachesov** [comment]
@SimonCropp Send solution file to your email.

**Comment by victor-kachesov** [comment]
Hello @SimonCropp 
Did you receive my solution file?
Are there any comments?

**Comment by SimonCropp** [comment]
i get no such error when building your sln. so a little difficult for me to proceed

**Comment by SimonCropp** [comment]
does it happen for you on another machine?

**Comment by victor-kachesov** [comment]
No, it happens only on my work machine. Is there any workaround?

**Comment by SimonCropp** [comment]
my guess would be a corrupted nuget package. delete you sln packages dir and your package cache and then do a package restore

**Comment by SimonCropp** [comment]
can u try a diff version of costura and fody

**Comment by victor-kachesov** [comment]
I tried to update Fody package from 2.0.0 to 2.4.6. After that error message has changed to
```
    Fody: Fody (version 2.4.6.0) Executing
      Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
      Fody/Costura:   	Embedding 'C:\Work\ModulKassa\1\FodyTest\WPFModulPOS.Common\bin\Debug\WPFModulPOS.Common.dll'
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.MethodDefinition> Mono.Cecil.Cil.AsyncMethodBodyDebugInformation.get_ResumeMethods()'.
MSBUILD : error : Type:
MSBUILD : error : System.MissingMethodException
MSBUILD : error : StackTrace:
MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
MSBUILD : error :    at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
MSBUILD : error :    at Mono.Cecil.MethodDefinition.get_Body()
MSBUILD : error :    at ModuleWeaver.CopyMethod(MethodDefinition templateMethod, Boolean makePrivate) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 143
MSBUILD : error :    at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 61
MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 35
MSBUILD : error :    at lambda_method(Closure , Object )
MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 200
MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 102
MSBUILD : error : Source:
MSBUILD : error : Mono.Cecil.Pdb
MSBUILD : error : TargetSite:
MSBUILD : error : Mono.Cecil.Cil.MethodDebugInformation Read(Mono.Cecil.MethodDefinition)
MSBUILD : error : 
    Fody:   Finished Fody 30ms.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

**Comment by NPSF3000** [comment]
I am getting the following when deploying to AWS beanstalk (not in usual build):

```
 Fody: build error: '' at (0,0): Fody: An unhandled exception occurred:
Exception:
Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.MethodDefinition> Mono.Cecil.Cil.AsyncMethodBodyDebugInformation.get_ResumeMethods()'.
Type:
System.MissingMethodException
StackTrace:
   at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at CecilExtensions.CheckForInvalidLogToUsages(MethodDefinition methodDefinition)
   at LogForwardingProcessor.ProcessMethod()
   at ModuleWeaver.ProcessType(TypeDefinition type)
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
Mono.Cecil.Pdb
TargetSite:
Mono.Cecil.Cil.MethodDebugInformation Read(Mono.Cecil.MethodDefinition)
```

Seems similar to @victor-kachesov's issue.

**Comment by Zagrophyte** [comment]
Seeing this here as well. Costura.Fody (1.6.2) with Fody (2.4.6):

`1> error : Fody: An unhandled exception occurred:
1>Exception:
1>Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.MethodDefinition> Mono.Cecil.Cil.AsyncMethodBodyDebugInformation.get_ResumeMethods()'.
1>Type:
1>System.MissingMethodException
1>StackTrace:
1>   at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
1>   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
1>   at Mono.Cecil.MethodDefinition.get_Body()
1>   at ModuleWeaver.CopyMethod(MethodDefinition templateMethod, Boolean makePrivate) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 143
1>   at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 61
1>   at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 35
1>   at lambda_method(Closure , Object )
1>   at InnerWeaver.ExecuteWeavers()
1>   at InnerWeaver.Execute()
1>Source:
1>Mono.Cecil.Pdb
1>TargetSite:
1>Mono.Cecil.Cil.MethodDebugInformation Read(Mono.Cecil.MethodDefinition)
1>
1>	  Fody:   Finished Fody 81ms.`

**Comment by Zagrophyte** [comment]
@SimonCropp Attached is a repro SLN, and information on my environment.

This is impacting every solution we try to build using VS2017 now.
**The same repro SLN below builds fine in VS2015 14.0.25431.01 Update 3, but we are no longer using VS2015 as primary IDE.**

[FodyVS2017Issue499Repro.zip](https://github.com/Fody/Fody/files/1873626/FodyVS2017Issue499Repro.zip)

Fody **2.4.6**
Costura **1.6.2**
Targeting .NET **4.5.2**
Targeting F# **4.4.3.0**
Visual Studio **15.6.4**
Windows **10** Version **1709** (OS Build 16299.309)

![image](https://user-images.githubusercontent.com/6778687/38278827-a8f771ac-376b-11e8-9779-8328222e6da7.png)
```
------ Rebuild All started: Project: FodyVS2017Issue499Repro, Configuration: Debug Any CPU ------
	  Fody: Fody (version 2.4.6.0) Executing
	    Fody/Costura:   	No reference to 'Costura.dll' found. References not modified.
	    Fody/Costura:   	Embedding 'C:\Work\Source\Repos\FodyVS2017Issue499Repro\FodyVS2017Issue499Repro\packages\Costura.Fody\lib\portable-net+sl+win+wpa+wp\Costura.dll'
	    Fody/Costura:   	Embedding 'C:\Work\Source\Repos\FodyVS2017Issue499Repro\FodyVS2017Issue499Repro\packages\Costura.Fody\lib\portable-net+sl+win+wpa+wp\Costura.pdb'
	    Fody/Costura:   	Embedding 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.3.0\FSharp.Core.dll'
	    Fody/Costura:   	Embedding 'C:\Work\Source\Repos\FodyVS2017Issue499Repro\FodyVS2017Issue499Repro\packages\Newtonsoft.Json\lib\net45\Newtonsoft.Json.dll'
	    Fody/Costura:   	Embedding 'C:\Work\Source\Repos\FodyVS2017Issue499Repro\FodyVS2017Issue499Repro\packages\System.ValueTuple.4.3.1\lib\netstandard1.0\System.ValueTuple.dll'
 error : Fody: An unhandled exception occurred:
Exception:
Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.MethodDefinition> Mono.Cecil.Cil.AsyncMethodBodyDebugInformation.get_ResumeMethods()'.
Type:
System.MissingMethodException
StackTrace:
   at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at ModuleWeaver.CopyMethod(MethodDefinition templateMethod, Boolean makePrivate) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 143
   at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 61
   at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 35
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
Mono.Cecil.Pdb
TargetSite:
Mono.Cecil.Cil.MethodDebugInformation Read(Mono.Cecil.MethodDefinition)

	  Fody:   Finished Fody 925ms.
Done building project "FodyVS2017Issue499Repro.fsproj" -- FAILED.

Build FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========```

**Comment by SimonCropp** [comment]
@Zagrophyte  seem to be fixed in version 2 of costura. can u verify

**Comment by Zagrophyte** [comment]
@SimonCropp Indeed it does! Updating to Fody **3.0.0** with Costura **2.0.0** successfully builds in VS2017. Thank you.
