### ISSUE TITLE
Specify weaver path directly

### ISSUE THREAD

**Issue by ilengyel** [Fody/Fody#5]
[Enhancement] Would like to specify a weaver path directly in the config file e.g.

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PersistibleIEntity WeaverPath="..\PersistibleIEntity\bin\Debug\PersistibleIEntity.dll" />
</Weavers>
```

https://github.com/ilengyel/Catfood/blob/master/IssueAttachments/SpecifyWeaverPath.diff

Further enhancement: support MsBuild properties eg, specify $(Configuration) instead of hardcoding Debug in the path

**Comment by omesh** [comment]
This functionality has been removed in the latest version of fody, Is there any alternative?

**Comment by ilengyel** [comment]
@omesh in the end even I moved to the nuget distribution model. For our specific weavers we have an internal nuget server, but even without the nuget server you could set the output directory of a weaver DLL to be under the search path as its convention based.. e.g.
`<nuget_package_dir>\<weaver_name>.Fody\`
