### ISSUE TITLE
Specifying path to FodyWeavers.xml

### ISSUE THREAD

**Issue by SlowLogicBoy** [Fody/Fody#501]
It would be nice If there would be a way to specify path to `FodyWeavers.xml`.
As an example:
```xml
<PropertyGroup>
    <FodyWeaversPath>$(MSBuildThisFileDirectory)FodyWeavers.xml</FodyWeaversPath>
</PropertyGroup>
```
This way I could add `MyProject.targets` to my build directory with:
```xml
<Project>
    <PropertyGroup>
        <FodyWeaversPath>$(MSBuildThisFileDirectory)FodyWeavers.xml</FodyWeaversPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Fody" Version="2.4.6"/>
        <PackageReference Include="AutoDI.Fody" Version="3.2.0-ci70"/>
        <PackageReference Include="PropertyChanged.Fody" Version="2.2.9"/>
        <PackageReference Include="NullGuard.Fody" Version="1.7.1"/>
    </ItemGroup>
</Project>
```
And import them to all of my projects using:
`<Import Project="../../build/MyProject.targets">`

Reason behind this is:
When building `dotnet build MySolution.sln` it searches current directory or in project directories.
When I build `dotnet build MyProject.csproj` it searches current directory and it's parent.
My directory structure:
```
├── build
│   ├── MyProject.targets
├── FodyWeavers.xml
├── MySolution.sln
├── src
│   ├── MyProject
│   │   ├── MyProject.csproj
│   ├── MyProject2
│   │   ├── MyProject2.csproj
└── Readme.md
```
If I want to build only one of my projects I have to copy `FodyWeavers.xml` also to `src` directory, and it becomes painful to have 2 or more of the same file and update them both.

**Comment by SimonCropp** [comment]
Sounds good. Submit a pr and i will test and deploy

**Comment by ltrzesniewski** [comment]
@isaacmcn no, nothing new, but PR #631 changes some relevant stuff related to config files, so feel free to add your input there.

**Comment by SimonCropp** [comment]
@isaacmcn happy to consider a PR that implements this

**Comment by tom-englert** [comment]
There are many options today:
https://github.com/Fody/Home/blob/master/pages%2Fconfiguration.md
