### ISSUE TITLE
Race condition in FodyPackaging

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/Fody#505]
Suppose you have an addin named `SomeAddin.Fody` which uses a library named `SomeAddin` (the usual Fody addin setup). There is no project dependency between `SomeAddin` and `SomeAddin.Fody`.

You add a reference to `FodyPackaging` to `SomeAddin`, and it will build a NuGet package which will include the output of `SomeAddin` and `SomeAddin.Fody`.

The issue is that if MSBuild builds these two projects *in parallel* to each other (due to a lack of dependency), there will be a race condition if the `SomeAddin` project finishes building before `SomeAddin.Fody` is done. The build process will try to package a file which has not been built yet, and it will produce a package with missing files.

This can be solved by adding a build dependency `SomeAddin` -> `SomeAddin.Fody`, but this is not documented anywhere AFAICT.

I can see there's already a workaround to something that looks like it's related to this, but it doesn't seem to solve this particular issue for me:

```XML
  <ItemGroup>
    <!-- this project targets netstandard2.0 (unnecessarily) and has the below ref to work around this bug https://github.com/Microsoft/msbuild/issues/2661 -->
    <ProjectReference Include="..\$(PackageId)\$(PackageId).csproj" PrivateAssets="All" Condition="$(TargetFramework)=='fake'" />
  </ItemGroup>
```

If I disable parallel builds, run a cleanup and *then* a rebuild, I end up with no weaver in the package, because `SomeAddin` builds *before* `SomeAddin.Fody`.

This does seem to do the trick for me though:

```XML
  <ItemGroup>
    <ProjectReference Include="..\$(PackageId)\$(PackageId).csproj" IncludeAssets="None">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
```

With parallel builds disabled, `SomeAddin.Fody` now builds before `SomeAddin`.

But I'm not quite sure what exactly you were trying to solve with that conditional reference, so I don't know if that's the right solution.

**Comment by SimonCropp** [comment]
ReferenceOutputAssembly is the correct solution. but it will only work for VS. it is still broken in `dotnet.exe` and `msbuild.exe` https://github.com/dotnet/sdk/issues/939 so i cant fix properly until 2.1.3xx.

until then u can package using VS or work around your race condition by forcing the parallele build to 1.

**Comment by ltrzesniewski** [comment]
Ok I see... I'm using VS, that's why it worked for me.

I'll keep the build dependency in the sln file, it doesn't hurt and works around the issue just fine (disabling parallel builds does not).

**Comment by SimonCropp** [comment]
closing this as it is not really a bug with fody
