### ISSUE TITLE
Overrideable name for FodyWeavers.xml

### ISSUE THREAD

**Issue by aakash1906** [Fody/Fody#506]
For multi framework targeting projects like, netstandard2.0;net471
we would require different weavers for different framework configuration.
Eg. Costura for 471 ; NullGuard for netstandard2.0 (as costura doesn't work here).

If the FodyWeavers.xml name is overrideable based on framework config, this would be easier.

(Didn't have time to submit any code right now.)

BUT temporary workaround I did is something similar to this (by defining 2 xml files):

<Target Name="SetFodyForNet" BeforeTargets="FodyTarget" Condition="'$(TargetFramework)'!='netstandard2.0'">
    <Exec Command="start xcopy $(ProjectDir)FodyWeaversNet.xml $(ProjectWeaverXml) /I /Y /R" />
  </Target> 
  <Target Name="SetFodyForNetStandard" BeforeTargets="FodyTarget" Condition="'$(TargetFramework)'=='netstandard2.0'">
	<Exec Command="start xcopy $(ProjectDir)FodyWeaversNetStandard20.xml $(ProjectWeaverXml) /I /Y /R" />
  </Target>

NOTE: I did try overriding the value of $(ProjectWeaverXml) in the target above, even directly overriding at fody.targets, but somehow the code within Fody seems not to accept the overridden file name, but rather the fixed name of "FodyWeavers.xml"

**Comment by aakash1906** [comment]
Additionally on checking the source, I could notice: Fody/ConfigFileFinder.cs has 

 var solutionConfigFilePath = Path.Combine(solutionDirectoryPath, "FodyWeavers.xml"); (Line #11)
 var projectConfigFilePath = Path.Combine(projectDirectory, "FodyWeavers.xml");(Line #18)

If the hardcoding of FodyWeavers.xml is removed and made configurable to read from values propogated to WeavingTasks as inputs from MSBuild Targets, that would be great enough to specify different weaver file for multi targetframework projects easily

**Comment by SimonCropp** [comment]
if u were not using costura, would u still need this feature?

**Comment by aakash1906** [comment]
Well, We would need Costura for not .net Standard case, and not need it for .net Standard.
However, it is a single C# new sdk style VS2017 multi-framework targeting project.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
