### ISSUE TITLE
Bug in Versions above 2.1.3 for multiple framework targeting support

### ISSUE THREAD

**Issue by aakash1906** [Fody/Fody#507]
Versions 2.4.1 and 2.4.6 with Costura.Fody 1.6.2 support individually target frameworks net452, net461, net471 too (the 3 i tried).

However, on a multiple framework targeting project- where multiple <TargetFrameworks>net452;net461;net471</TargetFrameworks> 
either 2 or 3  in any combination (basically more than 1)- causes Mono.Cecil Method missing exception.

**Comment by ltrzesniewski** [comment]
I encountered the same issue when working on Fody/FodyAddinSamples#33 and I managed to narrow down the conditions under which this happens.

To reproduce this, you have to **build from Visual Studio with parallel builds enabled**, and have projects with multi-targeting.
 - MSBuild on the command line works just fine, even with `/m`
 - ReSharper build works just fine
 - Visual Studio build without parallel builds works fine

You can easily reproduce this on FodyAddinSamples - there are lots of multi-targeted projects with Fody enabled there.

Make sure you have parallel builds enabled: 
![image](https://user-images.githubusercontent.com/7913492/38079472-4672e4b0-333f-11e8-9344-b94732a1391d.png)

Here's an error example:
```
34>            MSBUILD : error : Fody: An unhandled exception occurred:
34>            MSBUILD : error : Exception:
34>            MSBUILD : error : Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.MethodDefinition> Mono.Cecil.Cil.AsyncMethodBodyDebugInformation.get_ResumeMethods()'.
34>            MSBUILD : error : Type:
34>            MSBUILD : error : System.MissingMethodException
34>            MSBUILD : error : StackTrace:
34>            MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
34>            MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
34>            MSBUILD : error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
34>            MSBUILD : error :    at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
34>            MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
34>            MSBUILD : error :    at Mono.Cecil.MethodDefinition.get_Body()
34>            MSBUILD : error :    at CecilExtensions.<>c.<MethodsWithBody>b__4_0(MethodDefinition x)
34>            MSBUILD : error :    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
34>            MSBUILD : error :    at ModuleWeaver.ProcessAssembly(List`1 types)
34>            MSBUILD : error :    at ModuleWeaver.Execute()
34>            MSBUILD : error :    at lambda_method(Closure , Object )
34>            MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
34>            MSBUILD : error :    at InnerWeaver.Execute()
34>            MSBUILD : error : Source:
34>            MSBUILD : error : Mono.Cecil.Pdb
34>            MSBUILD : error : TargetSite:
34>            MSBUILD : error : Mono.Cecil.Cil.MethodDebugInformation Read(Mono.Cecil.MethodDefinition)
34>            MSBUILD : error :
```


Here's a full diagnostic build log of FodyAddinSamples: [Output-Build.zip](https://github.com/Fody/Fody/files/1859614/Output-Build.zip)  
Here's an output build log on "normal" verbosity, which contains less data but more Fody exceptions: 
[Output-Build-Normal.zip](https://github.com/Fody/Fody/files/1859638/Output-Build-Normal.zip)


I tried to tweak a few things to make this error go away (including things such as always recycling the `IsolatedAssemblyLoadContext`), but I couldn't fix the issue - I'm not very familiar with MSBuild. @SimonCropp do you have an idea what could cause such a weird bahavior under these particular circumstances?

**Comment by aakash1906** [comment]
I've currently managed to bypass this issue as below.
For the multi target frameworks as below:
<TargetFrameworks>netstandard2.0;net452;net461;net471</TargetFrameworks>

The combination below works fine.
2 things to note here:
Fody version 2.1.3 somehow works without the error.
At the same time, Costura doesn't get on with .netStandard projects. So, bypassing that based on conditional target framework references.

<ItemGroup Condition="'$(TargetFramework)'!='netstandard2.0'">
	<PackageReference Include="Costura.Fody" Version="1.6.2" />
	
	<PackageReference Include="NullGuard.Fody" Version="1.5.1" />
    <PackageReference Include="Fody" Version="2.1.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
	<PackageReference Include="NullGuard.Fody" Version="1.7.1" />
    <PackageReference Include="Fody" Version="2.4.6" />
  </ItemGroup>
