### ISSUE TITLE
Weavers must now inherit from BaseModuleWeaver

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#509]
`BaseModuleWeaver` exists in the [FodyHelpers nuget](https://www.nuget.org/packages/FodyHelpers/)

**Comment by tom-englert** [comment]
@SimonCropp just being curious - how will you ensure cross-version compatibility, i.e. Fody is updated and is based on a newer version of FodyHelpers than a plugin, or vice versa?

**Comment by SimonCropp** [comment]
unfortunately this is a creaking change, hence the major version number. plugins will need to update to be compat

**Comment by tom-englert** [comment]
And what if in future a plugin references a different version of FodyHelpers than Fody itself?

**Comment by ltrzesniewski** [comment]
I suppose the FodyHelpers *assembly* version will have to stay at v3.0.0 throughout the next Fody versions, until a public API change to Cecil or BaseModuleWeaver needs to be made.

I'm still curious about how it was possible for two different Cecil versions to end up being referenced in the first place given that a weaver is executed in its own AppDomain (on the full framework msbuild version anyway).

**Comment by SimonCropp** [comment]
> Are there any other call like that I should be aware of? Or is there any documentation I can work through?

this should not be a problem

> I suppose the FodyHelpers assembly version will have to stay at v3.0.0 throughout the next Fody versions, until a public API change to Cecil or BaseModuleWeaver needs to be made.

fody hacks the appdomain to redirect to the current version of FodyHelpers 

> I'm still curious about how it was possible for two different Cecil versions to end up being referenced in the first place given that a weaver is executed in its own AppDomain (on the full framework msbuild version anyway).

most likely some other extension in Vs or MSBuild

**Comment by benzsuankularb** [comment]
@SimonCropp 
What does `GetAssembliesForScanning` do?

P.S. I feel Better without magic method (Execute)
