### ISSUE TITLE
Getting ArgumentNullException after upgrading to 3.0.2.0

### ISSUE THREAD

**Issue by Tlaster** [Fody/Fody#515]
Just creating a new universal windows project and add fody library with version 3.0.2.0, then build the project, you will get ArgumentNullException in output
[minimal solution](https://github.com/Tlaster/FodyCrashSample)

**Comment by SimonCropp** [comment]
can u try 3.0.3

**Comment by Tlaster** [comment]
solve after upgrading to 3.0.3
