### ISSUE TITLE
issues for class inheriting in different assemblies

### ISSUE THREAD

**Issue by vincedan** [Fody/Fody#518]
version: 2.5.3.0
make two assemblies with two projects:
1) ClassLibrary1.dll
namespace ClassLibrary1
{
    public class Person : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public string GivenNames { get; set; }
        public string FamilyName { get; set; }
        public string FullName => $"{GivenNames} {FamilyName}";
    }
}

2)Model.exe
namespace A4
{ 
    public class Manager: ClassLibrary1.Person
    {
        public string Territory { get; set; }
    }
}

compile error:
1>    Fody: Fody (version 3.0.3.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\Vince\source\repos\WindowsFormsApp1\packages\PropertyChanged.Fody.2.5.3\netclassicweaver\PropertyChanged.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 208
1>MSBUILD : error :    在 InnerWeaver.Execute() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 103
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : Could not inject EventInvoker method on type 'A4.Manager'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on A4.Manager.
1>MSBUILD : error : Type:
1>MSBUILD : error : Fody.WeavingException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    在 ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType) 位置 C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:行号 81
1>MSBUILD : error :    在 ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType) 位置 C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:行号 29
1>MSBUILD : error :    在 ModuleWeaver.FindMethodsForNodes() 位置 C:\projects\propertychanged\PropertyChanged.Fody\MethodFinder.cs:行号 199
1>MSBUILD : error :    在 ModuleWeaver.Execute() 位置 C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:行号 18
1>MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 204
1>MSBUILD : error : Source:
1>MSBUILD : error : PropertyChanged.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 117ms.

**Comment by SimonCropp** [comment]
please re-read the instructions you are presented with when opening a new issue

**Comment by SimonCropp** [comment]
also i think this should be in https://github.com/Fody/PropertyChanged
