### ISSUE TITLE
FodyCecil, Resolve() type Action got null when use dotnet build

### ISSUE THREAD

**Issue by benzsuankularb** [Fody/Fody#519]
Given this code in my add-in 
```ModuleDefinition.ImportReference(typeof(Action)).Resolve().GetConstructors()```

`msbuild` build success
`dotnet build` build failed
`dotnet msbuild` build failed
clean before run another build

[easily try build it using this repo](https://github.com/benzsuankularb/fody-cecil-issue)

**Comment by SimonCropp** [comment]
fixed here https://github.com/benzsuankularb/fody-cecil-issue/pull/1

**Comment by benzsuankularb** [comment]
Done. Thankyou very much 

What difference between ModuleDefinition.ImportReference & FindType why ModuleDefinition.ImportReference doesn't work in command line build?

Why I need to GetAssembliesForScanning?

`public override IEnumerable<string> GetAssembliesForScanning()
    {
        yield return "netstandard";
        yield return "mscorlib";
        yield return "System";
        yield return "System.Runtime";
        yield return "System.Core";
    }`

**Comment by benzsuankularb** [comment]
But I got this instead, I think it's not the same issue

```    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'System.Action`1' from assembly 'MySolution.MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'```

Any idea what could make this possible ?
I think **System.Action`1** should find in **System** not **MySolution.MyProject**

**Comment by SimonCropp** [comment]
have you imported the reference?

**Comment by benzsuankularb** [comment]
How can I, Doesn't System.Action was in mscorlib?

**Comment by SimonCropp** [comment]
import like this https://github.com/Fody/BasicFodyAddin/blob/master/BasicFodyAddin.Fody/ModuleWeaver.cs#L56

**Comment by benzsuankularb** [comment]
Done, Thanks a tons. Appreciated.
