### ISSUE TITLE
Trouble with method decorator and Mono.Cecil

### ISSUE THREAD

**Issue by Diamed** [Fody/Fody#521]
Hi. After updating Fody from 2.4.6 to 3.0.3 i have trouble with building project with method decorator.
I tried original method decorator and forked method decorator PP. But these products didn't update.
With method decorator PP i have next trouble:

> Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.1.6, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.

But MonoCecil didn't update too and token '50-CE-BF-1C-CE-B9-D0-5E' is active.
In original method decorator i have this trouble:

> Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.

And MonoCecil in this product has version 0.10.0.0, not 0.9.6.0.
If i downgrade Fody to version 2.5.0 then project compiles fine. Also i tried to downgrade Fody to version 3.0.0 and this problem exists too.

**Comment by SimonCropp** [comment]
this should be raised in the MethodDecorator project

**Comment by Diamed** [comment]
@SimonCropp but this happened after update in fody project. Method decorator didn't updated at that moment
