### ISSUE TITLE
Unable to use Fody/Costura with strong named assembly

### ISSUE THREAD

**Issue by ryknuth** [Fody/Fody#522]
I get this error when attempting to use Fody/Costura on my dll:

  MSBUILD : error : Fody: An unhandled exception occurred:
  MSBUILD : error : Exception:
  MSBUILD : error : Unable to obtain public key for StrongNameKeyPair.
  MSBUILD : error : StackTrace:
  MSBUILD : error :    at System.Reflection.StrongNameKeyPair.ComputePublicKey()
  MSBUILD : error :    at System.Reflection.StrongNameKeyPair.get_PublicKey()
  MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
  MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
  MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
  MSBUILD : error :    at InnerWeaver.WriteModule() in c:\Code\Fody\FodyIsolated\ModuleWriter.cs:line 18
  MSBUILD : error :    at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 85
  MSBUILD : error : Source:
  MSBUILD : error : mscorlib
  MSBUILD : error : TargetSite:
  MSBUILD : error : Byte[] ComputePublicKey()
  MSBUILD : error :

I've looked around and the first thing I saw was that Fody cannot be used on password protected keys.  My /keyfile looks like this:
/KEYFILE:<path obfuscated>\ship.snk

I believe password protected keys are pfx files so I don't think that's the problem.

Also, our dll is delay signed.  This means that we sign with a developer key as a placeholder for developer builds.  Then the official builds get signed with the official key that I don't have access to.  I can't see why this would prevent Fody/Costura from working so I don't think this is the problem.

I've tried to get a minimal repro but I can't figure out what the problem is, sorry.  I'm assuming that our amazingly complicated build system is doing something that Fody doesn't account for.

**Comment by SimonCropp** [comment]
in your repro did u use delay signing?

**Comment by ryknuth** [comment]
[FodyTest.zip](https://github.com/Fody/Fody/files/1949383/FodyTest.zip)

I figured it out.  The snk file we use only has the public key, it does not have the private key.

I saw the code here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/d9ef264e-1a74-4f48-b93f-3e2c7902f660/determine-contents-of-a-strong-name-key-file-snk?forum=netfxbcl

and that helped me verify it.  I have attached a minimal project.  Still seems like this should be supported right?

**Comment by SimonCropp** [comment]
without a private key how would fory re-sign the assembly?

**Comment by ryknuth** [comment]
That's a good question.  Without a private key, how would msbuild sign the assembly in the first place?  Isn't that the point of delay signing?

Here's a quote from:
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/delay-sign-assembly

> You can use delayed or partial signing at build time to reserve space in the portable executable (PE) file for the strong name signature, but defer the actual signing until some later stage (typically just before shipping the assembly).

All that happens is the public key gets put into the assembly just to save space.  It seems like Fody could do the same thing yea?

**Comment by ryknuth** [comment]
Any thoughts?

**Comment by SimonCropp** [comment]
sounds reasonable. can you submit a pull request that adds delay signing support

**Comment by ryknuth** [comment]
I looks like Mono.Cecil does not support public-key only delay signing.  I have an email chain going with the Roslyn folks to make sure I understand what they do in this case.  I have a fix for Mono.Cecil and for Fody to support this scenario.  I will submit the PR when possible.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue

**Comment by AndrewSav** [comment]
@SimonCropp has this been fixed?

**Comment by SimonCropp** [comment]
no, it is being tracked here https://github.com/Fody/Fody/pull/538
