### ISSUE TITLE
What has changed?

### ISSUE THREAD

**Issue by ygoe** [Fody/Fody#525]
I've still got the task to upgrade my Fody addin from 1.x to 2.x on my list. Now I see that Fody is at version 3.x. Unfortunately that's all I know. Should I use it or ignore it and stay at 2.x, or even 1.x? There's no change log and the releases at GitHub are totally undocumented.

Can somebody please explain to me

1. What has changed in all the versions of Fody, at least relevant parts
2. What I need to do to update my addin to be compatible, if anything more than updating the Fody package reference is necessary

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
