### ISSUE TITLE
Fody failed build 

### ISSUE THREAD

**Issue by WonderGnagno** [Fody/Fody#526]
Hi,
in attach a simple solution that reproduce the problem.

I've a nuget.config file that contains a path with an Environment variable.  On build phase Fody doesn't convert the environment variable correctly.

See the image attached.

Note.
To correctly test the solution use start.cmd

BR
Enrico

>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:C:\butta\FodyTest\ConsoleApp1\Lib\Costura.Fody.2.0.1\lib\net452\Costura.dll /reference:C:\butta\FodyTest\ConsoleApp1\Lib\Faker.1.2\lib\Faker.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ConsoleApp1.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Users\simonenr\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cs" obj\Debug\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs obj\Debug\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs obj\Debug\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn
1>FodyTarget:
1>    Fody: Fody (version 3.0.3.0) Executing
1>    Fody: ProjectDirectory: 'C:\butta\FodyTest\ConsoleApp1\ConsoleApp1\'.
1>    Fody: AssemblyPath: 'C:\butta\FodyTest\ConsoleApp1\ConsoleApp1\obj\Debug\ConsoleApp1.exe'
1>    Fody: Found path to weavers file 'C:\butta\FodyTest\ConsoleApp1\ConsoleApp1\FodyWeavers.xml'.
1>    Fody: SolutionDirectory path is 'c:\butta\FodyTest\ConsoleApp1\'
1>    Fody: Finding weavers
1>    Fody: FindAddinDirectories:
1>    Fody:   No PackageDefinitions
1>    Fody:   Skipped directory from Nuget Config 'c:\butta\FodyTest\ConsoleApp1\%MYLIB%' since it doesn't exist.
1>    Fody:   Scanning the MsBuildThisFileDirectory parent: C:\butta\FodyTest\ConsoleApp1\'.
1>    Fody:   Skipped scanning 'c:\butta\FodyTest\ConsoleApp1\Tools' since it doesn't exist.
1>    Fody:   Skipped NuGetPackageRoot since it is not defined.
1>    Fody: No Weaver project file found.
1>MSBUILD : error : Fody: Could not find a weaver named 'Costura'.
1>MSBUILD : error : If you have nuget package restore turned on you probably need to do a build to download the weavers.
1>MSBUILD : error : Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate NuGet package.
1>MSBUILD : error : This url may provide more information http://nuget.org/packages/Costura.Fody/ .
1>    Fody:   Finished Fody 416ms.

[FodyTest.zip](https://github.com/Fody/Fody/files/2035973/FodyTest.zip)

**Comment by SimonCropp** [comment]
can u try updating to the new csproj sdk

**Comment by WonderGnagno** [comment]
What do you mean?

**Comment by SimonCropp** [comment]
see here https://github.com/Fody/Fody#project-formats

including the reference links

**Comment by lywyn** [comment]
When did you stop supporting the old csproj format (aka <Project ToolsVersion=...> ?
I need to revert back to a version of Fody that supports that version

**Comment by SimonCropp** [comment]
@lywyn 

the old project format has always been, and still is supported. What is not supported is:

> mixing the old .csproj format with new <PackageReference> nodes.

**Comment by SimonCropp** [comment]
closing due to no response

**Comment by WonderGnagno** [comment]
Hi Simon,
sorry for the late on the answer. I tried to use the new packagereference before meet this issue but I did a revert back because i had problems with TFS. When I add a new package reference it doesn't add to TFS. I need an offline compilation.

Anyway I resolved the problem using the absolute path without environement variable.

Thanks for your help and for your library.

BR
