### ISSUE TITLE
Issue with Fody 2.3.0+ in VB assemblies

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Fody#528]
I found the following error when trying to upgrade one of our VB projects to use the latest version of Fody:

```
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\jwoods\.nuget\packages\janitor.fody\1.6.1\netclassicweaver\Janitor.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 208
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 103
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Object reference not set to an instance of an object.
Type:
System.NullReferenceException
StackTrace:
   at CecilExtensions.Find(TypeDefinition typeReference, String name, String[] paramTypes) in C:\projects\janitor\Janitor.Fody\CecilExtensions.cs:line 110
   at ModuleWeaver.FindCoreReferences() in C:\projects\janitor\Janitor.Fody\ReferenceFinder.cs:line 7
   at ModuleWeaver.Execute() in C:\projects\janitor\Janitor.Fody\ModuleWeaver.cs:line 9
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 204
Source:
Janitor.Fody
TargetSite:
Mono.Cecil.MethodDefinition Find(Mono.Cecil.TypeDefinition, System.String, System.String[])
```

At first, I thought this was an issue with the Janitor weaver, but after trying to make a failing unit test in the Janitor project, I found that it ran correctly in the unit test.

Then I also noticed a similar error upgrading another VB project to use the latest version of Anotar.

I did a little digging and found that Janitor 1.5.2 works correctly with Fody 2.2.1, but if I just upgrade Fody to 2.3.0, I start getting this error.  I also upgraded both Janitor and Fody to the latest versions available (1.6.1 & 3.0.4, respectively) and still get the error (I've created a [repo](https://github.com/jasonwoods-7/JanitorVB) to show this error).

This error only occurs when running Fody on a VB assembly using the full .Net Framework.

Here are the test cases I used:

| Language | Framework | Result |
| --- | --- | --- |
| C# | netstandard2.0 | no error |
| C# | net462 | no error |
| VB | netstandard2.0 | no error |
| VB | net462 | ERROR |

After looking into the issue a bit, I found that on [line 7](https://github.com/Fody/Janitor/blob/82b1fc46d1441f2c50a23fa4e6d744660a21a68b/Janitor.Fody/ReferenceFinder.cs#L7) (from the Janitor weaver) the code `ModuleDefinition.TypeSystem.Object.Resolve()` returns `null` when running using Fody (again, it worked from the unit test, so that seems to indicate the error is not in Mono.Cecil).

My suspicion is that the error is somewhere in the Fody.Isolated project.  I've been trying to write a unit test to confirm my suspicion, but I have been having trouble doing that.

I just wanted to go ahead and raise this issue up here as you may have more success at adding a failing unit test than I'm currently having.

I'll update this issue if I find any further details.

**Comment by SimonCropp** [comment]
can u try Janitor.Fody.1.6.2

**Comment by jasonwoods-7** [comment]
I just updated to Janitor.Fody 1.6.3 with Fody 3.1.3 and this is the error thrown:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: Could not find 'System.Object'.	JanitorVB		1	
```

**Comment by SimonCropp** [comment]
can u try adding explicit references to your VB project


    <Reference Include="mscorlib" />
    <Reference Include="System" />

**Comment by jasonwoods-7** [comment]
adding `<Reference Include="mscorlib" />` fixes the issue.  weird that that's not automatically included in VB projects.

**Comment by SimonCropp** [comment]
>  weird that that's not automatically included in VB projects.

yeah, not sure what to say on that one :)

should we close this one?

**Comment by jasonwoods-7** [comment]
yes, it can be closed
