### ISSUE TITLE
mark ModuleDefinition.TypeSystem as obsolete

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#529]
Use `BaseModuleWeaver.TypeSystem` instead

**Comment by ltrzesniewski** [comment]
I noticed `BaseModuleWeaver.TypeSystem` is missing the `CoreLibrary` property while updating.

What's the rationale behind this change? Are there cases where Cecil's `TypeSystem` gives incorrect info?

**Comment by SimonCropp** [comment]
@ltrzesniewski a few reasons

 * it seemed to be resolving incorrect types in some cases. which i think was the cause of some duplicate mscorlib in the resulting binary. TBH i didnt bother digging too much deeper into this
 * also most addins want the `TypeDefinitions` to then pick the correct methods to use. Since these are already resolved in stored in the fody type cache it makes send to just go directly to them rather than do a resolve via the cecil type system.

not used the `CoreLibrary` property. what r u using it for?

**Comment by ltrzesniewski** [comment]
OK thanks for the info. That duplicate mscorlib thing is weird, but it's good to know such a thing could happen.

I'm using `CoreLibrary` for a few things:

- [here](https://github.com/ltrzesniewski/InlineIL.Fody/blob/4ef5fdd3b92957079aa7f81ae0842b148bd56ba8/src/InlineIL.Fody/ModuleWeaver.cs#L55) to create a `TypeReference` to a type I know is in the core library (I guess I could have simply used the resolver for this).
- I expose it in the API for use like [this](https://github.com/ltrzesniewski/InlineIL.Fody/blob/d2ba2661d9177e05039fb5341eac43302a0e9ce1/src/InlineIL.Tests.AssemblyToProcess/TypeRefTestCases.cs#L40-L41) for when you want to reference a core library type by name.

Those are certainly edge cases, and right now I'm accessing Cecil's `TypeSystem` with a `#pragma` to get rid of the "obsolete" warning.
