### ISSUE TITLE
Fody is not executed on Visual Studio Live Unit Test runs

### ISSUE THREAD

**Issue by Mrnikbobjeff** [Fody/Fody#530]
I noticed that Fody is not executed on Visual Studio Live Unit Testing runs. A minimal repro involving ReactiveUI-Fody (a PropertyChanged Weaver) and xunit can be found here: 
https://github.com/Mrnikbobjeff/FodyLiveUnitTestBugRepro

**Comment by SimonCropp** [comment]
Have u raised a bug with the vs live team?

**Comment by Mrnikbobjeff** [comment]
@SimonCropp Sorry for the long delay. Yes, a bug has been raised with the vs team yesterday. No replies yet

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
