### ISSUE TITLE
Question: Can Fody be enhanced to inject IL from compiled source?

### ISSUE THREAD

**Issue by jahmai** [Fody/Fody#535]
I've been a PostSharp user for years, but am frustrated with the number of breaking changes / failure to keep up with stable .net releases.

I think Fody is an interesting alternative, but I love that int PostSharp I can write some C# code and it gets compiled and injected for me, whereas it seems in Fody I need to learn IL.

Is there an extension out there that will take a reference to a compiled class or a .cs file and inject that instead of IL? If not, is there any reason why this wouldn't work?

**Comment by SimonCropp** [comment]
Theoretically yes. But it is not how fody is designed to work. Fody is just the bridge between msbuild and addins (that extend fody using cecil). 

You can of course create a fody addin that performs the behaviour you describe

**Comment by jahmai** [comment]
Thanks Simon. I am tempted to try it but wanted to confirm there were no technical limitations, so thanks for the clarity!

**Comment by tom-englert** [comment]
@jahmai I've started some experimental code that can import arbitrary methods or classes from one assembly to another. If you're interested, I can share it.

**Comment by jahmai** [comment]
@tom-englert I sure am :)

**Comment by tom-englert** [comment]
@jahmai OK, I've cleaned it up a bit and added it to https://github.com/tom-englert/FodyTools. 
Currently this has only the CodeImporter, but I think this will be growing over time.
