### ISSUE TITLE
configuring the output AssemblyFilePath

### ISSUE THREAD

**Issue by benblo** [Fody/Fody#543]
I'm upgrading a project from Fody 1.26.4 to 3.2.0 (because I'm also switching from VS2012 / .NET 3.5 to VS2017 / .NET 4.7.1, which isn't supported by Fody 1.26.4).
I've had a few issues during the upgrade, mostly due to the conversion from "baseless class with a bunch of delegates" to "class deriving from BaseModuleWeaver": in the past, I used to be able to access the InnerWeaver from my weaver (through the AssemblyResolver - a hack, granted), but now I can't do that anymore (not exposed anymore, segregation between Fody[Isolated] and FodyHelpers).

I realize that a task can run multiple weavers, so in theory they could all want a different output path... InnerWeaver is sort of the master of that and the dependency goes the other way, but in my case I always have just one weaver (in-solution), so my weaver is the master.

I'm implemented a (crude) workaround locally (in WriteModule(), get the path from the first weaverInstance), and would be happy to submit a PR (I'd rather have that fix as part of the official nuget package), but I'm not sure you'd want it: what could a better approach be?

**Comment by SimonCropp** [comment]
I am not sure what you are attempting to do

> I used to be able to access the InnerWeaver from my weaver (through the AssemblyResolver - a hack, granted),

Why do you need the InnerWeaver?

The best approach would be to upload a small solution that illustrates what you are trying to achieve.

**Comment by SimonCropp** [comment]
closing due to no response
