### ISSUE TITLE
Embedded debug info is not supported

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/Fody#544]
Fody assumes in many places that debug info *must* be in a separate file. If you process an assembly with embedded debug info, the debug info gets stripped away.

This means you can't really use both Fody and [SourceLink](https://github.com/dotnet/sourcelink) on the same assembly, as SourceLink doesn't seem to work reliably with an external portable PDB file (VS can't always find the PDB for some reason).

I thought about changing [the `DebugSymbols` property](https://github.com/Fody/Fody/blob/67be8226acc30c2c31761d009beb4cd038ba0440/Fody/WeavingTask.cs#L77) to an enum with values `None`/`Embedded`/`External`, and then using `debugReaderProvider = new EmbeddedPortablePdbReaderProvider()` when it's `Embedded` (same for the writer).

Does this approach seem OK?

**Comment by SimonCropp** [comment]
Yep that seems like a better way to go
