### ISSUE TITLE
The "Fody.VerifyTask" task was not given a value for the required parameter "SolutionDir"

### ISSUE THREAD

**Issue by contre** [Fody/Fody#548]
Using the latest version (3.2.1), I'm receiving the error message "The "Fody.VerifyTask" task was not given a value for the required parameter "SolutionDir"" with our in house project.

If I do a fresh checkout and build, I receive the error message. We are also only using Fody.PropertyChanged. If I do a series of clean and rebuild commands, it will go away but I have yet to identify the exact sequence.

This seems to be the same issue as #466 but we're using a much later version so I'm not sure what exactly may have changed.

**Comment by SimonCropp** [comment]
will reopen when a repro is provided

**Comment by contre** [comment]
At this time, I haven't been able to narrow it down to a smaller repro yet but I will attempt to do so in the future.

**Comment by contre** [comment]
These changes appear to have fixed the issue we were seeing.

Thanks for following up even though I couldn't provide a repro.

**Comment by mrspaander** [comment]
I also have this issue. I downloaded a sample from code project and receive the same error. I am using Visual studio 2022 and the project I tried can be found on" "https://www.codeproject.com/Articles/1349071/Generating-a-Certificate-using-a-Csharp-Bouncy-Cas".
