### ISSUE TITLE
Finding docs and examples on calling InnerWeaver from a console app

### ISSUE THREAD

**Issue by aleksander-oven** [Fody/Fody#555]
I have a custom weaver that works correctly when used normally (i.e. as a project reference inside Visual Studio). Now I'm trying to call it from a console app. The goal is to have an independent app that can be invoked as needed to accomplish the weaving on a machine without VisualStudio or MSBuild. From what I read, it should be possible by utilizing FodyIsolated features. I'd need to invoke the InnerWeaver myself.

So far I've managed to configure the InnerWeaver with the correct WeaverEntry and Logger. I can verify that my weaver is, in fact, executed this way. The problem is, I have no idea how to configure References, assemblyResolver, and the rest of the InnerWeaver properties in order to be able to get the weaver to resolve even the simplest of types it needs for its job.

I'm currently stuck with a bunch of errors, like:

Can't find 'mscorlib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Can't find 'System, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Can't find 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Can't find 'System.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not find 'System.Object'.
...

Where can I find information on what exactly is missing from my code? Googling wasn't exactly helpful...

And since this is a feature request: how about some more love for the docs? Pretty please? ;)

**Comment by SimonCropp** [comment]
That functionality is not documented because it is not a public api. It not meant to be consumed. 

If u want to see what is passed in u can look at the msbuild logs

Why do u want to do this.

 I dont think it is trivial to work out what references to pass in on the command line

**Comment by SimonCropp** [comment]
u still have not answered why.

also remember that the APIs you are using are not for public consumption. they may change or be remove in any release
