### ISSUE TITLE
InnerWeaver.AddVersionField uses FileVersionInfo.GetVersionInfo which requires a physical FodyCommon.dll file

### ISSUE THREAD

**Issue by aleksander-oven** [Fody/Fody#556]
During my work on trying to use Fody from a console app, independent of MSBuild, I discovered a slight problem with the InnerWeaver.AddVersionField method, which is invoked at the ending stages of weaving.

I believe it is taking a needless dependency on having access to a physical assembly file containing the IInnerWeaver type. I understand what the method does, but in my case (i.e. inside a console app at runtime), the dependencies themselves are built into a single executable via Costura. This would ideally include the FodyCommon.dll as well so that I'm left with a single executable file.

Unfortunately, doing so causes the typeof(IInnerWeaver).Assembly.Location to return an empty string, which then breaks the call to FileVersionInfo.GetVersionInfo inside InnerWeaver code. Excluding the FodyCommon.dll from Costura makes things work as expected again.

I propose a fix that would read the version info from the AssemblyVersionAttribute or other similar in-assembly location when there is no physical file to read from.

I also propose adding a new property on InnerWeaver class that would allow skipping the AddWeavingInfo call altogether.

**Comment by SimonCropp** [comment]
> I propose a fix that would read the version info from the AssemblyVersionAttribute or other similar in-assembly location when there is no physical file to read from.

i am ok with that. can u submit a PR

> I also propose adding a new property on InnerWeaver class that would allow skipping the AddWeavingInfo call altogether.

what value would this deliver?

**Comment by aleksander-oven** [comment]
Simon, I will try to prepare a PR, time permitting, yes.

As for the value of proposed property, my line of thinking was this... I'm not exactly familiar with the various way people are using Fody, so I'm wary of introducing even the smallest of changes that could potentially break unknown stuff. Fetching the version info from assembly attribute instead of the file could perhaps cause an undesired difference in the value, which could affect every weaved assembly out there from next version forward. I can't be sure if that's safe, because, as I've said, I'm not that familiar with the Fody ecosystem. Since I'm basically only trying to solve my immediate problem, I'd be happier leaving all the defaults as they are now and only remove the thing that is stopping me.

That's how I envisioned a property along the lines of: 

bool IncludeWeavingInfo { get; set; } = true

which I could then set to false for my case only, resulting in completely skipping the extra IL that gets emitted into assembly, which I don't require anyway.

The reason I liked this solution is because it involves minimal code (one new property and an extra IF check before calling AddWeavingInfo) while leaving everyone else completely unaffected. I can't exactly be sure if simply changing the source of version info for everyone would be as safe.

**Comment by SimonCropp** [comment]
Looks like u have found a way forward. So i will close this
