### ISSUE TITLE
Error about an out-of-date version of Mono.Cecil

### ISSUE THREAD

**Issue by UweKeim** [Fody/Fody#559]
Recently, I'm getting an error message while compiling an older project of mine (using .NET 4.7.2). 

This is the compilation output in Visual Studio 2017:

```
1>------ Build started: Project: ZetaFileSync.PublicRuntime, Configuration: Release Any CPU ------
1>    Fody: Fody (version 3.2.5.0) Executing
1>    Fody: Searched for 'ModuleInit'. Found: C:\P\ZetaFileSync\Source\packages\ModuleInit.Fody.1.5.9.0\ModuleInit.Fody.dll
1>MSBUILD : error : Fody: The weaver assembly 'ModuleInit.Fody, Version=1.5.9.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.
1>    Fody:   Finished Fody 365ms.
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

The core error message is:

> MSBUILD : error : Fody: The weaver assembly 'ModuleInit.Fody, Version=1.5.9.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.

I've tried to add a reference, but found no "FodyCecil version 3.0", just v2.4.5.

Any idea how to fix this?

**Comment by SimonCropp** [comment]
Can u try updating moduleinit

**Comment by UweKeim** [comment]
Thanks, Simon. If I do understand it correctly, you tell me to update the NuGet package "ModuleInit.Fody".

It currently has the version v1.8.1. Even if I check the "Include prereleases" checkbox, I do see no newer version of it.

Do I understand something wrong?

**Comment by SimonCropp** [comment]
In that case it looks like a bug. I will look into it further. In the short term move back one version of Fody

**Comment by UweKeim** [comment]
Thanks a lot. If I can provide my project in case it helps you, just send me a quick email at uwe.keim@gmail.com and I reply with the zipped project, in case it helps.

**Comment by SimonCropp** [comment]
can u try 3.2.6

**Comment by UweKeim** [comment]
No more compilation errors. Thank you very much for your fast help! 

Greetings from Germany 😄.

**Comment by SimonCropp** [comment]
greetings from Australia.

BTW if you are using fody in a work context. u might want to consider sponsoring it to keep it alive https://opencollective.com/fody

**Comment by UweKeim** [comment]
I was on that page already yesterday. My intention to donate was very disappointed when I saw the huge number of form fields to fill out before actually donating.

Why not have a simple PayPal donate button or something like this?

I'm regularily donating to CS-Script through [their simple donate button](http://csscript.net/Donation.html).

**Comment by SimonCropp** [comment]
@UweKeim will this suffice https://www.patreon.com/join/simoncropp/checkout?rid=3027265  ?

**Comment by UweKeim** [comment]
I've tried but unfortunately ended up at a monthly subscription (which I didn't subscribe to).

Thanks for your efforts, though!

**Comment by SimonCropp** [comment]
yeah i think u need to make a custom pledge and then cancel after the first month https://www.patreon.com/join/simoncropp/checkout?rid=0

the thing with both opencollective and patreon is that they both push for ongoing payments. which makes sense since the effort in maintaining OSS is ongoing.
