### ISSUE TITLE
NuGet install of Fody 3.2.6 on VS2015 corrupts project/fails to install

### ISSUE THREAD

**Issue by syserr0r** [Fody/Fody#560]
#### Describe the bug

Versions 3.2.5 and 3.2.6 of Fody do not install using Nuget on VS2015 when installed as an update or a dependency of another package -- the error is `The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <project-path>\packages\Fody.3.2.6\build\Fody.targets`

If one attempts to install Fody (not as an update or dependency) then it may appear to succeed, but the project will become corrupted -- closing and re-opening the project will cause it to fail to load with the following error:

`The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <project-path>\packages\Fody.3.2.6\build\Fody.targets`

This also applies to Fody.PropertyChanged version 2.5.12 (with the error mentioning that package and .targets file instead)

#### Minimal Repro

1. Make new `WPF Application` project
2. Install Fody using NuGet package manager (which will attempt to install Fody3.2.6)
3. Close VS and attempt to re-open project (Project will fail to load)
(To allow the project to open again, delete the `Fody.3.2.6` folder from `packages/`)

Alternatively:
1. Make new `WPF Application` project
2. Attempt to install PropertyChanged.Fody (which will attempt to install Fody3.2.6 and PropertyChanged.Fody.2.5.12)
3. Receive error and install is abandoned (project unaltered)

#### Additional context

Reverting to older versions of Fody and Fody.PropertyChanged appears to work-around this issue.

My understanding is that VS2015 should be supported.
I am currently using VS 2015 Version 14.0.25431.01 Update 3

**Comment by SimonCropp** [comment]
Why cant u move to vs2017?

**Comment by syserr0r** [comment]
I can, I haven't got around to it yet though -- if you're no longer supporting VS2015 it might be worth mentioning as much

**Comment by SimonCropp** [comment]
The issue template does state that i should be on the current stable version on Visual Studio 

Given it would take me a couple of hours to fix this. Can u instead move to vs2017?

**Comment by tom-englert** [comment]
These braking changes are always very annoying - what was the benefit of removing the namespace from the targets file?

LG
Tom
________________________________
Von: Simon Cropp<mailto:notifications@github.com>
Gesendet: ‎02.‎10.‎2018 01:54
An: Fody/Fody<mailto:Fody@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [Fody/Fody] NuGet install of Fody 3.2.6 on VS2015 corrupts project/fails to install (#560)


The issue template does state that i should be on the current stable version on Visual Studio

Given it would take me a couple of hours to fix this. Can u instead move to vs2017?

**Comment by SimonCropp** [comment]
@tom-englert in vs 2017 they are redundant. they were inconsistent in the projects. existed in some and not in others. so i made them consistent by removing them, i was not aware vs2015 blows up without them. it was not intentional

so the question is "is vs2015 supported?". given  i dont smoke test on it, wont be installing to to diagnose bugs, do we just declare it not supported?

**Comment by syserr0r** [comment]
I assumed support from this part of the README.md:
> ## Supported Runtimes
> - Classic .NET: See Support ended in [NET Framework version history](https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview). i.e only 4.5.2 and above is supported.

From that wikipedia page it shows 4.5.2 and above are still supported, the corresponding development tool(s) for 4.5.2 and above from that chart are: Visual Studio 2015, Visual Studio 2015 (Update 1) and Visual Studio 2017

You are correct, in that when opening a bug ticket it says:
```
Where relevant, ensure you are using the current stable versions of the following:

 * Visual Studio
```
Other than this I didn't see any mention of explicitly supported (or otherwise) versions of Visual Studio. I would also interpret the above to mean that VS2015 with all the latest patches is a 'current stable version'.

If VS2015 isn't supported that isn't a huge issue I don't think, I'll just have to stick with the current versions of Fody (and dependant packages) and upgrade when I get an opportunity.

I only wanted to raise it as I thought it was a bug that might need addressing -- it might be worth making clear what IDEs are supported as I didn't expect support for VS2015 to be dropped in a patch release -- I would've been less surprised on a major point release, which would also makes a clearer boundary but I'm not sure what version number scheme you are using (and don't want to intrude, just offering my thoughts as a user).

**Comment by SimonCropp** [comment]
ok i will release a fix within the next few hours

**Comment by SimonCropp** [comment]
@syserr0r i released 3.2.7 (pending a nuget cache update) with the namespace added back in. can u try it. i am not sure if the props file import also needs the namespace.  so let me know

**Comment by syserr0r** [comment]
I'll get it updated and report back shortly -- does PropertyChanged.Fody have a similar fix?

**Comment by SimonCropp** [comment]
> does PropertyChanged.Fody have a similar fix

not as yet. i want to confirm if it is required before going to the effort

**Comment by syserr0r** [comment]
I have successfully installed Fody 3.2.7 and restarted the solution with no ill effects, this appears to have fixed the issue for me, thank-you

**Comment by SimonCropp** [comment]
thanks for following up
