### ISSUE TITLE
$(SolutionDir)/Tools weavers should distinguish netclassic/netstandard

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#566]
When having a local weaver in the `$(SolutionDir)/Tools` folder, fody should support to distinguish between a netclassic/netstandard weaver by the default directory convention.
Currently it uses just the first it finds.

PR will follow.

**Comment by SimonCropp** [comment]
Would it be better to remove this convention, and instead allow people to add them to WeaverFiles in the Directory.props?

**Comment by tom-englert** [comment]
Yeah, this sounds to be the better solution, just didn't think of it.
