### ISSUE TITLE
Dotnet Fiddle compatibility

### ISSUE THREAD

**Issue by reflection-emit** [Fody/Fody#571]
Because Fody always requires the FodyWeaver.xml, it is not possible to use e.g. https://dotnetfiddle.net/ to demo code that requires Fody. This is actually very helpful and can come handy sometimes.
Honestly I don't have a nice solution for this except for having a constant string containing the content of FodyWeaver.xml.
Maybe other devs have better solution or ideas about such a feature. Lets discuss.

**Comment by ltrzesniewski** [comment]
To avoid the breaking change, maybe you could ask .NET fiddle to set a MSBuild property during build, like `DotNetFiddle=True`, and then Fody could act on it.

You wouldn't be able to configure a weaver this way though.

BTW there's a restriction:

> No access to File System IO

If this is also enforced for the NuGet packages used during build, then Fody would throw an exception anyway.

**Comment by reflection-emit** [comment]
Yes... You are right... I think its a good idea to talk to them first, what are the options and if weaving an assembly is possible.

**Comment by ltrzesniewski** [comment]
Wait, I just saw on their uservoice they don't even support C#6. If their stack is *that* obsolete, I wouldn't want to rely on this tool to see the resulting IL.

Better use https://sharplab.io/ for this, but this one doesn't let you reference NuGet packages at all.

**Comment by reflection-emit** [comment]
I 

>           Also, do they support postsharp?

I just tested it with their Logging Example from PostSharp's Webseite... Basically copy-pasta… It works fine.

**Comment by ltrzesniewski** [comment]
The Fody readme says it supports .NET >= 4.5.2, but Fody and its addins target .NET 4.6 and .NET Standard 2.0. So NET 4.5 is not supported, though it may work by coincidence. Microsoft doesn't support it anymore either.

BTW please don't edit your messages if you add something you want someone to notice, as there are no notifications when you edit. I just happened to refresh the page and that's why I saw your question.

**Comment by reflection-emit** [comment]
I sent them a message asking about the restrictions and what we can do to make Fody compatible.

For testing purposes… What if we create a test nuget (which we can unlist after the test) with a slightly modified Fody, that load all Plug-ins during weaving. And then we see if it is enough to just solved the FodyWeaver.xml "problem".

**Comment by SimonCropp** [comment]
There is a difference between compile time and run time for fody. Weavers need to target net 46 and standard 2 for compile time, since that is what msbuild targets. But that can support a wider range for run time

**Comment by reflection-emit** [comment]
I received an answer from the .NET Fiddle team. It sounds promising.

> Hello Alexander, 
> 
> From what I have read from your GitHub repository if that you only support .NET Framework starting from v4.5.2
> 
> Currently .NET Fiddle only support .NET Framework v4.5
> 
> I'm not sure if it will be possible or not to support your scenario but the first thing to do is for sure looking at our compiler to support some of the latest Framework.
> 
> We will start this task next week.
> 
> I will let you know as we progress in it.
> 
> Best Regards,
> 
> Jonathan
>

**Comment by SimonCropp** [comment]
@reflection-emit any updates?

**Comment by reflection-emit** [comment]
Yes there is actually... I have too much to do currently that I forgot to take care about it.
Here is the answer from them:

Hello Alexander,

Sorry for my late reply, just to let you know that .NET Fiddle now support `NET 4.7.2`

Now that's being done, how can we help you to use Fody in .NET Fiddle?

One problem that I'm afraid is about the security and make sure nothing will break what we currently coded.

________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by SimonCropp** [comment]
@reflection-emit if there is nothing to be done on the fody side, perhaps we should close this one?
