### ISSUE TITLE
Fody spams build output.

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#575]
Especially when targeting `netcoreapp` the build output contains many pages full of messages like this, making it hard to find real errors:
```
      Fody: Can't find 'Microsoft.Win32.Registry, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'Microsoft.Win32.Registry, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'System.Security.Principal.Windows, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'Microsoft.Win32.Registry, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
      Fody: Can't find 'System.Security.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'System.Security.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'System.Security.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
      Fody: Can't find 'System.Security.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```
The source of this message is here:
https://github.com/Fody/Fody/blob/e09fb1c6c0c54a65b8348d1eea374c4d20852635/FodyIsolated/AssemblyResolver.cs#L81-L88

IMO there are some options to solve this:
1. Just remove this log output at all
1. Log it only once per assembly
1. Introduce a new level of logging  (e.g. `LogDiagnostic(...)`) that maps to `MessageImportance.Low` and does not show up when build output verbosity is set to `Normal`. This way also weavers would benefit from being able to log diagnostic info, because as of now `LogDebug(...)` maps to `MessageImportance.Normal`, and `MessageImportance.Low` is not accessible.

@SimonCropp I would go for 2. + 3. and provide a PR if you don't have any objections.

**Comment by SimonCropp** [comment]
i went with removing it
