### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#579]
Since there is no PR support for the wiki: 
Here are my changes: https://github.com/tom-englert/Fody.wiki.git
(Preview at https://github.com/tom-englert/Fody/wiki)

**Comment by tom-englert** [comment]
@SimonCropp please have a special look at https://github.com/tom-englert/Fody/wiki/SupportedRuntimesAndIde

**Comment by SimonCropp** [comment]
Lgtm. U should be able to edit the wiki now

**Comment by tom-englert** [comment]
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "upstream" refs/heads/master:refs/heads/master
remote: Permission to Fody/Fody.wiki.git denied to tom-englert.
fatal: unable to access 'https://github.com/Fody/Fody.wiki.git/': The requested URL returned error: 403
:disappointed:

**Comment by ltrzesniewski** [comment]
Looks like you can edit it manually though

**Comment by tom-englert** [comment]
I would have to copy/paste every file manually :disappointed: 
@SimonCropp if you add my fork as a new remote, you can just merge & push.

**Comment by ltrzesniewski** [comment]
Oh ok, I thought you just changed one page or two as github doesn't show any diff.

**Comment by SimonCropp** [comment]
thanks for this. it is now merged
