### ISSUE TITLE
Logger MessageImportance mixup

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#589]
Documented in the module weaver:
https://github.com/Fody/Fody/blob/48f900d5cdee9dcd8706b7f069508e2240b01752/FodyHelpers/BaseModuleWeaver.cs#L19-L28

Implementation used in build logger:
https://github.com/Fody/Fody/blob/48f900d5cdee9dcd8706b7f069508e2240b01752/FodyHelpers/MessageImportanceDefaults.cs#L9-L13

I would have expected the mapping as documented, however in implementation the levels are shifted by one. 
Any objections adapting the implementation to the documentation? 
It would reduce the noise of Fody in the build output when verbosity is set to "normal". To see debug messages you would have to increase verbosity to "detailed"

**Comment by SimonCropp** [comment]
> Any objections adapting the implementation to the documentation?

sounds good to me
