### ISSUE TITLE
invalid public key

### ISSUE THREAD

**Issue by Ossiostborn** [Fody/Fody#592]
VS 2015: after update v3.2.9 to v3.2.13 -> invalid public key

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Unerwarteter Fehler bei der ResolveAssemblyReference-Aufgabe.
System.Security.SecurityException: Ungültiger öffentlicher Schlüssel für Assembly. (Ausnahme von HRESULT: 0x8013141E)
   bei System.Reflection.AssemblyName.nToString()
   bei System.Reflection.AssemblyName.get_FullName()
   bei Microsoft.Build.Tasks.ReferenceTable.MarkReferencesForExclusion(Hashtable exclusionList)
   bei Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
   bei Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
   bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Die Zone der Assembly, bei der ein Fehler aufgetreten ist:
MyComputer	TG.Lib.Math.Test	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1820	

Compiling the test-class fails.

**Comment by SimonCropp** [comment]
Please read the issue template
