### ISSUE TITLE
Better error message please, when attempting to apply Fody against a value type where it expects only reference types

### ISSUE THREAD

**Issue by mark4asp** [Fody/Fody#594]
My code failed to compile because my ViewModel, I was decorating a value property (an enum) with the [Reactive] Fody attribute.  A better error message would be good here!

e.g. An error which mentions the name of the Property upon which I should not apply Fody against because it can't handle it.

The actual error I get when compiling with VS2017 community :
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\MySolution\packages\ReactiveUI.Fody.9.1.1\netclassicweaver\ReactiveUI.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Sequence contains no elements
Type:
System.InvalidOperationException
StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute()
   at ReactiveUI.Fody.ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
System.Core
TargetSite:
TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource])	ApoG.ViewModels
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
It would be nicer if the error message mentioned the file, and or class name, and/or line / property it objected to.

**Comment by tom-englert** [comment]
This is an issue of `ReactiveUI.Fody` (as you can see from the stack trace..)

**Comment by SimonCropp** [comment]
Yep tom is correct. When a weaver throws an unhandled exception fody has no extra info to show. I suggest u raise it against reactiveui. Also rather than just raising an issue, perhaps u should submit a pull request that fixes the issue
