### ISSUE TITLE
ASP.net support

### ISSUE THREAD

**Issue by tdsrhh** [Fody/Fody#600]
Hi

I use the latest version of fody with costura. 

The asp.net web solution builds and embeds just fine using fody/costura. 

It's embedding 40 dll/pdb's. The total size of the dll is 24079 KB (guite large)

But when I try to run it in IIS I get :

-----

The type 'TDS.WebService.Mobile.Taxameter.Client.Service', provided as the Service attribute value in the ServiceHost directive, or provided in the configuration element system.serviceModel/serviceHostingEnvironment/serviceActivations could not be found. body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px} b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px} H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red } H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon } pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt} .marker {font-weight: bold; color: black;text-decoration: none;} .version {color: gray;} .error {margin-bottom: 10px;} .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; } @media screen and (max-width: 639px) { pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; } } @media screen and (max-width: 479px) { pre { width: 280px; } } Server Error in '/TEST' Application.

----

Running the same project without embedding everything works fine.

Any thoughts why ?

Regards

**Comment by tdsrhh** [comment]
Some more information. It looks this has nothing to do with how many dll's I embedd. One works, two or more results in the problem. If needed I can give you a small sample showing the problem.

Regards

**Comment by tdsrhh** [comment]
This seems to be a general problem using last stable version with asp.net building a simple web service. Can someone confirm this or am I missing something here ?

**Comment by SimonCropp** [comment]
did you read the issue template? https://github.com/Fody/Fody/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
