### ISSUE TITLE
Visual Studio 2015: Unknown attribute 'Update' in <None> element of Fody.targets

### ISSUE THREAD

**Issue by kroimon** [Fody/Fody#601]
#### Describe the bug

Can not load project in Visual Studio 2015 after updating to latest version 3.3.0.
When running VS with `set TRACEDESIGNTIME=true`, the following error is shown (in German):
> xyz.csproj : error  : Das Update-Attribut im <None>-Element ist unbekannt.  xyz\packages\Fody.3.3.0\build\Fody.targets

which roughly translates to

> xyz.csproj : error  : The Update attribute in the <None> element is unknown.  xyz\packages\Fody.3.3.0\build\Fody.targets

#### Expected behavior

I feel that the latest library version should at least support the previous Visual Studio version 2015 as not everyone can afford to always use the latest version of Visual Studio.

**Comment by SimonCropp** [comment]
> I feel that the latest library version should at least support the previous Visual Studio version 2015 as not everyone can afford to always use the latest version of Visual Studio

VS 2017 community is free

**Comment by Red5goahead** [comment]
> I feel that the latest library version should at least support the previous Visual Studio version 2015 as not everyone can afford to always use the latest version of Visual Studio.

It is not a problem with a money to spend to migrate to an updated version of visual studio.
It's a problem that often a company is stucked with a specific version for a lot of reason.
In this case a FodyWeavers.XSD is missing

**Comment by SimonCropp** [comment]
@Red5goahead @kroimon I understand why people ask for support for older versions. the thing you need to realise is that this takes significant effort to achieve. to support vs2015 properly requires

 * configuring and maintaining build server infrastructure
 * having a VM available to verify an bugs people raise
 * smoke testing all release against vs 2015

Then multiply all of the above over the 30+ fody weavers I maintain.

And most people expect this (often demand it) from me with my free time, without offering any help.

You need to thank both @tom-englert and @ltrzesniewski. they lobbied the case to continue supporting VS2015, and even worked on providing the fix here https://github.com/Fody/Fody/pull/602. TBH i would have preferred to detect VS2015 and throw a not supported error

But if you want VS2015 to continue to be supported you need to contribute your time in the form triaging and fixing issues, **and** also contribute to the fody collective https://opencollective.com/fody 

@kroimon next time you raise an issue can you please read the issue template

**Comment by SimonCropp** [comment]
this is now deployed pending a nuget cache refresh
