### ISSUE TITLE
Integration test chain

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#607]
I have setup an integration test chain, that builds Fody, and has three dependent builds that build a sample project using Fody from the master build, with different versions of VS.

Since AppVeyor does not support this, I have used Azure build pipelines. 
However I can only setup a CI build from my private fork. 
If I try to use Fody/Fody as a source, I get the error that I have no rights to establish the Webhook.

However not using my fork for the build will reveal errors only after I have merged the latest version, and will not work for PRs.

I could think of two ways to solve this:
- You give me temporary access to the Fody repo, so I can setup the Webhook.
- I give you access to my Azure build and you change the repo using your account: https://tom-englert.visualstudio.com/Open%20Source/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=23

**Comment by ltrzesniewski** [comment]
You probably didn't realize that, but your Azure Pipelines builds are not publicly accessible. I'm getting a "401 not authorized" error when I click on the badge in the wiki.

**Comment by tom-englert** [comment]
@tom-englert I've added @SimonCropp (simon.cropp@gmail.com) as build admin, so he should be able to follow this link.
However I didn't realize that they changed the badges to now contain a link, this needs to be removed, of course.

**Comment by tom-englert** [comment]
@SimonCropp when you merge #610 I can start with a nightly build, that doesn't need a webhook.

**Comment by ltrzesniewski** [comment]
Sure, I'll give you a hand, thanks for your trust!
Although as you say I think we should discuss this as I'm not quite sure what I'm supposed to do with *this* level of access.

**Comment by tom-englert** [comment]
I also appreciate your trust!
Let's join our forces to keep Fody a mature, stable and reliable tool.

**Comment by SimonCropp** [comment]
user error. try now :)

**Comment by ltrzesniewski** [comment]
@tom-englert BTW why do you want the integration tests to be private?
If a test fails, all the feedback you'll get will feel something like _"your commit failed, but I won't tell you why"_.

**Comment by tom-englert** [comment]
@ltrzesniewski just discovered this new option yesterday, I will change it of course 😄
