### ISSUE TITLE
Add configuration to turn of legacy weaver lookup

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#625]
Scanario: 
A weaver is configured in FodyWeavers.xml, but not included as NuGet package. 
The build may succeed, because Fody finds any weaver by legacy lookup. 

To make this more strict, there should be a flag in configuration that allows to turn of legacy lookup.
Alternative: Turn of legacy lookup by default, and have a flag to turn it on again.

@SimonCropp @ltrzesniewski Whats your opinion about this?

**Comment by ltrzesniewski** [comment]
Seems reasonable. I wouldn't mind having legacy support off by default (most weavers should be up to date), as long as the error message is clear and references the config option.

**Comment by SimonCropp** [comment]
Isnt legacy lookup prone to bugs via side effects? And if it doesn’t find one, isnt the fix trivial for the user?... add the package?

**Comment by tom-englert** [comment]
Yeah, default option for legacy lookup should probably be OFF

**Comment by SimonCropp** [comment]
What I don’t understand why would we want anyone to enable it?

**Comment by tom-englert** [comment]
There might be some legacy weavers around, and it's not a big deal keeping it for a while...

**Comment by SimonCropp** [comment]
Ok i am a little confused. What do u define as “legacy lookup” versus “legacy weaver”?
