### ISSUE TITLE
ReflectionTypeLoadException .net core 3.0

### ISSUE THREAD

**Issue by Logerfo** [Fody/Fody#627]
I'm currently starting to port my solution to cross-platform. Since it uses winforms, I was waiting for .net core 3.0 to be released. Yesterday a preview was made available. The following changes happened to my projects:
- From net framework 4.7.2 to .net core 3.0.0 preview 1.
- From Visual Studio 17 to Visual Studio 19 preview 1.

I'm listing them because I don't know the exact cause to repro my issue. As far as I know, they cannot happen separately. I'm using [InSolutionWeaving](https://github.com/Fody/Fody/wiki/InSolutionWeaving) and the Weavers project builds fine, but the weaver consumer fails to build:
>Fody: Could not load 'ModelPropertyWeaver' from 'Weavers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
It is possible the package needs to be updated.
exception.LoaderExceptions:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
File name: 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

>WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

As described [in another issue](https://github.com/Fody/Fody/issues/613#issuecomment-442825960), search strategies might not be useful for me.
I already tried including `<Reference Include="System.Runtime" />` in both the weavers and the consumer projects, but nothing has changed.

**Comment by SimonCropp** [comment]
@Logerfo just checking, did u read the issue template? 
https://github.com/Fody/Fody/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Logerfo** [comment]
I managed to solve the issue by using `netstandard2.0` instead of `netcoreapp3.0` in the Weavers project.
