### ISSUE TITLE
FodyHelpers v3.3.3: NullReferenceException in ReferenceCleaner.CleanReferences

### ISSUE THREAD

**Issue by aleksander-oven** [Fody/Fody#630]
I had a working console app that calls a custom weaver at run time via FodyHelpers (so, not a typical build-time weaving).

Things worked fine with v3.2.8, but now consistently fail with v3.3.3 with a NullReferenceException inside the ReferenceCleaner.CleanReferences call. From the logged output I can surmise that there are two probable values that could be null in 3.3.3 but weren't in 3.2.8. Both are referenced in [line 20](https://github.com/Fody/Fody/blob/master/FodyHelpers/ReferenceCleaner.cs#L20).

I'm aware that FodyHelpers is not public API. Still, a NullReferenceException usually means an unexpected code path was taken. Maybe someone could check?

**Comment by aleksander-oven** [comment]
Found the change that was causing problems. `InnerWeaver` now requires `ReferenceCopyLocalPaths` property to be assigned. A simple `new List<string>()` seems to satisfy it.

**Comment by SimonCropp** [comment]
@aleksander-oven any input on the support/patron changes? https://github.com/Fody/Fody#licensingpatron-faq

**Comment by aleksander-oven** [comment]
@SimonCropp: I can only say I understand the reasons behind the change. As far as changes go, I really hope this one brings more good than bad for Fody!

**Comment by tom-englert** [comment]
Maybe we should start using Fody to develop Fody - in this case NullGuard would have been useful.

**Comment by SimonCropp** [comment]
@tom-englert at on point fody was used to build fody. i removed it because the inception-like debugging experience of, when u find a bug in fody/weaver, caused all kind of headaches.
