### ISSUE TITLE
Fody.Packaging is not compatible with new NuGet License tags.

### ISSUE THREAD

**Issue by glennawatson** [Fody/Fody#638]
#### Describe the issue

NuGet are deprecating the _PackageLicenseUrl_ csproj tag shortly.

In ReactiveUI.Fody we are using the new recommended way of using **PackageLicenseExpression** (or **PackageLicenseFile** but we opted into using the Expression).

[FodyPackaging.props](https://github.com/Fody/Fody/blob/e924e1f361ab36fd37b5dff77561965285f05eae/FodyPackaging/build/FodyPackaging.props#L43) is setting a _PackageLicenseUrl_ if none is found and this is producing the following error:
```
error NU5035: The PackageLicenseUrl is being deprecated and cannot be used in conjunction with the PackageLicenseFile or PackageLicenseExpression.
```

#### Minimal Repro

1. Create a application that implements FodyPackaging
2. Set a PackageLicenseExpression (or PackageLicenseFile) to be 'MIT' for example.
3. Compile and see the build error that comes in.

#### Submit a PR that fixes the bug
#639

**Comment by glennawatson** [comment]
sorry not a patron but happy to give back the traditional way of doing the work for you guys on your behalf.

**Comment by SimonCropp** [comment]
@glennawatson this should now be deployed. thanks for the PR
