### ISSUE TITLE
Building already built project results in 1 succeeded instead of 1 up-to-date

### ISSUE THREAD

**Issue by jakubsuchybio** [Fody/Fody#642]
#### Describe the bug
Given I have 1 project in solution **without** Costura.Fody installed
When I build project for the first time
Then It results in 1 succeeded project built
And When I build the same project for the second time
Then it results in 1 up-to-date project built

Given I have 1 project in solution **with** Costura.Fody installed
When I build project for the first time
Then It results in 1 succeeded project built
And When I build the same project for the second time
Then it **results in 1 succeeded instead of 1 up-to-date** project built

#### Minimal Repro
see Description

#### Submit a PR that fixes the bug
I have no idea where to start to fix this issue. I could try it, with some navigation from you.

#### Expected behavior
I would expect that consecutive builds without any changes to the project would result in 1 up-to-date build. 

#### Additional context
When I set Output verbosity to 'Normal' in VS settings I get this build output:
```
1>------ Build started: Project: CP.LogAdapter, Configuration: Debug Any CPU ------
1>Build started 12.11.2018 8:07:01.
1>_HandlePackageFileConflicts:
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>FodyTarget:
1>Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files.
1>_CopyAppConfigFile:
1>Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
1>CopyFilesToOutputDirectory:
1>  CP.LogAdapter -> c:\DokumentySVN\MEWProjects\MEW\CP.LogAdapter\bin\Debug\CP.LogAdapter.dll
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.30
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Here you can see that FodyTarget is skipped, because target is up-to-date, however step with Copying the resulting assembly is still made. By my understanding this is not necessary and this step should be skipped as well.

**Comment by BrunoJuchli** [comment]
We've experienced the same symptoms.
We're still using Packages.config, too.
We could track it to:

>1>Project 'FOO.Bar' is not up to date. CopyLocal reference 'C:\dev\FOO\net\artifacts\Debug\Server\EmptyConstructor.dll' is missing from output location.

We've workaround this by:

![image](https://user-images.githubusercontent.com/2090172/50840497-f46cbb00-1362-11e9-847b-4fe6b959729b.png)

(in words: modifying the *.csproj: adding `<Private>False</Private>` to the `<Reference>` of `EmptyConstructor`).

We've done this for all Fody plugins.

**Updating the package will revert the change.**

**Comment by ltrzesniewski** [comment]
@BrunoJuchli thanks for looking into this! That may be not so easy to fix properly, I'll take a look at it when I'll have some time.

**Comment by ltrzesniewski** [comment]
Ok, so the issue here is that VS uses an optimization called FastUpToDateCheck: if VS can determine that a project is up-to-date, then it skips calling MSBuild altogether and shows the "1 up-to-date" line in the summary. But as soon as it calls MSBuild it considers the project is being built and you get thet "0 up-to-date" thing.

Fody confuses VS by switching a dependency's Copy Local property from true to false at build time, and VS thinks the file is missing and runs a build. The diagnostic build output in VS says the following:

> Project 'fody-costura-build-repro' is not up to date. CopyLocal reference 'C:\Dev\NuGet-Isolated\src\fody-costura-build-repro-master\fody-costura-build-repro\bin\Debug\Costura.dll' is missing from output location.

The documentation about this optimization is very scarce, and even more so for the old project system. I've found out that you can declare items such as `UpToDateCheckInput ` and `UpToDateCheckOutput` to customize this behavior, but I don't see anything in there which could be used to *remove* an input.

I tried a couple things but didn't manage to cause VS to skip the build. Setting Copy Local to false manually seems the way to go here, unless someone comes up with a better idea.

**Comment by jakubsuchybio** [comment]
Ehm, didn't expect that you would go so deep into this issue. 
I think that ```Setting Copy Local to false manually on Costure``` or any other Fody weaver is sufficient workaround. It is old package referencing. It will be old and deprecated soon *fingers crossed*
If I were you I wouldn't fix this further.

**Comment by SimonCropp** [comment]
@ltrzesniewski very impressive research effort

@jakubsuchybio oit of curiosity what is blocking u from moving to the new csproj format?

**Comment by jakubsuchybio** [comment]
@SimonCropp Long story short. My company does software for Medical and there are REALLY Conservative developers that still use VS2013 and VS2015. And they don't want to upgrade to VS2017, so that we could use Package References... (It is not possible to load project in VS2015 or older with package references) And also company doesn't want to pay for new licences of VS2017, but if developers would want, company would have to pay... Corporate... :D

**Comment by SimonCropp** [comment]
ok going with the suggestion from @jakubsuchybio 

> I think that Setting Copy Local to false manually on Costura or any other Fody weaver is sufficient workaround. It is old package referencing. It will be old and deprecated soon fingers crossed
If I were you I wouldn't fix this further.
