### ISSUE TITLE
Add ProjectFileName to ModuleWeaverBase

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#655]
I need the actual project path (e.g. csproj) of a project. We have ProjectDirectory, SolutionDirectory, DocumentationFileName, but not yet the ProjectFileName.

I think this is an easy one, isn't it?

**Comment by SimonCropp** [comment]
i have some doco to complete. so prob next weekend. if it helps i can deploy it in a beta

**Comment by GeertvanHorrik** [comment]
Would be nice, then i can update loadasssembliesonstartup

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
