### ISSUE TITLE
Weaver cannot find and weave target types decorated by attribute defined in different assembly on netstandard

### ISSUE THREAD

**Issue by lu8848** [Fody/Fody#661]
#### Environment:
Fody 3.3.5
FodyHelper 3.3.5
FodyPackager 3.3.5
VS 2017 Professional
Netstandard2.0 and Framework4.6.1

#### Issue:
I created a simple MyWeaver Nuget package for netstandard 2.0 and Framework 4.6.1 targets to test Fody 3.3.5. The weaver defines IAdvice interface and AdivceAttribute class (AdivceAttribute implements IAdvice) in its runtime assembly MyWeaver.dll. I want the weaver to detect and weave all target types that directly/indirectly implement IAdvice, when the weaver finds a target type, it LogInfo a message as "Simulate weaving <target type name>...". If no target type is detected, it LogError "No type was weaved."

In order to test MyWeaver package, I created two projects:
1) Advices project that contains MyAdvice class derived from AdviceAttribute class in runtime
    public class MyAdvice : AdviceAttribute
    {
    }

    Advices project targets to both netstandard2.0 and net461.

2) SmokeTest project that contains TargetClass class decorated by MyAdvice class as below. SmokeTest project references the Advices project.
    [MyAdvice]
    public class TargetClass
    {
            public int Add(int x, int y)
            {
                return x + y;
            }
    }

    SmokeTest project targets to both netstandard2.0.

I let both of projects reference MyWeaver.Fody package.

Phenomena:
- when built SmokeTest project targeting to netstandard2.0, MyWeaver.Fody cannot find target class and reports "MSBUILD : error : Fody/MyWeaver: No type was weaved." in Output window;
- Changed SmokeTest project target to net461 and built it again, MyWeaver.Fody correctly displays in Output window: "Fody/MyWeaver:   Simulate Weaving SmokeTest.TargetClass..."

#### Minimal Repro

A solution created by VS2017 is zipped into MyWeaver.zip, please have a look.
[MyWeaver.zip](https://github.com/Fody/Fody/files/2824104/MyWeaver.zip)

**Comment by lu8848** [comment]
> why does Advices.csproj have a package ref to `MyWeaver.Fody`?
> 
> ```
>     <PackageReference Include="MyWeaver.Fody" Version="3.1.9" />
> ```

Because Advices project contains MyAdvice class derived from AdviceAttribute class, and AdviceAttribute is in runtime DLL of MyWeaver.Fody.

**Comment by lu8848** [comment]
> the smoke test also has an incorrect package ref to myWeaver. it should look this https://github.com/Fody/Home/blob/master/BasicFodyAddin/SmokeTest/SmokeTest.csproj

I created a nuget package file MyWeaver.Fody.3.1.9.nupkg and saved it to local disk c:\tmp first, and then   installed it to SmokeTest project with command "Install-Package MyWeaver.Fody -Source C:\tmp\", and installer automatically added the reference into SmokeTest.csproj as `<PackageReference Include="MyWeaver.Fody" Version="3.1.9" />`

The end user of the package can use nupkg file only, no source code is packed.

**Comment by SimonCropp** [comment]
Will re open when questions are answered
