### ISSUE TITLE
[Fody 4.0.1] PE Verify issues with new Fody

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#663]
The new Fody spawns PE Verify issues we never had before. I will try to investigate and put the progress here, they might be useful for others that run into the same issue.

```
MSBUILD : error : Fody: PEVerify of the assembly failed. [C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
MSBUILD : error : [MD](0x8013120E): Error: TypeDef has a duplicate based on namespace and name, token=0x020002d5. [token:0x020002D4] [C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
MSBUILD : error : [MD](0x8013120E): Error: TypeDef has a duplicate based on namespace and name, token=0x020002d4. [token:0x020002D5] [C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
MSBUILD : error : 2 Error(s) Verifying C:\Source\catel\output\Release\Catel.MVVM\net47\Catel.Core.dll [C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
```

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/52591261-c7209a80-2e43-11e9-9091-c30bb386180a.png)

**Comment by GeertvanHorrik** [comment]
According to an [MSDN blog](https://blogs.msdn.microsoft.com/yizhang/2010/12/17/interpreting-hresults-returned-from-netclr-0x8013xxxx/):

HRESULT #define name | Value | Error message
-- | -- | --
VLDTR_E_TD_DUPNAME | 0x8013120e | TypeDef marked nested has no encloser.

**Comment by GeertvanHorrik** [comment]
And somehow I can't find the 0x020002D5, so could it be something with the ProcessedByFody generated class?

**Comment by GeertvanHorrik** [comment]
This is the (decompiled) code the class contains:

```
internal class ProcessedByFody
{
  /*Field FodyVersion with token 04000664*/
  // .field assembly static literal string FodyVersion = "4.0.1.0"
  internal const string FodyVersion = "4.0.1.0";
  /*Field Obsolete with token 04000665*/
  // .field assembly static literal string Obsolete = "4.4.3.0"
  internal const string Obsolete = "4.4.3.0";
  /*Field ModuleInit with token 04000666*/
  // .field assembly static literal string ModuleInit = "1.9.0.0"
  internal const string ModuleInit = "1.9.0.0";
  /*Field Catel with token 04000667*/
  // .field assembly static literal string Catel = "3.9.0"
  internal const string Catel = "3.9.0";
  /*Field MethodTimer with token 04000668*/
  // .field assembly static literal string MethodTimer = "2.3.0.0"
  internal const string MethodTimer = "2.3.0.0";
}
```

**Comment by GeertvanHorrik** [comment]
Interesting, it seems to happen when building Catel.MVVM (which has Catel.Core as dependency). So Catel.Core itself builds fine:

![image](https://user-images.githubusercontent.com/1246444/52593162-93943f00-2e48-11e9-9ffc-84b4ab96a925.png)

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/52593350-00a7d480-2e49-11e9-9f7c-bb0cef3142f2.png)

**Comment by GeertvanHorrik** [comment]
Basically it should never process an assembly that's not the assembly itself.

**Comment by ltrzesniewski** [comment]
No, Fody never checks for `ProcessedByFody`, I think we could remove all that code altogether.

I'm wondering how you managed to get it to process an assembly twice. Did you remove the output assembly from `bin` without clearing `obj`? That would explain it.

Anyway, this could certainly be improved by hooking Fody into `$(TargetsTriggeredByCompilation)`, but I'm not sure it would play well with previous VS versions.

**Comment by GeertvanHorrik** [comment]
The CoreCompile target knows it has to skip:

![image](https://user-images.githubusercontent.com/1246444/52593747-0b169e00-2e4a-11e9-9115-fab190015678.png)

**Comment by GeertvanHorrik** [comment]
I build them 1:1 using msbuild (so first Catel.Core using msbuild, then Catel.MVVM using msbuild, etc). The `ProcessedByFody` should not be removed, the reason it was introduced was because we could figure out which weavers and versions were used for an assembly.

**Comment by GeertvanHorrik** [comment]
I am preparing a hotfix where an assembly won't be processed if it contains the ProcessedByFody. It might not be the best solution, but at least it unblocks the usage of Fody 4.x

**Comment by ltrzesniewski** [comment]
An easy workaround could be to change [this line](https://github.com/Fody/Fody/blob/1e46ddc64a9223a8163722d533b4eaa47e3bc850/Fody/Fody.targets#L34) `Outputs="$(TargetPath)"` to `Outputs="$(IntermediateOutputPath)$(MSBuildProjectFile).Fody.CopyLocal.cache"`

**Comment by GeertvanHorrik** [comment]
Not sure, it shouldn't even kick off the verification & processing at all. Ultimately, it should detect that it's using an up-to-date reference and should skip all Fody processing.

**Comment by ltrzesniewski** [comment]
I removed my previous comment because I thought I wrote it a bit too quickly, but it actually may work (using `Outputs="$(IntermediateOutputPath)$(MSBuildProjectFile).Fody.CopyLocal.cache"` on `FodyTarget`) as the cache file is written *after* the output assembly.

Anyway, the idea was to make Fody rely only on the contents of the `obj` directory in order to determine if the assembly needs processing. The task would be skipped by MSBuild when up-to-date. If you implement code that checks for `ProcessedByFody`, you'd still have to open the assembly with Cecil. That could be ad additional security measure though.

**Comment by GeertvanHorrik** [comment]
> If you implement code that checks for ProcessedByFody, you'd still have to open the assembly with Cecil.

Good point, that's one of the downsides. Testing your suggested fix locally now!

**Comment by GeertvanHorrik** [comment]
Your fix seems to work great :)

![image](https://user-images.githubusercontent.com/1246444/52594611-3b5f3c00-2e4c-11e9-8d2a-691434625df7.png)

**Comment by ltrzesniewski** [comment]
Good! 😄 

Can I ask you a quick off-topic question? I implemented the search markers in the MSBuild log viewer you can see on your [screenshot here](https://github.com/Fody/Fody/issues/663#issuecomment-462492587), but they look misaligned ([reference screenshot here](https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/236#issue-249055599)) and you seem to have more margin between tree items than I have. Did you customize your Windows display settings in some way?

**Comment by GeertvanHorrik** [comment]
> Did you customize your Windows display settings in some way?

Nope, but I am using RDP to connect to a VM (which is my dev machine). I also have very old monitors with low DPI, so that could (but shouldn't) cause this. I did enable virtualization on the TreeView (but installed the latest version today via Chocolatey).

I am using Win 10 1809

**Comment by ltrzesniewski** [comment]
Ok, thanks, I'll try to figure out what causes this.

**Comment by GeertvanHorrik** [comment]
If you need any help (for example, with testing), feel free to ping me on Gitter or via Twitter.

Again, thanks for your help and stepping in.
