### ISSUE TITLE
Q: What are the changes/fixes in Fody 4.0?

### ISSUE THREAD

**Issue by fubar-coder** [Fody/Fody#666]
I'm unable to find a changelog for all the changes in 4.0. If there is one, can it please be linked to from the readme.md?

This is what I did:

- I skimmed over the pages in Fody/Home, but didn't find a changelog page
- Opening the "Releases" list of Fody/Fody, but didn't see an information for the version tags

**Comment by ltrzesniewski** [comment]
You can check the [4.0.0 milestone](https://github.com/Fody/Fody/milestone/101?closed=1). Milestones usually tell you the significant changes for a given version.

**Comment by ltrzesniewski** [comment]
I added a link to the Fody/Fody readme in b3a20953d26b15e28b40689377bb6278b17d6e97 and made a PR https://github.com/Fody/Home/pull/13

**Comment by SimonCropp** [comment]
@fubar-coder BTW To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
