### ISSUE TITLE
PropertyChanged in combination with MvvmLight

### ISSUE THREAD

**Issue by farth123** [Fody/Fody#667]
If I'm using FodyPropertyChanged in combination with MvvmLightLibs than I cannot use option "Edit and continue". How to fix this issue?

![image](https://user-images.githubusercontent.com/34681006/53102161-6e2fc100-352b-11e9-8562-8db1bb5a6cbf.png)

edit:  similar issue
https://stackoverflow.com/questions/45926161/fody-propertychanged-preventing-edit-and-continue-when-used-with-mvvmlight

**Comment by SimonCropp** [comment]
Edit and continue is not currently supported https://github.com/Fody/Home/blob/master/pages/common-errors.md#edit-and-continue

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by farth123** [comment]
Edit and continue works perfect. Only if I use ViewModelBase from MVVMLight it doesn't. ViewModelBase from DevExpress works too. Maybee it's bug of MVVMLight?

**Comment by SimonCropp** [comment]
@farth123 happy to look into this more once you become a patron

**Comment by redwyre** [comment]
Hi @SimonCropp I'm a patron and am getting this error.
It seems to only have become a problem after upgrading to .net standard (2.0)?

**Comment by redwyre** [comment]
Ok, I backported the library to netstandard2.0 (not fun) and that works fine too.
So it looks like the issue is with targeting netcoreapp3.0 specifically

**Comment by redwyre** [comment]
Updating to .net core 3.0.1 fixed the issue 🤷‍♂️

**Comment by SimonCropp** [comment]
@redwyre that makes no sense to me :(
