### ISSUE TITLE
Error after updating to 4.0.x from 3.3.5

### ISSUE THREAD

**Issue by dark2201** [Fody/Fody#672]
I'm using Costura. I've upgraded Fody to 4.x and I'm getting errors:

`packages\Fody.4.0.2\build\Fody.targets(42,9): error MSB4064: The "ProjectFile" parameter is not supported by the "Fody.WeavingTask" task. Verify the parameter exists on the task, and it is a settable public instance property.`

`packages\Fody.4.0.2\build\Fody.targets(36,5): error MSB4063: The "Fody.WeavingTask" task could not be initialized with its input parameters. `

**Comment by SimonCropp** [comment]
did you read the issue template? https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by dark2201** [comment]
It's simple enough:
![image](https://user-images.githubusercontent.com/3116731/53877752-4a2fad80-400a-11e9-9104-74badd96c5f7.png)

After updating it stopped working.

**Comment by ltrzesniewski** [comment]
Given the error, you probably have a corrupted csproj file which includes several versions of `Fody.targets`. Edit it manually to make sure only the reference to the latest version remains.

**Comment by SimonCropp** [comment]
@dark2201 

> To be using Fody you should be a [Patron](https://opencollective.com/fody/order/3059). See [Licensing/Patron FAQ](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md). With that in mind, it is assumed anyone raising an issue is already a Patron. As such your GitHub Id may be verified against the [OpenCollective contributors](https://opencollective.com/fody#contributors). This process will depend on the issue quality, your circumstances, and the impact on the larger user base.

**Comment by RNoeldner** [comment]
> Given the error, you probably have a corrupted csproj file which includes several versions of `Fody.targets`. Edit it manually to make sure only the reference to the latest version remains.

Indeed this fixed it for me the .csproj file showed two locations in Target / Error  and Import

**Comment by SimonCropp** [comment]
@RNoeldner unfortunately this is a bug in nuget that is unlikely to be fixed. to avoid it in the future you should update to the new csproj format
