### ISSUE TITLE
Cannot find native library

### ISSUE THREAD

**Issue by clintonvanry** [Fody/Fody#673]
I am have referenced google.cloud.vision.v1 which in turn references Grpc.Core
When you compile your project with this reference it outputs native libs for example
grpc_csharp_ext.x86.dll

I have included these native libs as embedded resources as explained in the following article:
https://idmedia.no/general/including-sqlite-interop-dll-into-your-c-project/

Please see my FodyWeaver.xml file

<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura CreateTemporaryAssemblies="true">
    <PreloadOrder>
      libmmd
      libiomp5md
      audiotools
    </PreloadOrder>
    <Unmanaged32Assemblies>
      grpc_csharp_ext.x86
      libgrpc_csharp_ext.x86
    </Unmanaged32Assemblies>
    <Unmanaged64Assemblies>
      grpc_csharp_ext.x64
      libgrpc_csharp_ext.x64
    </Unmanaged64Assemblies>
  </Costura>
</Weavers>

I can seem them embedded in the executable using ILSpy so this part looks correct.

When the process starts for the  project I can see that costura has unpacked it
..\appdata\local\temp\costura\{guid}\32\grpc_csharp_ext.x86.dll

When it starts to execute the following method
var channel = new Channel(ImageAnnotatorClient.DefaultEndpoint.Host,ImageAnnotatorClient.DefaultEndpoint.Port, channelCredentials);

It tries to load the native library but this fails with the following exception:

"Error loading native library. Not found in any of the possible locations: C:\\Users\\Clinton.VanRy\\AppData\\Local\\Temp\\Costura\\883A40ADF71EBB8F363341B5BAC08483\\grpc_csharp_ext.x86.dll,C:\\Users\\Clinton.VanRy\\AppData\\Local\\Temp\\Costura\\883A40ADF71EBB8F363341B5BAC08483\\runtimes/win/native\\grpc_csharp_ext.x86.dll,C:\\Users\\Clinton.VanRy\\AppData\\Local\\Temp\\Costura\\883A40ADF71EBB8F363341B5BAC08483\\../..\\runtimes/win/native\\grpc_csharp_ext.x86.dll":null}	System.IO.FileNotFoundException

How do I resolve this issue?
How can I specify the resolver to look at the \32 folder or \64 folder
![unpackednativelibs](https://user-images.githubusercontent.com/1840178/54047801-f242a380-41cf-11e9-9d62-7ab351415c15.PNG)

Any help or guidance will much appreciated.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
just realized this is in the wrong repo. Please re raise in https://github.com/Fody/Costura/

**But before you do that ensure you (and anyone else at your company using fody) become a fody patron**

also please read the issue template and ensure you have covered all the requirements https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
