### ISSUE TITLE
Fody still Not Executed on VS 2017 Live Testing

### ISSUE THREAD

**Issue by haroldcris** [Fody/Fody#675]
Related to #530  

Im using VS 2017 version 15.9.9

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
