### ISSUE TITLE
.net 472/MSBuild16 required at build time

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#679]
With the impending release of VS2019 (2nd April) it is planned to drop support for VS2017 and MSBuild15.

The motivations for this change are as follows:

 * Currently Fody addins are constrained in the .net runtime they can use. The current requirement for MSBuild15 support locks us in to .net4, a 4 year old runtime and SDK. Changing the minimum requirement to be MSBuild16 allows Fody addins to make use of features in newer .net versions.
 * Reduce support effort by not needing to troubleshoot bugs in VS2017, msbuild15, and older versions of NuGet.
 * Lowers the friction for contributors, since they do not need to install the net4 SDK.

Impact on users:

 * This does not effect people using dotnet build.
 * Fody will still be able to process .net assemblies on lower version
 * Build/dev machines will need msbuild16 (shipped with VS2019) installed
 * Users can remain on older versions of fody until they can update to VS2019

**Comment by bording** [comment]
Since Fody uses MSBuild tasks, I assume you're talking about using `net472` for the tasks assembly, right?

I'm not sure that's a good idea since AFAIK MSBuild 15 is built against `net46`. I know targeting a newer version of .NET Framework can cause problems when running a Visual Studio extension, so I suspect there might be a similar problem for MSBuild. 

For VS you can run into problems around differences of the versions of assemblies shipped and loaded by VS vs. the ones needed by the extension assembly, and there's no opportunity to deal with those differences with binding redirects, etc.

**Comment by SimonCropp** [comment]
Thanks for the heads up. I will do some testing

**Comment by bording** [comment]
This came up in LibGit2Sharp as well, so that's why it's already something I've been aware of: https://github.com/libgit2/libgit2sharp/pull/1651

Here's more context: https://github.com/github/VisualStudio/issues/1849#issuecomment-411570902

**Comment by SimonCropp** [comment]
Will double check msbuild 16. Might be easier to hold off till vs19 and just say “msbuild 16 is a minimum “

**Comment by ltrzesniewski** [comment]
Do you actually need any feature of 4.7.2? Deprecating VS2017 over this right now seems premature.

**Comment by SimonCropp** [comment]
There are also many other bugs in vs2017 that effect fody. Many of These bugs are being fixed only in vs2019. Eg the embedded symbols issue, many nuget qwerks. 

I would rather spend time ensuring vs2019 support, and also getting the newer runtime features, than spend effort supporting an abandoned ide. 

If i was being paid a livable wage from fody it would be a different matter. I would attempt to get as much reach as possible. But atm i am recouping less than min wage

**Comment by SimonCropp** [comment]
so MSBuild16 is net472

**Comment by tom-englert** [comment]
@SimonCropp since the current version of Fody is very stable and works fine with all versions of VS, the best way to keep this state would be to just not touch it - this would also heavily increase your hourly wage 😏

**Comment by SimonCropp** [comment]
> the current version of Fody is very stable and works fine with all versions of VS

And people can continue to use that version with VS 2017.

I think it is unreasonable for someone to a stance of 

> I want  to continue to use this old version of tool X, there for all other tools i use should be locked down to the constraints imposed by tool X

I my mind if people want to use older dev/tool sets then that is fine.  but, for tools that interact, they have to expect to be constrained to what is released in the same generation.

I also think it is an unfair restriction, on people developing fody addins, to be forced to target a runtime and sdk that is 4 years old. If i build a new dev machine today I would probably not even install net46 sdk.

**Comment by ramondeklein** [comment]
I can understand your issue and that you would like to move forward. For most professionals, VS2017 will be the default for next few months. If you switch to VS2019 only, then make sure you increment the major version and keep the VS2017 version available.

**Comment by SimonCropp** [comment]
@ramondeklein yep that is the plan

**Comment by tom-englert** [comment]
@SimonCropp since this is also a real breaking change for any addin, also the next major version of any addin using Fody 5.x should be bumped.

**Comment by ltrzesniewski** [comment]
I thought existing addins would still be compatible... What would cause an incompatibility there?

**Comment by ltrzesniewski** [comment]
Nevermind, I misunderstood what you were saying, sorry. Existing versions should probably still work but any version built against the next FodyPackaging will only be compatible with Fody v5.

**Comment by tom-englert** [comment]
Yes, and will only work on VS21019 - so this is not only a minor update.

**Comment by SimonCropp** [comment]
> the next major version of any addin using Fody 5.x should be bumped.

yep, agreed

**Comment by moh-hassan** [comment]
Till now CI appveyor and others still use vs 2017 and msbuild 15, even vs 2019 is not installed.
Ms still support [vs 2017](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.9.12) and release new fixes.

**Comment by SimonCropp** [comment]
@moh-hassan 

appveyor supports 2019 preview via `image: Visual Studio 2019 Preview`

MS may "support 2017" but they have already stopped back porting bug fixes to it.

Also i fail to see the point you are trying to make?

BYW to be using Fody [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue).

**Comment by mennodeij** [comment]
Thank you for breaking my solution. Now I need to downgrade Fody & all its dependencies 👎

**Comment by tom-englert** [comment]
@mennodeij if you are a sponsor, we can find a solution.

**Comment by mennodeij** [comment]
Unfortunately, I am not. My apologies for venting my frustrations, I know you cannot think of all use cases _a priori_

**Comment by SimonCropp** [comment]
@mennodeij what is blocking you from updating to VS 2019?

**Comment by mennodeij** [comment]
Our organisation uses VS2017.

**Comment by SimonCropp** [comment]
@mennodeij then what is blocking your organisation from updating to VS 2019?

**Comment by mennodeij** [comment]
It is in the works, but atm other more pressing concerns.

**Comment by mennodeij** [comment]
But I've settled on Fody 4.2.1 with VS2017 for now and everything is working again, so all good for the moment.

**Comment by qhq16** [comment]
> 但是我现在已经在VS2017上选择了Fody 4.2.1，并且一切都再次正常运行，所以暂时一切都很好。

Now, I use VS2015. Which version should I select?
