### ISSUE TITLE
Simplify symbol loading

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#687]
I found that the "WithNoPdb" test project actually did generate a pdb file, and there was no test verifying this. 
This was probably due to changes in the MSBuild project structure controlling the generation of debug symbols.
Now Fody itself relies on some special MSBuild keywords to determine the kind of symbols generated, which might also change in future, so eliminating this dependency seems to be an improvement.

The PR will: 
- Add some test that verifies correct loading of symbols
- Fix "WithNoPdb" project to build without symbols
- Simplify symbol loading in Fody to remove the dependency on the MSBuild variable.

**Comment by BrunoJuchli** [comment]
PR: #688
