### ISSUE TITLE
Problem generating manifest. Invalid assembly public key. (Exception from HRESULT: 0x8013141E)

### ISSUE THREAD

**Issue by Tejpalsb** [Fody/Fody#690]
after adding this nuGet to my c# desktop app while building project it shows,

Error		Problem generating manifest. Invalid assembly public key. (Exception from HRESULT: 0x8013141E)	MyMobileShopDesktopAppVS17		

installed version - 3.3.3
.Net framework 4.6.1

**Comment by SimonCropp** [comment]
Can u re read the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
