### ISSUE TITLE
Duplicate types

### ISSUE THREAD

**Issue by RayCarrot** [Fody/Fody#699]
Starting with version 4.0 there is an issue where Fody may inject a duplicate type, causing a System.BadImageFormatException. I have gotten this to appear with consistent results when using [this package](https://github.com/MarcStan/Resource.Embedder) which modifies the compiled program to include all resource assemblies.
The [developer of it suggested](https://github.com/MarcStan/Resource.Embedder/issues/13#issuecomment-482577829) adding a safeguard when [adding a type](https://github.com/Fody/Costura/blob/1b25844f04d674ca8070c3578a58456d180b4200/Costura.Fody/AssemblyLoaderImporter.cs#L59) if it already exists.
You can see more about the issue in this issue I opened with the developer when I thought his package was the cause of the error [here](https://github.com/MarcStan/Resource.Embedder/issues/13).

**Comment by tom-englert** [comment]
@RayCarrot Fody does not inject anything, it's only the platform for the addins. 
Every addin is responsible by it's own to not mess up the assembly.
