### ISSUE TITLE
guard against no MSBuildVersion

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#702]

**Comment by tom-englert** [comment]
@SimonCropp with older versions of VS you get this error:

```##[error]packages\Fody.5.0.2302\build\Fody.targets(38,12): Error MSB4186: Invalid static method invocation syntax: "[MSBuild]::IsOsPlatform(OSX)". Method '[MSBuild]::IsOsPlatform' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). 
```

**Comment by SimonCropp** [comment]
"older versions of VS "  what versions?

**Comment by SimonCropp** [comment]
@tom-englert i simplified it to checking `$(OS)`, and will remove when netcore incompat with VS on Mac is fixed
