### ISSUE TITLE
trying to support an old application that uses fody 1.29.4 and propertychangedfody 1.51.2

### ISSUE THREAD

**Issue by Nathan187** [Fody/Fody#703]
i'm trying to fix an old application that uses fody.  

for the longest time, we were able to apply fixes using xamarin/visual studio and mono runtime 4.8.1 

latest version of mac os (mojave) is killing us and there seems to be an issue using 4.8.1 (maybe 32 bit thing).   we want to upgrade fody to a version that works with  mono runtime 5.18.1.3 and pcl 4.5 profile 78.

is this possible?

**Comment by ltrzesniewski** [comment]
> there seems to be an issue using 4.8.1 (maybe 32 bit thing)

What are we supposed to do with such a description? You provided no details at all.

> is this possible?

I don't know, since you didn't tell what your issue is in the first place. Have you actually tried anything?

The issue template is there for a reason, please read it and follow the instructions.

**Comment by Nathan187** [comment]
sorry for the lack of detail lucas

the issue is, the application will not compile any longer.  before the mac was upgraded to mojave (macOS), it would compile in the past and we had to use mono runtime 4.8.1

if we use anything higher, the application will not compile and we get a very cryptic error relating to fody.  it had to do with compatibility of the pcl like, profile 78.  this app was dumped on me and i don't want to start ripping it apart if i don't have to.   i know it's a very old version.

i'll research the template and provide more information if necessary

**Comment by SimonCropp** [comment]
@Nathan187 your safest approach is to move back to the old OS version

**Comment by Nathan187** [comment]
will probably get yelled at or worse

i was able to actually fix the problem.  what i did was, i updated the fody packages (fody, asyncerrorhandling.fody, propertychanged.fody).  i also updated the latest version of xamarin forms for the pcl and ios projects.  changed to the monoruntime  5.18.1.3    did some cleaning (bin/obj folders), restarting visual studio and to my dang surprise...it actually compiles now and it actually still works.   (yes, I requested that this be rewritten)

thanks for the people who took time to respond
