### ISSUE TITLE
remove ncrunch file copy hack

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#705]
https://github.com/Fody/Fody/commit/e64fc1ddfa29c41c04e5e1bff6452942a12b9913

**Comment by ltrzesniewski** [comment]
@SimonCropp Why are you removing this? I need this thing... 😕

**Comment by SimonCropp** [comment]
I tested without the hack, on the current version of ncrunch, and it worked. Does it not work for you?

**Comment by ltrzesniewski** [comment]
This is only needed for the old project format with packages.config. The new format never required this.

**Comment by SimonCropp** [comment]
the problem is it breaks for packagerefereneces.

**Comment by SimonCropp** [comment]
https://stackoverflow.com/questions/55951942/ncrunch-build-fails-starting-with-fody-4-0-0-cannot-convert-transparent-pro

**Comment by ltrzesniewski** [comment]
That error message is... interesting.

Would you mind if we keep NCrunch support but tweak the condition to exclude the new project format?

```xml
<ItemGroup Condition="'$(NCrunch)' == '1' and '$(TargetFramework)' == '' and '$(TargetFrameworks)' == ''">
```

**Comment by SimonCropp** [comment]
yep that looks good. gimme 10

**Comment by ltrzesniewski** [comment]
Thanks! 😄

**Comment by SimonCropp** [comment]
5.0.6 pushed to nuget. nuget will take 10-15min. if u can verify, then i will create an issue+milestone

sorry for the hassle

**Comment by ltrzesniewski** [comment]
Oh crap, I just tested 5.0.5 and 5.0.6 and I'm really sorry, but it looks like they've finally fixed the issue in NCrunch. Both versions work fine on the old project format.

I found the following NCrunch config option ([docs here](https://www.ncrunch.net/documentation/reference_project-configuration_autodetect-nuget-build-dependencies)):

![image](https://user-images.githubusercontent.com/7913492/57178164-dde7f380-6e6c-11e9-904a-ad9ac1f4f581.png)

It defaults to true and solves the problem altogether. I'm sorry I made you revert this change without testing first - I just assumed the issue was still present in NCrunch.

Now the only difference is that 5.0.6 works fine if you disable this option, while 5.0.5 fails, but I don't think that's a compelling reason to leave the hack in Fody.

**Comment by SimonCropp** [comment]
no reason to apologize. i will remove the hack again and deploy again

**Comment by ltrzesniewski** [comment]
You don't need to bother redeploying just for this IMO. If you want to, you could delist 5.0.6 on NuGet.

**Comment by SimonCropp** [comment]
good point. done

**Comment by ltrzesniewski** [comment]
FYI, it seems that _"Auto-Detect NuGet Build Dependencies"_ is not a new NCrunch option after all (I just never noticed it before), but it doesn't work properly if you override the `repositoryPath` setting in a nuget.config file. In this situation, v5.0.5 fails.

I've reported the issue to NCrunch [here](https://forum.ncrunch.net/yaf_postst2726_-Auto-Detect-NuGet-Build-Dependencies--fails-when-repositoryPath-is-overridden-in-nuget-config.aspx).

**Comment by SimonCropp** [comment]
Thanks for following up. Is this something there should be a doco page about?

**Comment by ltrzesniewski** [comment]
I don't think so, it's a niche issue apparently. Either they fix the auto-detect feature in NCrunch and we're done, or we restore the (fixed) hack.

**Comment by ltrzesniewski** [comment]
Given that it seems it won't be a straightforward change in NCrunch, would you mind if I re-introduce the fixed hack so it's available in the next version? No need to release a new version for this though, or just re-list 5.0.6 if you like.

**Comment by SimonCropp** [comment]
> Given that it seems it won't be a straightforward change in NCrunch

not sure what you mean by this? for me it worked OOTB with the current version of ncrunch

**Comment by ltrzesniewski** [comment]
It doesn't work if you meet all of the following conditions:

 - You're weaving a project in the old format
 - You have a custom `repositoryPath` setting in nuget.config

All other cases work fine OOTB.

**Comment by SimonCropp** [comment]
How long do you propose keeping the hack?

**Comment by ltrzesniewski** [comment]
Well, if it doesn't cause problems I'd ideally keep it until NCrunch fixes the issue.

The conditions mentioned earlier arise if you have multiple dependent old-style projects in the same repo. The `repositoryPath` setting is needed to make NuGet updates work properly if a single project is used in multiple solutions from distinct directories. Also, some kinds of projects (WPF for instance) can't be updated to the new format just yet.
