### ISSUE TITLE
VS2017 nuget Fody installation unable to compile? 

### ISSUE THREAD

**Issue by 253513374** [Fody/Fody#710]
Fody is only supported on MSBuild 16 and above. Current version: 15.	Weitedianlan.WinUI

**Comment by SimonCropp** [comment]
use VS 2019

**Comment by copa017** [comment]
I am also restricted currently to the existing VS2017 Pro (...and cannot use Community Editions).
Isn't there any setting missing in e.g. fody manifest to avoid update notifications on VS2017 that are useless?
