### ISSUE TITLE
Fody:no weavers found for the configuration entire costure

### ISSUE THREAD

**Issue by moanhawks** [Fody/Fody#721]
![IMG_20190717_013157](https://user-images.githubusercontent.com/52075701/61316085-cc3ea700-a832-11e9-8e0e-3ad4b6158f16.jpg)
Can someone help me about this and what kind of that bug?

**Comment by SimonCropp** [comment]
Did you read the issue template?

**Comment by tom-englert** [comment]
@moanhawks what's unclear about this message? You have added Costura to the configuration, but not installed the NuGet package.

**Comment by SimonCropp** [comment]
@moanhawks so @tom-englert is correct. you are missing the add nuget step as defined in the readme https://github.com/Fody/Costura/#nuget-installation
