### ISSUE TITLE
Target framework of a weaver cannot be netstandard20

### ISSUE THREAD

**Issue by AlanHauge-Interacoustics** [Fody/Fody#730]
## Summary
I found a small (annoying) issue with FodyPackaging.
If the target framework of the weaver is netstandard20 (not netstandard2.0), the weaver cannot be found.

## Reproduce
Change SampleWeaver.Fody.csproj to:
    <TargetFramework>netstandard20</TargetFramework>

## Solution
Accept both netstandard20 and netstandard2.0 as weaver 'targets'
Pull request : #731

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by tom-englert** [comment]
`netstandard20` is not the official notation: https://docs.microsoft.com/en-us/dotnet/standard/frameworks
Why should we need to support this?

**Comment by AlanHauge-Interacoustics** [comment]
It was just an annoying little thing, where there was no help to resolve the issue.
