### ISSUE TITLE
update to cecil 12da1bf

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Fody#734]
update to Cecil 12da1bf7e0e10278e05eeb23adfc72760bbb6668  https://github.com/jbevain/cecil/commit/12da1bf7e0e10278e05eeb23adfc72760bbb6668

Examples of updates to the new Cecil API

 * https://github.com/Fody/Janitor/commit/50f080d0f84c5fe8b93134dde4b70f3873d486e4
 * https://github.com/Fody/Validar/commit/48cb3442e6b06cfbd08d0313904388a3eac3a0cf
 * https://github.com/Fody/Janitor/commit/50f080d0f84c5fe8b93134dde4b70f3873d486e4

**Comment by SimonCropp** [comment]
@tom-englert @ltrzesniewski so this will be a breaking change because of https://github.com/jbevain/cecil/commit/f9751dee3117b17b17884b349fbc0a91cfffa1c8 and require all downstream nugets to update :(

**Comment by ltrzesniewski** [comment]
Well OK, it's a necessary change anyway.
But shouldn't we wait for Cecil v0.11? Maybe @jbevain wants to add other breaking changes before releasing it.

**Comment by SimonCropp** [comment]
I looked into it a bit more. I think only downstreams  that use that api need to update.

**Comment by SimonCropp** [comment]
@jbevain do u have an eta for the next release? Would me doing a smoke test on all my downstream repos help?

**Comment by tom-englert** [comment]
@SimonCropp 0ece1bc looks really good :+1: - not forcing unnecessary updates, but letting it up to the user to stay with an old weaver if it works well and maybe no update is available yet. 

(I guess none of the existing weavers will run into real problems)

**Comment by SimonCropp** [comment]
> I guess none of the existing weavers will run into real problems

of the subset of weavers that are executed in the samples solution, the following fail

 * InlineIL
 * Substitute
 * WeakEventHandler

**Comment by SimonCropp** [comment]
and Validar

**Comment by ltrzesniewski** [comment]
Yeah I guessed InlineIL would fail, and not for a very good reason: there's a bit of code which visits the whole Cecil object graph and makes sure there's no reference left to an InlineIL type before removing the reference to its assembly. It's not exactly necessary, it's just a little nice to have additional check.

I'll update the lib once Fody v6 is available.

**Comment by SimonCropp** [comment]
I pushed a beta of version 6

**Comment by ltrzesniewski** [comment]
I pushed InlineIL v1.2.1 which is compatible with Fody v4 to v6 (it just skips the problematic check). I'll publish a v6-specific version later on.

**Comment by SimonCropp** [comment]
@tom-englert need help updating WeakEventHandler?

**Comment by SimonCropp** [comment]
@tom-englert also substitute needs an update

**Comment by tom-englert** [comment]
@SimonCropp I'm on it, I fixed the root cause, but now some tests are failing due to framework changes. I'll sort this out probably next weekend.

BTW, theoretically it's possible that this affects even more weavers, and we do not see it because the sample code does not contain generic classes...
