### ISSUE TITLE
Fody fails to weave from a library project

### ISSUE THREAD

**Issue by SirDragonClaw** [Fody/Fody#736]
**The issue**

When I create a simple Method Intercepter using Fody 6.0.0 and MethodDecorator.Fody 1.1.0 in a library it fails to weave projects using that library.

I can get the simple method interceptor working, but when I move my interceptor to be a part of the library that I want it to live in (for reusability) it just stops weaving with no error message or warning.

**Minimal Repro**

[FodyWeavingFailure.zip](https://github.com/Fody/Fody/files/3557918/FodyWeavingFailure.zip)

**The issue can also be seen here**
https://stackoverflow.com/questions/57684899/why-does-fody-weaving-fail-to-weave-other-projects

**Any help would be appreciated.**

**Comment by SimonCropp** [comment]
i think perhaps you are missing a 
```
[module: InterceptorFromLib]
```
in the FodyTest project?
