### ISSUE TITLE
[Feature proposal] Async-ready AOP

### ISSUE THREAD

**Issue by ndrwrbgs** [Fody/Fody#742]
_Removing default text, replacing with my replies_
Actual request isn't for a change in Fody itself, but for a new official plugin.

#### You should already be a Patron

I am :)

#### Guidance

I am not certain the feature will be accepted, the purpose of proposal is I know I don't (yet) have the expertise to raise the PR.

#### Is the proposal related to a problem

Not really, it's more of a new feature than a 'problem'

#### Describe the solution

Fody is super powerful, and _just almost_ gives us the ability to have proper AOP in C#. However, two libraries that try to do generic wrapping have some edge cases on `async` methods that are missed. It's a big ask, but I'm wondering if @SimonCropp might have the background knowledge about the IL generated for `async` methods to offer a full AOP async-ready solution.

Here are the projects that get super close, but the related issues in each:
- https://github.com/vescon/MethodBoundaryAspect.Fody
    - https://github.com/vescon/MethodBoundaryAspect.Fody/issues/5
- https://github.com/csnemes/tracer
    - https://github.com/csnemes/tracer/issues/81
    - https://github.com/csnemes/tracer/issues/88

**Comment by ltrzesniewski** [comment]
The way I see it, it's not something Fody itself can provide. Fody loads an assembly after compilation and executes its addins on the compilation result. Its job is to take care of the MSBuild integration, and all of the assembly modifications are actually made by the addins. Fody only provides [a very small library](https://github.com/Fody/Fody/tree/master/FodyHelpers) to its addins that mostly deals with integration with Fody.

So I may have misinterpreted what you mean by *"full AOP async-ready solution"*, but it looks like what you're really asking here is for the addins to fix their issues with async methods. If you think Fody should provide something to help them with that, what should it look like?

**Comment by ndrwrbgs** [comment]
> Actual request isn't for a change in Fody itself, but for a new official plugin

:)

**Comment by SimonCropp** [comment]
What exactly do you mean by “official plugin”?

**Comment by ndrwrbgs** [comment]
I was thinking like these:
- https://github.com/Fody/Caseless
- https://github.com/Fody/EmptyConstructor
- https://github.com/Fody/ConfigureAwait
- https://github.com/Fody/Equals

It's quite possible that the open questions on the other projects aren't something anyone here has particular know-how about either (in which case definitely close this :smile:), but I thought I'd reach out since I believe no one is actively looking at the others, to see if maybe the expertise to handle async methods existed around here.

The existing problem is that no one involved with these two weavers seems to have intricate knowledge about how the async state machine works. I gandered that perhaps someone playing at the level of IL already might have a bit more context.

**Comment by ndrwrbgs** [comment]
Upon looking for the 'official' plugins I did just stumble across https://github.com/Fody/MethodDecorator, which seems to be trying to do the same thing. I'll make a test with that and see what it does on async methods.

**Comment by ndrwrbgs** [comment]
Looks like that decorator has these items:
- Does not allow for manipulation of return values
- OnEntry is called before the state machine has loaded the LogicalCallContext (similar to the `tracer` addin)
- Since we can't modify the return values, the OnTaskContinuation doesn't allow us to mark exceptions observed, though it does allow us to observe the true end of the method which is nice!

I think that this decorator, similar to the `tracer` decorator, would work for the goals of AsyncLocal-enabled tracing, but to support things like a generic [Cache] for methods or [CircuitBreaker], etc like I'd like to see enabled in C#, we'd have to be able to modify the results of the calls like in the `MethodBoundaryAspect` addin.

To context-set for where I'm coming from, I stumbled upon Fody while looking for AOP in C#, and would _like_ if we were enabled in the language to just compose various elements. Something akin to
```C#
[CircuitBreaker(seconds: 20, failureRate: 80)]
[LogMethod]
[TraceMethod]
[LatencyMetric("someName")]
[Retry(attempts: 3, strategy: ExpBackOff)]
[OnException(OnExceptionStrat.Swallow)]
GetEmail() {
  return await WebClient.DownloadString(yadda);
}
```

to have 1 line to represent such various concerns rather than embedding them (or resulting in very Action-oriented-programming).

ActionOP way:
```C#
GetEmail() {
  OnException.Run(
    OnExceptionStrat.Swallow,
    () => Retry.Run(3, ExpBackOff, 
      () => LatencyMetric.Run(....
  return await WebClient.DownloadString(yadda);
}
```

In my experience this later way, which _can_ accomplish the same thing, gets a lot of resistance from C# developers.

**Comment by SimonCropp** [comment]
@ndrwrbgs i am not really how to proceed here. Fody explicitly does not perform AOP. It instead enables other weavers to manipulate assemblies. If any of those weavers chose to implement full async AOP, then they can do so. As you have noted some weavers get close to what you want. I personally dont have the capacity to do the kind of work you are asking for. i already maintain 100+ projects https://www.nuget.org/profiles/simoncropp. If you want to take on this task then go for it.

**Comment by SimonCropp** [comment]
ok going to close this one for now. if anyone needs specific help on making any of the existing addins more async friendly, or reviews of new addins, please ping me

**Comment by ndrwrbgs** [comment]
Thanks @SimonCropp, the request was mainly at those 100+ other projects (some of which could end up relying on this common substrate) but @csnemes over at https://github.com/csnemes/tracer ended up resolving the issues with async in a way that allows their "tracer" to be used for just about any AOP, :clap: thanks csnemes!

Issue can be closed until you personally think there's too many distinct parties trying to implement the same thing, and feel the "source" should offer it. Until such critical mass I agree there's no point in randomizing your efforts

**Comment by SimonCropp** [comment]
@ndrwrbgs what do you see a a first step that is a critical feature all addins could use when manipulating async code??

**Comment by ndrwrbgs** [comment]
Hard for me to make sure I'm thinking of the steps small enough for 'critical' not to scope creep, please let me know if this is too grandiose. I do just want to clarify that I imagine the below _not_ really part of `Fody` but as a first-level abstract library - not everyone manipulating IL needs to weave into the async state machine but I do think that opening that capability first-class could lead to some interesting community projects. Ideally we could abstract out what was done in `tracer` and just boost the signal for anyone doing enter/exit method modifications.

#### Critical steps:
I think weaving into the START of an async method ends up not being too difficult, the thing I worry most about folks having to reinvent (and hitting the same gotchas we were hitting) would be capturing the exit (since the state machine exits multiple times).
- [ ] Weaving to intercept 'exit' events of async methods

A nice secondary would be to wrap the Start too though, since there are gotchas there around ExecutionContext too.
- [ ] Weaving to intercept 'enter' events of async methods (requires allowing some of the state machine entry to execute first)

#### Alt
An alternative approach may be for me to try to extract out commonality between MethodBoundaryAspect and tracer, and try to get each of those project owners to accept a PR refactoring to rely on a common base library.

I'll presume that's on me going forward, and hope to find time to take it up before it's moot :-P

**Comment by tom-englert** [comment]
@ndrwrbgs a common place for shared code could be e.g. this:
https://github.com/tom-englert/FodyTools
| use this to share code for my weavers
