### ISSUE TITLE
Fody 6.0.4 contains FodyCommon.dll twice

### ISSUE THREAD

**Issue by pchinery** [Fody/Fody#763]
The nuget file of Fody 6.0.4 contains the File FodyCommon.dll twice in the folders netclassictask and netstandardtask.

This can be observed easily:
* Download the package from https://www.nuget.org/api/v2/package/Fody/6.0.4
* Open the file with a preferred ZIP tool (maybe rename it first)

You can now see, that the file FodyCommon.dll is contained twice in each folder.

At least when using Paket, this results in this error when using the package:

> Message: The file "C:\Users\XXXXX\\.nuget\packages\fody\6.0.4\netclassictask\FodyCommon.dll" already exists.

I have not been able to dig into the build scripts sufficiently to try to find the root cause. I have the impression though, that these two lines in the Fody.nuspec could cause this:

```
<file src=".\bin\$configuration$\net472\Fody*.dll" target="netclassictask" />
<file src="..\FodyIsolated\bin\$configuration$\net472\Fody*.dll" target="netclassictask" />
```

Against the statement in the template, I have created this issue anyway to make the error retrievable in search engines.

As a workaround, 6.0.3 does not have this behaviour.

**Comment by ltrzesniewski** [comment]
Oh wow, that's a weird bug, thanks for reporting it!

**Comment by pchinery** [comment]
Wow, that was quick, thank you very much!

**Comment by SimonCropp** [comment]
almost. forgot one file

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by SimonCropp** [comment]
@pchinery can u smoke test once nuget does its thing

**Comment by pchinery** [comment]
I have just updated the package and can confirm that the problem is gone. Thank you very much for the quick response

**Comment by SimonCropp** [comment]
@pchinery u caught when i had the solution on :)

BTW Fody relies on community funding to stay viable https://github.com/Fody/Home/#community-backed
