### ISSUE TITLE
Enable sponsorship for Fody

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#764]
Fody is supported on open collective. My suggestion is to enable sponsorship on the organizational level. Then we need to enable this *per repository* as well.

I tried doing this for Costura, but noticed the open collective for Fody organization is incorrect:

![image](https://user-images.githubusercontent.com/1246444/68782598-f3b74c00-0639-11ea-8a05-ac4ad3b677e0.png)

My suggestion is to lead people to opencollective.com/fody instead

**Comment by SimonCropp** [comment]
good point. done
