### ISSUE TITLE
How can I add a property that can be accessed from code (IntelliSense)?

### ISSUE THREAD

**Issue by Cyl18** [Fody/Fody#773]

**Comment by ltrzesniewski** [comment]
Your question is unclear.

**Comment by Cyl18** [comment]
I want to inject a property, eg

Code: 
```
[SomeAttrib]
public class A
{
      public void Foo() { obj.XXX(); }
}
```

After:
```
[SomeAttrib]
public class A
{
      public SomeType obj { get { some code injected } }
      public void Foo() { obj.XXX(); }
}
```

In another way, I want to access the `obj` property without actually writing it
(Sorry for my bad English)

**Comment by ltrzesniewski** [comment]
Unfortunately, that won't be possible using Fody, as it can only inject code *after* compilation, so the original code needs to be able to compile in the first place.

You may try to find a workaround, like providing an API which would get rewritten:

```C#
public void Foo() { YourWeaver.Property<SomeType>("obj").XXX(); }
```

Or use a different tool than Fody (like a code generator such as T4). It really depends on what you're trying to do.

**Comment by Cyl18** [comment]
> Unfortunately, that won't be possible using Fody, as it can only inject code _after_ compilation, so the original code needs to be able to compile in the first place.
> 
> You may try to find a workaround, like providing an API which would get rewritten:
> 
> ```cs
> public void Foo() { YourWeaver.Property<SomeType>("obj").XXX(); }
> ```
> 
> Or use a different tool than Fody (like a code generator such as T4). It really depends on what you're trying to do.

Thank you.
I wanna do such a thing like what Java APT does (e.g. ButterKnife). Do you have any way to do that?

**Comment by ltrzesniewski** [comment]
I'm not familiar with Java APT, so I can't really say much about it.

But looking at the ButterKnife examples maybe you could do something similar, like write the property yourself but annotate it for weaving:

```C#
[DoSomeMagic]
public SomeType obj => default;
```

**Comment by Cyl18** [comment]
Thank you so much!

**Comment by Cyl18** [comment]
> I'm not familiar with Java APT, so I can't really say much about it.
> 
> But looking at the ButterKnife examples maybe you could do something similar, like write the property yourself but annotate it for weaving:
> 
> ```cs
> [DoSomeMagic]
> public SomeType obj => default;
> ```
> 
> (the weaver would change the property implementation if `DoSomeMagicAttribute` is applied)

Btw, do you know any way that I can avoid to write the `obj` but access it from code?

**Comment by tom-englert** [comment]
Maybe have a look at https://github.com/AArnott/CodeGeneration.Roslyn

**Comment by Cyl18** [comment]
@tom-englert thank you
