### ISSUE TITLE
FodyHelpers.props DebugType problem for crossplatform

### ISSUE THREAD

**Issue by Simba-Mupfunya** [Fody/Fody#774]
Hello 

Please note that the change done in March replacing DebugType Portable as recommended by Microsoft to Embedded is causing breakpoints in cross-platform builds in Xamarin Android and iOS not to hit when referencing libraries that depend on Fody.
<DebugType>portable</DebugType> * Supported
<DebugType>embedded</DebugType> * Not supported

**Comment by SimonCropp** [comment]
i assume you are using https://www.nuget.org/packages/Realm.Fody/

if so that package incorrectly has a dependency on Fody helpers. this is not a bug in fody

**Comment by Simba-Mupfunya** [comment]
Hi Simon, yes and i assume you figured it out based on the discussion at microsoft visual studio support :-) you are the same Simon Crops. I open the issue at the relevent package
