### ISSUE TITLE
 How does Fody support dllimport?

### ISSUE THREAD

**Issue by SuperDcer** [Fody/Fody#786]
As the title, I have a DLL that I need to call using dllimport, But I don't know how to do it. 
Can anyone give me any advice? Thanks a lot

**Comment by SimonCropp** [comment]
i don’t understand the question. fody is an IL manipulation tool. how is that related to dllimport?

**Comment by SuperDcer** [comment]
> i don’t understand the question. fody is an IL manipulation tool. how is that related to dllimport?

Thank you for your reply, SimonCropp. Dllimport will try to find the target DLL from the EXE running directory, but when using fody, the target DLL is packed into exe, so dllimport can't find the target DLL

**Comment by SimonCropp** [comment]
I think you have conflated Fody with Costura (https://github.com/Fody/Costura). Perhaps raise an issue over there. BTW you should be a paying patron to use Fody or Costura https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md
If that doesnt work for you then you should not use either
