### ISSUE TITLE
Fody and LARGEADDRESSAWARE 

### ISSUE THREAD

**Issue by xobxcj** [Fody/Fody#793]
Hi !

I found an issue using Fody 4.2.1 : 
By default, compiling VS 2017 on "Any CPU" with "Prefer 32-bit" will enable the flag LARGEADDRESSAWARE on the binary. 
The flag enable using 4Go of RAM when we're on a 32 bit environnement.
We can check the flag using the command : `dumpbin.exe App.exe /headers`

When using Fody, this flag is disabled for some reason.
I try to find some explanation but didn't find anything so far. 

Is there a way to keep Fody enabled without losing this flag ?

Thanks
Mathieu

**Comment by SimonCropp** [comment]
does it happen in the current version of fody

**Comment by xobxcj** [comment]
I just tried and the problem is still there

**Comment by SimonCropp** [comment]
this is a know issue in cecil https://github.com/jbevain/cecil/issues/620. the issue will be resolved in Fody when it is fixed in the upstream cecil

**Comment by xobxcj** [comment]
ok, thanks for your help @SimonCropp
