### ISSUE TITLE
Add FodyWeavers.xml to the project on nuget install (if not present)

### ISSUE THREAD

**Issue by ndrwrbgs** [Fody/Fody#799]
#### Guidance

If you are certain the feature will be accepted, it is better to raise a [PR](https://help.github.com/articles/about-pull-requests/).

If you are uncertain if the feature will be accepted, outline the proposal to confirm it is viable.

Even if the feature is a good idea and viable, it may not be accepted since the ongoing effort in maintaining the feature may outweigh the benefit it delivers.

#### Is the proposal related to a problem

Not a problem, but an experience optimization for project onboarding.

#### Describe the solution

I _believe_ nuget allows for running scripts during nuget install in tools like Visual Studio. In the case that there is no FodyWeavers, we could auto add it.

**Comment by SimonCropp** [comment]
> believe nuget allows for running scripts during nuget install in tools like Visual Studio

this feature was removed in recent versions of vs

**Comment by ndrwrbgs** [comment]
😢

**Comment by ndrwrbgs** [comment]
https://blogit.create.pt/gustavobrito/2018/01/12/how-to-add-your-custom-content-files-into-a-nuget-package-for-visual-studio/

Is it possible to use the built-in file support instead of a script? Or is this reference also too old?

**Comment by tom-englert** [comment]
@ndrwrbgs `FodyWeavers.xml` is created after the first build, so it already contains configuration for all installed weavers.
However if you are using the old project format, and want to have it part of the project, you have to add it manually.

**Comment by ndrwrbgs** [comment]
explains my confusion now :) Silly me, being on old technology 😇
