### ISSUE TITLE
Not compatible with Source Link and non-portable PDB

### ISSUE THREAD

**Issue by MTantos1** [Fody/Fody#811]
#### You should already be a Patron
Disclaimer: I am not a patron.

#### Describe the issue
When using Fody, and [Source Link](https://github.com/dotnet/sourcelink) in a project targeting .NET framework (have tried 4.7.1 and 4.8) and set to output debugging information `Full` or `Pdb-only` the source link data is lost from the PDB stream. This issue doesn't occur if debugging information is set to `Portable`.

Tested with Fody 6.1.0, and weaver [Catel.Fody 4.3.0](https://github.com/Catel/Catel.Fody)

This issue has been raised on Source Link repo and the final response [#579 Comment](https://github.com/dotnet/sourcelink/issues/579#issuecomment-589451472) was to follow up here.

#### Minimal Repro
Can submit later if required.

**Comment by SimonCropp** [comment]
i just deployed 6.1.1. in this release fody defaults to the symbol loading behavior of cecil. so if you still have problems with 6.1.1 you need to raise an issue in the cecil project
