### ISSUE TITLE
Guard class doesn't have a namespace and it causes conflict 

### ISSUE THREAD

**Issue by giokh** [Fody/Fody#822]
Hello
Guard class (in FodyHelpers) doesnt have a namespace.
If any project contains a class with this name, there is a conflict on build. 
Please add a namespace for the class.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by giokh** [comment]
> To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

Actualy I have already made a pull request about this.
Please take a look. 
Writing classes without a namespace is not a good practice.

**Comment by SimonCropp** [comment]
yep i will get to deploying that this weekend. although i am surprised a fody weaver would have a type conflict for that name, given weavers dont have a public api

can you point me to the codebase containing the weaver so i can have a look at the scenario

**Comment by SimonCropp** [comment]
> can you point me to the codebase containing the weaver so i can have a look at the scenario

bump
