### ISSUE TITLE
'Application' is a namespace but is used like a type

### ISSUE THREAD

**Issue by dalton5** [Fody/Fody#824]
Hi,

I use Xamarin Forms application and I have an other project core with my models.

On my project with my models I install Fody and fody property changed

But every time I install Fody and Fody property changed I have a conflict with Application in my xamarin forms.

I have the error 'Application' is a namespace but is used like a type

Do you know where can come this conflict?

Thanks,

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
