### ISSUE TITLE
Documentation about debugging weavers

### ISSUE THREAD

**Issue by krk** [Fody/Fody#84]
Using fody from nuget, how can we debug weavers?

**Comment by ghuntley** [comment]
Here's how you do it https://ghuntley.com/archive/2016/01/07/debugging-a-fody-weaver-plugin-and-or-debugging-msbuild/

**Comment by Logerfo** [comment]
@ghuntley link's broken. Here's the working one: https://ghuntley.com/blog/debugging-a-fody-weaver-plugin-and-or-debugging-msbuild
