### ISSUE TITLE
MSBuild hangs forever when Fody writes assembly

### ISSUE THREAD

**Issue by bhattvishal** [Fody/Fody#847]
In my solution many project make use of Fody to inject the PropertyChanged weaver. Unfortunately at the end of the build, when Fody starts writing the final assembly, the process hangs and cannot be recovered.

See the StackOverflow link for more details https://stackoverflow.com/questions/59603131/msbuild-hangs-forever-when-fody-writes-assembly 

This is happening with all the team members (~6) in our team. Here's the development environment that we have.

- Windows 10 Enterprise
- Visual Studio 2017/2019
- Fody v2.1.2, PropertyChanged.Fody v2.1.3 (This is the issue the latest version of Fody as Well)

**Comment by SimonCropp** [comment]
as per the [issue template](https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

 * all 6 of your team should become patrons
 * update to the current stable of fody and PropertyChanged.Fody
 * share a repro that uses those versions
