### ISSUE TITLE
Enable configuring weavers via msbuild

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#873]
Allow to provide the FodyWeavers.xml via MSBuild variable.
See #842, https://github.com/Fody/Home/pull/187

**Comment by ltrzesniewski** [comment]
I'd say the two new features deserve a 6.2 version (unless 6.1.3 is already released)

**Comment by tom-englert** [comment]
OK, it's not pushed to nuget yet, so I can still remove  the 6.1.3
