### ISSUE TITLE
Test runner issues with ReSharper/Rider 2020.2 EAP6+

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/Fody#894]
ReSharper/Rider 2020.2 EAP6 introduced a change in the test runner which breaks the tests that use `ExecuteTestRun` on .NET Core.  

The new runner loads the tested assemblies in a separate `AssemblyLoadContext` (*not* the default one). The call to `Assembly.Load(byte[])` in `ExecuteTestRun` creates its own `AssemblyLoadContext` to load the assembly, which means its dependencies are no longer resolved correctly, as they are *not* loaded in the default context by the new runner version anymore.

Read more details in [the issue I reported to JetBrains](https://youtrack.jetbrains.com/issue/RSRP-480369).

There will be a new *emulate dotnet vstest resolve* option in EAP8 which should fix this, but it will be disabled by default. I'll wait for EAP8 to ship and then fix this in Fody so we can get the correct behavior by default.

**Comment by SimonCropp** [comment]
nice catch

**Comment by SimonCropp** [comment]
could it be related to this https://youtrack.jetbrains.com/issue/RSRP-480565

**Comment by ltrzesniewski** [comment]
If I understand their test runner change correctly, then yes, that *seems* related, although I'd have expected this to break in EAP6 as well.

**Comment by ltrzesniewski** [comment]
Ok, so I tested EAP 8 with InlineIL.Fody:

 - All tests pass when the _"Emulate dotnet test resolve behavior"_ option is enabled
 - `ExecuteTestRun` fails to load dependencies when that option is disabled

I wrote a quick and dirty fix [here](https://github.com/ltrzesniewski/InlineIL.Fody/commit/0079029012f7e4711172e6ed78c85eaaf89142f6) - it makes all tests pass when the option is disabled. It loads the weaved assembly into its own assembly load context, which then defers to the ALC in which Fody is loaded to load any additional dependencies.

Given that the R# test runner is still being actively worked on, I think I'll keep this fix aside for now, and apply it when 2020.2 is released after checking on a few other weavers to make sure it works everywhere.

**Comment by ltrzesniewski** [comment]
I realized that my fix would require adding a .NET Core target to the FodyHelpers project in order to access `AssemblyLoadContext`... I tested a few other things but I can't really get anything to work without having access to the ALC. 😕 

We could work-around this by adding the following to the `.sln.DotSettings` file of each weaver solution:

```XML
<s:Boolean x:Key="/Default/Housekeeping/UnitTestingMru/UnitTestRunner/EmulateDotnetTest/@EntryValue">True</s:Boolean>
```

But that would be less clean than a real ALC fix, and would require changes to each weaver solution, so I think that adding a .NET Core target to the FodyHelpers project is a better solution.

**Comment by SimonCropp** [comment]
> NET Core target to the FodyHelpers

I think that should be fine.

**Comment by ltrzesniewski** [comment]
They [reverted the load context change](https://youtrack.jetbrains.com/issue/RSRP-480731#focus=Comments-27-4330313.0-0) for the next version, so I suppose there's no point in changing `ExecuteTestRun` anymore.

I'll still keep this open until 2020.2 is released, and if everything works fine I'll just close this issue.

**Comment by ltrzesniewski** [comment]
I tested 2020.2 final: the _"Emulate dotnet test resolve behavior"_ setting is still present but it's now turned on by default, and the tests run fine.

However, given that the setting is still present and that the tests fail when you turn it off, I'm not sure what to do. Should we include the fix or not? What do you think?

**Comment by SimonCropp** [comment]
are there any drawbacks of the fix?

**Comment by ltrzesniewski** [comment]
I'd say the main drawbacks are the additional target in FodyHelpers and the slightly increased code complexity.
