### ISSUE TITLE
XamarinStudio build error: Could not find a weaver...

### ISSUE THREAD

**Issue by yallie** [Fody/Fody#90]
Looks like Fody doesn't support XamarinStudio out of the box.
XamarinStudio uses MSBuild behind the scenes. I have a project 
that builds OK with MSBuild, but under XamarinStudio Fody complains:

Could not find a weaver named 'PropertyChanged'. 
If you have nuget package restore turned on you probably need to do a build to download the weavers....

[Zipped project](http://www.sharp-shooter.ru/misc/bugreports/FodyTest.zip)

Seems like XamarinStudio runs MSBuild in an unusual way.
Maybe wrong startup directory or enviroment variables, I'm not sure.

Is there a way to configure Fody where to look for the weaver assemblies?
Is it possible to use Fody task without any Nuget packages installed?
I was unable to find anything about it in the documentation wiki.

Thanks!

**Comment by xleon** [comment]
Another solution is to add a file "Directory.Build.props" to the root solution folder with the following content: 

```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup Label="BasePath">
    <SolutionDir Condition="'$(SolutionDir)'==''">$(MSBuildThisFileDirectory)</SolutionDir>
  </PropertyGroup>
</Project>
```

**Comment by SimonCropp** [comment]
@asarapas @xleon  my understanding is that workaround should no longer be required. can one of you share a repro?

**Comment by xleon** [comment]
@SimonCropp what version is supposed to fix it? 
I can try upgrading and removing Directory.Build.props to see if it works

**Comment by SimonCropp** [comment]
not sure but here is the sln dir finding logic https://github.com/Fody/Fody/blob/master/Fody/SolutionDirectoryFinder.cs

**Comment by SimonCropp** [comment]
@asarapas @xleon btw there have been some changes in the usage requirements of Fody https://github.com/Fody/Fody#licensingpatron-faq
