### ISSUE TITLE
Fody: No weavers found for the configuration entries MethodDecorator. Add the desired weavers via their nuget package.		

### ISSUE THREAD

**Issue by qhq16** [Fody/Fody#914]
I have installed fody 4.2.1 and MethodDecorator.Fody.VS2015 0.9.0.7 with VS2015.
It call this error.  I want to know which version should I install with VS2015.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SirDragonClaw** [comment]
I'm getting the same issue as OP
