### ISSUE TITLE
(.NET Core) Fody fails without error/warning when added and used as a transitive/indirect reference

### ISSUE THREAD

**Issue by MGRussell** [Fody/Fody#917]
Reproduction:

1) Create a .NET Core project and add a reference to a Fody package. I tested this using ReactiveUI.Fody and PropertyChanged.Fody to ensure this was not a weaver specific issue.

2) Add another .NET Core project that references the first project, but does not directly reference Fody.

3) Use the Fody attributes in the second project.

---

Everything will compile and run fine, but the weavers will not function in the second project.

**Comment by ltrzesniewski** [comment]
That's basically the intended behavior: Fody does not process the projects transitively, as you'd need to explicitly disable it in all referencing projects otherwise if you only want it in a single project for instance.

**Comment by MGRussell** [comment]
That does make sense, however it can lead to very peculiar behavior when assuming the transitive reference will function. Perhaps a clean solution would be to base its behavior based on the presence or absence of a FodyWeavers.xml file?

**Comment by tom-englert** [comment]
The problem here is that the assembly containing the attributes is just passive, it has no functionality at all.
Since the weaver itselve is not executed on the second project, it can't complain about anything...

Does this still happen if you include the weaver with `PrivateAssets="all"`?

**Comment by MGRussell** [comment]
Setting `PrivateAssets="all"` does work and provides clear determinism. Now the project which was using the transitive references fails to compile which forces a direct reference to the package. Only downside is that being able to use transitive reference is really handy in some scenarios, but this should at least remove any unexpected behavior from the packages.

**Comment by ltrzesniewski** [comment]
I wonder if we should provide some way to suppress transitive references for weavers which set `ShouldCleanReference` to true, but it would probably end up being a hack, as there's no built-in way to specify you want `PrivateAssets="all"` by default in NuGet.

**Comment by tom-englert** [comment]
That's why we added the warning, so at least you can see you should fix it.

**Comment by ltrzesniewski** [comment]
Oh, right! I forgot about that 😉

**Comment by SimonCropp** [comment]
i dont think there is a way forward on this one. propose to close

**Comment by MGRussell** [comment]
I do think there should be some clearer indication that transitive references are not supported. A single line output warning does not necessarily express the magnitude of the issue, though only for those who are *intending* to use transitive references.

Of course from my perspective now there is no more issue, so no objections to closing this at your leisure.

**Comment by SimonCropp** [comment]
> I do think there should be some clearer indication that transitive references are not supported

happy to consider that. how do you propose that is achieved?

**Comment by MGRussell** [comment]
It seems that the easiest solution would be to simply change the warning to an error.

**Comment by SimonCropp** [comment]
@MGRussell that would result in a "fail to on install" experience. i am not sure we want that
