### ISSUE TITLE
Fody is only supported on MSBuild 16 and above. Current version: 15.

### ISSUE THREAD

**Issue by dardanshabani** [Fody/Fody#938]
This error message is showing when build in build environment.

**Comment by SimonCropp** [comment]
upgrade to VS 2019

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
