### ISSUE TITLE
Windows Defender Virus Dedect

### ISSUE THREAD

**Issue by kuxii2016** [Fody/Fody#969]
Using the latest version on .net Framework 4.6.1 since the last Windows update my app is now dedected as a virus. Now I did some research and found out that as soon as I remove Fody the app is clean. As soon as I install the nuget again (last version) it sounds the alarm again. 

Dedect as:
Backdoor:Win32/Bladabindi!ml

**Comment by SimonCropp** [comment]
you need to contact your virus vendor since this is a false positive
