### ISSUE TITLE
Fody Addin for adding and removing attributes by convention.

### ISSUE THREAD

**Issue by DamianReeves** [Fody/Fody#98]
I've used PostSharp in the past and they have the concept of a [`MulticastAttribute`](http://www.postsharp.net/aspects/multicasting), it's basically an attribute that can be applied once to add or remove attributes by convention.

I'd like to produce a addin that enables this, but I'm not sure if Fody/Cecil supports what I want to do:

I want to supply a class in the assembly which the Fody Addin would use to tell it at compile time which attributes to add to which types

``` CSharp
public class AttributeConventions {
   public IEnumerable<AttributeLocationInfo> AddAttributes(Type type) {
      // Example
      if (type.Namespace == "Test.ManualPropertyChanged") {
          yield return new AttributeLocationInfo(type, new[]{ PropertyChanged.DoNotNotifyAttribute()};
      }
   }

   public IEnumerable<AttributeLocationInfo> RemoveAttributes(Type type) {
      // same concept as above
   }
}

public class AttributeLocationInfo {
    public Type TargetType {get; set;}
    public MemberInfo TargetMember {get;set;}
    public IEnumerable<Attribute> Attributes {get;set;}

   // ctors omitted
}
```

The above API is not finalized, but demonstrates the point. I want the user to work with the reflection type system, but to be able to inject attributes at compile time based on these conventions.

Any idea how I can do this considering the need to switch between the System.Reflection typesystem and the Mono.Cecil typesystem?

**Comment by icnocop** [comment]
For reference, see https://github.com/Fody/MethodDecorator/issues/17
